### ISSUE TITLE
"Reapplications have shut down" page

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#1001]
Instead of 404 Not Found.

**Comment by emanuil-tolev** [comment]
Use this text (approved by email)

> Reapplications have shut down. The deadline for submitting a reapplication was midnight 31 Mar 2016.

**Comment by dommitchell** [comment]
@emanuil-tolev can this one be closed?

**Comment by dommitchell** [comment]
Closing for now.
