### ISSUE TITLE
Another broken icon on admin interface

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#1008]
Probably broken by the FontAwesome upgrade we had to do a long while back. We've caught all the public instances I think but this is on the Applications page for admins e.g.: https://doaj.org/admin/applications?source=%7B%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%2219167245%22%2C%22default_operator%22%3A%22AND%22%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D

Each application is supposed to have a little icon before the title.

Currently the CSS class string is `icon icon-signin`. It needs to be `fa fa-sign-in` (tested inline replacement in Chrome). It should take about 5 minutes to fix / rollout.

**Comment by dommitchell** [comment]
No longer a problem
