### ISSUE TITLE
Question: API returns blank articles list

### ISSUE THREAD

**Issue by akxlr** [DOAJ/doaj#1015]
Hi, I hope it is ok to ask about your API here. I am trying to get a count of articles for each OA journal in the DOAJ database. I have noticed that a lot of queries for articles come up empty (e.g. https://doaj.org/api/v1/search/articles/issn%3A1932-6203, which is PLoS one). Is this because the data doesn't exist, or is there something wrong with my query? Thanks!

**Comment by emanuil-tolev** [comment]
PLOS metadata is not in DOAJ (yeah, I know :) ). However, we've been running a project to harvest it all from europepmc.org and this project has passed the testing phase - we expect to get all the PLOS metadata very very soon!

**Comment by emanuil-tolev** [comment]
Your query seems correct, other than that. The public search interface at https://doaj.org/search should return the same results as the API (at least as far as data selection is concerned) so if you want to check if a particular ISSN has articles in DOAJ, just type it in there.

Here's an example for PLOS ONE which you've given in your question: http://bit.ly/1ZxbHLr

As you can see there's only 1 record, which is a journal record - but there are no articles.

**Comment by akxlr** [comment]
That makes sense, thanks for the quick response!
