### ISSUE TITLE
Public search returns results from Admin Notes

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1016]
http://bit.ly/1TQ8J35

3rd result down is an Indian journal. Only mention of PLoS is in our internal notes. https://doaj.org/admin/journal/8eb80b89f33f43c7b6a259b78ef07a4b

These should not be indexed in public engine. Please correct

**Comment by dommitchell** [comment]
Or assign @emanuil-tolev

**Comment by richard-jones** [comment]
Ok, interesting, I'll look into it.  I believe I know what's happening, but I'm not actually entirely sure what the fix is.

**Comment by richard-jones** [comment]
I've looked into this, and there are a couple of solutions:

1. Make some changes to the ES mappings and the behaviour of the free_text search.

This is the reference: https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-all-field.html

We need to modify the mappings and re-index.

2. Move the storage of notes to a separate index.  This would involve some changes to the admin form handling, and a migration on the current data.

In either case, this looks to be a 2 or 3 days work to make the relevant changes, which we could do under tnm.

**Comment by dommitchell** [comment]
Has been a bug since Sept 2013.

**Comment by dommitchell** [comment]
CL will investigate this first and then get back to us.

**Comment by emanuil-tolev** [comment]
Preference for option 1 overall.

**Comment by emanuil-tolev** [comment]
Option 1 try maybe do with zero downtime option here https://www.elastic.co/blog/changing-mapping-with-zero-downtime#_reindexing_your_data_with_zero_downtime . Note still quite hard but that's kinda inevitable with changing a structural/mapping thing like this.

**Comment by richard-jones** [comment]
Taking this out of tnm, and will do a separate assessment of the work

**Comment by ClaraDOAJ** [comment]
I think this one can be closed...

**Comment by emanuil-tolev** [comment]
Yep, that's been verified to not happen any more.
