### ISSUE TITLE
Question: could we suggest an account to associate an application to?

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1023]
Problem: we don't always spot that an application is from an account in DOAJ thta already has multiple journals allocated to it. This means we end up creating duplicates, leading to redundancy and confusion for the users.

Question: is there any way the system could intelligently suggest the 'best fit' account number for the application, based on publisher name? Or something.

A bit of lateral thinking needed here. Thoughts?

**Comment by dommitchell** [comment]
Dom to find older issue.

**Comment by ClaraDOAJ** [comment]
please close
