### ISSUE TITLE
Add new sponsor: Springer Nature

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1024]
Please add this logo: 
![sn_logo_cmyk_resized](https://cloud.githubusercontent.com/assets/5955396/15428115/d54016e8-1e99-11e6-83e9-38dbf77ce67a.jpg)
and link to http://www.springernature.com/gp/group/aboutus

and remove these 3 logos:
Biomed Central
Nature Publishing Group
Springer

**Comment by emanuil-tolev** [comment]
This is rolled out on live.

**Comment by dommitchell** [comment]
Smashing!
