### ISSUE TITLE
Adjust the text in the tooltip on APC facet

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1032]
Re #708 can you delete 'The data here may not be complete.'?

Fairly urgent if poss?

**Comment by emanuil-tolev** [comment]
@dommitchell just to confirm you still want this text deleted - I know we've discussed APCs after this issue was opened as well.

**Comment by dommitchell** [comment]
Yes please! Thanks!

**Comment by emanuil-tolev** [comment]
Should be live

**Comment by dommitchell** [comment]
Perfect!
