### ISSUE TITLE
Article overwriting not working again: causes duplication

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1033]
http://bit.ly/1OIORdZ
http://bit.ly/1sMN7fI

I asked the publisher to correct some broken characters and the new versions didn't overwrite the old version as it should have. Can you investigate?

**Comment by richard-jones** [comment]
I've had a quick poke around the tests to make sure that url and doi matching are working, and everything seems to be in order.

Can you give me a bit more detail on what the publisher was doing?  Is this a bulk XML upload, or an individual article metadata entry, or API request?

Is there any chance they can send us the source XML data, if it was an upload?

**Comment by dommitchell** [comment]
User account 1110662x, and they used XML upload feature. Files emailed to you.

**Comment by richard-jones** [comment]
Ok, I've found out what's going on and provided a hotfix.

The issue was that for accounts with >1024 issns associated with them, deduplication was failing due to a technical error with the deuplication query.

@dommitchell - while we get this deployed, the advice in the mean time is for all very large accounts to avoid uploading updates

**Comment by emanuil-tolev** [comment]
The hotfix is deployed. Not 100% sure how this is to be reviewed.. have one of the affected accounts upload (a small number of articles) again and see if no dupes occur?

**Comment by dommitchell** [comment]
Asking HIndawi...

**Comment by dommitchell** [comment]
Hindawi confirms that this has worked

**Comment by dommitchell** [comment]
Leaving this here as I htink that this has become an issue again: http://bit.ly/2aGmhzG

These 10 articles are identical to their 10 predecessors.

**Comment by Steven-Eardley** [comment]
It seems there are two identical versions which were created at different times on the same day. 

https://doaj.org/admin/admin_site_search?source=%7B%22query%22%3A%7B%22filtered%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22term%22%3A%7B%22_type%22%3A%22article%22%7D%7D%5D%7D%7D%2C%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%222466%5C%5C-3913%22%2C%22default_operator%22%3A%22AND%22%7D%7D%7D%7D%2C%22sort%22%3A%5B%7B%22index.unpunctitle.exact%22%3A%7B%22order%22%3A%22desc%22%7D%7D%5D%2C%22from%22%3A0%2C%22size%22%3A10%7D

e.g.

```
"hits": [
{
"_index": "doaj",
"_type": "article",
"_id": "9ca13a41c42d4de3a91fdc6d32376348",
"_score": 14.666588,
"_source": {
"index": {
"publisher": [
"Belgrade Center for Music and Dance"
],
"schema_subject": [
"LCC:Dancing"
],
"license": [
"CC BY-NC-ND"
],
"classification": [
"Dancing"
],
"classification_paths": [
"Geography. Anthropology. Recreation: Recreation. Leisure: Dancing"
],
"country": "Serbia",
"issn": [
"2466-3913"
],
"schema_code": [
"LCC:GV1580-1799.4"
],
"unpunctitle": "UTILITY OF SIMPLIFIED LABANOTATION",
"language": [
"English"
],
"date": "2016-02-01T00:00:00Z",
"date_toc_fv_month": "2016-02-01T00:00:00Z",
"asciiunpunctitle": "UTILITY OF SIMPLIFIED LABANOTATION",
"subject": [
"Dancing"
]
},
"last_updated": "2016-08-03T07:44:29Z",
"admin": {
"in_doaj": true
},
"created_date": "2016-08-03T07:44:29Z",
"id": "9ca13a41c42d4de3a91fdc6d32376348",
"bibjson": {
"title": "UTILITY OF SIMPLIFIED LABANOTATION",
"abstract": "After using simplified Labanotation as a didactic tool for some years, the author can conclude that it accomplishes at least three main functions: efficiency of rehearsing time, social recognition and broadening of the choreographic consciousness of the dancer. The doubts of the dancing community about the issue of ‘to write or not to write’ are highly determined by the contexts and their own choreographic evolution, but the utility of Labanotation, as a tool for knowledge, is undeniable.",
"author": [
{
"affiliation": "Chair professor at the University of Antioquia. Medellín, (Colombia)",
"name": "Maria del Pilar Naranjo"
}
],
"month": "2",
"link": [
{
"url": "http://accelerandobjmd.weebly.com/issue1/article09.html",
"type": "fulltext"
}
],
"year": "2016",
"keywords": [
"labanotation"
,
"kinetography laban"
,
"simplified labanotation"
,
"motif writing"
,
"writing dance"
],
"identifier": [
{
"type": "eissn",
"id": "2466-3913"
}
],
"journal": {
"publisher": "Belgrade Center for Music and Dance",
"license": [
{
"url": "http://accelerandobjmd.weebly.com/ethics.html",
"open_access": true,
"type": "CC BY-NC-ND",
"title": "CC BY-NC-ND"
}
],
"language": [
"EN"
],
"title": "Accelerando: BJMD",
"country": "RS",
"number": "1",
"volume": "1",
"issns": [
"2466-3913"
]
},
"subject": [
{
"code": "GV1580-1799.4",
"term": "Dancing",
"scheme": "LCC"
}
]
}
}
}
,
{
"_index": "doaj",
"_type": "article",
"_id": "9b4ca4e29c3447539283ab6855a635ee",
"_score": 14.66243,
"_source": {
"index": {
"publisher": [
"Belgrade Center for Music and Dance"
],
"schema_subject": [
"LCC:Dancing"
],
"license": [
"CC BY-NC-ND"
],
"classification": [
"Dancing"
],
"classification_paths": [
"Geography. Anthropology. Recreation: Recreation. Leisure: Dancing"
],
"country": "Serbia",
"issn": [
"2466-3913"
],
"schema_code": [
"LCC:GV1580-1799.4"
],
"unpunctitle": "UTILITY OF SIMPLIFIED LABANOTATION",
"language": [
"English"
],
"date": "2016-02-01T00:00:00Z",
"date_toc_fv_month": "2016-02-01T00:00:00Z",
"asciiunpunctitle": "UTILITY OF SIMPLIFIED LABANOTATION",
"subject": [
"Dancing"
]
},
"last_updated": "2016-08-03T14:00:07Z",
"admin": {
"upload_id": "fb37cd796d274cddab90e36624578515",
"in_doaj": true
},
"created_date": "2016-08-03T14:00:07Z",
"id": "9b4ca4e29c3447539283ab6855a635ee",
"bibjson": {
"title": "UTILITY OF SIMPLIFIED LABANOTATION",
"abstract": "After using simplified Labanotation as a didactic tool for some years, the author can conclude that it accomplishes at least three main functions: efficiency of rehearsing time, social recognition and broadening of the choreographic consciousness of the dancer. The doubts of the dancing community about the issue of ‘to write or not to write’ are highly determined by the contexts and their own choreographic evolution, but the utility of Labanotation, as a tool for knowledge, is undeniable.",
"author": [
{
"affiliation": " Chair professor at the University of Antioquia. Medellín, (Colombia) ",
"name": "Maria del Pilar Naranjo",
"email": "pilarnaranjodanza@hotmail.com"
}
],
"month": "2",
"link": [
{
"url": " http://accelerandobjmd.weebly.com/issue1/article09.html ",
"type": "fulltext",
"content_type": "html"
}
],
"year": "2016",
"keywords": [
"labanotation"
,
"kinetography laban"
,
"simplified labanotation"
,
"motif writing"
,
"writing dance"
],
"identifier": [
{
"type": "eissn",
"id": "2466-3913"
}
],
"journal": {
"publisher": "Belgrade Center for Music and Dance",
"license": [
{
"url": "http://accelerandobjmd.weebly.com/ethics.html",
"open_access": true,
"type": "CC BY-NC-ND",
"title": "CC BY-NC-ND"
}
],
"language": [
"EN"
],
"title": "Accelerando: BJMD",
"country": "RS",
"number": "1",
"volume": "01",
"issns": [
"2466-3913"
]
},
"subject": [
{
"code": "GV1580-1799.4",
"term": "Dancing",
"scheme": "LCC"
}
]
}
}
}
]
```

**Comment by richard-jones** [comment]
Is it just these 10, or are there other known examples?

@emanuil-tolev - how frequently is the article importer running at the moment?

Since neither record has a DOI, they must be attempting to match on the fulltext url, which we know does work (via the tests), but that will be my first port of call for the investigation.

**Comment by dommitchell** [comment]
No other examples reported at that time. Haven't been through publisher feedback yet so there may be more. Will add here if so.

**Comment by dommitchell** [comment]
Dom to contact publisher and get original XML files.

**Comment by richard-jones** [comment]
Consider adding a script which looks for duplicates which we can run periodically for our own sanity

**Comment by dommitchell** [comment]
More evidence of this:
/starts/
I wanted to update the year data of some articles but after uploading two xml files I got the following message: File system error when reading file

This error caused duplicated articles. Could you help me to solve this, for example, could you help me to delete all so I can upload the metadata again?

The following links shows a duplicated article with the same DOI and full text URL data:
https://doaj.org/article/63246a30e64c44579bebc2c0f44f2bf6
https://doaj.org/article/37045a6c47754aefa68404ba8e36acc8
/ends/

Have asked for XML files and a screenshot.

**Comment by dommitchell** [comment]
![image 1](https://cloud.githubusercontent.com/assets/5955396/19866454/78c7db02-9fa0-11e6-8e4c-3dee795aa454.png)

Email files forwarded to CL.

**Comment by emanuil-tolev** [comment]
We should pick this up next meeting again. Added to pad.

**Comment by richard-jones** [comment]
Superseded by #1294 #1295 and #1296

**Comment by ClaraDOAJ** [comment]
Ok, I think that when the article has a DOI we are not experiencing duplications. If the article does not have DOI we do have duplications that I have to manually delete.
