### ISSUE TITLE
Please add links to Groups to API page

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1035]
Please add a link to the 3 API groups that you created to https://doaj.org/api/v1/docs

**Comment by emanuil-tolev** [comment]
Gosh, sorry, I thought I'd done this ages ago! I had a local branch but I
think what happened is something urgent came up, and I forgot to push up
this small text addition. I'll add it tomorrow.

**Comment by emanuil-tolev** [comment]
https://doaj.org/api/v1/docs#intro_help
