### ISSUE TITLE
Inaccuracy in OAi-PMH

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1039]
Please asses this one for tnm. Would this be an easy thing to enhance the accuracy of? What are our options?

From a user:
/start/
I noticed that article records in Dublin Core OAI Article format (OAI_DC) include the dc:rights element. According to the documentation this is “the journal's content re-use policy. Will be one of the Creative Commons licences”.

Many OA journals offer authors a choice of Creative Commons licenses. This means that there can be discrepancies between an article’s actual re-use rights and the re-use rights described in the OAI-PMH record. For example, this Elsevier article is published under a CC BY license but the dc:rights information provided by DOAJ lists it as CC BY-NC-ND:
http://www.sciencedirect.com/science/article/pii/S2212096315000261
https://doaj.org/oai.article?verb=GetRecord&identifier=oai:doaj.org/article:3273ed9d74864a279f580c450a4700d6&metadataPrefix=oai_dc

Within the article record it is not made clear that this rights element applies at a journal level, and not necessarily to the article itself, which could cause problems for people using these records – especially if the DOAJ record lists an article as having a less restrictive rights policy than it actually does. Are you aware of this, and do you have any plans to improve the accuracy of this element, or plans to remove this element in the future? From a publisher’s perspective it’s concerning that there may be inaccurate rights information associated with article records. The current DOAJ upload XML schema does not allow for article-level rights information to be provided.

It is worth noting that records provided in OAI_DOAJ format do not contain an equivalent element.
/ends/

**Comment by emanuil-tolev** [comment]
Previously DOAJ has not held article-level licence information. I suppose that's the major decision to make rather than a technical challenge - either start accepting and holding such information, or make it clear the current field is journal-level only.

**Comment by dommitchell** [comment]
Right! That's a bigger issue

> or make it clear the current field is journal-level only.

How could we do that in the context of the feed? Just through documentation? Not actually in the feed itself?

**Comment by emanuil-tolev** [comment]
> How could we do that in the context of the feed?

Good question. cc @richard-jones who's written and ingested a lot of OAI feeds.

**Comment by richard-jones** [comment]
Consider moving the rights information to provenance: http://dublincore.org/documents/dcmi-terms/#terms-provenance

**Comment by richard-jones** [comment]
Done in upcoming PR

**Comment by richard-jones** [comment]
This one, with the associated documentation, is now on the test server @dommitchell

**Comment by dommitchell** [comment]
Looking good. Small typo in the change log:  inacurate in "Revision history - Article OAI-PMH DC"

**Comment by dommitchell** [comment]
Can I have an update on this one? I presume it's actually done and this just needs closing?

**Comment by emanuil-tolev** [comment]
Yep, the typo was a year. Fixed in 2016. https://github.com/DOAJ/doaj/pull/1066/commits/c5c69b0e42cd3d0d6d13df187527d27174958635
