### ISSUE TITLE
Large XML file uploads

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#1040]
A publisher account is uploading files large enough that it makes the article ingest script run for longer than 30 min. This has happened 2 days in a row and I think it's time we were better prepared for it.

As a result of these uploads multiples of the script can start, causing increased resource use and eventually instability if not taken care of manually. Once every 24h at the moment.

Presently the regular article ingestion job is stopped and run manually "until it completes". I don't know how long it takes at the moment - I will take this measurement today.

I doubt publishers will be very happy with the suddenly increased delay in XML processing time, so we need a solution.

- is it possible to run two ingestarticle jobs in parallel? I suspect this is not advisable, the script was not written with parallelisation in mind (and if we want to do that more generally, there's plenty of backend job frameworks we could use rather than regular scripts). Despite that, leaving the possibility open for discussion.

    If it were possible, I'm envisioning a "this script runs files over 750KB in size and only runs every 24h" alongside "this script runs files under 750KB in size every 30 min". I'd also advise to put a limit on the number of files processed by the small-file-script, like 20-30 - any beyond that will be picked up next run.

- run the regular script we have now for (however long it takes to run over the large files uploaded by the publisher which highlighted the issue) x3. If it takes 2 hours, run the job every 6h.

- other ideas here

Once we've decided on a suitable approach need to remember to also clear how long it'll take with @dommitchell . In the meantime, Dom, I presume this is high priority? If not just relabel it.

**Comment by emanuil-tolev** [comment]
Right, so it took 5h to do the "manual" run today, a fair bit more than 30 min. I've set the article ingest job to run every 24h now instead of every 30min till we find a better solution.

**Comment by dommitchell** [comment]
Thanks Emnauil. I have a feeling that this bulk uploading will not be a continuous problem but it is because Hindawi are doing a one-time correction to a load of corrupt article metadata. I think the steps that you have taken to change this to 3am every day are going to cause more trouble than good because we'll get loads of queries from other publishers wondering where their content is. Can you leave at 30mins and we'll ride out the Hindawi bulk uploads? Is that an option?

**Comment by emanuil-tolev** [comment]
This happened more than once and the files were uploaded in the same minute on two different days - hence why I assumed there'd be more uploads like that to come.

There's no way (currently) to separate [a few of these large Hindawi XML files] from [lots of these quick small XML files]. If there are super large ones then it can't run every 30 min. It also can't run in parallel, i.e. we can't have "this process will do Hindawi for 5h while this other process cleans the rest up every 30 min".

If we don't do any code changes we'll basically have to just run it on a 24h cycle until Hindawi tell us they're done and aren't going to upload huge files anymore (or we see they haven't uploaded any huge files for a few days and decide it's safe to switch back to shorter cycles).

**Comment by emanuil-tolev** [comment]
For future ref: we ended up doing a 3am and 3pm run, so every 12h.

This has now been reversed after confirmation from Hindawi that their retrospective updating is complete. We are back to ingesting XML article metadata every 30 minutes.
