### ISSUE TITLE
Removing a journal from DOAJ isn't removing articles too

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1042]
http://bit.ly/1ZZYzz4

and

http://bit.ly/24YS54w

This is the 2nd example. Both journals were removed automatically by CL after the closure of reapplication process: Can you check that these journals' articles were automatically removed as well?

**Comment by emanuil-tolev** [comment]
Should be resolved shortly after deploy on Thu 23 Jun 2016 as orphaned articles will be updated.

**Comment by dommitchell** [comment]
Closing!
