### ISSUE TITLE
Add distinction for Reapplication records. Facet?

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1045]
We need a new facet in admin to distinguish between reapplications and applications. 

Priority please.

**Comment by emanuil-tolev** [comment]
@richard-jones @Steven-Eardley maybe based on whether there is a linked journal record present? Don't recall if "reapplication" is directly recorded as an attribute anywhere. Sounds like it might have to be made one. index.reapplication: false | true .

**Comment by emanuil-tolev** [comment]
Any reasons *not* to do this, or to not do it in a particular way (e.g. a new field in the index part of each application record)?

**Comment by emanuil-tolev** [comment]
@dommitchell @greboun are we happy with an "Application type" facet with currently 2 values: "reapplication" and "new application"?

**Comment by dommitchell** [comment]
@emanuil-tolev Yep!

**Comment by emanuil-tolev** [comment]
This should be available on live now.

**Comment by emanuil-tolev** [comment]
(and on test)

**Comment by dommitchell** [comment]
Smashing!

**Comment by dommitchell** [comment]
Can we have it added to the Editor view as well? 

https://doaj.org/editor/group_applications?source=%7B%22query%22%3A%7B%22match_all%22%3A%7B%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D

**Comment by emanuil-tolev** [comment]
Should be live.

**Comment by dommitchell** [comment]
Perfect!
