### ISSUE TITLE
Proposed new layout for Application form

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#1049]
When we do the application form work, we should strongly consider changing the layout, as the complexity of the form and the 2 column layout are pulling at each other (IMO).

Suggest instead:
- A single column layout, allowing us to use wider form-controls
- Keep the current segmentation, and make those segments collapsible
- Have an overall progress bar at the top, and individual segment progress bars for usability

**Comment by dommitchell** [comment]
Other suggestions: 
- move subject classification close to keywords and Aims and Scope

**Comment by dommitchell** [comment]
- consider adding a new section to the publisher's form that will allow a publisher to indicate if this is a continuation.
