### ISSUE TITLE
Add new sponsor: APS

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1050]
![apsresize](https://cloud.githubusercontent.com/assets/5955396/16729041/48a20d6e-476a-11e6-9a5d-288e63ee64eb.jpg)

and link to https://www.aps.org/

**Comment by dommitchell** [comment]
@emanuil-tolev can you do this Steve's absence?

**Comment by emanuil-tolev** [comment]
Yes, no problem. I think you wanted static pages released as well, will do today.

**Comment by emanuil-tolev** [comment]
Should be live in 2 min

**Comment by dommitchell** [comment]
Smashing!
