### ISSUE TITLE
Question: Journal CSV - add 3 columns

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1056]
How feasible would it be to add two columns to the journal csv:
- number of articles uploaded to DOAJ?
- date of last update?

From a user:
DOAJ offers a very useful list of indexed journals in CSV format. However, the journal ID field, which would be very handy to link databases, is missing. It would be convenient to be able to add this ID to a database of journals to making linking with the DOAJ easier.

Can this be added?

**Comment by dommitchell** [comment]
No reason why this shouldn't work but will take longer to generate CSV.

**Comment by ClaraDOAJ** [comment]
Yes, could be a good enhancement of the csv.

**Comment by dommitchell** [comment]
@richard-jones would this one be post-refactor?
