### ISSUE TITLE
.pull and .save enhancements to integrate better with data objects

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#1058]
1. pull

``` python
    @classmethod
    def pull(cls, id_):
        '''Retrieve object by id.'''
        if id_ is None:
            return None
        try:
            out = requests.get(cls.target() + id_)
            if out.status_code == 404:
                return None
            else:
                return cls(**out.json())
        except Exception as e:
            return None
```

Don't swallow all exceptions: either don't swallow any at all (letting the respective page crash if the pull failed - not unreasonable if the pull is for the main item to display on the page!), or only swallow network exceptions (socket layer and requests).

2. save

This currently doesn't check if the object to be saved conforms to the data schema, which is however applied on .pull. The reason for this is that .save simply saves whatever is in the .data attribute of the object - which could've been modified by functions like .prep() just before .save. There is no explicit check that the information in .data complies with the data schema applied by the object's constructor. There probably should be such a check.

**Comment by richard-jones** [comment]
Since I'll be working on the model layer during the provenance project, I'll look at this at the same time

**Comment by emanuil-tolev** [comment]
I have some suggestions related to data object validation (specifically using Cerberus http://docs.python-cerberus.org/en/stable/ ) rather than our homebrew validation. Ours is good for validating, but surfacing what the validation rules are to the user without a lot of hard-to-maintain copy/pasta is quite difficult (since that's not what we wrote ours for). Cerberus is also capable of expressing much the same rules as us in a more self-contained way (e.g. nested objects, lists of a certain type, how to treat nulls/Nones - but also I think a better handling of a range of allowed values in a field).

This won't directly affect your work here, since ultimately there will be an interface method that allows you to validate an object and the exact implementation of the validation won't matter. Still, mentioning it here in case it might be useful to catch up while you do the provenance work.

**Comment by richard-jones** [comment]
The thing to bear in mind is that the dataobjs don't only do validation, they also do data coersion, and provide a stable means to interact with a datastructure without breaking it.

Also, it supports handling of ranges and allowed values.  I'm also not sure we would want to surface the validation rules of the object directly to the user.

So, while I'm not particularly against using another library, I'd suggest that anyone's validation is homebrew until someone else starts using it, and I'm not convinced that Cerberus is written for our use case, so we might wind up with both that and dataobjs, which would be even more maintenance effort.

Anyway, in the mean time, I'm putting the pull/save fixes in, which actually barely touch the dataobjs, they're more focused on the dao layer.

**Comment by richard-jones** [comment]
Ok, for intermediate review, here are the solutions:

1/ errors are now only swallowed if caused by requests.  All other errors are raised:
https://github.com/DOAJ/doaj/blob/feature/provenance/portality/dao.py#L164

2/ All objects that want to can call self.check_construct() prior to save, which throws an error if the data structure is invalid
https://github.com/DOAJ/doaj/blob/feature/provenance/portality/models/journal.py#L666

Note that this doesn't attempt to coerce the internal structure to the correct form, because doing so breaks pointers/references in other objects, which could be bad (certainly it breaks the tests!).

**Comment by emanuil-tolev** [comment]
Fair enough, I'll find a way to surface what I need while still keeping it maintainable. Cerberus looked nicely similar to our own schema, and it does have coercion (calls it normalization I think). E.g. their docs explicitly mention what will happen if `a coercion callable or method raises an exception` during document processing. http://docs.python-cerberus.org/en/stable/usage.html#validated-method

**Comment by emanuil-tolev** [comment]
> 1/ errors are now only swallowed if caused by requests. All other errors are raised:
> https://github.com/DOAJ/doaj/blob/feature/provenance/portality/dao.py#L164

OK, seems reasonable.



> 2/ All objects that want to can call self.check_construct() prior to save, which throws an error if the data structure is invalid
> https://github.com/DOAJ/doaj/blob/feature/provenance/portality/models/journal.py#L666
> 
> Note that this doesn't attempt to coerce the internal structure to the correct form, because doing so breaks pointers/references in other objects, which could be bad (certainly it breaks the tests!).

Is it possible to run `self.check_construct()` on *every* object (so modify DomainObject's `.save`) and catch the exception `check_construct()` raises to output a warning? Certain other objects can then call it and explicitly not catch the exception it raises, so the save really fails. Basically failure on save is still elective, but warnings are not.

**Comment by richard-jones** [comment]
Thing is, check_construct isn't a general feature of a model object - not all of them are dataobjs.  So, we could do that, but we'd also have to check that it was the right kind of object, and then it starts to feel a bit icky.

Otherwise, what warning were you thinking?  I mean, getting a DataStructureException is a pretty big warning :)

**Comment by emanuil-tolev** [comment]
> Otherwise, what warning were you thinking? I mean, getting a DataStructureException is a pretty big warning :)

Yeah, the same thing, but as a warning and in a more generally applicable place (DomainObject.save) (since not all Data Objects might want to fail on save() if the construct check fails). I agree with you however, I don't think we should be putting in this kind-of-general check but have to have a `hasattr` call in DomainObject.save.

It feels like we should refactor how the data objects interact with the DAO further. Perhaps not now.
