### ISSUE TITLE
Duplicate journal entries: unable to load XML without deleting articles

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1060]
Sometimes we have two journals entries in DOAJ because a new application was accepted in place of the reapplication record and the old original record remains. You will remember that we cannot have two records with the same ISSN in DOAJ; it breaks the ToC pages and returns an error. Our solution has always been to take the old journal out of DOAJ and accept the new record (and simply reject the reapplication).

However, this then produces an error in the XML uploader for a publisher trying to upload XML to that journal. The XML uploader sees that the the journal isn't in DOAJ and will not process the XML. To solve this, the journal record that is *not* in DOAJ must be deleted. However doing that also deleted all of the articles attached to the journal record that is in DOAJ.

Look at Chinese Journal of Cancer. Until today it had 241 articles associated with it and two journal records; one IN and one OUT. I deleted the OUT record and no there are no articles: https://doaj.org/toc/1944-446X

**Comment by dommitchell** [comment]
Notes from the call today: it is possible to call a delete that removes the journal record only but just now a delete call removes everything. 

In the emeantime, use ISSN xxxx-xxxx

**Comment by dommitchell** [comment]
Is there any way that we can retrieve these articles?

**Comment by richard-jones** [comment]
We have identified copies of all these articles in the history system, so it would be possible to restore them.  Have to just run through in our heads what's involved, having never actually had to do it before, but shouldn't be too difficult to script it.

**Comment by Steven-Eardley** [comment]
The goodies can be found in ```~/appdata/doaj/history/article/2016-08-02/ ``` on ```doaj-app-1```. We can find files using the ISSN above.

**Comment by dommitchell** [comment]
Publisher has just connected via API and will upload that way. Closing.
