### ISSUE TITLE
Add Seal to Hindawi records

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1062]
Is it possible to:
- automatically change the answer to Qu 51 to Sherpa/Romeo; and
- automatically add the DOAJ Seal to all accepted Hindawi records that have the Tick? That's about 394 journals at the time of writing: http://bit.ly/2aG0WsK

Can you quote for this?

**Comment by richard-jones** [comment]
We could do this under tnm, and I'd estimate it at around 4 hours, mostly due to testing required.

**Comment by dommitchell** [comment]
OK, forget it. I can do this manually in 3. Ta!
