### ISSUE TITLE
Quick question: marathi

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1063]
Can the web site display marathi?

Do you know if Wordpress can?

**Comment by emanuil-tolev** [comment]
> Can the web site display marathi?

The language, right? Yes, we should have no problem. And if we do it should be fixable.

> Do you know if Wordpress can?

It should be able to, yes, esp. if a new version (like hosted by wordpress.com or another WP hosting service).

**Comment by emanuil-tolev** [comment]
Tbh I'd just try it, copy some lines in Marathi from the web into WP.

**Comment by dommitchell** [comment]
Thanks!
