### ISSUE TITLE
Upgrade to ES 5.x

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#1064]
This is just a placeholder to remind us that at some point we'll need to do upgrade to ES 2.x.  

It's not possible right now, as 2.x drops support for facets, which are required by facetview to work.  We'd need to either modify fv2 or upgrade to Edges in order to support this.

**Comment by emanuil-tolev** [comment]
This would be good to improve monitoring as well, as ES 2.x offers in-depth (free!) monitoring and alerting based on internal Elasticsearch factors, and I imagine it includes a significant step-up in terms of reliability and distributed system management, although 1.7 is already almost rock-solid for us.

**Comment by richard-jones** [comment]
I've just updated the title to remind us that ES 5.x is now out!
