### ISSUE TITLE
Delete 10008 Hindawi articles

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1068]
Duplicates caused by issue #1033 https://github.com/DOAJ/doaj/issues/1033#issuecomment-225295757

Can you delete these for us?

**Comment by dommitchell** [comment]
Email me for the CSV file.

**Comment by dommitchell** [comment]
Notes from call: email list to Richard.

**Comment by richard-jones** [comment]
The code to do this has now been merged, and deployed on test.  We should probably run it on test to ensure that it works.  I have the list of article ids to remove, so @emanuil-tolev if I send these over to you, can you just execute the script and check it functions.  The command is:

    python portality/scripts/articlerm.py -c <path to csv>

**Comment by emanuil-tolev** [comment]
Steve executed this on test. @richard-jones if you are/were happy with the results, the script is now on live. If you send the IDs over I'll run this on live.

**Comment by dommitchell** [comment]
Can this one be updated please?

**Comment by Steven-Eardley** [comment]
@dommitchell this is still assigned to me - can we close? (I hope so, this was over a year ago!)

**Comment by dommitchell** [comment]
I never got confirmation that this had actually been done. Was it done?

**Comment by Steven-Eardley** [comment]
It was not done. I imagine It was assigned to me after a conversation not logged here so that I'd run it rather than emanuil as noted above.

**Comment by Steven-Eardley** [comment]
It should still be possible using the original script and CSV file:

[ArticleIDs.csv.txt](https://github.com/DOAJ/doaj/files/1507046/ArticleIDs.csv.txt)

**Comment by Steven-Eardley** [comment]
It's worth noting, these are going to be deleted by https://github.com/DOAJ/doaj/issues/1296 eventually anyway. When we eventually run it in production, that is.

**Comment by dommitchell** [comment]
So perhaps not worth duplicating effort then? If you are certain that #1296 will catch them all then I am happy for this to be closed.

**Comment by Steven-Eardley** [comment]
I'm satisfied it will work for them - I've checked a couple of the IDs in the test server's log for the dedupe script, and they feature. Actually, it may be the better course of action - these IDs in the CSV are the more recent version with better metadata (abstract vs no abstract), the script would delete the older versions instead and keep these.

They trigger both DOI and full text, since they are genuine duplicates:
```
cloo@doaj-test:~$ grep '5f15e13134dd4fda8b34300d08b893c4\|d8a9d7e0a0c746a1a699143af40c7c2f\|bef8981d3c6e46b79a1da18abe690c44' dedupe_2017-11-27.log -A 2
d8a9d7e0a0c746a1a699143af40c7c2f
	1 DOI duplicates: be7a674dabe448ab99eb8d42b0a8b893
	1 fulltext duplicates: be7a674dabe448ab99eb8d42b0a8b893
--
bef8981d3c6e46b79a1da18abe690c44
	1 DOI duplicates: 614f2145e3fa41f5b3dfab083fd8726e
	1 fulltext duplicates: 614f2145e3fa41f5b3dfab083fd8726e
--
5f15e13134dd4fda8b34300d08b893c4
	1 DOI duplicates: 53dad865aa8e4d60853f0bd2c86a3ae2
	1 fulltext duplicates: 53dad865aa8e4d60853f0bd2c86a3ae2
```
