### ISSUE TITLE
Please enable Owner in the Admin view for Applications

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1071]
https://doaj.org/admin/applications?source=%7B%22query%22%3A%7B%22match_all%22%3A%7B%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D

For all views.

**Comment by emanuil-tolev** [comment]
Enable as in...? Be able to facet on that, add it to each search result, or be able to search inside that specific field?

Or all of them :)?

**Comment by dommitchell** [comment]
Ooops. Just want that information to be visible in the search results display. No need to facet it, or be able to search on it. Just want it displayed, when that info is present,

**Comment by Steven-Eardley** [comment]
The changes to the admin applications facetview are live now.

**Comment by richard-jones** [comment]
@ClaraDOAJ - could you take a look at this one and close if you are happy it's complete

**Comment by ClaraDOAJ** [comment]
How can I look at the applications as owner? Sorry- I don't know how to do it.

**Comment by richard-jones** [comment]
Looking back at the notes above, it looks like what Dom wanted was just the Owner field to appear (linked) in the search results.  If you look at the application search in the admin area, you should be able to see applications which have been assigned to accounts have that data:

https://doaj.org/admin/applications?source=%7B%22query%22%3A%7B%22match_all%22%3A%7B%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D

Looks like it's done, then, but just check it's what you need.

**Comment by ClaraDOAJ** [comment]
Understood. It can be closed! Many thanks!

Clara Armengou
DOAJ - Community Manager
