### ISSUE TITLE
Articles are in DOAJ but not appearing on Journal ToC page

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1072]
https://doaj.org/toc/1578-1283?source=%7B%22query%22%3A%7B%22filtered%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22term%22%3A%7B%22index.issn.exact%22%3A%221578-1283%22%7D%7D%2C%7B%22term%22%3A%7B%22_type%22%3A%22article%22%7D%7D%5D%7D%7D%2C%22query%22%3A%7B%22match_all%22%3A%7B%7D%7D%7D%7D%2C%22from%22%3A0%2C%22size%22%3A100%7D

https://doaj.org/article/87eb1caee5b74826998c5b748b336504

[GACETA_28_1.txt](https://github.com/DOAJ/doaj/files/429642/GACETA_28_1.txt)

**Comment by emanuil-tolev** [comment]
Run article_cleanup_sync.py every day, like sitemap (with anacron).

**Comment by dommitchell** [comment]
Can this one be closed now?

**Comment by dommitchell** [comment]
Yes can be closed.
