### ISSUE TITLE
run script: journals IN DOAJ with a rejected reapplication

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1073]
Can we do this?

Unfortunately, I think there are a number of journals still IN DOAJ that have actually failed the reapplication process. I'd like to get an idea of how many we are talking about and go through and remove them if possible.

**Comment by richard-jones** [comment]
@ClaraDOAJ - do you still need us to look into the possibility of running this query?

**Comment by ClaraDOAJ** [comment]
Let me ask Tom.
