### ISSUE TITLE
Add new status to applications and send automated email

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1084]
Add 'Auto-rejected' to the list for Admin only, for new applications. 

When auto-rejected is selected, an automated email is sent to the person who has filled in the application.

Adding this a high priority as I would like it to be done at the next round of tnm, if possible.

**Comment by emanuil-tolev** [comment]
How is it auto-rejected if it's manually rejected?

I can see that the difference is different text, possibly different target for the rejection email (though we must surely email the person who filled in for normal rejections too?) and admin-only permissions. Those are fine features - I'm just concerned about having a clear name for the status.

**Comment by dommitchell** [comment]
:) Sorry. It's lazy terminology on our part. I mean that we reject them - manually - automatically without review because of missing information in the application. A correct status would actually be 'Rejected without review'.

Because the application is some way incomplete, the email should go to the person who filled in the form (Qu 56-58) rather than the Journal Contact. (I can't remember if that's what we do now.)

**Comment by dommitchell** [comment]
RJ: feels a bit like we're overloading the statuses here. I would suggest instead a 'Reject' button that also sends the email and adds a Note.

**Comment by richard-jones** [comment]
Create a button on the Application form page (similar to the withdraw/reinstate on the Journal form) which does the following:

* Sets the status to "rejected"
* Adds a suitable note (text to be configurable)
* Sends the rejected email (text to be configurable/templated)

It should do this without passing through form validation, in the same way that the journal withdraw/reinstate does.

**Comment by emanuil-tolev** [comment]
We need the text for the reject email to finish this.

**Comment by richard-jones** [comment]
@emanuil-tolev - does that mean that you've got a feature branch with the rest of the code written?

**Comment by dommitchell** [comment]
Getting this one squared away would be fab! We have revamped our Triage process, where these 'Rejected without review' applications happen so if we can send these emails, that would be great.

We have different reasons for rejection so ideally we should be able to configure the message each time. I am unclear if that is an option?

**Comment by richard-jones** [comment]
Just to confirm that we /don't/ have any code for this yet, so it can be started from scratch
