### ISSUE TITLE
Journal CSV: missing information

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1085]
Column J in the journal CSV (Journal article processing charges (APCs)) only shows APC Yes. 'No' and 'No information' are missing.

https://doaj.org/csv

Can you fix?

**Comment by dommitchell** [comment]
A fix to produce 'No information' was done on the facet so this just needs to be made the same in the CSV too.

**Comment by dommitchell** [comment]
Can I have an update on this one please?

**Comment by Steven-Eardley** [comment]
I've made a fix this afternoon, should be released soon, once reviewed.

**Comment by dommitchell** [comment]
@Steven-Eardley  Not seeing that in test. Where can I review?

**Comment by Steven-Eardley** [comment]
@dommitchell sorry I meant code review - @emanuil-tolev @richard-jones there's a PR up for this.

**Comment by emanuil-tolev** [comment]
@dommitchell I think it's up on the test site now, could you try it? https://testdoaj.cottagelabs.com/csv

**Comment by dommitchell** [comment]
Looks great! Can go to live.

**Comment by Steven-Eardley** [comment]
Released now, it should re-generate soon and the changes will be visible on live.

**Comment by Steven-Eardley** [comment]
Confirmed on live, closing.
