### ISSUE TITLE
Create basic provenance reports

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#1086]
Create queries over provenance data, and produce CSV outputs which will provide the following information:
- Number of records (apps or reapps) touched by one user, by month, year
- Number of records fully processed to a conclusion by a user, by month, year
- Number of records (apps or reapps) touched by an editorial group, by month, year
- Number of records (apps or reapps) processed to a conclusion by an editorial group, by month, year
- Number of applications added per country per year

These reports can be run on a schedule, and the outputs automatically distributed to the DOAJ team.

**Comment by dommitchell** [comment]
Is there a way to run a one-off report retrospectively? From June 15th to October 15th?

**Comment by Steven-Eardley** [comment]
There is! From @richard-jones (for future reference):

>If you want to fully customise the report run, you can do
```python portality/scripts/reports.py --f <from date> -t <to date> -o <output directory>```
Dates of the form ```YYYY-MM-DDTHH:mm:ssZ```

I'll generate for the range you've requested before today's meeting.

**Comment by richard-jones** [comment]
Only the applications by country report will mean anything, though, as we won't have any provenance records for edits to applications from before when the code went live.

**Comment by dommitchell** [comment]
> Only the applications by country report will mean anything, though, as we won't have any provenance records for edits to applications from before when the code went live.

Lars would like this report please! Thank you!

**Comment by dommitchell** [comment]
Lars would like two reports if possible:
1. March 21st (project start date) - Oct 15th
2. June 23rd (after Crete) - Oct 15th

Thanks!

**Comment by Steven-Eardley** [comment]
Using the following commands on the production server:

    export DOAJENV=production ; /home/cloo/repl/production/doaj/bin/python /home/cloo/repl/production/doaj/src/doaj/portality/scripts/reports.py -o /home/cloo/reports/mar-oct -f 2016-03-21T00:00:00Z -t 2016-10-16T00:00:00Z

and

    export DOAJENV=production ; /home/cloo/repl/production/doaj/bin/python /home/cloo/repl/production/doaj/src/doaj/portality/scripts/reports.py -o /home/cloo/reports/jun-oct -f 2016-06-23T00:00:00Z -t 2016-10-16T00:00:00Z

I assumed you meant this year, and Oct 15th inclusive (so my -to date is 0000h on the 16th). Attached are just the applications by year by country reports, since the others are meaningless.

[applications_reports.zip](https://github.com/DOAJ/doaj/files/557076/applications_reports.zip)

**Comment by dommitchell** [comment]
@Steven-Eardley Thanks! This includes reapps too?

**Comment by dommitchell** [comment]
Getting that weird error message again... Windows 10 on a PC.
![parameter](https://cloud.githubusercontent.com/assets/5955396/19799240/d5bd8c10-9cf5-11e6-8f33-1468ea101b86.jpg)

**Comment by dommitchell** [comment]
Each report is only showing 10 countries. Is that correct?

**Comment by richard-jones** [comment]
Not sure about the Windows error - I tried opening the files myself and they all seem to be working.

There are only a few countries from which applications have been received.  I think in testing there were maybe 20, but exactly 10 is worth double checking.

@Steven-Eardley - could you run the report for all time and forward around the resulting country sheet?  That will give us some context.  Cheers!

**Comment by Steven-Eardley** [comment]
The windows error may be the filename - bad characters or too long. It's fussy like that. Here's the requested one for all time until now now (evening Oct 28th).

@richard-jones can you comment on whether this is reapplications too; I assume it is (since they are a subset of applications).

[applications_by_year_by_country__1970-01-01T00:00:00Z_to_2016-10-28T17:53:24Z__on_2016-10-28T17:53:24Z.csv.zip](https://github.com/DOAJ/doaj/files/559068/applications_by_year_by_country__1970-01-01T00.00.00Z_to_2016-10-28T17.53.24Z__on_2016-10-28T17.53.24Z.csv.zip)

**Comment by richard-jones** [comment]
Great, thanks.  After a bit of a ponder, and looking at the admin area, I'm convinced that the reports are not complete.  I can see what I've done wrong, too - I haven't set the aggregation sizes sufficiently large to capture all the results.  My bad!  I'll submit a hotfix shortly.

@Steven-Eardley - with regard to reapplications, yes it does include them.  Reapplications are not treated any differently internally to ordinary applications, except at the point that they are converted to journals.

**Comment by Steven-Eardley** [comment]
@richard-jones the changes seem to have uncovered an issue, only seen when running over all-time (which it does every month) perhaps in the CSV writer:

```
cloo@doaj-app-1:~/reports$ export DOAJENV=production ; /home/cloo/repl/production/doaj/bin/python /home/cloo/repl/production/doaj/src/doaj/portality/scripts/reports.py -o /home/cloo/reports/all_time_31st
Running in production
Loaded final config from /home/cloo/repl/production/doaj/src/doaj/production.cfg
Saving reports to /home/cloo/reports/all_time_31st
Traceback (most recent call last):
  File "/home/cloo/repl/production/doaj/src/doaj/portality/scripts/reports.py", line 60, in <module>
    reports(args.from_date, args.to_date, args.out)
  File "/home/cloo/repl/production/doaj/src/doaj/portality/scripts/reports.py", line 11, in reports
    reporting.content_reports(fr, to, outdir)
  File "/home/cloo/repl/production/doaj/src/doaj/portality/reporting.py", line 62, in content_reports
    writer.writerow(row)
  File "/home/cloo/repl/production/doaj/src/doaj/portality/clcsv.py", line 235, in writerow
    self.stream.write(data)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf4' in position 1: ordinal not in range(128)
```

**Comment by richard-jones** [comment]
Darn.  I thought the csv writer would handle that - maybe I was just being lazy.  We should be able to use the UnicodeWriter to sort this out.  I'll do another hotfix, though may not get to this today.

**Comment by Steven-Eardley** [comment]
@dommitchell here are the two reports you asked for, this time with shorter names.

[Archive.zip](https://github.com/DOAJ/doaj/files/561797/Archive.zip)

**Comment by dommitchell** [comment]
Works well! Thank you. Please close if this is now finished.

**Comment by Steven-Eardley** [comment]
Not quite, todo:

- [ ] merge RJ's utf-8 pull request
- [ ] new hotfix - script should output more Windows-friendly file names

**Comment by richard-jones** [comment]
done a while back

**Comment by dommitchell** [comment]
Where do I find these reports? I need a memory jog!

**Comment by Steven-Eardley** [comment]
The reports are emailed to feedback@doaj.org, and are retained on the app server in ```~/reports``` (for future sysadmin reference). However, the most recent one I can see is from April this year. I'll take a look at whether the background task is scheduled properly.

**Comment by dommitchell** [comment]
Great. Let me know what you find. Now I'm back, we are going to start proper throughout monitoring so these reports are essential

**Comment by Steven-Eardley** [comment]
I'm re-closing this old development issue; we can track this new problem with issue #1364.
