### ISSUE TITLE
Stylesheet change: increase standard font and line spacing on static pages

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1088]
To increase readability of the static pages, which are dense to say the least, please can you increase the standard font size and the line spacing?

What is the font now?

**Comment by Steven-Eardley** [comment]
At the moment we have the bootstrap default, e.g. from the /features page I pulled this (on OS X):

```
font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
font-size: 13px;
line-height: 18px;
```

**Comment by emanuil-tolev** [comment]
To elaborate a tiny bit, that means it will attempt

Helvetica Neue, then if that's not there
Helvetica, then if that's not there
Arial, then if that's not there (are you trying to view DOAJ from a washing machine controller?)
use any sans-serif font.

We can play with the font-size and line-height. I'm generally a fan of (r)em relative units. See https://zellwk.com/blog/rem-vs-em/ . It means it'll scale a bit better on mobile and other such things, in addition to playing nicely with browser customisations (e.g. if somebody has a +8 shortsightedness dioptre on their glasses and has their browser set to 40px font size we'll screw with that with our current 13px setting).

**Comment by richard-jones** [comment]
Probably we can just add a class on the wrapper to any "documentation" page, and attach whatever font declarations we need to it.

**Comment by dommitchell** [comment]
@richard-jones would this be part of the refactor updates to the UI?
