### ISSUE TITLE
Bulk change of URLs from http to https

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1089]
A publisher has asked if we can change all their URLs from http to https across all their entries.

The publisher is Hindawi so we're talking about > 500 journals.

The URLs all currently start with:

http://www.hindawi.com/journals/.....

and should be changed to https://www.hindawi.com/journals/....

Can you do this automatically for us?

**Comment by dommitchell** [comment]
Technically doable. Bit time-consuming probably. Probably have to write a migrate script. 

DM to provide a list of all the ISSNs or a search criteria.

**Comment by emanuil-tolev** [comment]
Yes, could do under TnM. Have to consider articles, journals and (re?)applications.

**Comment by dommitchell** [comment]
> Have to consider articles, journals and (re?)applications.

Only applies to journals and (re)applications.

**Comment by Steven-Eardley** [comment]
I'm looking to take this on using a migrate script - can you supply the ISSNs or searches which cover the journals and applications from Hindawi?

**Comment by ClaraDOAJ** [comment]
Hi @Steven-Eardley, I could. It is 564 entries. I have the search but I am not sure you are able to see it if I paste it here.

https://doaj.org/admin/journals?source=%7B%22query%22%3A%7B%22filtered%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22term%22%3A%7B%22admin.in_doaj%22%3A%22T%22%7D%7D%5D%7D%7D%2C%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%22hindawi%22%2C%22default_operator%22%3A%22AND%22%7D%7D%7D%7D%2C%22from%22%3A0%2C%22size%22%3A564%7D

**Comment by Steven-Eardley** [comment]
Thanks @ClaraDOAJ - When checking over the search you provided, I found they're not all owned by the same account. I'll send an updated search by email as it contains non-public information.

We can take our time and get things right, I can proceed in the meantime on the assumption we'll have search criteria to use, and write the script accordingly.

**Comment by Steven-Eardley** [comment]
@ClaraDOAJ This has been run on the test machine now. Can you give its effects on the Hindawi journals a quick check before I run on live?

**Comment by ClaraDOAJ** [comment]
Hi @Steven-Eardley I see that there are some entries that do not have the https. See second entry. 
![image](https://cloud.githubusercontent.com/assets/22593616/22080152/cd4677cc-ddbe-11e6-85c5-c78bd1d57c93.png)

Thanks!

**Comment by Steven-Eardley** [comment]
Ah! I only changed hindawi URLs, to be safe. I in fact tried those isrn URLs with HTTPS and it caused an error, whereas the HTTP one as written there redirects to the hindawi domain over HTTPS.

**Comment by ClaraDOAJ** [comment]
Ok, then!

**Comment by Steven-Eardley** [comment]
This has been run on live now. This issue can be closed if you're happy with it!
