### ISSUE TITLE
Missing papers

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1090]
ISSN 1989-4147

See screenshot of publisher area. All uploads worked well.
![image002](https://cloud.githubusercontent.com/assets/5955396/19069181/114ed5f0-8a26-11e6-8ea6-2f05afe72fef.jpg)

There are two entries for this journal. One old one out, one new one in. I just changed the ISSN numbers for the old one to xxxx-xxxx.

Can you investigate please?

**Comment by dommitchell** [comment]
I have had other similar reports. Linked to issue #1060

**Comment by richard-jones** [comment]
If I search for the issn I don't see any articles which match:

https://doaj.org/search?source=%7B%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%221989%5C%5C-4147%22%2C%22default_operator%22%3A%22AND%22%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D

and likewise for the other issn:

https://doaj.org/search?source=%7B%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%221576%5C%5C-9402%22%2C%22default_operator%22%3A%22AND%22%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D

Can we get some other identifying information for these articles, so we can be sure that they actually made it into the system or not?  Say, fulltext URLs, or some titles?

**Comment by dommitchell** [comment]
Closing as old .
