### ISSUE TITLE
Test harness for XML files

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#1093]
Would be good if we could develop a script or even UI feature for validating article XML files in a way that gives the user more feedback.  There is a recent request to review a couple of files, so propose that we put such a feature together as a script initially, and then use those files as a test-base.

**Comment by dommitchell** [comment]
This is an excellent idea. Ideally it will be a process that I can use without bothering CL.

**Comment by dommitchell** [comment]
CL will discuss this week,.

**Comment by richard-jones** [comment]
This is live
