### ISSUE TITLE
Group name sort for Editorial Groups doesn't work

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1094]
https://doaj.org/admin/editor_groups?source=%7B%22query%22%3A%7B%22match_all%22%3A%7B%7D%7D%2C%22sort%22%3A%5B%7B%22name%22%3A%7B%22order%22%3A%22desc%22%7D%7D%5D%2C%22from%22%3A0%2C%22size%22%3A44%7D

**Comment by richard-jones** [comment]
@Steven-Eardley could you take a look at this one when you have a chance

**Comment by Steven-Eardley** [comment]
Need to add a ```.exact``` to https://github.com/DOAJ/doaj/blob/develop/portality/static/doaj/js/available_facetviews/admin.editorgroups.facetview.js#L24

**Comment by Steven-Eardley** [comment]
Released to live - the editor groups can now be sorted A-Z or Z-A.

**Comment by ClaraDOAJ** [comment]
Many thanks!
