### ISSUE TITLE
Add WK logo and remove Co-Action logo

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1101]
We need to add Wolters Kluwer logo in our sponsors page. The logo needs to be of a similar size as the rest. We also need to remove the Co-Action logo - they have been bought by Taylor&Francis.

Attached the logo and their url http://wolterskluwer.com/
![wk 1](https://cloud.githubusercontent.com/assets/22593616/19447827/7f82c026-949f-11e6-84db-5d81f4455e9a.gif)

Given that we do not upload logos that often, maybe we could make this page static so it can be easily updated by us. Let's see what Dom thinks about it.

I have made a couple of changes to the static pages, can we have them refreshed, too?

Thanks

**Comment by emanuil-tolev** [comment]
Coaction removed, WK added, static pages updated. Should be visible on https://doaj.org/ and https://testdoaj.cottagelabs.com/ .

> Given that we do not upload logos that often, maybe we could make this page static so it can be easily updated by us. Let's see what Dom thinks about it.

@Steven-Eardley @richard-jones what do you guys think? I'd say it's a good idea. The current solution is basically a nice interface for software developers to update the content - it's an OrderedDict called SPONSORS in portality/app.py. Ultimately the HTML produced is quite simple, much simpler than other static pages edited by the DOAJ Editorial team. Provided the team is careful when putting in URLs, this should be fine - but anybody can be careful to put in the right URL.

One additional consideration is uploading sponsor logos:

- Github provides a nice interface for uploading files: https://github.com/DOAJ/doaj/tree/static_pages/portality/static/doaj/images/sponsors , then click "Upload Files" from the buttons on the top right.
- file sizes must be kept down. The biggest sponsor logo is currently 16 KB and the total size is ~231KB, which I'm still not thrilled about (try loading that on "2.5G", a.k.a. "E" (EGPRS) mobile connection). Most logos that come from publishers will be reasonable and web-optimised. @Steven-Eardley and I have been downsizing and converting the bigger logos ourselves.

    Although this sounds like a point in the process where developers have to get involved, you can actually achieve similar results with online tools, and the skill is not that difficult to teach to the DOAJ editorial team - everything is achievable using completely free image manipulation software (GIMP).

I think this is very achievable, perhaps after producing a short guidance document for people with access to static_pages. There will be a small amount of Time and Materials work involved, but let's first see if the idea sounds reasonable to everybody.

**Comment by Steven-Eardley** [comment]
I think this is a good suggestion - although the current method is neat and simple for us, it's even simpler for us if we don't have to do it! 😇

Furthermore, there's still a bit of code oversight since we still do the actual releases, so should be able to notice any broken URIs. 

One thing to keep in mind if we change the system, the logos are currently automatically sorted into alphabetical order, presumably because this is fair and equitable. Making the page plain HTML would lose this feature - how about instead we factor out the Dict to a different location from ```app.py``` and provide documentation on how to add sponsors? That way it can be in a less crucial place, and the benefits of the current approach remain.

**Comment by dommitchell** [comment]
I am always in favour of us being given controls to do anything. Nice suggestion @ClaraDOAJ !

**Comment by Steven-Eardley** [comment]
Moved new feature discussion to #1102, closing this because the logo and static changes were released.
