### ISSUE TITLE
Give DOAJ team the ability to edit sponsor logos

### ISSUE THREAD

**Issue by Steven-Eardley** [DOAJ/doaj#1102]
From discussion in #1101, @ClaraDOAJ asked: 

> Given that we do not upload logos that often, maybe we could make this page static so it can be easily updated by us.

@emanuil-tolev says:

> The current solution is basically a nice interface for software developers to update the content - it's an OrderedDict called SPONSORS in portality/app.py. Ultimately the HTML produced is quite simple, much simpler than other static pages edited by the DOAJ Editorial team. Provided the team is careful when putting in URLs, this should be fine - but anybody can be careful to put in the right URL.
> 
> One additional consideration is uploading sponsor logos:
> 
> Github provides a nice interface for uploading files: https://github.com/DOAJ/doaj/tree/static_pages/portality/static/doaj/images/sponsors , then click "Upload Files" from the buttons on the top right.
> file sizes must be kept down. The biggest sponsor logo is currently 16 KB and the total size is ~231KB, which I'm still not thrilled about (try loading that on "2.5G", a.k.a. "E" (EGPRS) mobile connection). Most logos that come from publishers will be reasonable and web-optimised. @Steven-Eardley and I have been downsizing and converting the bigger logos ourselves.
> 
> Although this sounds like a point in the process where developers have to get involved, you can actually achieve similar results with online tools, and the skill is not that difficult to teach to the DOAJ editorial team - everything is achievable using completely free image manipulation software (GIMP).
> 
> I think this is very achievable, perhaps after producing a short guidance document for people with access to static_pages. 

@Steven-Eardley says:

> One thing to keep in mind if we change the system, the logos are currently automatically sorted into alphabetical order, presumably because this is fair and equitable. Making the page plain HTML would lose this feature - how about instead we factor out the Dict to a different location from app.py and provide documentation on how to add sponsors? That way it can be in a less crucial place, and the benefits of the current approach remain.

This issue is to decide on approach and confirm under TnM.

**Comment by dommitchell** [comment]
Please refer to issue #1470

**Comment by dommitchell** [comment]
Post call: the work in issue 1470 will not need this development. Leaving for now.
