### ISSUE TITLE
Change 'Login' to make it clear that this is for Admin, Editors and Publishers only

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1105]
We are suddenly getting a heap of emails from people asking how to register, or why they can't log in , why we don't have their email address etc etc.

I'd like to explore ways to make it clearer that the login button is only for Admin, Editors and Publishers.

Maybe we could add text next to it: 'Publishers only' (Admin and Editors would know to use the button anyway.)

**Comment by richard-jones** [comment]
@ClaraDOAJ - did you guys still want to do this, or have any other ideas as to what should be changed?

**Comment by ClaraDOAJ** [comment]
I don't get so many queries at the moment. Leave it for later when we have time.

**Comment by dommitchell** [comment]
Closing for now
