### ISSUE TITLE
OAI-PMH error message

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1107]
@DOAJplus I am having trouble using your oai-pmh server with the oai-doaj metadataPrefix. See doaj.org/oai?verb=ListR…

https://doaj.org/oai?verb=ListRecords&metadataPrefix=oai_doaj

<error code="cannotDisseminateFormat">The metadata format identified by the value given for the metadataPrefix argument is not supported by the item or by the repository.</error>

**Comment by richard-jones** [comment]
This would work if the user went to:

https://doaj.org/oai.article?verb=ListRecords&metadataPrefix=oai_doaj

There are 2 OAI endpoints on the DOAJ, and they support different formats.  See:

* Journals: https://doaj.org/oai?verb=ListMetadataFormats
* Articles: https://doaj.org/oai.article?verb=ListMetadataFormats

In the above request, the user is requesting an article format from the journal endpoint, which is behaving correctly by displaying an error.

**Comment by dommitchell** [comment]
Thanks!
