### ISSUE TITLE
Add "article level metadata" field to journal data model

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#1110]
Currently the "article level metadata" field is stored only in suggestions, but it should also be available in the derived journal object.  This change will require:
- Update of the journal data model
- Update creation of journal from application
- Update of journal forms
- Update of all form crosswalks
- Migration for existing re-applications to retrospectively populate the data

**Comment by dommitchell** [comment]
@richard-jones refactor project work?
