### ISSUE TITLE
Add OCLC logo on sponsors page

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1115]
We need to add OCLC logo in our sponsors page. The logo needs to be of a similar size as the rest. We also need to remove the Co-Action logo - they have been bought by Taylor&Francis.

Attached the logo and their url https://www.oclc.org/en-europe/home.html?redirect=true

Do you need me to modify the logo so it is the appropriate size, or will you do it?

Please see attached.
![oclc](https://cloud.githubusercontent.com/assets/22593616/19819864/e58d0dbc-9d56-11e6-8a66-5559cd59f381.png)

**Comment by Steven-Eardley** [comment]
Released now. The co-action logo was already removed in #1101

**Comment by ClaraDOAJ** [comment]
Thanks!

Clara Armengou
DOAJ - Community Manager
