### ISSUE TITLE
Set up S3 File server and S3 Fuse on test

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#1129]
+ instructions to wire up any dev machine to S3 test

**Comment by emanuil-tolev** [comment]
Some possible issues with this I've been researching last week.

I've selected https://github.com/s3fs-fuse/s3fs-fuse out of several alternatives due to POSIX compatibility (so no leaky abstractions - you can do to it what you can do to any other local file).

But ... the limitations section:

> Generally S3 cannot offer the same performance or semantics as a local file system. More specifically:

> - random writes or appends to files require rewriting the entire file

Don't care, as long as it takes care of it automatically.

> - metadata operations such as listing directories have poor performance due to network latency

Only very occasionally would we have to keep this in mind. (Large directory listings or an operation done often - **if done *every* time a task runs, could be an issue.**)

> - eventual consistency can temporarily yield stale data

I have to think about this a bit more (and have spent most of the time doing exactly that). That's the final big concern. @richard-jones can you paste the photo of the planned workflow that we drew on your whiteboard into this issue?

> - no atomic renames of files or directories

If we ever implement logic by rename, this might be an issue. (E.g. rely on renaming to result in the old file definitely not being there, or the new file being there immediately.)

> - no coordination between multiple clients mounting the same bucket

Hmmmm. Sounds like writing to the same file would be an issue (conflict) - not clear what the resolution strategy is. Of course we don't plan to do this.

There might be other effects, but we can only know if we try, I've not been able to find further info on the exact possible effects, short of reading the s3fuse source code.

> - no hard links

Fine.

**Comment by richard-jones** [comment]
![2016-11-16 09 12 55](https://cloud.githubusercontent.com/assets/856138/20341167/e7eeee42-abdc-11e6-99cd-b6688b4f16b2.jpg)

**Comment by richard-jones** [comment]
I'm not sure why the orientation is wrong, sorry!

**Comment by richard-jones** [comment]
Also, that's creepy that the photo on the wall behind is just visible over the top!

**Comment by emanuil-tolev** [comment]
Thanks Richard.

A little further info from the s3fs man page:

* * *

Due to S3's "eventual consistency" limitations, file creation can and will occasionally fail. Even after a successful create, subsequent reads can fail for an indeterminate
       time, even after one or more successful reads. Create and read enough files and you will eventually encounter this failure. This is not a flaw in s3fs and it is  not  some‐
       thing  a FUSE wrapper like s3fs can work around. The retries option does not address this issue. Your application must either tolerate or compensate for these failures, for
       example by retrying creates or reads.
