### ISSUE TITLE
DOAJ API Data analysis

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#1147]
I can run a one-off analysis on the server access logs and break down:

- by action (search articles, search journals, search both, create articles, create applications, retrieve individual articles or journals, etc.)
- by date

Agreed in meeting today this would be useful with @greboun and @ClaraDOAJ .

**Comment by dommitchell** [comment]
@emanuil-tolev @richard-jones can you remember what this was for? Is it solved by the Google Analytics stuff?
