### ISSUE TITLE
error when uploading

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1148]
Dear CL

This user gets an error in the notes even when the article has been successfully uploaded. Could you help me please?

Thank you for the email.

I honestly don't know what the error is as it says that it's been processed successfully. but in the notes it gives me the error message. When I click on explain then I'm redirected to a page that says that I have to contact you.

https://doaj.org/publishers#File%20system%20error%20when%20reading%20file
![image](https://cloud.githubusercontent.com/assets/22593616/21150872/d3b39bf0-c160-11e6-98a2-e74bafa1d7fc.png)
I hope that helps!

Regards

**Comment by richard-jones** [comment]
The top two records are very close together, one with an error and the
other not.  I guess the second from the top is the one which has caused the
error to be displayed.  Did the user just upload one file, or did they
upload multiple, do we know?

**Comment by ClaraDOAJ** [comment]
As far as I understand it was just one single file... 

This one according to her email:
SAJP file I tried to upload on th 8th of Dec 2016 gave me an "File system error when reading file"

**Comment by richard-jones** [comment]
Hm, very peculiar.

@emanuil-tolev - I notice this is a file system error, which suggests the inode problem resurfacing.  Is there any way that you can imagine that this error would be thrown initially, and then the file would get written and processed anyway?

I'm not sure I can think of a way that two FileUpload records could be created for the same account, so some investigation would be required.

So, a couple of thoughts:

* It's possible that the user accidentally uploaded the file twice, even if they think they didn't, which would account for it
* Do we know if anyone else has experienced this problem?
* We are about to replace all of this code with new code in February, so spending time debugging this might not have a lot of value.  Nonetheless, if it can be reproduced, we should look into it.

**Comment by emanuil-tolev** [comment]
> I notice this is a file system error, which suggests the inode problem resurfacing. Is there any way that you can imagine that this error would be thrown initially, and then the file would get written and processed anyway?

It's not the inode problem since we archive off all the history files every day now, I've been checking (and just re-checked). I'll think about how we can get more info on the problem though, maybe more in the logs (and look at what is in them now).

**Comment by richard-jones** [comment]
The user should have a go at re-uploading the file and let us know if they still experience an issue.

**Comment by ClaraDOAJ** [comment]
I keep`getting this sort of query very often. Today I got two of them. Unfortunately they do not give much detail, but I am concerned that is is happening so often.

Today I got a query from journal Vértices and Journal of Dental Research, Dental Clinics, Dental Prospects.

**Comment by ClaraDOAJ** [comment]
This is their xml

﻿<?xml version="1.0" encoding="UTF-8"?>
<records>
  <record>
    <language>eng</language>
    <publisher>Tabriz University of Medical Sciences</publisher>
    <journalTitle>Journal of Dental Research, Dental Clinics, Dental Prospects</journalTitle>
    <issn>2008-210X</issn>
    <eissn>2008-2118</eissn>
    <publicationDate>2016-12-21</publicationDate>
    <volume>10</volume>
    <issue>4</issue>
    <startPage>201</startPage>
    <endPage>206</endPage>
    <doi>10.15171/joddd.2016.032</doi>
    <publisherRecordId>JODDD_181_20161229121935</publisherRecordId>
    <documentType>article</documentType>
    <title language="eng">Assessment of the changes in alveolar bone quality after fixed orthodontic therapy: A trabecular structure analysis</title>
    <authors>
      <author>
        <name>Abdolaziz Haghnegahdar</name>
        <affiliationId>1</affiliationId>
      </author>
      <author>
        <name>Hooman Zarif Najafi</name>
        <affiliationId>2</affiliationId>
      </author>
      <author>
        <name>Maryam Sabet</name>
        <affiliationId>3</affiliationId>
      </author>
      <author>
        <name>Maryam Saki</name>
        <email>mary_sa68@yahoo.com</email>
        <affiliationId>4</affiliationId>
      </author>
    </authors>
    <affiliationsList>
      <affiliationName affiliationId="1">Department of Oral and Maxillofacial Radiology, School of Dentistry, Shiraz University of Medical Sciences, Shiraz, Iran</affiliationName>
      <affiliationName affiliationId="2">Orthodontics Research Center, Department of Orthodontics, School of Dentistry, Shiraz University of Medical Sciences, Shiraz, Iran</affiliationName>
      <affiliationName affiliationId="3">Student Research Committee, School of Dentistry, Shiraz University of Medical Sciences, Shiraz, Iran</affiliationName>
      <affiliationName affiliationId="4">Student Research Committee, Orthodontics Research Center, Department of Orthodontics, School of Dentistry, Shiraz University of Medical Sciences, Shiraz, Iran</affiliationName>
    </affiliationsList>
    <abstract language="eng">Background. Tooth displacement changes the periodontium. The aim of orthodontic treatment is desired tooth movement with minimum side effects on the alveolar bone quality. The aim of the present study was to assess changes of alveolar trabeculation in children, young adults and adults and the two genders. Methods. In this cross-sectional study, 63 patients who had been treated in Department of Orthodontics, School of Dentistry, Shiraz University of Medical Sciences, Shiraz, Iran, were chosen with convenient sampling method. They were divided into three groups based on their age. Their digitized panoramic radiographs (PRs) were evaluated at six interdental sites from the mesial aspect of the mandibular second molars to the distal aspect of the mandibular first premolars using a visual index. The trabeculation pattern was assigned as either dense (score 3), dense-sparse (score 2) or sparse (score 1). Data were imported to SPSS. Mean of the scores before treatment (score B) and mean of them after treatment (score A) were compared for each group with paired t-test. Changes between score B and sore A of the groups were compared using one-way ANOVA and post hoc tests. Results. Mean score A was significantly higher than mean score B in children (P = 0.001). In contrast, mean score A was significantly lower than mean score B in young adults (P = 0.003). Conclusion. Orthodontists should be cautious when treating young adults and adults regarding the probable, yet possibly temporary, negative effects of orthodontic therapy on the alveolar bone quality.</abstract>
    <fullTextUrl format="pdf">http://journals.tbzmed.ac.ir/JODDD/Manuscript/JODDD-10-201.pdf</fullTextUrl>
    <keywords language="eng">
      <keyword>Bone</keyword>
      <keyword>orthodontic appliances</keyword>
      <keyword>panoramic radiography</keyword>
    </keywords>
  </record>
</records>
