### ISSUE TITLE
question on xml file

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1149]
This user doesn't seem to be able to upload their file. Their OJS Support person at McMaster UniversityLibrary press edited the xml file to address the issue but it doesn't seem to be working. 

I am attaching the xml, if you please guys could have a look and see if there is something wrong, I'd be grateful. 

[hro-ors_export to doaj_2016-12-09.xml.zip](https://github.com/DOAJ/doaj/files/654336/hro-ors_export.to.doaj_2016-12-09.xml.zip)

**Comment by richard-jones** [comment]
Can you tell me how they're going about uploading it.  Is this via the UI or through the API from OJS?  Also, are there any details on the error?

The file you attach is a zip file, which definitely won't work if they upload it, it would need to be unzipped first.

**Comment by ClaraDOAJ** [comment]
Hi!
Ah, I attached the zip file because git hub wouldn't let me attach an xml
(apparently). They did send me an xml. They normally use the OJS plug in to
upload.
Many thanks!

Clara Armengou
DOAJ - Community Manager

**Comment by ClaraDOAJ** [comment]
Hello
Did you have the chance to look at this? 

Thanks!

**Comment by richard-jones** [comment]
I've run an upload test on this on the test server, and everything imported fine.  I did notice that there are two journals associated with the mcmaster university press for different accounts, so perhaps they were uploading it to the wrong one?

**Comment by ClaraDOAJ** [comment]
I think they have sorted it out. I see content from 2017.
Thanks!
