### ISSUE TITLE
xml problems 

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1162]
I got this email from a user and I don't know how to sort it out

------

I am trying to validate an XML file using the file  doajArticles.xsd
The message I get is
Cvc-elt.1.a: Cannot Find The Declaration Of Element 'xs:schema'., Line '3', Column '65'.

Line 3 of the file doajArticles.xsd  reads
"http://email.doaj.org/c/eJwtjc0KgzAQhJ_G3Az7Yw17yKEXX6Nkk7XaHxQVfP1GKAzDfIeZKZEZi7o5EmCPxNU7ZPEUQgDPLHBrOihLerVpXVt0U1QCNRqDmgKO0pkZ5d6oCIgoZveJ03GsDd8bGqrO8_TXgF-2Z8U9T_ZNe03zvjx6lpa0AnpwWxzNiqb8_n9elR8y_y8r"

I type this address on a web browser and gives an error message

If you are looking for a piece of content, it looks like that item has either been removed from DOAJ or has moved. Send feedback to us by using the Contact link at the bottom of the page.

Please tell me the correct address for
"http://email.doaj.org/c/eJwtjc0KgzAQhJ_G3Az7Yw17yKEXX6Nkk7XaHxQVfP1GKAzDfIeZKZEZi7o5EmCPxNU7ZPEUQgDPLHBrOihLerVpXVt0U1QCNRqDmgKO0pkZ5d6oCIgoZveJ03GsDd8bGqrO8_TXgF-2Z8U9T_ZNe03zvjx6lpa0AnpwWxzNiqb8_n9elR8y_y8r"
in line 3 of  doajArticles.xsd.

Thanks,

**Comment by richard-jones** [comment]
Probably the XML being supplied is wrong, though it is difficult to say in what way.

The doajArticles.xsd URL is a red-herring, that's just a namespace that we use for the language codes, and it doesn't resolve to anything (and doesn't need to).

If they can't figure it out, if they send the XML we can take a look.
