### ISSUE TITLE
xml that appear to be correct but records are not updating

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1163]
![upload_xml](https://cloud.githubusercontent.com/assets/22593616/21784470/f0750542-d6bb-11e6-8dec-a920efffc607.jpg)
These are the records from user 03044866
Thanks

**Comment by richard-jones** [comment]
To debug this we will need:

* Which field did they expect to change
* Could we get the article upload XML again from them
* which DOIs/which query to see the records they expected to get updated
