### ISSUE TITLE
problem with test API

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1181]
Email from user

Could you help me with this?

We are trying to test create article API on your page with a key:

f6eaa7b4c5144bbab9b62a8a1df02c6b

given to "Econviews: Review of Contemporary Business, Entrepreneurship and Economic Issues" journal, but after submiting a form we get response:

{
  "status": "forbidden",
  "error": " (ref: 98fb9b04-d84c-11e6-8202-04014a62b401)"
}

Response code: 403

What are we doing wrong? Thx.

**Comment by richard-jones** [comment]
We need a bit more information to be able to diagnose this.  Can they give us the URL they were posting to, and what data they were posting?

They mention posting to a form, which is confusing, as the API and the form are different, so maybe there's just some crossed wires there?

**Comment by emanuil-tolev** [comment]
This is definitely an API response. I assume by form they mean the demos on the API docs page, which have a Try it out! buttong and input fields.
