### ISSUE TITLE
DOAJ support button

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1182]
Dear CL

Can we change the colour of DOAJ support button so it is more visible? Maybe blue?

I have made some changes on the static page so this button will now need to point to membership.html (first on test site)

Also can we have this button on the right hand side below the social networks icons?

Thanks!

**Comment by Steven-Eardley** [comment]
How's this:

<img width="1501" alt="screen shot 2017-01-19 at 15 46 00" src="https://cloud.githubusercontent.com/assets/1446355/22113565/9389d8f8-de5e-11e6-93fe-80dfbf67190c.png">

I think the button looks good there; do you still want it to be blue?

**Comment by ClaraDOAJ** [comment]
Looks good, but I would have it in both places, given the one on top was a heading and can be seen in every single page.

Also, remember the button now needs to point to the membership.html page.

Many many thanks!

**Comment by Steven-Eardley** [comment]
Both places it is! And yes, I've made the change to its target. Is the old page to be removed?

**Comment by ClaraDOAJ** [comment]
Yes. Remove old page but do not throw it away. :P I might need to see if other things point to it and need to change them...

**Comment by Steven-Eardley** [comment]
This is live now

**Comment by ClaraDOAJ** [comment]
looks great! thanks
