### ISSUE TITLE
CRITICAL article_cleanup_sync is duplicating articles

### ISSUE THREAD

**Issue by Steven-Eardley** [DOAJ/doaj#1183]
Running this locally, it's using lots of CPU and my article count is climbing. This is not the desired behaviour. Actually, that's one of the things it was supposed to be fixing.

All of the scary labels have been used. ->

**Comment by Steven-Eardley** [comment]
While running ```article_cleanup_sync.py -w -p``` to prepare all articles and pick up the new ```index.has_seal```  for #985

**Comment by richard-jones** [comment]
We have a new version of the script as a background task, is it that one or the old one that is causing the problem?

Presumably this isn't being done on live, right?  As in, we haven't duplicated articles in live at this stage?  As long as this script is not on a cron, then lets just make sure we don't run it.  If it is on a cron, can you remove it?

**Comment by emanuil-tolev** [comment]
This script does not currently run on live. It has been run a few times however.

Did we have a duplicates script in place as well? We can easily reuse the duplicate detection behaviour from the article upload code used for the various ways you can enter an article into DOAJ.

**Comment by emanuil-tolev** [comment]
Whatever it is, we should best write a test for it since it was subtle enough not to be picked up in code review.

**Comment by Steven-Eardley** [comment]
I was running the background task version, and yes, we need to disable that version from running on test via the Huey schedule. I haven't checked whether it's previously had an effect on live yet.

**Comment by richard-jones** [comment]
@Steven-Eardley and I have been investigating, and the script looks good, but it consumes a lot of resources when it runs.  We're currently working on reducing its resource usage.

**Comment by richard-jones** [comment]
This issue has been dealt with.  The article duplication was an artefact of the test data, but we've done some detailed analysis of the behaviour of the script and significantly improved its memory performance.  The new version of the script is now on test and will go live with the new background jobs.
