### ISSUE TITLE
Embedded metadata for Google Scholar

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#12]
As promised, please find following both the "full" and then the "abbreviated"
set of "citation_XX" metatags that could be used for Scholar indexing.  As we
chatted about, the abbreviated set would be perfect for DOAJ:

JOURNAL ARTICLE EXAMPLE (FULL)

```
<meta name="citation_journal_title" content="Journal of Biological Chemistry">
<meta name="citation_journal_abbrev" content="J Biol Chem"> (Multiple
abbreviations are ok)

<meta name="citation_publisher" content="ASBMB">

<meta name="citation_author" content="Nazumi Alice Yamada">
<meta name="citation_author_institution" content="Lawrence Livermore
National Laboratory, Livermore, CA 94551">  (Multiple institutions are ok)

<meta name="citation_author" content="John M. Hinz">
<meta name="citation_author_institution" content="School of Molecular
Biosciences, Washington State University, Pullman, Washington">
<meta name="citation_author_email" content="jmhinz@wsu.edu
<mailto:jmhinz@wsu.edu> ">
<meta name="citation_author" content="Larry H. Thompson">
<meta name="citation_author_institution" content="Lawrence Livermore
National Laboratory, Livermore, CA 94551">
<meta name="citation_author_email" content="thompson14@llnl.gov
<mailto:thompson14@llnl.gov> ">

<meta name="citation_title" content="XRCC3 ATPase Activity Is Required
for Normal XRCC3-Rad51C Complex Dynamics and Homologous
Recombination">

<meta name="citation_publication_date" content="2004/05/24">

<meta name="citation_volume" content="279">

<meta name="citation_issue" content="22">

<meta name="citation_firstpage" content="23250">
<meta name="citation_lastpage" content="23252">

<meta name="citation_doi" content="10.1074/jbc.M402247200">
<meta name="citation_pmid" content="15037616">  -- This is the PubMed Id
<meta name="citation_arxiv_id content="arXiv:astro-ph/9710327">

<meta name="citation_abstract_html_url"
content="http://www.jbc.org/cgi/content/abstract/279/6/4034
<http://www.jbc.org/cgi/content/abstract/279/6/4034> ">
<meta name="citation_fulltext_html_url"
content="http://www.jbc.org/cgi/content/full/279/6/4034
<http://www.jbc.org/cgi/content/full/279/6/4034> ">
<meta name="citation_pdf_url"
content="http://www.jbc.org/cgi/reprint/279/6/4034.pdf
<http://www.jbc.org/cgi/reprint/279/6/4034.pdf> ">

<meta name="citation_issn" content="ISSN Of the Journal"> (multiple
ISSNs are ok)

<meta name="citation_language" content="Language Name">
<meta name="citation_keywords" content="keyphrase1; keyphrase2; ...">
```

(Multiple citation_keywords tags are ok).

JOURNAL ARTICLE EXAMPLE (ABBREVIATED)

```
<meta name="citation_journal_title" content="Journal of Biological Chemistry">


<meta name="citation_publisher" content="ASBMB">
<meta name="citation_author" content="Nazumi Alice Yamada">
<meta name="citation_author" content="John M. Hinz">
<meta name="citation_author" content="Larry H. Thompson">


<meta name="citation_title" content="XRCC3 ATPase Activity Is Requiredfor Normal
XRCC3-Rad51C Complex Dynamics and HomologousRecombination">

<meta name="citation_publication_date" content="2004/05/24">

<meta name="citation_volume" content="279">

<meta name="citation_issue" content="22">

<meta name="citation_firstpage" content="23250">
<meta name="citation_lastpage" content="23252">


<meta name="citation_pdf_url"
content="http://www.jbc.org/cgi/reprint/279/6/4034.pdf
<http://www.jbc.org/cgi/reprint/279/6/4034.pdf> "> (only if the PDF is also
hosted on DOAJ.org)

<meta name="citation_issn" content="ISSN Of the Journal"> (multiple
ISSNs are ok)
```

Note that embedding these into the DOAJ site would require that the individual
articles with their abstracts have their own URLs or landing pages (linked to
sans Javascript from the browse/TOC/search results). Is this possible?

From Google Scholar: As well as "citation_XX" metatags, can you

(1) Create a per-article abstract page for each article
Currently, there isn't a separate page for each article - abstracts are shown via javascript - see
http://doaj.org/search?source={%22query%22:{%22match_all%22:{}}}

and

(2) Add an XML sitemap (e.g. http://doaj.org/sitemap.xml) with URLs of all such article landing pages
You could then include it in your robots.txt file as
Sitemap: http://doaj.org/sitemap.xml

**Comment by richard-jones** [comment]
@markmacgillivray - need to take this into account for ToC generation

Otherwise, also see #178 - probably some crossover.

**Comment by emanuil-tolev** [comment]
Need to check today about the status of article pages since they are required before we put metadata on them :). @Steven-Eardley ?

**Comment by Steven-Eardley** [comment]
It'll be started in the next week or so; the current plan is to shoehorn the same list of fields from the public search results into a modified copy of the journal TOC template.

How would you like the meta tags included?

**Comment by emanuil-tolev** [comment]
Not sure yet, will be investigating here what ones we need and what we can do (like can we do Keywords based on a bit of simple ES text mining, what tags are best currently for Google and other engines, can we autowrite a Description..). All this will happen in parallel to article pages being developed. Once the article pages are up just say :) and I'll add the meta tags we've come up with.

**Comment by emanuil-tolev** [comment]
Articles pages are now done so this can proceed

**Comment by dommitchell** [comment]
@emanuil-tolev @richard-jones do we have anything to look at so that I can ask Google to test?

**Comment by dommitchell** [comment]
From Google: "Regarding the testing, it would be great to see some example article landing pages, with the "citation_XX" metatags included, as well as the sitemap file (just to confirm the size + structure); it's pretty common to have a few iterations on how best to format the values in the metatags for improved indexing + accuracy in search results, etc., so it would be lovely to help with that process/make it as easy as possible. "

I am not promising iterations yet but it would be nice to get their feedback.

**Comment by dommitchell** [comment]
@emanuil-tolev @richard-jones Sorro to nag but I'd really like to know whether there is anything I can show Google Scholar. Thanks!

**Comment by richard-jones** [comment]
@dommitchell - Metadata should be available later this evening, @emanuil-tolev is just working on the PR right now.

In terms of providing the sitemap discussed above, we decided for PVOD not to include the single article pages in the sitemap because - since there are so many of them - it requires a fundamental change to the way that we structure them: we would exceed the standard sitemap format's size and content limits, so need to do something more advanced.

If you want to consider extending the sitemaps to cover individual article pages we can look into doing it, but it will be a non-trivial amount of work.

**Comment by emanuil-tolev** [comment]
> <meta name="citation_pdf_url"
> content="http://www.jbc.org/cgi/reprint/279/6/4034.pdf
> <http://www.jbc.org/cgi/reprint/279/6/4034.pdf> "> (only if the PDF is also
> hosted on DOAJ.org)

Er, the PDF is never ever hosted on DOAJ.org. I've excluded the full-text URL from this for now. @dommitchell feel free to explain to Google that DOAJ is just a metadata catalogue, and to confirm if we are allowed to post full-text URL-s to the PDF-s in the metadata. We are naturally legally allowed, as these articles are all open access, but does it somehow affect or break the harvest mechanisms they have in place?

**Comment by emanuil-tolev** [comment]
OK, PR pending.

**Comment by emanuil-tolev** [comment]
@dommitchell give the Google guys this: https://doaj.cottagelabs.com/article/0000178c89214dc8b82df1a25c0c478e

Plenty more examples at https://doaj.cottagelabs.com/search . Clicking on the title of any *article* record will take you to the article landing page, with abstract and meta tags.

**Comment by dommitchell** [comment]
Someone has noticed that we don't include <meta name="citation_doi" content="xxxx"> in every article. 

https://doaj.org/article/519ebe21d82e417dad362c6bfc9eecf3

Is there a reason for that? Did we decide not to support that?

Note that the article has a DOI
