### ISSUE TITLE
DHET and DOAJ comparison

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1202]
Dear CL

As per Tom's request yesterday, I am attaching the DHET list to be compared with our database. Tom said that it should not be very difficult with the issns.
Thanks!
[2016-17 Journal Lists.zip](https://github.com/DOAJ/doaj/files/745315/2016-17.Journal.Lists.zip)

**Comment by greboun** [comment]
Dear CL

Can you attend to this issue with priority?
The sooner we have the comparison #1202   the better

Thanks

TOM



Dr. Tom Olijhoek
Editor-in-Chief  DOAJ
Support us: www.doaj.org/support

**Comment by Steven-Eardley** [comment]
I created a [couple of scripts](https://github.com/Steven-Eardley/doaj_api_scripting) to run this comparison on the public search API. This means we only see results for ISSNs that are in_doaj. 

Because there are two files with some overlap, in the 2016 one I only read the 2016 sheets, and in the 2017 one I only read the 2017 sheets.

First I found all unique ISSNs in each Excel sheet and asked the DOAJ search API whether it had that Journal:
```
Opening 2016 workbook DHET Accredited journal lists for publications made 2016.xls
	Reading sheet DHET 2016
		Found 341 ISSNs. 4 duplicate(s) on the sheet.
		65 ISSNs are present in the DOAJ.
	Reading sheet IBSS 2016
		Found 2991 ISSNs. 2 duplicate(s) on the sheet.
		179 ISSNs are present in the DOAJ.
	Reading sheet ISI 2016
		Found 22346 ISSNs. 862 duplicate(s) on the sheet.
		1431 ISSNs are present in the DOAJ.
	Reading sheet Norwegian List 2016
		Found 3884 ISSNs. 0 duplicate(s) on the sheet.
		59 ISSNs are present in the DOAJ.
	Reading sheet ScieLO SA 2016
		Found 120 ISSNs. 1 duplicate(s) on the sheet.
		64 ISSNs are present in the DOAJ.
	Reading sheet Scopus 2016
		Found 29882 ISSNs. 19 duplicate(s) on the sheet.
		0 ISSNs are present in the DOAJ.

Opening 2017 workbook DHET Accredited journal lists for publications to be made in 2017.xls
	Reading sheet DHET 2017
		Found 346 ISSNs. 2 duplicate(s) on the sheet.
		72 ISSNs are present in the DOAJ.
	Reading sheet IBSS 2017
		Found 2691 ISSNs. 4 duplicate(s) on the sheet.
		172 ISSNs are present in the DOAJ.
	Reading sheet ISI 2017
		Found 22614 ISSNs. 1008 duplicate(s) on the sheet.
		1485 ISSNs are present in the DOAJ.
	Reading sheet Norwegian List 2017
		Found 3872 ISSNs. 0 duplicate(s) on the sheet.
		67 ISSNs are present in the DOAJ.
	Reading sheet ScieLO SA 2017
		Found 127 ISSNs. 1 duplicate(s) on the sheet.
		70 ISSNs are present in the DOAJ.
	Reading sheet Scopus 2017
		Found 30657 ISSNs. 20 duplicate(s) on the sheet.
		0 ISSNs are present in the DOAJ.
```

Next, I tweaked the script to assume they're one journal per line (I think they all are) and see how many journals were visible by one or both (if present) ISSNs it finds in each row of the sheet, to get an idea of how many journals we have complete information for, and whether these spreadsheets are worth getting information from:

```
Opening 2016 workbook DHET Accredited journal lists for publications made 2016.xls
	Reading sheet DHET 2016
		Found 277 rows containing ISSNs.
		17 journals found by both ISSNs, 31 found by one, 229 found by neither.
	Reading sheet IBSS 2016
		Found 2993 rows containing ISSNs.
		0 journals found by both ISSNs, 179 found by one, 2814 found by neither.
	Reading sheet ISI 2016
		Found 12558 rows containing ISSNs.
		370 journals found by both ISSNs, 691 found by one, 11497 found by neither.
	Reading sheet Norwegian List 2016
		Found 2076 rows containing ISSNs.
		20 journals found by both ISSNs, 19 found by one, 2037 found by neither.
	Reading sheet ScieLO SA 2016
		Found 61 rows containing ISSNs.
		31 journals found by both ISSNs, 3 found by one, 27 found by neither.
	Reading sheet Scopus 2016
		Found 22414 rows containing ISSNs.
		0 journals found by both ISSNs, 0 found by one, 22414 found by neither.

Opening 2017 workbook DHET Accredited journal lists for publications to be made in 2017.xls
	Reading sheet DHET 2017
		Found 277 rows containing ISSNs.
		24 journals found by both ISSNs, 24 found by one, 229 found by neither.
	Reading sheet IBSS 2017
		Found 2695 rows containing ISSNs.
		0 journals found by both ISSNs, 172 found by one, 2523 found by neither.
	Reading sheet ISI 2017
		Found 12662 rows containing ISSNs.
		386 journals found by both ISSNs, 714 found by one, 11562 found by neither.
	Reading sheet Norwegian List 2017
		Found 2042 rows containing ISSNs.
		24 journals found by both ISSNs, 19 found by one, 1999 found by neither.
	Reading sheet ScieLO SA 2017
		Found 65 rows containing ISSNs.
		34 journals found by both ISSNs, 3 found by one, 28 found by neither.
	Reading sheet Scopus 2017
		Found 22704 rows containing ISSNs.
		0 journals found by both ISSNs, 0 found by one, 22704 found by neither.
```

As I mentioned before, then main thing missing from my analysis is how many of these journals are in the database but are not public, or how many are sitting in the system as applications and are yet to be journals. That's because I only used the public interface.

**Comment by emanuil-tolev** [comment]
> As I mentioned before, then main thing missing from my analysis is how many of these journals are in the database but are not public, or how many are sitting in the system as applications and are yet to be journals. That's because I only used the public interface.

That's fine, the definition of `DHET and DOAJ comparison` is "what is publicly available by DHET and DOAJ" to me.

**Comment by greboun** [comment]
I now have received a list of South African open access journals in DHET , this can be compared with the DOAJ list and probably shows high overlap Could you run this Steven?
[doaj_oa.xlsx](https://github.com/DOAJ/doaj/files/799059/doaj_oa.xlsx)

**Comment by ClaraDOAJ** [comment]
Let's revitalise this again, please.

**Comment by dommitchell** [comment]
No longer needed.
