### ISSUE TITLE
display bug

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1205]
Here you have an email by an editor. Can you help, please?

I have been making some changes to Alan Bowen's IRCPS website in order to automate the creation, updating, and deletion of records on the DOAJ site. Alan and I have noticed one thing which would appear to be a display bug on your end. If you go to https://doaj.org/article/bcf38a30455a4b50ad07d4d19ae47935, you'll see that the volume and page number information is given as: 

2010;78-12

I'm not sure what it should be, in your citation format, but this is certainly a mistake. The volume # is 7, and the page numbers are 8-12. There should be a space or some other delimiter after the 7.

**Comment by emanuil-tolev** [comment]
They appear to be correct in the bug report.

Here's a snippet of the relevant data:

```json
    "bibjson": {
      "end_page": "12",
      "start_page": "8",
      "volume": "7",
}
```

It seems it is properly recorded in the datastore, but not displayed quite right.

**Comment by ClaraDOAJ** [comment]
What would the solution be?

**Comment by emanuil-tolev** [comment]
Sorry, should've clarified I've not looked into the exact problem, just confirming that it's not a case of the publisher's data being wrong. I.e. the publisher gave us correct info.

**Comment by richard-jones** [comment]
It's just a missing ":" in the template for the page.  If you take a look at ToC search results you'll see how it should be displayed:

**Comment by richard-jones** [comment]
http://doaj.org/toc/1549-4497?source=%7B%22query%22%3A%7B%22filtered%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22range%22%3A%7B%22index.date%22%3A%7B%22lt%22%3A%221293840000000%22%2C%22gte%22%3A%221262304000000%22%7D%7D%7D%2C%7B%22term%22%3A%7B%22index.issn.exact%22%3A%221549-4497%22%7D%7D%2C%7B%22term%22%3A%7B%22_type%22%3A%22article%22%7D%7D%5D%7D%7D%2C%22query%22%3A%7B%22match_all%22%3A%7B%7D%7D%7D%7D%2C%22from%22%3A0%2C%22size%22%3A100%7D

**Comment by richard-jones** [comment]
@Steven-Eardley - could you take a look at this and update the template for the article page?

**Comment by Steven-Eardley** [comment]
Aye, I'll get on it

**Comment by Steven-Eardley** [comment]
Fixed now on live.

**Comment by richard-jones** [comment]
@ClaraDOAJ - can you just check this quickly for us and make sure it's as you want on live.  Then this can be closed.

**Comment by ClaraDOAJ** [comment]
Fixed!
