### ISSUE TITLE
Testing: Feature 5- Removing a single journal from DOAJ (and putting it back in).  

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1213]
In general this feature did work both in IE and Firefox. The only concern is the fact that the action is queued and we don't get a notification of when this has been done.

It was tested by one of our team members in Chrome and he reported the journal Removing 1932-6246
 was not removed.

**Comment by richard-jones** [comment]
So, this is an issue with notification of the action, rather than the action itself?

Let me know if this is still a problem after the lastest update.

**Comment by ClaraDOAJ** [comment]
That is fine. We can close this issue.

Many thanks!
