### ISSUE TITLE
Testing: Feature 2- On the admin > Journals and Articles (Admin) page, you will find 5 bulk actions

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1215]
We experienced several errors in Safari. Tried to delete a journal from Bahrain and we encountered the following error "There was an error with your request."

We also had the following error examples

**Delete articles, Journals vs. Articles: article In DOAJ?: T Subject: Medicine** 
Publisher: MDPI AG Journal title (Articles): Cancers 
Withdrew, reinstate hindawi
note on mdpi and added it to my group, didn't work

unable to delete articles, "error with your request"

note on mdpi and added it to Rikard group, didn't work

Browser: Internet Explorer
What did you test? delete articles, Journals vs. Articles: article In DOAJ?: T Subject: Medicine 
Publisher: MDPI AG Journal title (Articles): Cancers 
Withdrew, reinstate hindawi
note on mdpi and added it to my group, didn't work

Was the result correct? unable to delete articles, "error with your request"
withdrew hindawi, reinstate hindawi did work
note on mdpi and added it to Rikard group, didn't work

Browser: Firefox
What did you test? Delete Hindawi articles from Doaj 
Was the result correct? No
Delete Hindawi articles from Doaj (again)
“There was an error with your request.”
Hindawi journals withdraw from Doaj. Yes. Queued
Reinstate the same. Yes Queued
Assign journals to ed. Group. Yes, queued
Add a note. Yes, queued

**Comment by emanuil-tolev** [comment]
Delete should be working very soon - I'm fixing that. Thanks for reporting.

Is this basically the only action that didn't work as expected? From the feedback it seems it's just deleting that you had trouble with (which is good, we already know about that from our prev. meeting).

**Comment by ClaraDOAJ** [comment]
No, I am reporting other things at the moment.

**Comment by emanuil-tolev** [comment]
> note on mdpi and added it to Rikard group, didn't work

> note on mdpi and added it to my group, didn't work

We might need to double check ourselves. Maybe ask him what selection of journals he tried to add a note to so we can try to replicate with the same data.

**Comment by richard-jones** [comment]
@ClaraDOAJ - can you re-check whether the issues with adding notes re-surfaced, and give us some more details if this is still a problem?

**Comment by ClaraDOAJ** [comment]
I have tested this and the tasks have been queued, so it looks it is working. As soon as these three jobs have been done, this ticket can be closed.

set_in_doaj by clara status: queued
Job ID: 8df67d4fa25645f3a75fef2371a4504d
Job Created: 6 Mar 2017 at 17:53
Job Last Updated: 6 Mar 2017 at 17:53

More Information
set_in_doaj by clara status: queued
Job ID: 859d51c0b96547b3b1affa7d2ac6b639
Job Created: 6 Mar 2017 at 17:52
Job Last Updated: 6 Mar 2017 at 17:52

More Information
set_in_doaj by clara status: queued
Job ID: ec75f9acaf5d4f24b60dafd2cc5575f4
Job Created: 6 Mar 2017 at 17:52
Job Last Updated: 6 Mar 2017 at 17:52
