### ISSUE TITLE
Testing:Feature 6- Uploading article XML.  

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1216]
Browser: Google Chrome v. 56
What did you test? I tested the upload of a journal issue exported from OJS using the DOAJ Export Plugin
Was the result correct? The upload failed, while the same file was successfully uploaded in mid January to the live website (I’ll put it in a folder)
As I tend to be stubborn, I tried to upload a single-article XML (as before, it was successfully updated on the live version), same result. 

Browser: Microsoft Edge
What did you test? I tested the same files
Was the result correct? It took more that half an hour to get the responses, and the uploads failed again

**Comment by emanuil-tolev** [comment]
If possible:

- the files that they attempted to upload?
- which user account uploaded them and around what date and time did they upload them? I can go and have a look at the failed uploads in more detail then

**Comment by richard-jones** [comment]
@ClaraDOAJ - did you get a chance to get together the things that @emanuil-tolev was looking for above?  Then we can take a detailed look at what went wrong here.

**Comment by emanuil-tolev** [comment]
One piece of data to possibly help:

```json
{
  "_index" : "doaj",
  "_type" : "upload",
  "_id" : "12519782002b475ca918a5a7caf8066d",
  "_version" : 3,
  "found" : true,
  "_source":{"status": "failed", "error": "All articles in file failed to import", "last_updated": "2017-02-17T13:55:32Z", "created_date": "2017-02-03T06:53:07Z", "owner": "ilaria", "schema": "doaj", "id": "12519782002b475ca918a5a7caf8066d", "filename": "journal-1 (1).xml"}
}
```

**Comment by emanuil-tolev** [comment]
@ClaraDOAJ for the most recent article upload failure: the file was submitted by "ilaria". But this account does not own any journals. Users would need to submit article uploads as the publisher who owns the journals.

**Comment by richard-jones** [comment]
@ClaraDOAJ - if you're happy that this is now working, you can close this issue when you are ready.
