### ISSUE TITLE
Testing: Feature 11- Several aspects of the application form implementation changed

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1217]
Instructions:
erify that the application form works in all the appropriate contexts.

- the public interface
- managing editors
- editors and associate editors

Examples of failed testing:

Browser: Internet Explorer
What did you test? Looked at application form in public, editor, and admin view
Was the result correct? No, fields appear outside the orange frames.
Graphics generally look as if in fail safe mode… see screenshot

Browser: Safari
What did you test? View form while logged out, and logged in as public, admin and editor mode
Was the result correct? No. Poor layout of questions 25, 28, 33, 48 and 51.  Selecting “Other” in questions 25, 28, 33 and 51 leads to error, as the form requires further information but there is nowhere to enter it.

Browser: Google Chrome v. 56 / Microsoft Edge

What did you test? I tested one random ready journal as managing editor, and I checked mandatory fields (eg. Archiving Policy: if you answer something different than “None”, if the form was incorrect). 
Was the result correct? Partly: if you select “Other”, then there is no field where to put the answer

**Comment by richard-jones** [comment]
@ClaraDOAJ - can you attach the screenshot for me?

**Comment by ClaraDOAJ** [comment]
![image](https://cloud.githubusercontent.com/assets/22593616/23101287/626754b8-f690-11e6-9029-fd349bdad04d.png)

**Comment by emanuil-tolev** [comment]
@ClaraDOAJ this should be fixed now. See https://testdoaj.cottagelabs.com/application/new#digital_archiving_policy-container (question 25 on test) for example. Could the reporter retry this?

**Comment by ClaraDOAJ** [comment]
Fixed!

**Comment by greboun** [comment]
I tested the application form with testjournal
All OK now
tried to fill out date of first open access as 2017003  and this was
detected
wrong formats URL were not accepted
other boxes were functional
THANKS
TOM

Dr. Tom Olijhoek
Editor-in-Chief  DOAJ
Support us: www.doaj.org/support
