### ISSUE TITLE
Bulk actions UI feedback is confusing

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#1220]
- "queued for editing" is confusing, consider "queued for execution"
- we should email people when the job starts, and when it finishes
- immediately after a bulk action is submitted, we should direct people to some place where they can easily see the progress of their job with instructions on what will happens next (expect an email, it will not happen immediately, etc.)

Anything else @ClaraDOAJ @greboun ?

**Comment by emanuil-tolev** [comment]
On the individual journal pages, Putting a journal into DOAJ and removing it from DOAJ now behaves very differently (does not update the button). May need to rethink that part of the UI and also make it clearer it won't happen immediately (but the person will get an email when it happens).

**Comment by richard-jones** [comment]
A new version of the feedback interface has been provided.

**Comment by ClaraDOAJ** [comment]
many thanks! ;)
