### ISSUE TITLE
Should we just remove the Delete records bulk action

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#1221]
This will leave only Withdraw/Reinstate. Only certain people (probably CL) will be able to do a drastic delete.

It's also confusing to have both Withdraw and Delete in the dropdown, delete being much more severe and not undoable.

**Comment by richard-jones** [comment]
I wonder if there's a way to make the delete option only appear if you have a specific system role?  This would have to exclude the "admin" role explicitly, though, so we could add a "bulk_delete" role to our accounts, to differentiate them from other managing editor roles.

**Comment by richard-jones** [comment]
reference: #1215

**Comment by richard-jones** [comment]
Delete is now only available to users with the ultra_bulk_delete role (that includes admins)

**Comment by ClaraDOAJ** [comment]
Thanks!
