### ISSUE TITLE
names of publishers starting with u' and duplicates

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1222]
We discovered a possible bug with our data, in this case publisher names. I use the Publisher facet and let it count 200. Below you will for instance see De Gruyter Open listed twice and David Publishing Company as well.

There is quite a few publisher names starting with u` and in brackets, see screenshot.

Is this a bug?

![image](https://cloud.githubusercontent.com/assets/22593616/23014259/76e1764e-f42e-11e6-9095-a4bd2e8af336.png)

**Comment by emanuil-tolev** [comment]
#1196 is related to this and a hotfix is in review for it

**Comment by emanuil-tolev** [comment]
This is now rolled out on live. Is it fixed? (You didn't say what search query you were using when you saw the problem, so I'm not sure how to get to the same search results on live to check.)

**Comment by ClaraDOAJ** [comment]
It looks like it is fixed. Many thanks!

**Comment by ClaraDOAJ** [comment]
Still seeing the problem in Admin- Applications ![image](https://cloud.githubusercontent.com/assets/22593616/23204511/224044f4-f8e7-11e6-876d-b1cb13a89036.png)

**Comment by ClaraDOAJ** [comment]
fixed
