### ISSUE TITLE
delete articles that start with http://

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1228]
The site of the Journal "Annales du patrimoine" ISSN: 1112-5020 has changed from (http://) to (https://)

I made the changes for the important urls, but all the articles that start with "http:// need to be deleted.

Could you do this for me?

Thanks

**Comment by richard-jones** [comment]
Is it possible to define a set of search criteria that identify those articles.  So, starting from:

https://doaj.org/admin/admin_site_search?source=%7B%22query%22%3A%7B%22filtered%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22term%22%3A%7B%22_type%22%3A%22article%22%7D%7D%5D%7D%7D%2C%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%22%5C%221112%5C%5C-5020%5C%22%22%2C%22default_operator%22%3A%22AND%22%7D%7D%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D

Are there any further refinements that define this set of articles?

If not, can you define in more detail for us the criteria that you want to use?

**Comment by ClaraDOAJ** [comment]
I think that the publisher just want all the articles that start with http:// without the "s" to be deleted. This is very difficult for me to find. Once they are deleted, they will upload metadata again. 

Another solution would be just removing everything and ask them to reupload their whole thing again. I would be happy with this if it is too difficult. - and see if the publisher agrees.

Thanks

**Comment by ClaraDOAJ** [comment]
Hello,

The publisher just agreed that I delete all the content and they will upload it again. I am closing this issue.

Many thanks!
