### ISSUE TITLE
Next articles right arrow doesn't wrap nicely

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#123]
See screenshot. Happens when window is resized. Right arrow is pushed out of its box.

![right_arrow](https://f.cloud.github.com/assets/5955396/2397765/570064da-a9ee-11e3-8548-f3d7882e158e.gif)

**Comment by richard-jones** [comment]
I've re-written the pager using a more bootstrap approach.  It will still wrap on a screen that is too small, but it will do so less brokenly.

**Comment by dommitchell** [comment]
New orange arrow doesn't invoke the 'pointer' symbol when you hover over it with the mouse, so it doesn't look like its hyperlinked. Am using FF
Mozilla/5.0 (Windows NT 6.3; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0

**Comment by dommitchell** [comment]
Also, can we make the image a couple of sizes bigger? It's a bit lost just now.

**Comment by richard-jones** [comment]
both done, ready for review at next PR

**Comment by dommitchell** [comment]
Great!
