### ISSUE TITLE
merged to accounts and the journal does not display

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1235]
Something weird, here.

A user requested me to merge two journals into their other account so they could access them as a single username. One of them did merge but the other does not appear under this user's list. If I go to the journal, it does have the correct username!!

The username is 19999637 and I had to merge AJHPE and SAJCC.  AJHPE is visible but SAJCC is not. I think I am doing something wrong or there is a bug. I've done this many times, so I do not understand what's wrong.
Thanks!

**Comment by emanuil-tolev** [comment]
You:

1. Went to https://doaj.org/admin/journal/10265879af1b4392845a8c7d1be9c6a9 , the Southern Afican Journal of Critical Care
2. Changed the Owner to `1999 7639`
3. Went to user 19997639 and did not see SAJCC appear in their list of journals (I can see it's still not there)

When changing the Owner in step 2, it's always best to select the correct account from the drop-down menu that appears. The field will allow you to set whatever owner you want, *even if no such user exists*. The owner dropdown will:

- give you suggestions of existing accounts, if any exist
- if none exist, it will display what you typed in as the only possible option to select

In this specific case, I think the space in the middle of the username is the problem. Try setting the journal's owner to `19997639`, not `1999 7639` (note space in the middle).

There is one case where you might want to put in a non-existent user, when you're editing an Application - especially one you're about to accept into DOAJ. Perhaps we need to change the behaviour of the field so when you're editing an already-accepted journal, it doesn't allow setting non-existent users as Owner and gives you an error. TnM task?

**Comment by ClaraDOAJ** [comment]
Fantastic! this is working now!

:) many thanks!

Clara Armengou
DOAJ - Community Manager
