### ISSUE TITLE
database query

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1237]
Hello CL

Can I get the title, contact person and contact email from these 200+ Indian Journals?

https://doaj.org/admin/journals?source=%7B%22query%22%3A%7B%22filtered%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22term%22%3A%7B%22admin.in_doaj%22%3A%22T%22%7D%7D%2C%7B%22term%22%3A%7B%22index.country.exact%22%3A%22India%22%7D%7D%5D%7D%7D%2C%22query%22%3A%7B%22match_all%22%3A%7B%7D%7D%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D

Many thanks!

**Comment by richard-jones** [comment]
Hi @ClaraDOAJ - I've preliminarily tagged this as medium priority, but feel free to update the label if you have a higher priority on it.

**Comment by ClaraDOAJ** [comment]
Thanks, I think medium is fine for the moment.

Clara Armengou
DOAJ - Community Manager

**Comment by ClaraDOAJ** [comment]
This still needs to be done according to our Ambassador, Vrushali.
