### ISSUE TITLE
Ingenta open logo added and Dove Press removed

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1238]
Dear CL

Could we have the Ingenta logo added to our sponsors page? https://doaj.org/sponsors (see logo attached). Please use a similar size as the others.

Also, we need to remove the Dove Press one.

Many thanks!
![ingenta_open_blue-rgb](https://cloud.githubusercontent.com/assets/22593616/24101031/f499e628-0d76-11e7-81f6-1dce26ac807e.PNG)

**Comment by ClaraDOAJ** [comment]
UPDATE:

Please also remove logo of Elsevier from our sponsors, too.

**Comment by Steven-Eardley** [comment]
Can you provide the link for ingenta?

**Comment by ClaraDOAJ** [comment]
http://www.ingenta.com/

Clara Armengou
DOAJ - Community Manager

**Comment by Steven-Eardley** [comment]
Released to live now!
