### ISSUE TITLE
Weird highlighting issue is back

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#124]
The sporadic orange highlighting issue is back. See screenshot. Has been replicated in Chrome and Firefox. Always seems to be the 3rd record in the list.

![highlighting](https://f.cloud.github.com/assets/5955396/2399127/e32bb704-a9fb-11e3-95c0-a38e7efa51f3.gif)

**Comment by dommitchell** [comment]
![highlight](https://cloud.githubusercontent.com/assets/5955396/7882915/76d76d22-0612-11e5-8734-0a3f4dd3fe16.jpg)

**Comment by richard-jones** [comment]
We've never got to the bottom of this, and it hasn't been mentioned for a while, so closing off
