### ISSUE TITLE
Query forwarding to DOAJ

### ISSUE THREAD

**Issue by psmukhopadhyay** [DOAJ/doaj#1249]
We are using an open source library discovery system (VuFind) that supports query forwarding mechanism. For example, the entry below can snatch articles from PLoS-One by taking the search term given by user. It replaces q=ontology if user entered search term ontology in search box and select Articles@PLoS-One from drop-down option. This mechanism expects query string as the last component in the encoded URL.

type[] = External
target[] = "https://www.plos.org/search?q="
label[] = Articles@PLoS-One

In the same fashion we tried to forward query to DOAJ (see the entry below) by observing the search mechanism in DOAJ, but encountered error.

type[] = External
target[] = "https://doaj.org/search?source={""query"": {"filtered": {"filter": {"bool": {"must": [{"term": {"_type": "article"}}]}}, "query": {"query_string": {"default_operator": "AND","query": ""}}}}}"
label[] = Articles@DOAJ

DOAJ is returning nothing possibly  for the following two reasons:

1. It is taking the query at the end (not within the braces) like:
https://doaj.org/search?source={query: {filtered: {filter: {bool: {must: [{term: {_type: article}}]}}, query: {query_string: {default_operator: AND,query: }}}}}web#.WNLa2UTYluE

2. It's (the query as forwarded above) differing from the actual DOAJ search string (given below) in "" like query: in our case and "query": in DOAJ search.

https://doaj.org/search?source={"query": {"filtered": {"filter": {"bool": {"must": [{"term": {"_type": "article"}}]}}, "query": {"query_string": {"default_operator": "AND","query": "web"}}}}}#.WNLbaETYluE 

Is there any easier solution?

Thanks and regards

**Comment by richard-jones** [comment]
Hi @psmukhopadhyay 

If you want to issue search requests against the DOAJ from another system, the best way of doing this is via the Search API: http://localhost:5004/api/v1/docs

The UI search interface is not formally supported for external integrations, and its behaviour is subject to change without notification, so is not advised to build integrations on.  Also, it is not (and won't be) documented.

Cheers,

Richard

**Comment by richard-jones** [comment]
Gave you the wrong url for the API docs: https://doaj.org/api/v1/docs

**Comment by psmukhopadhyay** [comment]
Thanks richard-jones

I tried and it worked also but the problem remains the search string (https://doaj.org/api/v1/search/articles/web+ontology) provides response in the following format (given below) and not quite friendly for searchers.
How can we handle this issue?

Regards

{"last": "https://doaj.org/api/v1/search/articles/web%2Bontology?page=62&pageSize=10", "pageSize": 10, "timestamp": "2017-0329T16:51:58Z", "results": [{"last_updated": "2016-06-25T05:49:20Z", "id": "d8b44bcbf09f4b36bd0ac58679e28d93", "bibjson": {"end_page": "289", "start_page": "280", "author": [{"affiliation": "Presidency College (Autonomous), Chennai \u2013 600 005, India", "name": "Jothi Venkateswaran C."}, {"affiliation": "Avinashilingam Institute for Home Science and Higher Education for Women University, Coimbatore \u2013 641 043, India", "name": "Sudhamathy G."}], "abstract": "Users of the web have their own areas of interest. Given the tremendous growth of the web, it is very difficult to redirect the users to their page of interest. Web usage mining techniques can be applied to study the users navigational behaviours based on their previous visit data. These user navigational patterns can be extracted and used for web personalization or web site reorganization recommendations. Web usage mining techniques do not use the semantic knowledge of the web site for such navigational pattern discovery. But, if ontology is applied along with web usage techniques, it can improve the quality of the detected patterns. This research work aims to design a framework that integrates semantic knowledge with web usage mining process that generates the refined website ontology that recommends personalization of web. As the web pages are seen as ontology individuals, the user navigational behaviours over a certain period are considered as the user expected ontology refinement. The user profiles and the web site ontology are compared and the variation between the two is proposed as the new refined web site ontology. The web site ontology has been semi-automatically built and evolves through the adaptation procedure. The result of implementation of this recommendation system indicates that integrating semantic information and page access patterns yield more accurate recommendations. ", "title": "Ontology Based Navigation Pattern Mining For Efficient Web Usage", "month": "2", "link": [{"url": "http://www.enggjournals.com/ijet/docs/IJET15-07-01-332.pdf", "type": "fulltext"}], "year": "2015", "keywords": ["Web Usage Mining", "Semantic Web", "Ontology", "Web Page Recommendation"], "identifier": [{"type": "eissn", "id": "0975-4024"}], "journal": {"publisher": "Engg Journals Publications", "language": ["English"], "license": [{"type": "CC BY", "title": "CC BY"}], "title": "International Journal of Engineering and Technology", "country": "IN", "number": "1", "volume": "7", "issns": ["0975-4024"]}, "subject": [{"scheme": "LCC", "term": "Engineering (General). Civil engineering (General)", "code": "TA1-2040"}, {"scheme": "LCC", "term": "Technology", "code": "T"}, {"scheme": "LCC", "term": "Technology (General)", "code": "T1-995"}]}, "created_date": "2015-03-10T09:27:08Z"},
