### ISSUE TITLE
Alphabetical listing should ignore punctuation

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#125]
See screenshot: punctuation marks drift to the top of the list, letters with accents drift to the end

![ascendarticalphab](https://f.cloud.github.com/assets/5955396/2399500/24930a1e-a9ff-11e3-97e3-c04a23068589.jpg)

![descendingalphabjournal](https://f.cloud.github.com/assets/5955396/2399509/30e89fea-a9ff-11e3-9258-62ae0211e6f9.jpg)

**Comment by richard-jones** [comment]
@markmacgillivray - another one for you in the ES upgrade process.  What is your preferred approach?  From the discussion I see:

* custom mapping for that field, which strips punctuation and accented characters
* custom document field (e.g. index.alpha_title) which has punctuation and accented characters removed before save

My gut instinct is for the latter, because then this behaviour is encoded in the software rather than the database/index set-up, but happy either way.

**Comment by dommitchell** [comment]
@richard-jones 

> which strips punctuation and accented characters

> which has punctuation and accented characters removed before save

You don't mean stripped out upon submission of data do you? We absolutely want to retain the accents and punctuation in the metadata.

**Comment by richard-jones** [comment]
Nope - just stripped in the indexed/searchable data, so that we can search/browse over it

**Comment by markmacgillivray** [comment]
Propose best option is to pre-process into a field we use only for sorting. However this will also have to take into consideration future updates to whatever field drives that sort field. The only alphabetical sort that we allow on search results is title, so whenever title is updated re-create the title-sort field. 

Will require an update to all the records currently in the system, to introduce this new field in the first instance.

**Comment by richard-jones** [comment]
Yup, sounds reasonable.

If you put the code to do this in the prep() method on the object that you need to do it to, it will be prepared at save time with the correct data.  Our convention is to put all this non-canonical stuff in a bit of the object called "index", so you could create the field "index.sort_title" or something.

**Comment by markmacgillivray** [comment]
pre-process into a field without punctuation and sort on that.

**Comment by markmacgillivray** [comment]
Alphabetical listing now ignores punctuation. However there are other things it still does not ignore. Have a look, see what you think.

**Comment by dommitchell** [comment]
Looking good. Closing.
