### ISSUE TITLE
Elsevier failing metadata

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1251]
Hello CL

There is apparently a problem with these journals from Elsevier. I have asked to provide me with the failing xmls.

Is there something in the setup for these four journals that would have prevented the upload of metadata for them? We’ve repeatedly encountered errors when we try to upload data.

![image](https://cloud.githubusercontent.com/assets/22593616/24238597/21a56bca-0fab-11e7-8e40-16579875f927.png)

**Comment by ClaraDOAJ** [comment]
The xml files
[FailedXMLFiles.zip](https://github.com/DOAJ/doaj/files/864143/FailedXMLFiles.zip)

**Comment by ClaraDOAJ** [comment]
Hello, any news on this one? Publisher is chasing.

Thanks!

**Comment by ClaraDOAJ** [comment]
Hello,

The publisher is chasing this...

**Comment by richard-jones** [comment]
@ClaraDOAJ has asked publisher if they can identify for us the specific files that are causing the issue.

In the mean time, we can look at the publisher's account on the test server and see what file uploads succeeded and failed.

**Comment by richard-jones** [comment]
Hi @ClaraDOAJ 

I ran the first one of the XML files in the zip, and the new error code showed me this:

"The following ISSNs in your article metadata are owned by you and another user. This is a problem at our end, please contact us with the details:
0717-3458"

I expect this is the case with all the other errors that they have.  I checked 0717-3458 and it really is owned by another user account.

**Comment by richard-jones** [comment]
I mean - there is a journal with that ISSN owned by another user account.  There are actually two journals with that ISSN, each with a different owner.  One of which is not in_doaj, but that doesn't make a difference to the article ingester.

**Comment by ClaraDOAJ** [comment]
We deleted the duplicate journal for 0717-3458 and it worked for them. 

Now we have deleted other duplicate records and we are waiting to see if this solved the problem. We are getting there! :)
