### ISSUE TITLE
JATS

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1255]
Would it be possible to support JATS? 
How difficult would it be to implement? and how would it affect our current project for diagnosing xmls?

Thanks

**Comment by greboun** [comment]
JATS would  e very good to have
Everyone talked about it in the meeting of ISMTE in Beijing vit is the XML
Standard for publishers

Tom

**Comment by dommitchell** [comment]
ON a recent call, you asked us to provide an example of JATS. Adding that here. (Had to save it as a txt file to get it to upload)
[OTS-beta-JATS.txt](https://github.com/DOAJ/doaj/files/1520734/OTS-beta-JATS.txt)

You said you would take a look at the file and help us determine how various elements within it fit with our own DTD.
