### ISSUE TITLE
ASCO JGO uploads to DOAJ

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1257]
ASCO has requested for Sheridan to upload content from their Journal of Global Oncology to your site and if you could answer a couple of questions before we begin we’d greatly appreciate it.
 
We are capable of producing XML for individual articles or batching multiple articles into a singular XML can you confirm which method you would prefer to receive article XML?  I’ve attached a sample of each for reference.
 
We have sample XML ready to test that it conforms to DOAJ’s requirements and we want to ensure it loads correctly.  Is there a staging environment that we could load this content to where it will be private, or during the upload process is there a way of reviewing the uploaded XML before deciding to push it live?
 
Thank you very much!
-Thomas
[ASCOxmls.zip](https://github.com/DOAJ/doaj/files/884864/ASCOxmls.zip)

**Comment by emanuil-tolev** [comment]
> We are capable of producing XML for individual articles or batching multiple articles into a singular XML can you confirm which method you would prefer to receive article XML? I’ve attached a sample of each for reference.

They certainly can upload multiple articles in one file, that's how a lot of publishers do it.



> We have sample XML ready to test that it conforms to DOAJ’s requirements and we want to ensure it loads correctly. Is there a staging environment that we could load this content to where it will be private, or during the upload process is there a way of reviewing the uploaded XML before deciding to push it live?

Sure - the usual. Could they use https://testdoaj.cottagelabs.com/ ? XML uploads should be ingested on there just the same as live.

**Comment by richard-jones** [comment]
Please let's not point end users to testdoaj - this is not a staging server, it's our development/acceptance server, so we have no idea whether it will be up or functioning correctly at any given time, and it often is not functionally equivalent to the live server.  Sending users there will just make us open to having to answer more questions when it doesn't behave as they expect.

The short answer to their question is that no there isn't a staging environment, but if their XML uploads are broken they won't get imported when they try to upload.  And when we've rolled out the new XML validation code it will give them much more information on why.

**Comment by ClaraDOAJ** [comment]
Makes sense! Many thanks!
