### ISSUE TITLE
xml upload error

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1259]
Dear all,

today I was uploading some metadata from our journals and I got the "File system error when reading file".

The error happened with the following timestamp and filename:

24 Mar 2017 12:32:55 UTC     psicoart-v6-2016-last.xml

24 Mar 2017 12:17:35 UTC     danzaericerca-8-2016.xml

24 Mar 2017 12:05:04 UTC     brunopini-v7-2016.xml

24 Mar 2017 13:49:46 UTC     psicoart-v6-2016-last.xml (tried again a few minutes ago, if useful you have the last xml attached)

If relevant, our account number is 20386184.

Best regards,

Piero Grandesso
[psicoart-v6-2016-last.xml.zip](https://github.com/DOAJ/doaj/files/886033/psicoart-v6-2016-last.xml.zip)

**Comment by richard-jones** [comment]
I've just tried this on the test server and everything worked fine.  I can see from their account history that they did have an error, but I can't explain it.  I suspect it was a blip around the time we deployed the new background jobs code, so shouldn't happen again.

**Comment by ClaraDOAJ** [comment]
Thanks!
