### ISSUE TITLE
redalyc xml problems

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1260]
Hi CL
Yet another xml issue
They have problems with the following journals. I am also attaching xmls
[redalycxml.zip](https://github.com/DOAJ/doaj/files/886430/redalycxml.zip)

164 Estudios Políticos

436 Agronomía Costarricense

714 Texto & Contexto Enfermagem

920 Revista Eureka sobre Enseñanza y Divulgación de las Ciencias

1552 Lecturas de Economía

3420 Revista ION

**Comment by ClaraDOAJ** [comment]
I think this has been sorted.

**Comment by ClaraDOAJ** [comment]
Could you have a look at this one? It has not been solved after all.

**Comment by ClaraDOAJ** [comment]
Please, could you have a look at this one?

Many thanks

**Comment by richard-jones** [comment]
It's difficult to reproduce these without logging into the user's account on the live server.  Do they have an error message that they received that they could tell us about?

**Comment by richard-jones** [comment]
I've added TnM tag for investigating user issues - if it turns out to be a bug we'll re-evaluate the status.

**Comment by richard-jones** [comment]
I have run one of the files (164.xml) on the test server (which is not an exact copy of live, but is close enough), and I got an error saying that the issn 0121-5167 is shared with another user account.  I haven't investigated the other files, but I guess it's a similar situation.  The UI does report these errors, so perhaps ask the user to check their error messages and let you have them, and I suspect then this can be fixed administratively.

**Comment by ClaraDOAJ** [comment]
Ok this has been sorted for 0121-5167. I am gonna check the others now and we might be able to close this ticket.

**Comment by ClaraDOAJ** [comment]
Ok, I have sorted the issn duplication and I am awaiting response from publisher. Once they confirm it is alright, I will close the ticket. 

Many thanks!
