### ISSUE TITLE
xml processing failed 0214-0071

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1267]
I am attaching two xmls. I checked with a validator and they seemed fine. 

Could you have a look please?

![image](https://cloud.githubusercontent.com/assets/22593616/24670352/f4644038-196d-11e7-9487-26829df00381.png)
[xml_cienciasdeporte.zip](https://github.com/DOAJ/doaj/files/893981/xml_cienciasdeporte.zip)

**Comment by richard-jones** [comment]
@ClaraDOAJ - can we ask them to re-upload these files with the new error reporting, and let us know if they still have an issue.
