### ISSUE TITLE
CJC  1000-467X

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1272]
Hello CL

We talked about this one in one of our hangouts a couple of weeks ago. Unfortunately this has not resolved and I need more help.

The Chinese Journal of Cancer is now managed by BioMed Central, and the previous editor has flagged up that the content has disappeared from the TOC. This should not have happened even when the journal is administered by another account.

The previous editor (account 1000467X) says he still sees the content in his publisher area, but not on the public platform.

We guess that the articles were removed somehow and BioMed central needs to reupload them. Apparently BMC say that the API has some bug and they cannot upload the content. 

Could you have a look at this?

Thanks

**Comment by emanuil-tolev** [comment]
> We guess that the articles were removed somehow and BioMed central needs to reupload them. Apparently BMC say that the API has some bug and they cannot upload the content.

What do they say? (Or was that the one where they were getting an internal server error on access? That's not "on upload" though, that was on access... anyway, probably best to paste their feedback here or in an email if you think it's confidential.)

**Comment by ClaraDOAJ** [comment]
Their feedback is on the issue.

Is the API still not working for BMC?

**Comment by richard-jones** [comment]
From today's meeting: @ClaraDOAJ will contact BMC to find out what issue they are having with the API

**Comment by ClaraDOAJ** [comment]
This is still with the publishers.

**Comment by ClaraDOAJ** [comment]
This issue is with @emanuil-tolev at the moment. Have you heard from them, Emanuil?

**Comment by emanuil-tolev** [comment]
I haven't, no :/

**Comment by ClaraDOAJ** [comment]
@emanuil-tolev any news on this? Thanks!

**Comment by emanuil-tolev** [comment]
Sorry @ClaraDOAJ , I haven't heard anything from BMC about issues they're having with the API. Who's asking for this - what problems are they having? Reading the issue it seems like the last action was to go find out any details we could, on the 16 May:

> This is still with the publishers.

I haven't actually gone out and emailed the relevant account myself. I assumed you were asking whether somebody from BMC had emailed me, which they haven't. Is there somebody you or I can email to find out more, or are you currently in touch with somebody at BMC?

**Comment by emanuil-tolev** [comment]
Ah ok, that's #1352 in my head, thank you

**Comment by ClaraDOAJ** [comment]
Sorry, should have probably linked it. I do not want to close this ticket as I am in touch with the person in charge. Could you please work on this one #1352 asap? 

many thanks again and sorry for not being clearer.

**Comment by dommitchell** [comment]
Continued by #1352. No response from publisher
