### ISSUE TITLE
Notes project deployment

### ISSUE THREAD

**Issue by Steven-Eardley** [DOAJ/doaj#1275]
**Steps to deploy on live**
1. Optimise the live index.
1. Put app in read-only mode by setting ```READ_ONLY_MODE``` and ```SCRIPTS_READ_ONLY_MODE``` True in ```production.cfg```. Edit on ```doaj-gate``` and replicate to ensure persistence. Restart app (graceful: `kill -HUP $(sudo supervisorctl pid doaj-production)`). Stop huey `sudo supervisorctl stop all` on the doaj-background-apps-1 server.
1. Run the reindex task on the app server: ```DOAJENV=production time python -u update_mapping_reindex.py -o doaj -n doaj_v1 -a doaj_alias >> /home/cloo/update_mapping.log 2>&1```
1. Tell the app to use the new alias by editing & replicating ```production.cfg``` again. Restart app. Start huey back up.

**For extra credit**
1. Once the result has been verified, delete the old ```doaj``` index.
1. Replace ```doaj_alias``` alias with ```doaj``` so that current and subsequent index versions can all access the index via ```doaj``` e.g on test:
    ```
    curl -X POST \
      http://localhost:9200/_aliases \
      -d '{
         "actions": [
             { "remove": {
                "alias": "doaj_alias",
                "index": "doaj_v1"
            }},
            { "add": {
                "alias": "doaj",
                "index": "doaj_v1"
            }}
        ]
    }'
    ```
1. Edit and replicate ```production.cfg``` to use  index```doaj``` again. (But this time it's an alias!) restart app.

**Comment by Steven-Eardley** [comment]
Deployment to test restarted 10/04/17 because the test server ran out of disk space last time. Re-run took 5h 52m with the following result:

```
time DOAJENV=test python update_mapping_reindex.py 

type: account
index doaj: 9436
index doaj_v1: 9436

type: bulk_upload
index doaj: 181
index doaj_v1: 181

type: bulk_reapplication
index doaj: 56
index doaj_v1: 56

type: background_job
index doaj: 19101
index doaj_v1: 19089

type: provenance
index doaj: 37679
index doaj_v1: 37679

type: lock
index doaj: 15681
index doaj_v1: 15681

type: journal
index doaj: 16966
index doaj_v1: 16966

type: cache
index doaj: 3
index doaj_v1: 0

type: upload
index doaj: 755704
index doaj_v1: 755704

type: journal_history
index doaj: 0
index doaj_v1: 0

type: article_history
index doaj: 0
index doaj_v1: 0

type: lcc
index doaj: 1
index doaj_v1: 1

type: suggestion
index doaj: 20725
index doaj_v1: 20725

type: toc
index doaj: 0
index doaj_v1: 0

type: article
index doaj: 3167527
index doaj_v1: 3167526

type: news
index doaj: 49
index doaj_v1: 49

type: editor_group
index doaj: 41
index doaj_v1: 41
all equal:  False

real    351m55.471s
user    15m56.090s
sys     0m28.803s
```

As you can see, the counts aren't equal for all types - background tasks have been continuing while the task was running. I'm not sure where the disparity in article counts comes from, however.

**Comment by emanuil-tolev** [comment]
> background tasks have been continuing while the task was running

That won't happen if read-only mode is turned on... which you can try if you feel it's worth doing before doing it live at this point. Just set `READ_ONLY_MODE=True` in `/home/cloo/repl/test/doaj/src/doaj/test.cfg` on doaj-gate, sudo supervisor restart all on doaj-test.

**Comment by Steven-Eardley** [comment]
Yeah, that's good. I just thought it was already on - I set it for the previous deploy and wasn't expecting it to have changed. Looks like it has, though!

**Comment by emanuil-tolev** [comment]
> Yeah, that's good. I just thought it was already on - I set it for the previous deploy and wasn't expecting it to have changed. Looks like it has, though!

If you change it on doaj-test, any deploy (including develop) will overwrite it by virtue of calling `/home/cloo/repl/replicate.sh` which will propagate what is on doaj-gate to every server. If you do that yourself when setting it, then it won't be turned off of course.

**Comment by Steven-Eardley** [comment]
Success. After fixes to esprit and augmentations to the script, it ran though. Interestingly, despite both ```READ_ONLY_MODE``` and ```SCRIPTS_READ_ONLY_MODE``` set to true, the background tasks continued to run. These won't be editorial tasks, however, just things like the sitemap and CSVs. I reckon that's safe. 5 hours.

```
type: account
index doaj: 9436
index doaj_v1: 9436

type: bulk_upload
index doaj: 181
index doaj_v1: 181

type: bulk_reapplication
index doaj: 56
index doaj_v1: 56

type: background_job
index doaj: 19366
index doaj_v1: 19356

type: provenance
index doaj: 37679
index doaj_v1: 37679

type: lock
index doaj: 15681
index doaj_v1: 15681

type: journal
index doaj: 16966
index doaj_v1: 16966

type: cache
index doaj: 3
index doaj_v1: 3

type: upload
index doaj: 755704
index doaj_v1: 755704

type: journal_history
index doaj: 0
index doaj_v1: 0

type: article_history
index doaj: 0
index doaj_v1: 0

type: lcc
index doaj: 1
index doaj_v1: 1

type: suggestion
index doaj: 20725
index doaj_v1: 20725

type: toc
index doaj: 0
index doaj_v1: 0

type: article
index doaj: 3167531
index doaj_v1: 3167531

type: news
index doaj: 49
index doaj_v1: 49

type: editor_group
index doaj: 41
index doaj_v1: 41
all equal:  False
908.47user 26.31system 4:47:47elapsed 5%CPU (0avgtext+0avgdata 170456maxresident)k
14008inputs+8088outputs (229major+99298minor)pagefaults 0swaps
```

**Comment by Steven-Eardley** [comment]
With huey properly turned off, the final re-run of the notes deploy on test worked as expected, with equivalent indexes.

```
Reindex complete.

type: account
index doaj: 9478
index doaj_v1: 9478

type: bulk_upload
index doaj: 181
index doaj_v1: 181

type: bulk_reapplication
index doaj: 56
index doaj_v1: 56

type: background_job
index doaj: 34413
index doaj_v1: 34413

type: provenance
index doaj: 39893
index doaj_v1: 39893

type: lock
index doaj: 15895
index doaj_v1: 15895

type: journal
index doaj: 17027
index doaj_v1: 17027

type: cache
index doaj: 3
index doaj_v1: 3

type: upload
index doaj: 770582
index doaj_v1: 770582

type: journal_history
index doaj: 0
index doaj_v1: 0

type: article_history
index doaj: 0
index doaj_v1: 0

type: lcc
index doaj: 1
index doaj_v1: 1

type: suggestion
index doaj: 20905
index doaj_v1: 20905

type: toc
index doaj: 0
index doaj_v1: 0

type: article
index doaj: 3185846
index doaj_v1: 3185846

type: news
index doaj: 50
index doaj_v1: 50

type: editor_group
index doaj: 41
index doaj_v1: 41
all equal:  True
925.83user 26.81system 6:24:00elapsed 4%CPU (0avgtext+0avgdata 171120maxresident)k
2968inputs+121008outputs (15major+97786minor)pagefaults 0swaps
```

**Comment by Steven-Eardley** [comment]
On live, all went as planned. Took a while, though. the index machines had replicas set to 2. I'm going to see how that proceeds.

```
Reindex complete.

type: account
index doaj: 9504
index doaj_v1: 9504

type: bulk_upload
index doaj: 181
index doaj_v1: 181

type: bulk_reapplication
index doaj: 56
index doaj_v1: 56

type: background_job
index doaj: 34877
index doaj_v1: 34877

type: provenance
index doaj: 40626
index doaj_v1: 40626

type: lock
index doaj: 15949
index doaj_v1: 15949

type: journal
index doaj: 17060
index doaj_v1: 17060

type: cache
index doaj: 3
index doaj_v1: 3

type: upload
index doaj: 770847
index doaj_v1: 770847

type: journal_history
index doaj: 0
index doaj_v1: 0

type: article_history
index doaj: 0
index doaj_v1: 0

type: lcc
index doaj: 1
index doaj_v1: 1

type: suggestion
index doaj: 20964
index doaj_v1: 20964

type: toc
index doaj: 0
index doaj_v1: 0

type: article
index doaj: 3191577
index doaj_v1: 3191577

type: news
index doaj: 50
index doaj_v1: 50

type: editor_group
index doaj: 41
index doaj_v1: 41
all equal:  True
1865.81user 134.75system 8:15:45elapsed 6%CPU (0avgtext+0avgdata 171248maxresident)k
72inputs+10104outputs (1major+92196minor)pagefaults 0swaps
```

**Comment by Steven-Eardley** [comment]
App is now live using the new index, under the ```doaj_alias``` alias until we've verified it's working as expected. For the sake of disk space, we should delete ```doaj``` soon though.

**Comment by Steven-Eardley** [comment]
Old DOAJ index has been deleted, and the app is now running stably on index ```doaj_v1``` under alias ```doaj```.
