### ISSUE TITLE
Cannot see article data- International Journal of Ophthalmology (2222-3959)

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1279]
The publisher of International Journal of Ophthalmology (2222-3959 (Print); 2227-4898 (Online)) uploaded the below two articles metadata successfully, but failed to find them when searching at DOAJ website. Attached please find the screenshots. Could you please have a look?

Aritle title:
Effect of trapping vascular endothelial growth factor-A in a murine model of dry eye with inflammatory neovascularization
DOI: 10.18240/ijo.2016.11.02

Article title:
A novel splice site mutation of CRYBA3/A1 gene associated with congenital cataract in a Chinese family
DOI: 10.18240/ijo.2017.01.01

See screenshots attached
[Can't search the uploaded articles if submit by user name 22223959..zip](https://github.com/DOAJ/doaj/files/927754/Can.t.search.the.uploaded.articles.if.submit.by.user.name.22223959.zip)

many thanks!

**Comment by ClaraDOAJ** [comment]
We keep uploading the article to DOAJ “Enter Article Metadata” page, and the webpage also prompt article created/uploaded successful, but still couldn't search the articles which was uploaded by 22223959 account, please help us find the reason ,and you could tried to search the following articles in DOAJ:
1. Effects of exogenous recombinant human bone morphogenic protein-7 on the corneal epithelial mesenchymal transition and fibrosis 
2. Edge detection and mathematic fitting for corneal surface with Matlab software
3. Two mutations in the transforming growth factor beta-induced gene associated with familial Lattice corneal dystrophy

**Comment by ClaraDOAJ** [comment]
Similar issue with the journal Biomédica: revista del Instituto Nacional de Salud

The journal articles have been loaded successfully using the XML upload option, but they are not visible on the website https://doaj.org/toc/0120-4157

[Biomedica (Spa).xml.zip](https://github.com/DOAJ/doaj/files/933307/Biomedica.Spa.xml.zip)

**Comment by richard-jones** [comment]
Hi @ClaraDOAJ - is this still an issue?  I took a look at the ToC page above, and there are lots of articles available there, so not sure if these ones came through or not after all?

**Comment by ClaraDOAJ** [comment]
I think it has been resolved. Thanks!
