### ISSUE TITLE
Please add Al Mandhuma logo

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1280]
Dear CL

Could you add Al Mandhuma logo to our sponsors page? Please add it in a similar size as the others

website: http://www.mandumah.com/

![dar almandumah logo](https://cloud.githubusercontent.com/assets/22593616/25174132/b9a04c50-24f6-11e7-8b58-1e76c1a30180.png)

Many thanks!

**Comment by Steven-Eardley** [comment]
Released to live with static pages updates
