### ISSUE TITLE
Add author search to public facetview

### ISSUE THREAD

**Issue by Steven-Eardley** [DOAJ/doaj#1286]
And fix admin facetview to use ```bibjson.author.name``` rather than ```bibjson.author```.

**Comment by Steven-Eardley** [comment]
@greboun this is live now, have a look and close this issue if you're happy with how it works.

The Article: Author search option should now work on the administrative site search for admins, and also should be present on the public search interface.

**Comment by ClaraDOAJ** [comment]
I can confirm it is present on the public search interface and on "Journals and Articles (Admin)" as it should be. 
Closing ticket.
