### ISSUE TITLE
Display of continuations where there are many previous journals

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#1287]
Update the ToC to display continuations information better when there are many next or previous journals

**Comment by richard-jones** [comment]
Some of folding for the interface.  Something like:

1. show the first one, plus a more button (maybe with count)
2. Show the first few, plus a more button (maybe with count)
3. Don't show any, have a "show all" button (maybe with count)

**Comment by Steven-Eardley** [comment]
Meeting 2017-07-18: de-prioritised this to medium priority. It would be good to get it fixed at some point, but not pressing.
