### ISSUE TITLE
Associate editors privileges

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1293]
Hello CL

We have detected that associate editors are able to change the status of an "accepted" application to "completed". This does not make any sense in terms of workflow but it is also dangerous for our database.

Associate editors should only be able to go from "pending" to "in progress" and "completed".

Thanks!

**Comment by Steven-Eardley** [comment]
@ClaraDOAJ there are few things I'd like to clear up before I submit my fixes.

Firstly, there's already code in place on each role's application edit form which prevents changes when an application is "accepted" - including admin. Can you confirm you're definitely seeing associate editors changing it successfully, and not seeing this message:
```You cannot edit applications which have been accepted into DOAJ.```

Secondly, do you only want to limit changes to the application status, e.g. prevent associate editors from changing 'on hold' to 'in progress', or do you want to prevent them from editing any aspect of the application - for example, preventing associate editors from changing a contact email address on an application that's in status 'ready'. They'd not be able to make any changes, instead see a message like:
```You cannot edit applications which are in status ready.```

Finally, do / should associate editors handle reapplications? At the moment there is a distinction in the admin form between pending applications and pending reapplications, which has been hidden from other users. If I lock down associate editor privileges to the 3 statuses above they will no longer be able to edit pending reapplications. Was this intended?

From last time I changed this, there's a full list of editorial status permissions in issue https://github.com/DOAJ/doaj/issues/801:

**reapplication pending** (visible to admin and publishers)
**reapplication submitted** (visible to admin and publishers)
**pending** (visible to asseds, editors, admin)
**in progress** (visible to asseds, editors, admin)
**completed** (visible to asseds, editors, admin)
**ready** (visible to editors and admin)
**accepted** (visible to admin)
**rejected** (visible to admin)
**on hold** (visible to admin)

**Comment by ClaraDOAJ** [comment]
reapplication pending to be deleted

**Comment by emanuil-tolev** [comment]
> reapplication pending to be deleted

we should probably do that in a separate issue though. But still:

> If I lock down associate editor privileges to the 3 statuses above they will no longer be able to edit pending reapplications. Was this intended?

Basically, yes. It's ok if they can't handle reapp pending because that's no longer used as a status.

**Comment by greboun** [comment]
As discussed in the weekly meeting a write up of all privileges
Privileges as follows
ass editors  can see  reapplication submitted ,pending, in progress, completed   can change reapplication submitted to pending to in progress to completed   CANNOT change completed
editors can see reapplication submitted ,pending, in progress, completed  can change reapplication submitted to pending, to in progress, to completed , can change completed back to in progress, completed to ready  CANNOT change ready back to other status
admin  can see all statuses, can change between all statuses, are the only ones who can change ready to accepted, rejected
NB all can SEE accepted , rejected  but only admin can change status to accepted, rejected

**Comment by Steven-Eardley** [comment]
@greboun are you sure you want to restrict the state transitions to only 'forwards' in the process? That will mean editors couldn't, for example, set an in progress application back to pending if they become unavailable to work on them for any reason.

**Comment by Steven-Eardley** [comment]
From meeting 2017-06-23: yes, forward edits only for (associate)editors. Plus, drop-down to only show statuses we are allowed to set to, grey out when in disallowed status and open the read-only form with the message:

```You cannot edit applications which are in status {x}.```

**Comment by Steven-Eardley** [comment]
@ClaraDOAJ This can be tested on the test server now - look at the application form as a managing editor, editor, associate editor. 
- [ ] You should see they each have different available options in the status drop-down
- [ ] Only valid options (forward in editorial pipeline) appear in the drop-down list
- [ ] If the application is opened beyond the editor's permissions, the status box is greyed out
- [ ] There is a message at the top of the form when an editor can't edit an application
- [ ] The save button is greyed out when an application can't be edited (e.g. accepted for ManEds)

**Comment by ClaraDOAJ** [comment]
Many thanks, we will test it today or tomorrow.

**Comment by ClaraDOAJ** [comment]
Dear CL

This has been tested and works well. Please release in live.

Many thanks!

**Comment by emanuil-tolev** [comment]
Released live by @Steven-Eardley .

**Comment by ClaraDOAJ** [comment]
Hello all,

I am reopening this issue because we have realised that editors should be able to make a backwards action which is to put applications back "in progress". Not associate editors, just editors.
Can you have a look at this, please?

Many thanks

**Comment by Steven-Eardley** [comment]
Opened #1406 to track the changes to editors. I see it was in fact specified by Tom earlier, so it looks like I missed that the first time around.
