### ISSUE TITLE
Nearly 5k articles don't have titles

### ISSUE THREAD

**Issue by Steven-Eardley** [DOAJ/doaj#1304]
And the majority of those articles are ```in_doaj```.

The query:
```json
{
    "query": {
        "filtered": {
            "filter": {
                "missing" : { "field" : "bibjson.title" }
            },
            "query": {
                "match_all": {}
            }
        }
    },
    "size": 0,
    "aggregations": {
        "in_doaj": {
            "terms": {
                "field": "admin.in_doaj"
            }
        }
    }
}
```
Result as of today: 
```json
{
  "took": 41,
  "timed_out": false,
  "_shards": {
    "total": 6,
    "successful": 6,
    "failed": 0
  },
  "hits": {
    "total": 4848,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "in_doaj": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 0,
      "buckets": [
        {
          "key": "T",
          "doc_count": 3071
        },
        {
          "key": "F",
          "doc_count": 1777
        }
      ]
    }
  }
}
```

The articles now show TOCs properly due to fix for #1095, but we should clean up the data.

**Comment by emanuil-tolev** [comment]
Does the JSON data mean that 3071 articles "in DOAJ" do not have a title, and also 1777 that are "not in DOAJ" don't have a title?

**Comment by Steven-Eardley** [comment]
Yup

**Comment by dommitchell** [comment]
Can you update this and let me know if this is still a problem? I'm wondering if it has disappeared now that we have finished the Reapplications project. Thanks!

**Comment by Steven-Eardley** [comment]
@dommitchell the number of articles without titles has increased slightly:
```json
{
    "took": 905,
    "timed_out": false,
    "_shards": {
        "total": 6,
        "successful": 6,
        "failed": 0
    },
    "hits": {
        "total": 4924,
        "max_score": 0,
        "hits": []
    },
    "aggregations": {
        "in_doaj": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
                {
                    "key": "T",
                    "doc_count": 3095
                },
                {
                    "key": "F",
                    "doc_count": 1828
                }
            ]
        }
    }
}
```

A contemporary example is https://doaj.org/article/7c26aeeea16f4cf795c23b5120d91562

**Comment by dommitchell** [comment]
Ugh. And this is weird because it clearly has a title: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1516-44462003000200014&lng=pt&tlng=pt

I wonder if accented characters are breaking the XML import or the JSON generation? Or if the export at there end is being broken by the accented characters.

@Steven-Eardley  Can you grab me a list of 15 articles that do not have titles, so I can do some checking?

**Comment by Steven-Eardley** [comment]
@dommitchell 

https://doaj.org/article/7c26aeeea16f4cf795c23b5120d91562
https://doaj.org/article/793b2c3b55c44311b419b6ce2b476c3a
https://doaj.org/article/7991ac86e73442c780c716b08a867090
https://doaj.org/article/7b08efa039e54e328fea6d5f1bbd7e0b
https://doaj.org/article/7ace4565b3ef442e859912eeb0d03735
https://doaj.org/article/7b8ad695e006481c8156a83e3dea9199
https://doaj.org/article/7b6b10686799485284441d68c94a0ce1
https://doaj.org/article/4a8e747aa19148a59d1473df4f039fa9
https://doaj.org/article/52b4f4c2a517435186c0bc9beff978f8
https://doaj.org/article/51d02bbe8606482ba33324ae12b83a2a
https://doaj.org/article/4d52a46579fc43b3811a6064fc4ddb0c
https://doaj.org/article/5108cb9d85a449ef8192c34d47da9cc4
https://doaj.org/article/5fc03294eee0424f95e6e1d05e0bdb09
https://doaj.org/article/627382d69d58471ca4822d8275b67bd2
https://doaj.org/article/59c1dc0a0b1449c78ba914f6e05c4cca

**Comment by dommitchell** [comment]
Looks like we have a mixed bag here: some of them are Editorials and have no title, some of them are in Arabic (I don't know if it's the Arabic per se that caused the title not to appear) and some of them have titles which never made it to DOAJ.

I'm loathe to delete 3000 articles when some of them may well be articles without titles. Best practice would have had those non-titles articles sent with their article type as title instead: Editorial, Book Review, Letter etc. @Steven-Eardley do we store article type against these articles anywhere? I'm wondering if we can do some work to replace the missing title with an article type.

The other option is that we replace the missing article with something universal like 'Article' or 'Titl not provided by publisher' but then we're getting into the realms of messing with metadata. 

I'd welcome your thoughts here.

**Comment by Steven-Eardley** [comment]
Interestingly, after adding the following aggregation:
```json
"article_age" : {
            "date_histogram" : {
                "field" : "created_date",
                "interval" : "year",
                "format" : "yyyy"
            }
        }
```
it seems that the articles without titles aren't all old data - there's quite a spread of ages.
```json
"article_age": {
            "buckets": [
                {
                    "key_as_string": "2004",
                    "key": 1072915200000,
                    "doc_count": 428
                },
                {
                    "key_as_string": "2005",
                    "key": 1104537600000,
                    "doc_count": 18
                },
                {
                    "key_as_string": "2006",
                    "key": 1136073600000,
                    "doc_count": 8
                },
                {
                    "key_as_string": "2007",
                    "key": 1167609600000,
                    "doc_count": 2
                },
                {
                    "key_as_string": "2008",
                    "key": 1199145600000,
                    "doc_count": 3
                },
                {
                    "key_as_string": "2009",
                    "key": 1230768000000,
                    "doc_count": 9
                },
                {
                    "key_as_string": "2010",
                    "key": 1262304000000,
                    "doc_count": 10
                },
                {
                    "key_as_string": "2011",
                    "key": 1293840000000,
                    "doc_count": 26
                },
                {
                    "key_as_string": "2012",
                    "key": 1325376000000,
                    "doc_count": 20
                },
                {
                    "key_as_string": "2013",
                    "key": 1356998400000,
                    "doc_count": 2084
                },
                {
                    "key_as_string": "2014",
                    "key": 1388534400000,
                    "doc_count": 28
                },
                {
                    "key_as_string": "2015",
                    "key": 1420070400000,
                    "doc_count": 99
                },
                {
                    "key_as_string": "2016",
                    "key": 1451606400000,
                    "doc_count": 146
                },
                {
                    "key_as_string": "2017",
                    "key": 1483228800000,
                    "doc_count": 214
                }
            ]
        }
```

**Comment by Steven-Eardley** [comment]
Here's the title field in the XML Schema - we should be seeing titles from XML uploads, unless something is silently failing in the Xwalk.

```xml
<xs:element name="title" minOccurs="1" maxOccurs="unbounded"> 
    <xs:complexType>
     <xs:simpleContent>
      <xs:extension base="xs:string">
       <xs:attribute name="language" type="iso_639-2b:LanguageCodeType" />
      </xs:extension>
     </xs:simpleContent>
    </xs:complexType>
   </xs:element>
```

**Comment by dommitchell** [comment]
Can we check if something is failing silently in the Xwalk?

**Comment by Steven-Eardley** [comment]
Perhaps one of the 3 vectors for article ingestion allows something like a space for the title, which is later stripped out. I'll have to check the test server:

- [ ] Article XML (does the Schema disallow a space?)
- [ ] API Article create
- [ ] metadata upload form
