### ISSUE TITLE
Minor Change in the Application form online

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1305]
Dear CL

Could we change the sentence:

45) Does the journal embed or display simple machine-readable CC licensing information in its articles? *

so it now reads:
45) Does the journal embed or display licensing information in its articles?*

On https://doaj.org/application/new

I think this page is not a static template so I cannot change it

**Comment by emanuil-tolev** [comment]
> I think this page is not a static template so I cannot change it

No, it's not. There's some reapplication code (that ingests reapplication CSVs) that also relies on precise wording. Reapplications are of course offline now, but it's still good to keep that up to date in case we need it later.

This will be out on live in approx 10-15 minutes from this comment so should be ready for review.

**Comment by ClaraDOAJ** [comment]
Hi @emanuil-tolev - what do you mean with "reapplications are offline now"? 
Thanks

**Comment by emanuil-tolev** [comment]
> Hi @emanuil-tolev - what do you mean with "reapplications are offline now"?
> Thanks

Not related to this issue.

I meant that publishers can't submit new reapplications. That's been the case for months (a year+ now?), not referring to recent changes.

**Comment by emanuil-tolev** [comment]
This change is live btw

**Comment by ClaraDOAJ** [comment]
Ok, thanks.
The page needs to be updated because they use it for new applications too.

**Comment by emanuil-tolev** [comment]
> The page needs to be updated because they use it for new applications too.

Yeah, absolutely. I meant that the question text is ALSO in publisher reapplication processing code, and this should be kept up to date with the normal web application form. I've kept it up to date in this case.
