### ISSUE TITLE
Libraries IP information

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1306]
Dear CL

Do we have this info? where can I get it?

Hello. I am the Director at the Tom Green County Library and we have had a change in IP address. Please provide the information you currently have on file for our IPs. Thank you.

**Comment by emanuil-tolev** [comment]
We don't hold libraries IP address ranges. They are used heavily in the closed access publishing world to restrict and track the distribution of content. I've seen talks by companies that specialise in providing such services.

The DOAJ is entirely open to anybody, including non-library users. Thus we have no need for libraries' IP addresses.

**Comment by ClaraDOAJ** [comment]
Thanks!
