### ISSUE TITLE
Optics Express

### ISSUE THREAD

**Issue by moqri** [DOAJ/doaj#1311]
Optics Express is removed from your list on July 2016 due to "not open" reason:

https://docs.google.com/spreadsheets/d/183mRBRqs2jOyP0qZWXN8dUd02D4vL0Mov_kgYF8HORM/edit#gid=1650882189

Could you clarify how the journal is not open?

**Comment by emanuil-tolev** [comment]
Hi @moqri ! You might have more luck writing to feedback@doaj.org as this github repository is related to DOAJ technical and API issues.

**Comment by moqri** [comment]
The above mentioned journal come out as one of the most cited open access journals in my analysis. Just wanted to make sure its removal is not due to technicality.
