### ISSUE TITLE
Reconsider keyword limit restriction, or how it affects API payloads

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#1315]
1. Should articles and journals with over 6 keywords be allowed?

1. Even if more than 6 keywords are not allowed, should we silently truncate to the first 6 keywords supplied (possibly returning a warning in the 200 response)?

    Alternatively we could provide a parameter to toggle this behaviour if we don't want to do any silent data processing.

People are having trouble with the requests failing just because of the keywords, and the most straightforward course of action they all take is to just chop off all but the first 6 keywords. This has been reported before via email but the most recent example is in a library that integrates with the DOAJ API for depositing metadata: https://github.com/pkp/pkp-lib/issues/2543#issuecomment-304710135

**Comment by emanuil-tolev** [comment]
@ClaraDOAJ 1. is an editorial decision, 2. is more of a technical one.

**Comment by richard-jones** [comment]
We need to update the API documentation one way or another to point out the limit

**Comment by emanuil-tolev** [comment]
DOAJ editorial team to think about the limit.

If it's set to something like 15 or 20 we might get far fewer cases of this being a problem at all.
