### ISSUE TITLE
403 on article submission via API

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#1317]
An API user is experiencing a problem depositing to the article API, and is getting a 403 in response.  I have checked the authorisations code, and it is straightforward and working correctly.  The largest likelihood is that the article exhibits issns which do not match to a journal owned by the user's account.  The API does not provide a nice error message when this happens, it just fails (correctly) with a 403.  We should verify this situation (information required from the publisher to do so), and enhance the error responses from the API.

**Comment by richard-jones** [comment]
TODO:

* get example failing data from the publisher
* check for issn conflicts between accounts owned by the publisher (if there's more than one)
* check for issn conflicts between accounts throughout DOAJ

**Comment by richard-jones** [comment]
Should be covered by the Pre-Refactor work to put error reporting into the API.  Revisit this one after that work has completed, and check that the publisher can now see the error.

**Comment by dommitchell** [comment]
@richard-jones pre-refactor label added
