### ISSUE TITLE
Connection problems in the Philippines

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1321]
One of our members is experiencing access problems. They are based in the Philippines. Here you have the screenshot they shared with us. I would think this is a local problem, but I would appreciate any insights.

Many thanks!

![image](https://user-images.githubusercontent.com/22593616/27217996-84659c3a-527c-11e7-9cec-659df94562a4.png)

**Comment by richard-jones** [comment]
I'm not sure what's going on here, but they are connecting to "doaj.org.library.xu.edu.ph" not "doaj.org", and I expect whatever strange local networking setup they have is responsible for this error.  I've checked doaj.org and all is working as expected.

**Comment by ClaraDOAJ** [comment]
Thanks @richard-jones! That is basically what I responded to them.
Closing ticket.
