### ISSUE TITLE
Bulk edit- error 3

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1328]
I wanted to give Hindawi journals the seal but it didn’t work
 
journal_bulk_edit by sonja status: error
Job ID: c31ef35247c6457494085ecdb0de51ec
Job Created: 19 Jun 2017 at 11:14
Job Last Updated: 19 Jun 2017 at 11:14
 
More Information
Parameters:
journal_bulk_edit__ids -- 23b499e545964b82a3f9c3db88821301, 2a23104904a4441fadadac0ec2d83145, 2b536f7bb57f4ad1a97c2867a11f5838, 11c6f59043dd483aba9ee579c57310c2, 12ce798e17a44a31b88ad76549043aaf, 13782067c66d46a9b737875efdfab841, 15bf3149865d428fb6356aa9a4367fbe, 2eed9ff866e54c5c989f50195c1003a9, 30c1e2d69697496683aa7d6367ae563a, 32b937640f8e4267b40c0df7c1c3a040, 3641570ea9e24ac18cb091e070efd884, 00979e3ce58a4a8fbcedf906762c70c0, 02cd6faac00f4475b9aab95624ee22ae, 042a468580f54edda6dcb1f7f5804905, 0580a6e881334ce5982e64a837acbb0c, 4888a5b098cd4ffaaf4fcec9c3e50964, 4b3caf3c498749bea56c58d949fcae54, 4eb2aee8bfb84505ab3d679280474378, 5152994395ce4c898ccc28f3ca4df27d, 596eb5897e8f49faadb6cc501411eb8b, 5d043c1621ef453194a346eabe806e49, 61b68a13f40f40b9bd0cd4e57d5e4178, 62780e6088294ad69a81f8151e9f1ae6, 64194c2bbb044c81859119e492c9377f, 646fa5ec0d41412aaca3a14f91e4db2a, 681046ed721e45c598a78a56c7f7d5b2, e1ae0d0487b346c488dc9ef0536185dc, e29e28763e494216ac9d37868d9b30b0, f15a2533e088448d90d7d0fd45401293, a5c3339506e14470981d03fb7b11cc04, a8a12402ee9f4a00bb97ae99ca447deb, ac6d289357a044e9a15e9a7722824bc5, ad11fe04d4a5423fb4f35ef028980f17, b0f54e09a64143f29696d7aa23b7dfaa, 9a82a912405a476bbb958ca1e581ac03, 9a90510e1ac641b08c0d1b9a0fd80287, 9c86949f8a054ba7b99607a3d6a0a464, 9c8d5c11fe6643a598ddf6ae6ec553e8, 9cd6264016cf468e936fdb90728de490, a0b4f5f7a1284cb9874558c71bdbaf45, 782435671d434549b34d1ac8113cad53, 7905eb45f58943ba86220f55ccdbadd9, 7d8847fc09394ca4b8d51e43f4d0dc15, 7dbc89db1cce4ad587da0c5590e148a3, 815259931000442c9d4c98d8da5b3034, 82d7414b1e7c47b58f412b14c3510d6c, 8abf617212a149b88c02ba5c53b939c2, 8ad8bc3c93294cabbb24d25fa9945902, 8f212f3df3384bb9a8ea5e7da3289849, 8f49e2f7edea48ee97e2be87263a50ba, 91ff146023f94b70b6823b78b775ec39, 92e44715a2614731a12b4d833eea55db, f3a4a84974d040488a985bee999d6ee0, f3b05386cb7c41ac840b5111dba828d9, f4ec5d81a4114e2295f717b799525058, fd3928c15fd94c8daa0caf64db90d737, d51a2f1914624ed9bcf6e98a4e2b8dbd, dbe9424566ee4548898fa90d8f5cbe6c, dcb81c9f87e8406781bace420aa4b57d, e051a568276c4136aebf19d9e5f0fdba, 708054faeb384682988be2bbe71d4056, 72263ef2941a4b90a508f0236bbb6b58, 728e1706026a4deba39a7bd1a7d87fc1, bbe8de11f47a487ebf0aacc0e6d13ca0, bd1c9c391ecc468096cdb99a44641416, bdb87ddc735c44919a0332b5936ef56b, c285b15a8bdf4550b867f45305e9827c, c4ca804e3a9a40ae839c3ec6c746ebc5, c4f10c6021674c11ac5c4f509b1fe133, c569784c68ef44038fb8dcf6ad192954, cac84803c518463d896443cb86c16817, cb0734aaf52c4037b8b33e0705621be7, cd8d6a4de00d4119ab53f45c44fc9c32, cfdeac9135f74f948ea0d5bb573daad5, d14a7ec4abda4ef4801d0ce221a31932, 77c8d08d6b4c4ecaba7af2eb17cec9e9, 14f34da818584c7c8f6d0813cfa50992, 0bc2444567894693adca63324d49cfa9, 50d284250e2e4f39a18aecb17dff9728, 097a890320474dddbe726ef7a949f778, 493ced18378747768534a555d2ad6343, 3a89f9e69cb24a9a84ea87e503d088ed, 5513d9af8a1e4f35b7aa036b40e17630, 54b1747bb4524d69b13c5cb7714451e4, 2bb4929aab8b4b38929e45f6d15d002f, 0ff08c4aad6b4e5c95dc70fcba631c9c, 1111ab75dc3d413791e27c6e3c9c7c3d, 0e2a0757914f46da83e79f991822a3dd, 2f724d532386457b9c7d4527fb397df1, 46bd4f15a533475abf7d7ded2e3b48ad, 16d2268950fe4831bcd7e4a7926e7df1, 17613c84f7f24507bc8990e38909d729, 0a53021c7b5f404186574dd83f513c56, 11d1f6d4bc0743d882b672f658f165ee, 16e8e7f622924393ad5ad930c1852afe, 1e82b0d75b244db7bab9e5d4f5e3884d, 3593eb84cb20493f9e805098befb6c17, 372e1e127a494b03819e4159a0e55b3c, 37b5d7412e55416c8e26eaea5780145c, 20d1d9f79d93477ebf37350758748c43, 20f08fe001884516af6af1d40a99367b, 28dbc12eb58e4bce9380c22b32836a5b, 2bb29e9e3eb7484d8597e19b5d6734c1, 2d95c2dca9754449a86eed5d187d250b, 2e253fa0182a4d0cbe627824b5ccd47e, 0391eafddabc4b65abda52d7664ddc29, 09140c80d9054d25813bd6947ff8c342, 584dac38ceb2454980628db3ccbcf08f, 5ed40ed56aa84ec59f9780eb4f25c654, 68b36f60458f49618475e67094ceaf60, 69e9fee2ec3b463eaa0cdcda1de99780, bcb2f7bcd43c4a57ae3c0e1085577826, bd23672d92fe4d41bbde9d4571dac88d, be3c82ff6f6f463eaacf86155866d1d2, bf68843d1ec748f99c92a5c9e55ab4ed, c09803b16220479882e0f642223d6c3d, c110f13bdec145b0b6f9df7b1a90d897, c305e41d90ac46c6b8d304cbb2b23635, c4f5c48ff7ee48e2a23af1c77217b297, c872582bba2942619f55e1bf415e70d9, ca5cf8a14b1542c488ef855d6bda66d9, ca7dc81eeef643e4a12bc49cfbce4368, d16970d1bf124405bb95470319608820, d201d05f24d84a1988be81415523aed5, a6643b21aef541a68e79b05d52b117ee, aa2d279283674d548f625bb86b1d89e7, ac5da2864d8647f6b1c97869bf19ac68, adf1fa6e35be45299fdfe0512ea38b62, b44fe76a2e4c471a8228b017c1f1781a, b75956ab30ff41a79b5fd24393255f66, d664eb679c894e9eb40447357361facf, d66d13f19b604f96bdb1296ad8d5735f, d7b431180f3a4a28812a30d86aa69001, db146a74d4bf4ddab1ed8e19a28c1732, dd1dd6cce1e6470185cf48029bf83965, 41815776adcb410f994df80c00d0452d, 41f99dca10ef40b2b72f9fa4959a895d, 43f1fd88281a40fa874aea82efbcd8cb, 4440c5ae681a405b9c4635788dd28ada, 44f34802d1e146b4a5516086aa8df4ce, 45d0b5083ce24d8d899eb3f10919aa12, 491f9cdf010c4c6a87837f2dcef5cc99, 4c5660f1b2234a968126e91b95b1c82f, 4dbb86e4e0cc4ee39c9d4739476da0cf, 4dd86700039248899b12c66822e76915, 4e2f9e8b8a9d436cbbe918106f398f58, 4e91cf2053cf456db0584cbd462bfb0f, 502f2534c4f54378962e9eee1ba49318, 6b6d6b7c7d454e1fae4faa28a7dc349a, 72c9b0dec8fa45f3a022b6e20b2e9596, 7951c111db9e4575b7d87f4d78fea444, 8e4bbd747cdc40e8b3b5facf89f530d5, 9356b032854f42eaaf9aa4efec3f729c, 9371b4af558941948dde59c5a7aa32d6, 95aab7f533aa4e83b3d6e6e4a990d8fb, 79bec13206be4309aae4a540f81ddf4a, 7a509445ac40453a8d49dd8079e170c9, 80caa5f4811645719ece25f0ceefa1ef, 83f04c7a12e04cfdab164404d38c66fc, 84cfda86a6144e83bbd42d819573c680, 9d487226544346609c9621dccabe88c3, 9eb0b04001ba4790bf68812a43476934, e5e9c422ad1d4ca0b80a0bb2d5a4cae5, e68fea399970453ea8128dc1318fbed0, e8a7771342ba44169ecee0e142e15c6b, e9710cf3679846a3af25482f85a64a7f, ea3ed6813902400189114e9ba4a5b732, ea7fb865bdcc4bfca5416dd24680203c, edc7a04c51244c9eada3a5d6f8c7702d, ef81db908a4347fda6437fa093d5b7d4, f0459da4223e47a8a414d0fa4cfb6508, f259da2f745d4c748c907e8358c50d6c, f37335989e5b4565abda8d5b5e799a13, f4cc1f215d4f4c47bc6fe9f813ce4420, f51cfe26cdb24349b86b0bc436277041, f606f9f865844f478a835c5b682d6ddf, f757ec7784e0428d94fdb1ed380766d9, fb5b5223b9474cad98a7bf9b5d4aa32e, df409e86e8744102898313fdf015e3a4, 30264d97e5d148bfa12511b3c98b86d7, 3089643f015f49c58131cdd5b2a98e45, 31b91894bcfd4843a850051fce7ee207, 34640011b1ae4cbbb675cac2b27a34ea, 3a93de1054c94761959bc8ee19cdf104, 3b0ccfc75a9d465aabec6e27f3592cfb, 3bc878db6b0c4985b84939002f1650c3, 022876e44baf44c18c981bce853a5ef2, 027e93171d6c4c5f92fb1053a8b62fc3, 03128772cd944dad96ba8d2592d2e27d, 03a80263030243c595c8d84b7295a621, 055256215d4d4f74995c52640f84d80f, 06ccf677c3744822a04780d85aad8a66, 0796b75cfe3a4e119b3ea4ca4a6624cf, 090fd93f07be4de1a95a3adb17cb45f8, 0925ed1f57a240d0b073ac02abdfb91a, 0a4684a80f444b1f9bef217dc5dfaf9d, 0ee6ccf867b440f4b0db227d949df8d3, 10788bdbc14140d0bba0acd54c2ba963, 11698c7454c4468f8fd2f1644c582eff, 11e6f685ca4349588a188272f45f47eb, 18d982106d6c49cfac47ae19c869bbd6, 1a225d2db76943e99ecd26982f4a7eb4, 1a50443a9d804dd5b9818df6bedc46b6, 1b93c1762cae4a75aafd1cb25c12acae, 1c310a2286c24cabad5d46fc3992163e, 1ea090f0250d49349b226fad058e73e7, 208571b226904a1c95748b46f05b991e, 2655f615db394db686fdcfe5e91e1034, 275e8d42a5fa462baf8003660c7b0861, 27d3a22739b94ced8f841713fca0d365, 2c2560fc775a4d9eba5b2d708cb9ae2a, 2cf74ed034704d67a88e4fa79d66354b, e476a5c9a24f4b7c87b93d5d7d2162bb, e59dd8f0229642b3a6e4e605ac1b18d2, e85fd8639e9d42c3bf8340de0b232e8a, e9c6e8fd07fd46a7b35b60f468008a25, ec009ea188e64c23ad7d8f04b01658c7, ed8c0d76e05041a6a4078013e13d55cd, f37fdd4389a440698837e4f9b7b5e6c9, f88f83630928402f915e9aff71944cc9, 463ac6ea5c8247f2898c4a8889a3c34c, 47cfc1ac283543eda31830b01bd33c01, 4c4f3c1ca5494b6a84e2c1e2eb7871ca, 4e69a58bed2d4480971f9be702460cb1, 50f6dc74a5a649f58c3d3351dfd4fe8b, 517f32eb88ca4208a8c42e799a9a16c3, 5214b8cbb0634d4090f1211223b67d12, 54ff5727cdaa44a1b2868602b161b1d1, 58e23081fdbe4e6094ecb29ae6e31d86, 5bfbf157468c48a4a7f6ef2df0583bf4, 5dd26199ccdb47b9b53842e2f595261b, 654f5ae693974df39f8dc24ab9468521, 65e709b7ba884822945c17270d9b2fec, 691adcbbbaf44c378511cf0913f08d73, d317cbcc7f5f422bacfca6687ed03cfc, d5550fcc9a034ff1b93a0d278bce8d31, d89abec448b64d928e29130483f53524, d8b537e49af94aa4afd2f9da0199ad43, d9fe54f287d64456bca3e15abfb86ca5, dabe59c283a343c498e74ae753fdc293, dbab7a942aed4fbf87f6353787414c2c, e36eec4dc6c34d76a44c5315b626a03f, c173094af3224b1a8ff5f2365990b500, cc9c8c20789549448b456143213aac26, d15cad9c2dc34b12bfe0c67c7da8823e, 97c3ce1078824914a0bf41e00ba82ed6, 9915c280e2a94c9dba25ee02029c8cae, 9bf579812e3f4a5686f4d2f27857da15, a017d8a2dea04c8ebaf49853d063a9c7, a25b8c4e1ec24713845231f04e75ed2f, a5838d0dea10439b8902f2107d60a8a6, 6c73caa4b0f346cbb0a9f785ad07a26d, 6e33e92235ce414e8abdf46f553ebcb0, 6f40bf297b914c848ee2943bda8b11ef, 72c458e22cbe44c6989e9a1deaf4365d, 75affa37b6a645169b18e02dd1d99835, 75d20aa7b35b42198d1c14689668d013, 763bc632b2ad44eab648cb9a8098e0a8, 775348751ba843fe894b23df826c024b, 8310a12b05a84a3e8e2e30279c931f0c, 86b0e4682d3d429aaa099d6013971886, 8b87c27c0b0c45e7a0e46a6b0c707b83, 8fac7aa3995f42ea8baa505e06918188, a5f4e5d9bfae417d90712a776e41649a, a6bb3a299c7e485ea4e98a696068c57e, a942efc88b854a438426a15b28548cfe, abc1b01b61874f99b2f617154be39a74, abdcf5d373504dddb048ce2f98613c5e, aec64c8081824bc78913599fc23f4686, b51890c3f5b2498c819c4d9f22e7bf9b, b52182b0a34648288e68786662032929, b7e68f7b57dd4244a7bbfa2f08e62d33, b86d5e3f9989477780fd435c1b3b49df, bb13004cc7c44eddb9a60e7f122cfb80, bc0f73c551db4640a0ea7b7499026454, 73496429191543a7b49593e95b6ef7cd, cbf1b9a701594f23aa5cd60ca09d5d22, 13ee377ab54345778b7d6f08e620c0b0, 14081bb7c2f24f24920cb0a990065fb8, 14a1bd401f7e4773a43aaee77ce2d461, 153e2c55274e42a783bdc034256a0268, 1820f52c162d4d69a12e8f1775a2de2b, 183feda75e57406aac5e171ac87b0cab, 1ea477e247d74ee4b9cb11c1683ec351, 241696bbc3d645c9bc8c429ff1ccce29, 24a3a763776a49a5954a50f328a59e04, 259b42fce42b46a4a5c0624838df5673, 2a1d983a5a5f4c21a27e6cad8b0005b6, 2b3974bbadb14dac9814ccd84677e6f0, 34136b8507e64157b3f2d0803306032e, 35b1847ae16e40278865f37d1d5a18ec, 36004cd4fd014d7f9c717ec559f2ecf4, 370cfbd05ef247d1ae2ddd585de391de, 39a36f6f0942426a9b33ded63e60dc87, 3bf85704021a4f76b6eb81f24fe6ae6c, 097f3b61e5484ed98d7899c36a9bcd37, 0e83f74d928c4e00b3bf4398454fe95c, 0ea56673163a4d17a61778c38c5b56da, 0f886d25d8ee4e40ba155d8f442b86a9, 107d0047c9ca43ba95bfca21d8ac36b3, 10ab06f92d2043349b8d07a8e031467b, 00766127d7334d939b1a9caeef29145a, 841617cd2d234316a9ad2ee8796b2c29, 84770af4ba884cf8bb2a999dde8ff6f6, 87f1ca370a3549dda7d36b8a4947d2e1, 8ae875cdfdd24879b284891ded59b89c, 8dff0b0f116540139cf3e4a6c474e700, 8fcd44d28a1a4dc680fee5675aa6c700, 91f0e3ace98243e98508455280a97384, 949bf9b150704d3a86e67a3ca0ed1b33, 6fa00d246ecf429dbad40355586f8b10, 703b3a3f089c464a8134b26dfccfb3b3, 770f49e02ffe4186955ceb4fd9e4fcd0, 7c0e63918fef4c3a80061c90d09973c6, f09cd00889054e2b83ffdffcbd10b77f, f63e77978eea4f0c8251277a96c812f0, f6e45aaf9eb7481883f420db6ab65a84, ff2960db82f5437d8da2dfa9653d80cd, 4f9aee4795844ee6a38602dac1e3dd55, 52943442a66d4bfe856e47f0777d4d07, 538503b383a74b07bbcf1d8c117554d9, 544307632af540a186818ae5da08bafd, 54865c82469643f4bb1439713d299f67, 556e0b0fabaf453fb2a07e856fa57613, 55bd693d7dee413aaf6946fadd60cfae, 5a7a4f9617ac4eb08c55ca9c66176757, e179ebfb96784bc7a3911fe40929ac45, e1bcb615315c4f8b8ce06e86c655e1fc, e3d26d65d59944cd81d7be4ef74808fb, e70d318dcb294ef3b7078c7160b6e853, ec7838594d184a16ae6f9b981338c942, ec8a5c855b594e13bdea5a31377a3023, ed6a7f8792ec40baba99551ed78669f9, 978c1b0920304967a897368ecfc412b4, 9b7ef01ff85a4859bf3c7cf127005c04, 9ec45227ffe44c7a8df885616ddc2e29, a35299157369429cacbdfc224eaf744d, 3e6520e69b004af2860323a8d437898b, 45a7087c837a469db7f35dfa8bb58945, 493f00da743c4ae1b7441ea97a1e38a4, 4c98eab2f2c14bc3a7a3b4a69e0a536b, 4e0598abbef241658bbd6e92db6f9a1d, a63888207aca49cbbeb61b1dcb1d93de, ab2f27b42acc4243a435310ab91a80da, ab93b6852c5049799efb5d9535b51181, ab9ebabb9c014d1c9a062fef6c0765c2, ad2ad146ee50445a93b1466b730d6f9f, b36bc23fea3a4a7d8317b5e223bdb08e, dcec3ea175a146538eb60bbab9c1b5d5, ddba7ae884a14957b26abc162c1521aa, 62a6d2258a3545d5ad5a6c0c8ae4132d, 655d1638004648bb9d92a5e914850bdd, 65eec4af31c540fcb3ee1bceb1b71f8e, 687f0c9984714ed3987b3d93ec7beec3, 699b36a21aef499faf1b94bfa3b3e055, b61241b3772b41caabca92b51a9dfc5b, bfc4adb1e54a41148b51361f1d2f7141, c1fdc9de834d4e6d9f961e4a38c6bc58, c2636767f3aa45588f87799d31c321ee, c8d206414d684f5daad45522c5c80613, cc1105bc7e70400a88b9a036df9fec02, 015f4cd6015048fe9068fd988882f867, 077209493e964cdc94288b3890187a1e, 0a4117a4e8734e41a24ce1954d5fd58e, 0a43783d9b9c4326911578e58b8cca38, 0c30df10df9b4d8882f1a890a05d8a5d, 0c328bc19bcd4203b9670248e1ab46fc, 0ca8c9b40c964c90b187b76638d5b07e, 0fe685b0606342c6812ccb3b99453a19, 108663765f054b07a7f08f036ae595da, 11c1f2f84b1a424383b92df2c90b086b, 14ac2e131cc64c1b991eb9cd66209a3a, 154c1628378e4c33972925d415a2eebf, 1f31c731e9ba458d967cc78bbb6fe96c, 21ba5e42f0c0462d996660b6a5aa8ee6, 223fac38d6d847c3bd9a81e5ed09a26b, 2af78dc7ebd340338f0bbd5485bbc82b, 2b2b16b13b044f1a92588e187fa59ea6, 3128e8aafe294c7baa9448c2902f7561, 318e308f739d4435a814e958ddd53218, 35b5517396ad4d768e52e3ddbf57f60e, 36825813e4414c15b68d2916de61d307, 375f05f412bf44f28c2a8792f8dbf70c, 3b30c1d4d5894831b14b7e1e2fa303a6, 3b754201290549008482ba9abe05db05, 3ba8df1657ce42dcab5f0a35302ab1dc, 3c4508c6753b49b1b625925b945da6f8, 3c9e3011d9f440449ede478fc1c1849d, 3cdb8cf301c046edaf5edfc6051d6df6, 3e64153de15c4521bb3dfa5b55fc7535, 41d1d801ddb04c88808d28306173ac72, 4402132ba3364ec2bfb2daf2a5dae971, 4b082f90f7094b239e2770138d2a3c7e, 4d6bdd98830b4262a6eb76b34affaa00, 4ff135c7affb4278a2cc63b89f9eb3a7, 5252439d33b041e49c6ced46c5a84611, 533bac3a3b4c4bd4a3171b829f3986ea, 559c474999e9472b933627a5433e800e, 59e1863d120e48bab133cd5d8e1000ae, 5a0ee6da991640d1b6691a019bb3bf1a, 5a2bc139711841c1ab13bae04a7696b9, 5acbc44f176b4f9a88527fc8c5282202, a707f2fb37244ca98663409bd5e42182, a7d7f9d2eac54c82bc08be2fdbaf768d, a9ac1ebc74b346e494b221e6aeda76ae, ae2a1dcb2b0d4673a51fa720f4a24772, afe6f48c5716409090b6f044d2c020d4, b1366a271e7e458ca4728150ba81c3e6, ba2cf006913046e798a6a228dbd3a959, baae5675798d41d2b87fcbea0e6cef2e, bd59fdebf89345ff97badfc7e8f4d7b0, c00dc0b6ef064762a67876876467702a, c8c86ee241814fc0ab104e2764cd8b23, c904f6f6540d4d63ad6b69f83af23b4f, ca5be00aeba34df28fc8aed9d5f4b356, cb82861312f34e67abe2f09b9be2f449, 7e1c838e0c3a43fea71f8383fb1fca2d, 7fbb4bf8acfe4ba88e495335ff9cefb3, 860d0130f55e4e39a949651426c2c224, d9b65bb4cc8045db9b4ee53c18ba5f3d, da2d0421e83d457cae8cb0fe61e6bbce, dc71831a25644a5eae44b1305582c389, dd9d5f47fa4b489994cbe3f7f23adc30, ddee53ae2c5648059189818d45a6f411, de069f1d543e432cae28893a4f93aace, 8a1be52d2adf470c9e1ab0c17052152b, 8aa970f45c754cb8860f796dd5a8d78c, 8b6c0a38b66146ceac6b0b4b7568ae63, 8f888b992ff64056a7e2b743b97ff7a9, 91896f2c959649db94fbeb670e9d8659, 91ac17d7dfa34eba8a5bb2fef759b31f, 92637a549ad04c24830a657d8cbc2da8, 94402d11225a41ed8c050d7841ccfc98, 94adfe0556ee427f8b12c3f610aac7be, 94c7f8af24324663b3be00214726f942, 94f315c8edc448f193ac3390ba1e4065, 95a78aa21cdb4519860608937bd1d477, 60be3cf223ed469e8e49b50e8a347ded, 6544740214464f97b4fe764a6419d409, 6623ed544ede4ebc963d5cc6298e7042, 670436375184414e8015fb51697966c7, 69b67aa31f49405db18a0904a10979f1, 6dff42b8e1954be299eb6f22685868f4, 70bd442987064f968bdf1239d326689b, 974f2b7a00864913a503d6c262d2df42, 97a1b1c87beb4ea2a087c6edb9a41a5d, 97ff58bcc54e442f81e46c21f04b408b, 998bec0749ec4ce2913340b09bc779ac, a2640730bc6049c99a60a8b9d3d73904, e633bb97d29540d9947d3e001138a21d, eade57108a0a46b597754455cce40afb, eff0e67bf6a54bb2be70042f0d5ac692, f05ce3a5e2b34444ac3e8b6c800d7678, f1515454a1b247c8adc2a8d268ecc34a, f9e63baa4ccb44a3a33173ce1e4c9bac, fa47a297714f4765a9eaab6d0f5c0348, fad3cd1a4e8548a69b355b302bb10dcf, fc3f83cd25014fb68488654e014919fe, fc4df7d1e71c4554a443ee3864f22b98, fd77caceb1094c1688074182b8449297, fe2fd09ca82240d68c94620100f767fb, ff0f63efe7c142599236ceab2b31e75a, 62aa4be7d72a41dd876c21059ac97fe2, 08b7e1cf31e145728b828c87e3729428, 0a42776a6d1e4459b432b1279f082e85, 0b9882fde4d442019cfd8ccb3741af7f, 0c57bda6178e420a920e6e96de4b9cc2, 0df262c3785c4b1dbe56604dafc4eba4, 0e9a85a7e0c44837909c05bb09e8bbe1, 0f86cdbec3864ffd864154da28eb91bf, 1410f045d07e443ea7a995c9b517a955, 14aa4fa05c66431e8033169cb0482918, 18bb4f1573904fd0b94c043c2cdf0e4f, 1b134158ab904c83ad88870715fbd510, 1ccf1e6fd8294ec692f1c36c81dd764c, 1d97ec47ba4743c1bb17843f65adbecd, 1e443e7d3f7541829dfe333ddf9cbe90, 1ef56dfecf32424895323ea39a0b1fc7, 1f1502f07ce94028bd4d332f4c01e7ad, 2435b743d46a4bf6bc978e4eb3b3ee77, 254b7046248c4925943c7fe0182ab411, 26d6d5eefb53497e8f12ca8a052278ac, 2a651488e5ed4717b685328c8b3a6aad, 2c05cbef88a1422fb0f88cf30ca06e23, 2dcc24d0ba814dc3a697efae6eee72c7, 300d97bc336f4c6ba014f7af89701dea, 303cc7afd1984ccea9b2d865974b6459, 30c7e15fde7b4a6c9842baa7e7541275, 36f0c3efd4b3495896dc5ef71a23e4bb, 017852e0b1df469d95aeb23fd01466ac, 0385621b664848319ad98ee8dbe38079, 03f66d6b36374aa7b006dd1de00f2302, 3d0fdf058d314b79b2e8c7ac0ceec003, 3d96d2ea76aa4ca38fee0cf9683a2e21, 3f547a1ff72848b28f73ecdeefc4b92d, 409626df7f8549d290a64dffff9e4220, 415fcb2c245b44dfb07b4fe649a43bc3, 433c26d6d23d48ea8f6fc7b86336406d, 43aabf16f87143e0a46fad65e26583bd, 4579407bbf394ac6b3aa27c7c32e08f7, 45beddf52a884dcf9c084d512860cff2, 4cddd98e0c244dd88aa77c92203900f2, 4dd4e99156184d90b1e6ce29e5f1662c, 4e3bd2a4058241a28f2e6dd550722734, 4eeb1898ff264e9ea03be8a57a19f222, 4ffad7f648d340338dd5c3610696085e, 557d852b451c42b9b37f501a75bb6959, 57b81a659f364d2da9886b725bd01165, a8337479b77d45b4b005666ece28b399, a893aa3cf9e1458299b098bc61ccd651, ad3027c90b4247739ec96b3e0faff236, b19bc368affe4de88358e61c463f7475, b458047c46a6444cb314c0a403f01702, b92c6e012c694c4f88b0e1fc2e50cbc6, b97c4ac6ce544733946371b48f91e49c, be28142c645a47ae9b0c090ba8b2827a, c0467c26554a430c991a0e0c7baf9eaa, c07269537475476b881acfef09649b07, c108d7089d2147da850c5721094b3301, c33a94025592410db52fce8d415c673a, c64bcb4c42b1480c889ac853902ad1b9, ca38d314bc4b4acc915f326d76fb36bc, d233b84293f048548c85c22714a72b99, 5d7ccecd8fbd4f66a8e104a792250f56, 5f236f5b6a6e4e18af738e0e288c1c4a, 5fcf6c99958541e9b3d97f2d467926d6, 5fdf4e051e3943acb36931310f2b3cce, 63f77c75f91a4facb8f59cb1291968e9, 97d9f1f35c6f4303afaee7d57c8566c9, 984b6134be844c40a13089f28a600ae2, 99fd5b420f9b4941868839fd809cf893, a06f95a1fe7e41aa8cd9a6f9bda51ff6, a2870134473f4d4fb1c83006a25ceb61, a40e99199f7a43a7bf8a6b42ac8c1580, a4ba75dc44164e0dbf35d028043f8c3f, 8897cf15416a419eaa3d127e8a623273, 8c7a660b90954805a3dbe3de4c97e3b7, 8c950d4b3b614326ba1dcc8c85090ef6, 8fcb533d41f84b1abc9a8067d5788395, 9117f499a1ae474daf364937950aaa41, 927e000751c1442dbbdba4291dbab510, 79ae80265119436d9ee7b10051f3b11e, 7a10dfacfa864f14b4ce286ec4ff6450, 7cf4b620d7444cf6aa64ec5b597391f3, 7ddb0a805fbe4bb39257fe46eca03e91, 80c57ef3105f4f1aa346c1e4181afe2d, 81421375fd7d4ba4928d237156a83400, 85d9f335b50e4bf8a891f5d5197cab30, 87933053b4b74e4aa256bec71a4ad7cc, 6a8191f0c97a4df2942f918079b3c971, 6bb846e45529421eb3cd07cd3192f047, 708b67cae2ad41deaeb6c2876d1af174, 71251fb0458e400d92c5ba6d9d579e12, 72f4ffc722504b09b862a4b829461484, 75727260626b459484adb6e5f580fe54, 77f5de55948a444f81b838436e0b14cb, d4b7f6dfc0d943de93dd9034867340e8, d5709d57d99242e49393dd97f5e01ea3, d5b17382cef948b89359b741bd5287b3, dc08d8bd2ecd495299947ba72e72e123, e0b1b2d4da7f41b8b9ca49bebc55c11f, e16af55fe3fc4c8c87818fc4499c7234, e77e40c745c84497a4dae81c4c179bf3, ec81deb77a994774981ae9f983adca29, ee0d58006d8c4b0693edd59c3284fbcf, f2aa369a95364a7ebc00fcbf9223edff, f2ba9c5cd0f44fcf9476a3c66948df4f, f2f7854bdad74bb0b39e8d6da1957bea, f3cf8c3aa46a48b293944fa0f7f3fd7b, f7ba14dc96674e6689fb28d37020fb39, fa710fd8ccfd4d1ebdf1881818109c8c, fb5328e4b6fc4caa972c7508497d58c2, fe69a3c85f1e419190c0761bcdbc1943, ff55e8ffcc164bcb9cec5f72451f7d02, 84a8cf2e822248d78de55ec67eeeedbf
journal_bulk_edit__replacement_metadata -- {"doaj_seal": true}
Reference:
journal_bulk_edit__selection_query -- {"query": {"filtered": {"filter": {"bool": {"must": [{"term": {"_type": "journal"}}, {"term": {"admin.in_doaj": "T"}}]}}, "query": {"query_string": {"query": "hindawi", "default_operator": "AND"}}}}}
Audit Messages:
2017-06-19T11:14:25.178906Z -- Job Started
2017-06-19T11:14:25.208229Z -- Setting doaj_seal to True for journal 23b499e545964b82a3f9c3db88821301
2017-06-19T11:14:25.214937Z -- Error in Job Run
2017-06-19T11:14:25.216100Z -- Caught in job runner during run: Traceback (most recent call last): File "/home/cloo/repl/test/doaj/src/doaj/portality/background.py", line 47, in execute background_task.run() File "/home/cloo/repl/test/doaj/src/doaj/portality/tasks/journal_bulk_edit.py", line 141, in run if fc.validate(): File "/home/cloo/repl/test/doaj/src/doaj/portality/formcontext/formcontext.py", line 1374, in validate self.pre_validate() File "/home/cloo/repl/test/doaj/src/doaj/portality/formcontext/formcontext.py", line 1317, in pre_validate self._validate_editor_field() File "/home/cloo/repl/test/doaj/src/doaj/portality/formcontext/formcontext.py", line 327, in _validate_editor_field raise FormContextException("Editor '{0}' not found in editor group '{1}'".format(editor, editor_group_name)) FormContextException: Editor 'nathan' not found in editor group 'English1' 
2017-06-19T11:14:25.216643Z -- Job Run Completed
2017-06-19T11:14:25.217150Z -- Cleanup Started
2017-06-19T11:14:28.930336Z -- Job Cleanup Completed
2017-06-19T11:14:28.930952Z -- Job Finished

**Comment by richard-jones** [comment]
This is the same error as #1327 so the same fix will work

**Comment by ClaraDOAJ** [comment]
Thanks! all good here
