### ISSUE TITLE
Unassign editors when account is deleted

### ISSUE THREAD

**Issue by Steven-Eardley** [DOAJ/doaj#1330]
Or don't delete, only 'deactivate' users.

Issues with the bulk API, such as #1327 & #1328 are caused by disappearing editor accounts preventing the records from being saved, including with unrelated actions. For example:

```
FormContextException: Editor 'cafe' not found in editor group 'Portuguese3'
```

When we delete a user account, we should unassign them from all records. The system should avoid invalidating records unseen.

**Comment by dommitchell** [comment]
If we unassign a user from all records and then delete the account, would this have any impact on the provenance reports? Would their history disappear?

I prefer the deactivating option.
