### ISSUE TITLE
special characters

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1333]
We performed these searches: 

a/ Limbaj si Context in “search all” (3) si and şi and “search title” (2) 
b/ Limbaj şi Context in “search all” (1) and in “search title” (1)

The question here is how do we treat special characters? It is a little concerning that the results are different when you add the special character.

**Comment by emanuil-tolev** [comment]
Hmm. This should have been resolved in #54 a while back

**Comment by emanuil-tolev** [comment]
@Steven-Eardley could this have been lost with the migration to index `doaj_v1`? We generate mappings from the app, but index settings like asciifolding are a different thing .. not sure how those are set. If they are in the ES settings, we should check them.

**Comment by emanuil-tolev** [comment]
@ClaraDOAJ let's talk about this in more depth. I'd like to understand what behaviours are counter-intuitive and for what fields

@richard-jones suggested:

> have a field like `index.titles: [original title, asciiunpunctitle, unpunctitle]`

**Comment by emanuil-tolev** [comment]
Potential use cases for special characters in search:

1. be able to find journal record using both characters.

  We already do this to a good extent, you should be able to at least find any journal record by its title regardless of whether you search for the "s with cedilla" or without it.

2. be able to find **other records** that refer to the journal by name somewhere in the metadata using both characters

  We don't do that at the moment - whatever is in the metadata, that's what you can search by. If the metadata has `s` then you can only find it by typing in `s`, not `ş`.

3. are there any other use cases?

  For example, is this ultimately solveable by an extremely broad use case - that a user should be able to use `s` or `ş` pretty much interchangeably in all search pages, in all metadata fields of all records?

**Comment by emanuil-tolev** [comment]
@ClaraDOAJ to confer with Editorial team. Whatever the decision, we should build up some use cases that can always be loaded into the test server or locally by developers, so that we can test and design the correct user experience here. That's what this is really about, UX and expectations of how things should work.

**Comment by ClaraDOAJ** [comment]
Let's add this to the next editorial meeting

@greboun
