### ISSUE TITLE
xml upload problem

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1334]
Publisher account: 23931140

It had been a while now! Definitely the new diagnose feature is helping a lot!
[diacronia.doaj.5.xml.zip](https://github.com/DOAJ/doaj/files/1124461/diacronia.doaj.5.xml.zip)

**Comment by richard-jones** [comment]
Do you know what error message they got when they tried to upload this?

**Comment by ClaraDOAJ** [comment]
Solved.
