### ISSUE TITLE
OAI-PMH - metadata harvesting

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1335]
I harvest your metadata via OAI-PMH on a per-article base for our library catalog at https://aksearch.arbeiterkammer.at/

I realized that since yesterday, a lot of the language information in oai_doaj format is missing (e. g. if an article is german or english). Will this be changed again or - if language information is needed - should I use oai_dc instead of oai_doaj?

Thank you very much for an answer in advance.

**Comment by richard-jones** [comment]
The actual problem here was that we just weren't running a conversion from our 2 letter internal representation of language to the 3 letter representation of language required by doajArticle.xsd, which governs the shape of oai_doaj.

There's a PR in which will give us this conversion, so most if not all journals should soon have language information via the OAI in this format.

**Comment by richard-jones** [comment]
@ClaraDOAJ - this fix is now live, your user should find the language codes available now

**Comment by emanuil-tolev** [comment]
**OLD CONTENT - the fix is now live as @richard-jones says**

Just to provide some old context

@richard-jones said:

> The code governing this process hasn't changed since March 2015, so it's not a problem with the OAI endpoint itself. You can clearly see, though, that languages are being omitted from records in the oai_doaj format:

> https://doaj.org/oai.article?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:doaj.org/article:f9a2ca95cccd4533b23a5f5089fdd565

> https://doaj.org/oai.article?verb=GetRecord&metadataPrefix=oai_doaj&identifier=oai:doaj.org/article:f9a2ca95cccd4533b23a5f5089fdd565

> The user thinks that this used to work, but no longer does. I've looked at the data, and it appears to be correct, and I've reproduced this locally in a dev environment. That would suggest to me that this may never have worked! I'll dig deeper, anyway....

> I've tracked this down to an error in the crosswalk from country name to 3 letter code - this only works if there is a country name, and if there's a code instead it omits it. I can put in a quick fix...
