### ISSUE TITLE
Applications in admin

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1346]
I discovered that when I change the application status from "completed" or "ready" to "in progress" again, the email is sent to the group editor, not to the associate editor who took care of the application.

I guess the proper way should be to send the notification to the associate editor, or even both to him/her and the editor.

**Comment by emanuil-tolev** [comment]
Send an email to both the group editor and the currently assigned editor at the time of changing the status (as per OP above).

**Comment by emanuil-tolev** [comment]
Clara to review with Editorial team whether workflow has changed here (looks like ManEds were only supposed to bounce applications back to Editors, not associates).

**Comment by ClaraDOAJ** [comment]
@greboun What is your opinion here? Shall we put it in the next ed meeting?

Thanks!

**Comment by ClaraDOAJ** [comment]
Hello, this went to our editorial meeting today. We have decided that both editor and associate editor should get the email. 
Can this be done?

Many thsnks

**Comment by Steven-Eardley** [comment]
Released now. You'll see that editors can set to 'in progress' and that an email is sent to the assigned associate editor when either an Ed or ManEd changes it.
