### ISSUE TITLE
Some journals are listed in the removed list but still exist on the website

### ISSUE THREAD

**Issue by moqri** [DOAJ/doaj#1349]
During my analysis of your journals, I came across some journals that are listed as [removed](https://docs.google.com/spreadsheets/d/183mRBRqs2jOyP0qZWXN8dUd02D4vL0Mov_kgYF8HORM/edit#gid=1650882189) journals but are still exist on your website. Could you please take a look and let me know what's the reason?

Journals' ISSNs:
['0104-5970']
['0034-7094']
['0352-5139', '1820-7421']
['2218-7405', '2077-1770']
['2233-7849']
['1519-6984']
['0102-311X']

For example, the second one (ISSN=0034-7094), "Revista Brasileira de Anestesiologia" is removed due to "Journal not adhering to Best practice" on November 2016 but is still listed on your website here: https://doaj.org/toc/1806-907X

**Comment by emanuil-tolev** [comment]
1806-907X has been added back in for a valid editorial reason. 

How did you get information on why it was removed? Whatever dataset you're using might be out of date. 

Also I wasn't aware of this being public information.

**Comment by emanuil-tolev** [comment]
Oh sorry, I saw the Google doc link. That's a list of journals removed at that time, after updating editorial criteria and removing lots of journals. It's almost certainly out of date now. A journal can be added back in if it changes behaviour and reapplies. @claradoaj knows more than me here.

**Comment by dommitchell** [comment]
@ClaraDOAJ we need to reply here and action. Would you like me to take this one?

**Comment by ClaraDOAJ** [comment]
@dommitchell Yes, please. Many thanks!

**Comment by dommitchell** [comment]
Hi @moqri - thanks for your question.

The general reason for the discrepancies is that updates to the Google sheet are not automated and journals do get taken out of DOAJ and then put back in later. I have provided reasons to each ISSN below:

> ['0104-5970'] - journal failed the reapplication process but has since applied again and been accepted.
> ['0034-7094'] - was no longer on the spreadsheet but again, the journal failed our Reapplication process and then was re-accepted.
> ['0352-5139', '1820-7421'] -  journal failed the reapplication process but has since applied again and been accepted.
> ['2218-7405', '2077-1770'] - was no longer on the spreadsheet but again, the journal failed our Reapplication process and then was re-accepted.
> ['2233-7849'] - not in DOAJ
> ['1519-6984'] - was no longer on the spreadsheet but again, the journal failed our Reapplication process and then was re-accepted.
> ['0102-311X'] - was no longer on the spreadsheet but again, the journal failed our Reapplication process and then was re-accepted.

I've been through the Googe sheet and made sure that all are removed. Thanks for your feedback.
