### ISSUE TITLE
Discrepancy with search results

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#135]
If you do a search on ORTAÇAĞ AVRUPASI’NIN İKTİSAT TARİHİNDE 2 articles are returned:
https://doaj.org/search?source={%22query%22:{%22query_string%22:{%22query%22:%22ORTA%C3%87A%C4%9E%20AVRUPASI%E2%80%99NIN%20%C4%B0KT%C4%B0SAT%20TAR%C4%B0H%C4%B0NDE%22,%22default_operator%22:%22AND%22}}}

Now search on the author name and 3 articles appear all with the same title:
https://doaj.org/search?source={%22query%22:{%22query_string%22:{%22query%22:%22K%C3%BCr%C5%9Fat%20Haldun%20AKALIN%22,%22default_operator%22:%22AND%22}},%22sort%22:[{%22created_date%22:{%22order%22:%22desc%22}}]}

Related to https://github.com/DOAJ/doaj/issues/127

**Comment by dommitchell** [comment]
Referencing issue #195 for the record.
@richard-jones Will this actually be fixed by @markmacgillivray 's work on #125 ?

**Comment by richard-jones** [comment]
Yes, this has been partially or completely fixed.  @dommitchell do you want to review and close if done?

**Comment by dommitchell** [comment]
No normalisation between ' and ’ so leaving open for now

**Comment by richard-jones** [comment]
https://doaj.org/search?source=%7B%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%22AVRUPASI%E2%80%99NIN%22%2C%22default_operator%22%3A%22AND%22%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D

https://doaj.org/search?source=%7B%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%22AVRUPASI%27NIN%22%2C%22default_operator%22%3A%22AND%22%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D
