### ISSUE TITLE
Analyse Springer submission logs

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#1352]
1. categorise errors
1. respond to each error
1. ask for more information if necessary

Contact: Jeff

**Comment by ClaraDOAJ** [comment]
We need this to be done ASAP. The publisher is chasing again and it reflects badly on DOAJ if we cannot react soon enough. 

Did you get the needed info from Jeff?

**Comment by richard-jones** [comment]
@emanuil-tolev - what's the status of this one?

**Comment by emanuil-tolev** [comment]
@richard-jones responded to a lot of the issues on 4 July 2017 by email. A lot are caused by 403 Forbidden errors due to mismatch between the incoming Springer article metadata and the ISSNs that DOAJ has for that journal. I'm going to send another email summarising the issues now.

**Comment by ClaraDOAJ** [comment]
Thanks!

**Comment by dommitchell** [comment]
@ClaraDOAJ please close this if this is done.
