### ISSUE TITLE
CEON/CEES xml problem

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1353]
Email from user
---
On the screen for uploading XML, I received the message successfully processed (again screen shot below:), but there is no content uploaded on the journal page (https://doaj.org/toc/1820-1202). Journal Title: Acta Stomatologica Naissi

Since XML are made with the same software I have used for other journals, I don't think that the xml is problem. I attached here one XML for this journal, and maybe this will help to all of us to resolve this problem.
---
[28_66.xml.zip](https://github.com/DOAJ/doaj/files/1173757/28_66.xml.zip)

**Comment by emanuil-tolev** [comment]
@ClaraDOAJ which account is doing the XML uploading?

**Comment by ClaraDOAJ** [comment]
Hi Emanuil

This is a big account with 35 journals. In this case it has a name instead of an account number:
CEON-CEES

**Comment by ClaraDOAJ** [comment]
Dear CL
This publisher is having the same problem with another journal. See email:

Dear Clara, 

the same situation repeated with another journal (accepted today to DOAJ). Journal title: Industrija (0350-0373, 2334-8526). Again I received message : "The following ISSNs in your article metadata are owned by you and another user. This is a problem at our end, please contact us with the details: 0350-0373, 2334-8526"

For the Acta Stomatologica Naissi, I tried to upload articles metadata again, and received: "5 articles imported (0 new, 5 updated)". This means that articles exist in DOAJ system, but they have not been connected to the journal title: https://doaj.org/toc/1820-1202 . Additionally I noticed on CEON/CEES journal page in Publisher Area, this Journal appears 2 times (old provider, and new one), and the answer is No for the "In DOAJ?" for the first provider (screen shot below). Maybe, this is the reason for confusion.

![image](https://user-images.githubusercontent.com/22593616/28722898-704bff82-73b5-11e7-87ff-9550610761a3.png)

**Comment by ClaraDOAJ** [comment]
I have sorted this problem, so closing.
