### ISSUE TITLE
Articles successfully uploaded- They do not appear in ToC but I see them in admin

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1355]
Hello CL

The journal "Spreadsheets in Education" has successfully uploaded 76 new articles. If I am in Admin, I can see these articles, but unfortunately they do not appear in the journal's ToC. Can you help me, please?

Admin system displays the 76 articles.
![image](https://user-images.githubusercontent.com/22593616/28610517-d96c996e-71e8-11e7-97c7-3e8b537fa939.png)

ToC is empty
![image](https://user-images.githubusercontent.com/22593616/28610556-0090ffb2-71e9-11e7-94a9-2815ba3d8389.png)

Successful upload
![image](https://user-images.githubusercontent.com/22593616/28610569-06a1760c-71e9-11e7-9edf-a69a5c4f0b84.png)

**Comment by Steven-Eardley** [comment]
@ClaraDOAJ I'm seeing the articles on the TOC now - maybe something has changed in the 3 weeks it took for me to look into this issue!

**Comment by ClaraDOAJ** [comment]
Thanks @Steven-Eardley! I am closing the ticket now.
