### ISSUE TITLE
Progress in Economic Sciences is experiencing a problem with API

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1358]
I gave API rights to this journal (acccount 23915951) and generated a new API key.

They have tried to connect but they are not able to. At the moment they get this:

**Deposit was not successful! The DOAJ API returned an error: '1 -

301 Moved Permanently**

Thanks!

**Comment by emanuil-tolev** [comment]
They need to ensure they are sending API requests to https://doaj.org . Note https, and note no www prefix.

**Comment by ClaraDOAJ** [comment]
Thanks!
