### ISSUE TITLE
Articles should be migrated to corrected record

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1361]
http://bit.ly/2wS56DY - all of these articles should be migrated to Malaysian Family Physician. 

http://bit.ly/2w3HAqf

There are two records for this journal and I have changed the ISSNs on the old record so that the articles should attach themselves to the new record but this isn't happening.

**Comment by dommitchell** [comment]
Another example where the status of the articles haven't changed

http://bit.ly/2vIIMyg

**Comment by dommitchell** [comment]
Could someone look at this please?

**Comment by Steven-Eardley** [comment]
> http://bit.ly/2wS56DY - all of these articles should be migrated to Malaysian Family Physician.

On the TOC for (the in_doaj) Malaysian Family Physician I am seeing all 319 articles from that search: http://bit.ly/2x5OqZS

This may be related to #1355. Bulk actions are handled asynchronously - they are added to a queue and processed later - so certain actions won't have immediate results. Can you check the other links you've included in this issue for the results you were expecting?

**Comment by dommitchell** [comment]
> Bulk actions are handled asynchronously - they are added to a queue and processed later - so certain actions won't have immediate results.

Ah-ha. That explains a lot. That's new for me! Ha. Thanks.
