### ISSUE TITLE
Check status of reporting background task

### ISSUE THREAD

**Issue by Steven-Eardley** [DOAJ/doaj#1364]
It looks like scheduled reports haven't run since April. See #1086.

**Comment by dommitchell** [comment]
Hopefully you can run them retrospectively

**Comment by Steven-Eardley** [comment]
Good news: The reports have been running successfully as asynchronous background tasks up to 1st August.  I wasn't looking in the right place because since the upgrade they are on the background task server rather than the app server. They have not, however, been configured to send emails since April.

Bad news: the report filenames are being written in a way that makes them un-openable on Windows computers - the colon character ```:``` in the timestamps works in Linux paths, appears as a ```/``` on my Mac, and doesn't work at all on Windows.

I have 2 tasks:

- [ ] Re-enable emailing of reports
- [ ] Change how the filenames are written so that they don't include disallowed characters.
- [ ] Rename the existing reports on the server to use the same method (or re-run them)

Here's a zip of the files before I've changed filenames (only useful if you use Mac or Linux):
[doaj_reports.zip](https://github.com/DOAJ/doaj/files/1239084/doaj_reports.zip)

**Comment by dommitchell** [comment]
Please tell me there's a clever way to convert this with a 3rd party program so that they work on Windows! We need the info contained in these.

Re your 3rd point above, re-running them would be best for us.

**Comment by Steven-Eardley** [comment]
No worries - It's just the file names that are incompatible so I can write a script to rename them. That'd be quicker than running them all again, too. Do you have an additional reason to prefer that approach?

**Comment by dommitchell** [comment]
Renaming them would be perfect! Great!

**Comment by Steven-Eardley** [comment]
Here are the renamed reports. I've just taken the timestamps out using the following commands

```rename 's/[T_].*$//' *``` for the directories, and recursively renamed the files with
```find . -type f  -exec rename 's/T\d+:\d+:\d+Z//g' {} \;```

[doaj_reports_renamed.zip](https://github.com/DOAJ/doaj/files/1241551/doaj_reports_renamed.zip)

**Comment by dommitchell** [comment]
Yes, got them and they work! Thanks!

**Comment by Steven-Eardley** [comment]
The fix has been released, you can expect an email on the 1st September (feedback@doaj.org) and for the reports to be open-able on Windows. Close this issue if it transpires thus.

**Comment by ClaraDOAJ** [comment]
Thanks -closing!
