### ISSUE TITLE
xml failure: 0872­-3419

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1366]
Dear CL

I am attaching an xml that is not working. The editor has apparently corrected all the errors according to the validator but it still does not work. Could you please have a look?
Also attaching a screenshot:
![image](https://user-images.githubusercontent.com/22593616/29565004-73711c5e-8744-11e7-9a67-faf30f203a50.png)
[vol33.xml.zip](https://github.com/DOAJ/doaj/files/1241949/vol33.xml.zip)

Many thanks

**Comment by Steven-Eardley** [comment]
From meeting 2017-08-22 : file system errors are uncommon, and usually temporary / intermittent if file syncing is slow between computers. User should retry the  upload.

**Comment by ClaraDOAJ** [comment]
Thanks, Steve- what about the others?

**Comment by emanuil-tolev** [comment]
Which others? Sorry, I thought this issue was specifically about vol33.xml attached in the first post.

**Comment by ClaraDOAJ** [comment]
Sorry, my mistake. 

I will get back to the user now.

**Comment by ClaraDOAJ** [comment]
Hello

They tried again and it did not work. See screenshot:

![image](https://user-images.githubusercontent.com/22593616/29626282-86bd49be-882e-11e7-9ed7-bb017267a766.png)

thanks!

**Comment by ClaraDOAJ** [comment]
This has been sorted.

many thanks!
