### ISSUE TITLE
Typo in LCC subject browser category

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1369]
'Warehouses' spelt 'warhouses'

![warhouse](https://user-images.githubusercontent.com/5955396/29814974-6a269d8e-8caf-11e7-9ca3-ef9bb8d07b37.jpg)

**Comment by Steven-Eardley** [comment]
Fixed other obvious typos:

https://github.com/DOAJ/doaj/pull/1370/files#diff-76f81c2efb5015daa453214e617a6684

**Comment by dommitchell** [comment]
Wow. So many! Good catch. Thanks for fixing.

**Comment by Steven-Eardley** [comment]
That's been released now.

**Comment by dommitchell** [comment]
Great!
