### ISSUE TITLE
DOAJ's development list as of September 2017

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1372]
We were encouraged to pull together a list of developments that we want done soon so that, if possible, some of them may be incorporated into the Refactoring Project. For Cottage Lab's perusal, comments, regrouping etc. 

Remaining list items at #18 

SEARCH/BROWSE
- automated public list of journals added/removed XXX
- more sophisticated search capabilities: interface and functions. XXX

DESIGN
- mobile-optimised site: responsive design, low bandwidth [designer review of the site?], accessibility changes and accessibility statement on site #472 XXX
- display most recent Note first in journal and application records. XXX
- changing the layout of the Application form, including reordering of questions, Save progress in Application Form. Link out to underlying data ('Submisssion' and 'Display') #1049 XXX

USERS
- allow more than one account to be associated with a journal; or more than one email address associated with an account. XXX
- stronger security around authentication and checking that passwords are strong XXX

METADATA
- point the metadata harvester to a new source (possibly #1043) XXX
- ORCID ID. (In metadata upload, search, download and facets; ORCID ID hyperlinked author name in short view.) XXX
- ability to upload external datasets, e.g ISSN, DEFER, BibPurls #1091, OADOI (https://oadoi.org/) XXX
- display article metrics (Altmetrics) XXX
- flag journals and user accounts internally to show that they are banned and how long for. XXX
- general data cleanup (see label in Github) XXX
- compatibility with multiple DTDs, especially MathML, JATS #1255 XXX
- Preferred Language plus Alternative Title support for multiple language article titles. #264 XXX
- greater visibility into the article corpus: who has uploaded what, when did they last upload, was it within 3 months of being awarded the Seal etc #1371 #1167 XXX

METADATA QUALITY SYSTEM
- auto-checking for duplicate ISSNs in records of all statuses, user accounts, #383 XXX
- ability for publishers log in and update their existing journal records or pending applications. -
 Highlighting of changes in updated records to allow for ease of checking. XXX
- allow publishers to EDIT article metadata in situ #275 XXX

API
- ability to search for Seal journals via API. #1082 XXX
- ability to retrieve Continuation information #1356 XXX

ASSOCIATE EDITOR WORKFLOW
- close down reapplication workflow XXX
- extra features for bulk editing in Applications (see Task #1316, #1338) XXX
- ability to impersonate other users in Admin #141 XXX

DATA VISUALISATION
- Statistics for the amount of data transferred/requested, ability to identify who is using our metadata (crawlers, aggregators, indexers etc) #265 XXX

CONTENT
- wysiwyg Page Admin Tool (CMS) XXX

STABILITY
- Web application stability, easier trouble shooting, easier upgrading (or allowing component upgrades like Elasticsearch 5.6), easier continued maintenance for stability

**Comment by emanuil-tolev** [comment]
Added stability section

**Comment by dommitchell** [comment]
We have received a very specific request to add a new option to the archiving question (25) on all application forms. See #137 

Question 25: add CINES and PKP PLN as options

Is this something that can be done under tnm or should it also wait?
