### ISSUE TITLE
2202-9478 International Journal of Education and Literacy Studies 

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1381]
Hello CL
The journal manager is trying to upload an xml but keeps getting this message> Internal Server error 500

![image](https://user-images.githubusercontent.com/22593616/30370579-5716e42c-9878-11e7-97b0-9a797fb1bf1f.png)

Does this problem come from our end? In case it does, please treat this with urgency.
Many thanks

**Comment by emanuil-tolev** [comment]
Yeah, it probably does, we'll investigate why we weren't alerted. I suspect Redis (a component we use for queuing up tasks) is down.

**Comment by emanuil-tolev** [comment]
That was bulk edit jobs not working correctly. I did notice that the jobs were at least recorded before this error was given. We have now reprocessed all of those jobs, so all of the uploads that they got an Internal Server Error for should now be processed.

![image](https://user-images.githubusercontent.com/1190172/30385661-bffb6932-989f-11e7-81f4-88ce6b204674.png)

**Comment by ClaraDOAJ** [comment]
Thanks all!
