### ISSUE TITLE
Change default ordering view for the Applications tab to 'Date applied', oldest first

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1391]
Please change the default ordering view for records under the Applications tab to 'Date applied', oldest first:

![dateapplied](https://user-images.githubusercontent.com/5955396/30685863-a6aaa3b8-9eb6-11e7-9475-5edb8c9c6356.jpg)

This would be for all roles.

**Comment by Steven-Eardley** [comment]
@dommitchell this would probably only be useful if you've already filtered out rejected / accepted applications, because the oldest will probably be those.

And if you want to ignore both of those at the same time, this will require an upgrade to Edges, which can do the OR facet selection.

**Comment by dommitchell** [comment]
> this would probably only be useful if you've already filtered out rejected / accepted applications, because the oldest will probably be those.

Agreed but it's a safety net to help our Triage folk. Please go ahead. 

Ignore Accepted/Rejected with OR in Edges is a good idea for the future.

**Comment by Steven-Eardley** [comment]
@dommitchell this has been released now.

**Comment by dommitchell** [comment]
Great!
