### ISSUE TITLE
Harvesting BUG?

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1396]
Dear CL

I received this email today. Could you help, please?

Hey there,
maybe I found a bug with the resumptionToken in your oai implementation, while harvesting metadata. It seems it will use twice (on the second last and the last page, e.g. see: https://doaj.org/oai.article?verb=ListRecords&resumptionToken=eyJuIjogOTQxMDAsICJtIjogIm9haV9kYyIsICJmIjogIjIwMTctMDktMDEifQ%3D%3D) but in the specification of the protocol it should be empty on the last page (see http://www.openarchives.org/OAI/openarchivesprotocol.html#Idempotency).
Best Regards
t

**Comment by richard-jones** [comment]
I've done some testing here, and I can't reproduce this problem.  I have done the following things:

* checked the link they provide.  Their link shows a page which does have a resumption token, and that resumption token is different to the one in the url, which is what we'd expect.  It's also not the last page that it points to.  That's not that surprising - resumption tokens aren't supposed to be persistent, they really only last a short amount of time before the data underneath shifts.  Probably, therefore, that this doesn't work doesn't tell us anything useful.

* I crafted a resumption token that did take me to the last page of results, and there was no additional resumption token in the resulting XML, which is what I'd expect, and in line with the spec.

* I ran a functional test over a local copy of the journal oai-pmh (the article one would take several days to complete), and as expected, on the final page there was no resumption token and the harvest finished successfully.

Perhaps this is a misunderstanding or misinterpretation by the user.  I can confirm that the OAI endpoint in DOAJ /is/ in line with the spec that they cite, and resumption tokens are not recycled or duplicated over the final pages.
