### ISSUE TITLE
Publish entire DOAJ dataset

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#1399]
In the same format that the API produces.

Possibly broken up by common use cases, e.g. articles by year, or whatever people want to do with the data.

This should help significantly with people wanting to siphon huge amounts of data off the API, which kind of clashes with other people who just want to use the discovery mechanisms to get a much smaller amount of data.

Also this should significantly improve DOAJ data re-use by the wider public. Imagine being at a hackday on the theme of "improve academic publishing" and you want to use DOAJ data. Do you want to wait 2-8 hours siphoning the entire catalogue off the API (it is possible, just slow and computationally expensive), or do you want to just download a single file?

**Comment by emanuil-tolev** [comment]
Just need a decision on whether this is OK to do under the same format and license as the data the API already returns. (Keep in mind they can already get all this data via the API, just much harder and resource-expensive for us for no reason.)

**Comment by dommitchell** [comment]
I see no reason why we shouldn't do this. We get asked for this stuff anyway. 

Is the implication here that by doing this we can reduce impact on the site?

**Comment by emanuil-tolev** [comment]
We *can*, people would still have to actually use it of course ;). But I think they will if it's clearly signposted.

Downloading a static file generated by us every 24h will definitely be less load than the equivalent API calls. And a much nicer user experience for those use cases.

**Comment by dommitchell** [comment]
Good. Please go ahead and do this.
