### ISSUE TITLE
Please add NSD sponsor Logo

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1401]
Dear CL

Could you add the following logo to our sponsors' page? I cannot attach it, as we have it in .eps. So an email will follow.

Norwegian Centre for Research Data
http://www.nsd.uib.no/nsd/english/index.html

**Comment by Steven-Eardley** [comment]
Released to live now.

**Comment by ClaraDOAJ** [comment]
Many thanks! Closing...
