### ISSUE TITLE
Editors should be able to revert to "in progress"

### ISSUE THREAD

**Issue by Steven-Eardley** [DOAJ/doaj#1406]
See https://github.com/DOAJ/doaj/issues/1293#issuecomment-330530959 - Currently, changes in status 'backwards' in the editorial pipeline are disallowed for associates and editors. Changing to "in progress" from "completed" should be possible for editors.

**Comment by Steven-Eardley** [comment]
Released now, editors should be able to change back to in progress now.

**Comment by dommitchell** [comment]
@ClaraDOAJ this has been added to the training manual for asseds

**Comment by dommitchell** [comment]
@Steven-Eardley @ClaraDOAJ don't we need a notification for this event too? Associate Editors get a notification when an application has been assigned to them. Can we re-use that for this instance too?

**Comment by ClaraDOAJ** [comment]
Thanks @dommitchell! 

I think this might have broken something. Now the feedback account gets an email every time an editor sends an application back to an associate editor.

![image](https://user-images.githubusercontent.com/22593616/32770102-a4e4e9f2-c91e-11e7-8a55-cbc3de913a71.png) Why could this be?

**Comment by Steven-Eardley** [comment]
>  don't we need a notification for this event too? Associate Editors get a notification when an application has been assigned to them. Can we re-use that for this instance too?

By 'we' do you mean a notification for managing editors? If so, is the email below enough?

> I think this might have broken something. Now the feedback account gets an email every time an editor sends an application back to an associate editor.

The feedback address is CC'd by default into all emails that the system sends.

**Comment by ClaraDOAJ** [comment]
@Steven-Eardley but I only got these notifications lately. Don't worry, I will create a filter to skip inbox.

**Comment by dommitchell** [comment]
So it looks as if notifications are already set up? Let's see what Steve says.

**Comment by dommitchell** [comment]
Notifications as being sent out.
