### ISSUE TITLE
2457-8827 random articles uploaded

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1410]
Hello CL
This journal keeps having the same problem. They upload xmls with a successful note. And only 5 of the 15 articles they upload appear on their ToC. Every time they try it is a different set of 5 articles. COuld you have a look at it?

"As you can see in the email exchange bellow, we have re-uploaded the articles from our latest issue of Metacritic Journal for Comparative Studies and Theory, as you advised, and we got the „successful upload” message after each of them, but the problem persists: only 5 articles out of the 15 appear on DOAJ (a different selection of five at every upload, but still only five).
Could it be a glitch on your end"

**Comment by dommitchell** [comment]
@ClaraDOAJ can you provide me with the page numbers? It sounds as if the articles are overwriting each other. Each article must have a unique page number *and* DOI

**Comment by ClaraDOAJ** [comment]
I need to ask the publisher, right?

**Comment by dommitchell** [comment]
> I need to ask the publisher, right?

Yep, have them send the XML file.

**Comment by ClaraDOAJ** [comment]
Ok, done.

**Comment by ClaraDOAJ** [comment]
The publisher said they uploaded everything manually. They had a tab for each submission and they realised that the upload worked if they closed the tab after submitting. So this problem is sorted. many thanks!
