### ISSUE TITLE
Two identical journal records created upon acceptance

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1413]
http://bit.ly/2kC6mZU

They are identical and both were created at exactly the same time. Any idea why?

**Comment by dommitchell** [comment]
And another: http://bit.ly/2xCFEBS

**Comment by richard-jones** [comment]
That's very weird!  Did you just discover these in the dataset, or did you see them being created.  Can you tell us what you were doing when you created them, and anything "interesting" about these records that sets them apart from normal?

**Comment by dommitchell** [comment]
Have connected you to Rikard via email. He spotted these.

**Comment by ClaraDOAJ** [comment]
hi! Apparently the man editor computer has been registering double clicks when he single clicks and this caused duplicate records in some instances...

Can we just delete one of the records?

**Comment by ClaraDOAJ** [comment]
And another one

http://bit.ly/2z9iDsD

Please can you help?

**Comment by richard-jones** [comment]
Hi @ClaraDOAJ - it's fine just to delete one of the records.  I believe @emanuil-tolev is working on a fix to prevent this from happening when the button is erroneously clicked twice.

**Comment by ClaraDOAJ** [comment]
Thanks! I have withdrawn the journals with this problem from DOAJ and added a note so publishers can continue to work with them. I haven´t deleted them completely. @dommitchell I think we should, but I wanted your opinion.

**Comment by dommitchell** [comment]
Yes, we should just delete them as they will just clutter up the db. Thanks!

**Comment by ClaraDOAJ** [comment]
@dommitchell have you just done it?

**Comment by dommitchell** [comment]
Nope!

**Comment by ClaraDOAJ** [comment]
Weird, most of them are not showing in the search as duplicate (with a yes-no) anymore. I have deleted two extra that Rikard had on a separate list too.

**Comment by richard-jones** [comment]
@ClaraDOAJ - do you have a list of the ones that are duplicated, or do we need to try and make one?  We'd basically need to run a report over the database that identified duplicated ISSNs, and then you would review it to see if there is any action that needs taking.  Let me know if you want us to look at that.

**Comment by ClaraDOAJ** [comment]
Hi @richard-jones, in principle it was a silly problem of a failing mouse that kept clicking twice. The man editor made a list of 5 and I have taken action in all of them. If I encounter any more instances I will ask you to run the report, unless it is very easy.

**Comment by richard-jones** [comment]
Ok, great, I've just assigned this one to you as well then.  We do have a fix that will be out shortly to defend against those double clicks.

**Comment by ClaraDOAJ** [comment]
I am closing the ticket then. Many thanks!
