### ISSUE TITLE
DOAJ data download issue

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1414]
Dear CL
I received the following email and I will need your help:

Hi Team,
                We are not able to download DOAJ records. We are getting error while downloading records. PFB error.
                  Is there any server issue from your side? Please let us know. We are able to download some records but for most of records we are getting this error.
                  PFA for sample downloaded file.
 
                  Error:-
                     <html>
        <head><title>503 Service Temporarily Unavailable</title></head>
        <body bgcolor="white">
        <center><h1>503 Service Temporarily Unavailable</h1></center>
        <hr><center>nginx/1.4.6 (Ubuntu)</center>
        </body>
        </html>
        ;503
 
 
      Steps to download data are as follows:
                Step 1
https://doaj.org/oai.article?verb=ListSets
 
Step 2  FIND medicine
https://doaj.org/oai.article?verb=ListIdentifiers&metadataPrefix=oai_dc&set=RE9BSjpJbnRlcm5hbCBtZWRpY2luZQ~~
 
Step 3   - resumption token
https://doaj.org/oai.article?verb=ListIdentifiers&resumptionToken=eyJzIjogIlJFOUJTanBKYm5SbGNtNWhiQ0J0WldScFkybHVaUX5-IiwgIm0iOiAib2FpX2RjIiwgIm4iOiA2MDB9
 
Step 4
https://doaj.org/oai.article?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:doaj.org/article:fcb85b13cb3a44e6ab1f9dfa2fe605a6

**Comment by richard-jones** [comment]
503 is just a connectivity issue (Service Temporarily Unavailable) - could be that there was a period of high activity which the infrastructure couldn't quite cope with.  The links provided are all working fine now.

@Steven-Eardley - did this come up on your radar in monitoring the performance on the scaled-down infrastructure?

**Comment by ClaraDOAJ** [comment]
Thanks!

**Comment by Steven-Eardley** [comment]
The site as a whole didn't go down at all during the infrastructure changes, but there was a period where the index was running on just 2 machines with 8GB RAM, which in resources isn't far off running on just one machine before the scale-down. Everything should have stayed up, though - we want it to remain performant in this circumstance.

The site monitoring did not record anything but 200 responses from loading the main page, and
I was also keeping an eye on response times for all requests and didn't see a major increase, but the OAI endpoint wasn't specifically monitored.

Nginx returning 503 implies it wasn't hearing from the app, perhaps all the workers were busy.

**Comment by Steven-Eardley** [comment]
I've tried the links at a high rate and am not seeing the same error either.

**Comment by ClaraDOAJ** [comment]
Dear CL

The user is still having problems, so it was not a problem of high activity, apparently.

See email:
     I have tried to download records from DOAJ link and still facing same issue. We are not able to fetch all the records from below link.
                  Most of the records are missing in source files. It’s giving same error. Please suggest.
 
                Link to fetch records: https://doaj.org/oai.article?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:doaj.org/article:a8d54dd6c76a4bdcad61768f5f9e75b2
 
                  Error:
                  <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
;503

**Comment by ClaraDOAJ** [comment]
Any updates on this one, please? User is chasing.

Thanks

**Comment by richard-jones** [comment]
The link the user provides is working for me: https://doaj.org/oai.article?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:doaj.org/article:a8d54dd6c76a4bdcad61768f5f9e75b2

A 503 indicates something temporary, so it doesn't seem like it's something that we can easily reproduce.

@Steven-Eardley - could they be hitting a rate limit?

**Comment by Steven-Eardley** [comment]
They certainly could, we are limiting to 2 requests per second, with a burst limit of 5 (i.e. we buffer 5 requests, if more come in and we have to exceed the queue, a 503 is returned).

**Comment by Steven-Eardley** [comment]
Since OAI-PMH is one of our slower endpoints, I'd prefer not to increase the limit. Rather, we should make the rate limit apparent in documentation.

**Comment by ClaraDOAJ** [comment]
This user keeps trying but they keep getting error. What can we do?

Thanks

**Comment by Steven-Eardley** [comment]
Have they confirmed they are trying at a slower rate, e.g. 1 per second?

**Comment by ClaraDOAJ** [comment]
It is working now that they tried at a slower rate. However, see their response:

Hi Team,
                I have tried with slower rate 1 request per sec and it’s working but taking too much time to download records.
                It’s taking near about 40 Mins to download 2700 records. Can you please improve this threshold?
                We have near about 8 lacs records to download.
 
Thanks,

**Comment by ClaraDOAJ** [comment]
And another email by this user who is now experiencing problems even with lower threshold

Hi Team,
                Now I am facing same data downloading issue with minimum threshold i.e. 1. Not able to download all records.
                Getting same error as previous. Please look into it.
 
                Error:
                     <html>
        <head><title>503 Service Temporarily Unavailable</title></head>
        <body bgcolor="white">
        <center><h1>503 Service Temporarily Unavailable</h1></center>
        <hr><center>nginx/1.4.6 (Ubuntu)</center>
        </body>
        </html>
  ;503

**Comment by ClaraDOAJ** [comment]
Any news?

**Comment by emanuil-tolev** [comment]
It appears to be configured correctly and when we try we seem to get the correct rate limit, so 1 req per second.

We'll attempt a more thorough test trying to harvest live OAI data. 

Could you ask, please:

> What is your source IP address? Could it be that multiple people are attempting to download DOAJ data, or that you're using multiple processes to do the harvesting?

**Comment by emanuil-tolev** [comment]
Also to consider raising the limit or raising it for OAI. But after we finish testing.

**Comment by ClaraDOAJ** [comment]
Thanks! Will ask that now.
