### ISSUE TITLE
problem when bulk uploading via API

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1418]
Dear CL

I received this email by a user at Elsevier. Can you help me, please?

Thanks!

----------

I have a query:
If I post my single Json file in the CRUD Articles post it is working perfectly.
If I post the same json file via bulk upload through API it is showing error “Supplied data was not valid JSON”. However it is an valid JSOn file.
 
For your quick reference:
 
 
:/Perl64/bin/DOAJ/today/new/S0123592317300451.json string(519) "HTTP/1.1 100 Continue HTTP/1.1 400 BAD REQUEST Server: nginx/1.4.6 (Ubuntu) Date: Fri, 27 Oct 2017 10:49:19 GMT Content-Type: application/json Content-Length: 114 Connection: keep-alive Access-Control-Allow-Origin: * Set-Cookie: session="vEdaYwC20yJCt8OKaHqFhEli980=?_fresh=STAxCi4=&_id=Uyc1NGU3MjdjY2E3ZjgwNGQ2YTRhNTEwZWIzYmMxZDk3YicKcDEKLg==&user_id=VjIyMTMwODk2CnAxCi4="; Path=/; HttpOnly {"status": "bad_request", "error": "Supplied data was not valid JSON (ref: 7c4c2a64-bb04-11e7-932a-04015bfb3501)"}"
 
Is it possible to setup a call in skype? So that it would be easy for us to move further.

**Comment by emanuil-tolev** [comment]
> - The bulk API accepts lists [{one article}, {second article}, {etc}] rather than single-record data. If you try to send *the exact* same data (e.g. a single article) to the individual article Create endpoint and the Bulk endpoint, it won't work since Bulk expect a list.

> - Could we have the JSON file you tried to send to the API? That might be the fastest way to diagnose the issue.

**Comment by ClaraDOAJ** [comment]
Hello Emanuil,

Response from publisher:

 
Thank you for your email.
 
I tried to upload 10 files using bulk method.  9 files uploaded successfully. 1 was thrown as an error. File attached here is the error file.
 
However, if I tried to upload it as a single file. It is uploaded . Please help me to sort out the issue.
 
Looking forward to your response.
[S0123592317300451.json.zip](https://github.com/DOAJ/doaj/files/1433872/S0123592317300451.json.zip)

**Comment by ClaraDOAJ** [comment]
Hello all,

The publisher is chasing this. Could you have a look at the json file I sent you a few days ago, please?
Thanks

**Comment by Steven-Eardley** [comment]
I've had a look. The file is indeed valid JSON. However, as we state in the [Bulk API docs](https://doaj.org/api/v1/docs), the bulk API accepts:

> A list/array of article JSON objects that you would like to create or update. The contents should be a list, and each object in the list should comply with the schema displayed in the GET (Retrieve) an article route. Partial updates are not allowed, you have to supply the full JSON.

Which the file isn't. It's a single {object}, not a [{list}, {of}, {objects}].

Secondly, there's an outside chance this could be an encoding issue. The file is encoded **ISO-8859**, I'd recommend trying using **utf-8**.

**Comment by ClaraDOAJ** [comment]
I have answered the publisher. Let's see what they say and I will close.

**Comment by ClaraDOAJ** [comment]
@Steven-Eardley the ISO-8859 encoding was the problem. They changed to utf-8 and it worked perfectly. Thank you very much for your solution! 
Closing ticket now.
