### ISSUE TITLE
Information does not stay in questions 5,6,7 on application form

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1420]
A user is trying to submit an application for South African Journal of Occupational Therapy and apparently they cannot submit it as information does not stay in questions 5,6,7. Could you have a look at it?

**Comment by richard-jones** [comment]
I've done a quick test on a dev system, and applications are working fine, and questions 5, 6, 7 are all kept populated both during a submission and a submission which results in validation errors.

Could you find out what values the user is trying to input in those fields?

**Comment by ClaraDOAJ** [comment]
I have asked them to use another browser and they will try.  I really think this was a problem at the user's end.

**Comment by ClaraDOAJ** [comment]
I will leave this open until I get a response from the user (I will close it if they do not respond in a few days)
