### ISSUE TITLE
Duplicate journal causing many server errors

### ISSUE THREAD

**Issue by Steven-Eardley** [DOAJ/doaj#1425]
This TOC page has been requested many times and returns a 400 error on the live site:
https://doaj.org/toc/2008-6970

Probably because it's duplicated:
http://bit.ly/2ysFwtZ

Someone's keen to see it though, there've been thousands of requests for this TOC page in the last 24 hours. Could be automated again, but this time with a user agent string that looks like a normal browser.

In any case, this 400 error should not occur. To fix:
- [ ] The DOAJ team can fix the data
- [ ] CL can provide a more useful error when two journals share a TOC URL.

**Comment by dommitchell** [comment]
@jbarnsby can you take care of this one? Thanks!

**Comment by jbarnsby** [comment]
Will need to remove new app accepted in error and keep reapp. Are there any articles associated with either journal record?

**Comment by jbarnsby** [comment]
New app taken out of DOAJ, leaving reapp in place. Page now working. Note no articles shown in live site.

**Comment by dommitchell** [comment]
Thank you Judith!
