### ISSUE TITLE
Misaligned search box on facetview pages

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#1426]
For reasons unknown, the search box on the search pages has drifted 1px out of alignment with the rest of the tools on the search bar.

**Comment by richard-jones** [comment]
This problem seems to only affect Chrome.  Experiments with adding padding fix the problem in chrome without breaking it in firefox, so I'll submit a minor fix.

**Comment by Steven-Eardley** [comment]
This is strange; only Richard could see this so the fix for this (pull request #142) has been closed without issuing the changes.
