### ISSUE TITLE
Admin bulk edit not working

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1433]
I am trying to bulk delete some articles and the bulk edit option keeps telling me that 0 articles will be deleted and then it proceeds to show an error message. Can you help me, please?

![image](https://user-images.githubusercontent.com/22593616/32783802-4626a9d0-c94d-11e7-8491-9865c0e8aae1.png)

**

**Comment by Steven-Eardley** [comment]
Verified this issue on the test server, so this is a problem with the front-end or the web app.

**Comment by ClaraDOAJ** [comment]
I have now deleted the 57 articles manually as a publisher was waiting for it. But this functionality is very useful, so please let me know if I can do anything to help.

**Comment by Steven-Eardley** [comment]
Fun fact: if you escape the colon in the text box, the delete will work. I.e. rather than

**Exchanges: The Warwick Research Journal**

You'd use
**Exchanges\: The Warwick Research Journal**

Also, the text in the box is superfluous when the **Journal title (Articles)** facet is selected, as it is in the example.

**Comment by Steven-Eardley** [comment]
@richard-jones @emanuil-tolev This seems to go all the way down to the ID iterator in https://github.com/DOAJ/doaj/blob/develop/portality/tasks/article_bulk_delete.py#L88

```python
@classmethod
    def resolve_selection_query(cls, selection_query):
        q = deepcopy(selection_query)
        q["_source"] = False
        iterator = models.Article.iterate(q=q, page_size=5000, wrap=False)
        return [j['_id'] for j in iterator]
```

The Article iterator doesn't return any results with the un-escaped query string from the text box, even though these results are present in the facetview interface. There's a little discrepancy here.

Perhaps this problem exists everywhere and we should look into how we get the facetview query in https://github.com/DOAJ/doaj/blob/develop/portality/view/admin.py#L585

```python
@blueprint.route("/articles/bulk/delete", methods=['POST'])
def bulk_articles_delete():
    if not current_user.has_role("ultra_bulk_delete"):
        abort(403)
    payload = get_web_json_payload()
    validate_json(payload, fields_must_be_present=['selection_query'], error_to_raise=BulkAdminEndpointException)

    q = get_query_from_request(payload)
    summary = article_bulk_delete.article_bulk_delete_manage(
        selection_query=q,
        dry_run=payload.get('dry_run', True)
    )

    return make_json_resp(summary.as_dict(), status_code=200)
```

**Comment by Steven-Eardley** [comment]
When we make the query in facetview, it is passed to elasticsearch via the following functions in [es.py](https://github.com/CottageLabs/facetview2/blob/edc415f42fcdddb3deceff144e55085fda07ef63/es.js):
```js

function jsonStringEscape(key, value) {

    function escapeRegExp(string) {
        return string.replace(/([.*+?^=!:${}()|\[\]\/\\])/g, "\\$1");
    }

    function replaceAll(string, find, replace) {
      return string.replace(new RegExp(escapeRegExp(find), 'g'), replace);
    }

    function paired(string, pair) {
        var matches = (string.match(new RegExp(escapeRegExp(pair), "g"))) || []
        return matches.length % 2 === 0;
    }

    // if we are looking at the query string, make sure that it is escaped
    // (note that this precludes the use of queries like "name:bob", as the ":" would
    // get escaped)
    if (key === "query" && typeof(value) === 'string') {

        var scs = esSpecialCharsSubSet.slice(0);

        // first check for pairs
        for (var i = 0; i < esPairs.length; i++) {
            var char = esPairs[i];
            if (!paired(value, char)) {
                scs.push(char);
            }
        }

        for (var i = 0; i < scs.length; i++) {
            var char = scs[i];
            value = replaceAll(value, char, "\\" + char);
        }

    }

    return value;
}

function serialiseQueryObject(qs) {
    return JSON.stringify(qs, jsonStringEscape);
}
```
So the ```:``` is escaped in the facetview but not in the query sent to the backend for the bulk action.

Should we be:
* making the escaped query accessible via ```get_web_json_payload``` somehow
* duplicating the escaping code in Python so we can use it for ES user queries from facetview
* using something ~hacky~ fancy like [bond](https://pypi.python.org/pypi/python-bond) to share JS code with Python apps to avoid duplication

**Comment by Steven-Eardley** [comment]
Implemented option 1 above.

**Comment by dommitchell** [comment]
Hi @Steven-Eardley I tried to do this today by moving a bunch of applications from one editorial group to another but it returned an error. Can you check this for me?

http://bit.ly/2CofxCl

![error](https://user-images.githubusercontent.com/5955396/34036995-5eb63324-e187-11e7-9725-3424ee6c8a15.jpg)

**Comment by Steven-Eardley** [comment]
This is unrelated to the above issue, and is to do with the connection to the task queue being lost. That's sorted now and we've opened issue #1471 to clear the old tasks, including this one.

**Comment by dommitchell** [comment]
Great. Closing.

**Comment by Steven-Eardley** [comment]
@ClaraDOAJ The fix has been deployed now, you should see searches like the one above working for bulk actions now.

**Comment by ClaraDOAJ** [comment]
Working!
