### ISSUE TITLE
I cannot access the account for 1934-5755 

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1435]
I need to reset the password of this account, and when I click into the owner's account (19345755), the system shows an error.

Can you help?

Thanks!

![image](https://user-images.githubusercontent.com/22593616/32836078-e49d1ac0-ca08-11e7-8553-7d2748a0e284.png)

**Comment by Steven-Eardley** [comment]
That account appears to be completely missing, which is a bit odd.

**Comment by richard-jones** [comment]
Yes, there is no account with this ID in the system, which is why you're seeing the error.

How did you get the link to the user page?

**Comment by Steven-Eardley** [comment]
There's a journal owned by this account which has the link:

https://doaj.org/admin/journals?source=%7B%22query%22%3A%7B%22filtered%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22term%22%3A%7B%22admin.owner.exact%22%3A%2219345755%22%7D%7D%5D%7D%7D%2C%22query%22%3A%7B%22match_all%22%3A%7B%7D%7D%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D

**Comment by ClaraDOAJ** [comment]
That is the one "Macrolinguistics".

**Comment by ClaraDOAJ** [comment]
Hello, the same problem happens with Journal 2088-7612. It was accepted on 16/11/17

**Comment by ClaraDOAJ** [comment]
And also with account  24588849.
This is worrying me quite a lot!

**Comment by ClaraDOAJ** [comment]
And another one  2458-8849
Account 24588849

**Comment by ClaraDOAJ** [comment]
And another one 01215469
Revista Colombiana de Psicología

**Comment by richard-jones** [comment]
Looks like all of these have been caught by the extended analysis this morning.

**Comment by dommitchell** [comment]
These three are now fixed. Closing
