### ISSUE TITLE
Migration upgrade script patchy coverage

### ISSUE THREAD

**Issue by Steven-Eardley** [DOAJ/doaj#1436]
Running the migration script #1429 on the test server; it didn't seem to collect all records.

I was keeping an eye on the misspelled 'litterature' in the subject **Japanese language and literature** - it managed to change a few, but not the majority of articles. That's despite completing scrolling through articles, journals, and applications on the whole index. Some of the articles are related to a journal that was successfully altered.

Here's a search on the test server showing those that were changed:
https://testdoaj.cottagelabs.com/search?source=%7B%22query%22%3A%7B%22filtered%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22term%22%3A%7B%22index.classification.exact%22%3A%22Japanese%20language%20and%20literature%22%7D%7D%5D%7D%7D%2C%22query%22%3A%7B%22match_all%22%3A%7B%7D%7D%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D#.WgrvnracaRc

And those that were left unaffected:
https://testdoaj.cottagelabs.com/search?source=%7B%22query%22%3A%7B%22filtered%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22term%22%3A%7B%22index.classification.exact%22%3A%22Japanese%20language%20and%20litterature%22%7D%7D%5D%7D%7D%2C%22query%22%3A%7B%22match_all%22%3A%7B%7D%7D%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D#.WgrvnracaRc

**Comment by richard-jones** [comment]
I suspect this is a scroll timeout.  I've seen today that when the scroll times out, it does so silently, so it appears to have finished but actually doesn't.  Esprit has a bit of code that looks for scroll timeouts to throw errors, but it is not being triggered, so there could be a bug there.

**Comment by Steven-Eardley** [comment]
This worked correctly, closing.
