### ISSUE TITLE
Error message re sending account email

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1437]
Can you remind me why we get messages like this:

Hm, sending the account creation email didn't work. Please quote this magic number when reporting the issue: 9f544256-c885-11e7-ab85-04014a62b401 . Thank you!

when the account was created successfully? We double-checked and no email was sent.

**Comment by richard-jones** [comment]
These messages are to alert us if something goes wrong while sending specific emails.  Looks like email sending failed for some reason.  The magic number helps us track it down in the logs.  @Steven-Eardley / @emanuil-tolev could you take a look?

**Comment by Steven-Eardley** [comment]
Not a particularly insightful error message from the app server log:
```
2017-11-13 15:16:28,740 - portality.core - ERROR - 9f544256-c885-11e7-ab85-04014a62b401
EmailException(gaierror(-2, 'Name or service not known'),)
```

**Comment by Steven-Eardley** [comment]
I reckon this is a (temporary) issue connecting to our email sending service. It's a low-level error coming from the socket trying to resolve mailtrap's URL to an IP address.

**Comment by dommitchell** [comment]
No action here. Closing.
