### ISSUE TITLE
1818-331X accepted but does not appear as accepted

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1449]
This journal was accepted on the 15th Nov. Although the application show as accepted, the journal does not show on the public or admin site as accepted.

I think this could be related with the data problems we are experiencing now.

![image](https://user-images.githubusercontent.com/22593616/33265708-fd8c3070-d372-11e7-8a56-39859c2ab01e.png)

**Comment by ClaraDOAJ** [comment]
Also happening with 1995-5588. Is this related to #1435 ?
![image](https://user-images.githubusercontent.com/22593616/33312798-2dc9799e-d429-11e7-9063-e0a38f6e2cd3.png)

**Comment by ClaraDOAJ** [comment]
Hello,

The application number for Aderna Fizika is
64219d320c9649ed8660c1f4c97fa7a2
Did not appear in your latest data inconsistencies analysis of 24th Nov

The application ID for Zanco Journal of Medical Sciences is
02d5ff707a0d49ffb5cb9a6f3b2db782
And it also does not appear on your latest data inconsistencies report of the 24th Nov

Is there anything else I can do to help?

**Comment by richard-jones** [comment]
The first of these (64219d320c9649ed8660c1f4c97fa7a2) does have an equivalent journal, but it is in_doaj=False.  This means that we need to extend the analysis a little further to cover the situation where an application does have a corresponding journal, but they are either sufficiently far apart in time the other way around (i.e. the journal is much earlier than the application) and/or the journal is withdrawn.

The second (02d5ff707a0d49ffb5cb9a6f3b2db782) does appear in the last analysis, under the tab "Applications accepted with no matching Journal"

**Comment by dommitchell** [comment]
This is now sorted and was related to the data inconsistencies. Closing
