### ISSUE TITLE
API issues. Error -1 when uploading metadata: The Warwick Research Journal

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1455]
This user (account 20539665) recently changed their journal to OJS and is trying to upload their metadata via API. Unfortunately they are experiencing some problems with the deposit of their metadata, as the API shows an -1 error.

See the user message below:
----
There are 16 random articles still showing on the DOAJ page and I’m not sure how they got there.  Also when we try to register articles through the API we get the below error message:
 
“Deposit was not successful! The DOAJ API returned an error: '1 -
 
301 Moved Permanently
 
nginx/1.4.6 (Ubuntu)”
 
Is there anything you could suggest we try to resolve this?  Am I better off going back to the XML uploads?

-----
Could you help me, please?

**Comment by Steven-Eardley** [comment]
That's a normal redirect, probably from HTTP to HTTPS. It should be possible to enable following of redirects in their Api client, or use the correct form of URL so the redirects don't happen.

e.g. When I type ```http://doaj.org/api``` in my URL bar, I get the following redirects:
```
Status Code	URL	IP	Page Type	Redirect Type	Redirect URL	
301	http://doaj.org/api	46.101.12.197	server_redirect	permanent	https://doaj.org/api
301	https://doaj.org/api	46.101.12.197	server_redirect	permanent	http://doaj.org/api/
301	http://doaj.org/api/	46.101.12.197	server_redirect	permanent	https://doaj.org/api/
200	https://doaj.org/api/	46.101.12.197	normal	none	none
```

I've opened issue #1468 to look into the extra redirect where it goes back to http with the ```/``` added.
