### ISSUE TITLE
Add new sponsorship logo in Jan 2018

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1459]
Link to: http://www.chaoxing.com/
![chaoxing_logo](https://user-images.githubusercontent.com/5955396/33474561-879067cc-d67b-11e7-897f-796907081711.jpg)

**Comment by dommitchell** [comment]
Restructure to sponsorship pages needed first.

**Comment by Steven-Eardley** [comment]
This was added without a restructure, in response to email from @ClaraDOAJ 2018-04-01.
