### ISSUE TITLE
search API

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#146]
somebody asked about a search API for a system which integrates with scholarly catalogues

I responded, but they need a bit more info I think + elasticsearch is behaving a bit unexpetedly (e.g. DOI matching doesn't seem to work well).

Otherwise they just need a few more examples really.

I'll summarise the correspondence here when the email thread's finished, could be quite valuable for writing up an informal search API doc in the future.

**Comment by richard-jones** [comment]
Discovery API now rolled out
