### ISSUE TITLE
Support ongoing update of journals by publishers

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#1463]
For the full specification, see: https://docs.google.com/document/d/1sy77He5cZEdbXW0QW7qGr4beQo160BmjrwgisEzelRM/edit

In outline this requires:

1. Cleanup old reapplication code
2. Create the UI components and mechanism for creating an update on-demand
3. Change the workflow name from “reapplication” to “update request”.
4. Review and modify as needed the Reapplication Form Context
5. Extend Application CRUD API to accept a journal as a target of an update request
6. Support Editors in review of update requests

**Comment by richard-jones** [comment]
@dommitchell @ClaraDOAJ - a couple of questions for you on the application form that publishers will use to submit updates:

1. Are there any fields that the publisher cannot change?  Basing this on the reapplication, the publishers cannot update the issns or the contact details - is that still true?

2. Are there any fields that we don't need to ask them for.  In particular, I'm thinking of the fields that are only stored on the application, and never come through to the journal.  These are: 

Q21 How many research and review articles did the journal publish in the last calendar year? *
Q22 Enter the URL where this information can be found *
Q29 Does the journal provide, or intend to provide, article level metadata to DOAJ? *

**Comment by dommitchell** [comment]
> Are there any fields that the publisher cannot change? Basing this on the reapplication, the publishers cannot update the issns or the contact details - is that still true?

Yes. All of those and title and alternative title.

Instead of just the red blocking/unavailable logo, is it possibe to program a more helpful message that pops up when one hovers the mouse over uneditable fields?

> Are there any fields that we don't need to ask them for. In particular, I'm thinking of the fields that are only stored on the application, and never come through to the journal.

We do need them to be able to update those 3 questions so no, all questions must be available on the form.

**Comment by richard-jones** [comment]
Questions 1 and 3 also need to be non-editable

@dommitchell - could you provide text for the introduction to the "update request" form

**Comment by dommitchell** [comment]
@richard-jones 

This form is only for updating an existing journal in DOAJ. The information in the form below has been copied from the current journal entry. Once you submit the update, it will go to our Editorial Team for review.

You may not change Questions 1, 3-5, and 9-11 (Journal Title, Alternative Title, ISSNs, contact details). If you want to change those, send an email to feedback@doaj.org with the new information.

Guides to filling in this form are also available in other languages (العربية, 中文, فارسی, français, Bahasa Indonesia, Italiano, Polski, Português, Română, Русский, Español, Türkçe, Українська).

**Comment by richard-jones** [comment]
@dommitchell @ClaraDOAJ - a question for when you're back in the office

Now that publishers can submit update requests, we need to add a page where they can see and then edit their pending requests.

In the reapplication, once a reapp was picked up by the editorial team, it disappeared from the publisher's view.

Does this behaviour still make sense?  There are a few things to consider:

1. A publisher can now repeatedly submit updates for the same journal, so it makes sense that they can see records in their publisher area that they have submitted, and which they can't currently edit.  This will help with the user experience of knowing when and if they can submit subsequent updates to a journal.

2. It might be confusing if items disappear from their update requests page, but the journal is not yet updated.

3. Publishers may have a list of reapplications from the reapplication period, which will suddenly appear in their "update requests" tab if we change the criteria of what appears on that page.

My recommendation would be to do the following:

* Enable viewing of all update requests
* Sort results so newest (by last updated date) appear at the top
* Provide edit links only for items which are in the status "submitted"
* Provide contextual information about the state of an application on all other records

Do we also want to consider giving publishers a read-only view of previously submitted and no longer editable records?

**Comment by dommitchell** [comment]
> Does this behaviour still make sense?

I think we agreed in London that we would retain this as a sort of version control. We do not want publishers to submit new updates on records that are in progress.

I think your proposal sounds good. I am slightly confused by (3) above. Can you elaborate?

> Do we also want to consider giving publishers a read-only view of previously submitted and no longer editable records?

I think this would be necessary as it may help them understand a journal's history but I'd like @greboun to input.

**Comment by richard-jones** [comment]
To clarify this one:

3. Publishers may have a list of reapplications from the reapplication period, which will suddenly appear in their "update requests" tab if we change the criteria of what appears on that page.

Reapplications are really a special kind of update request - they result in an Application in the database which originates from a publisher account, and which has ultimately been accepted or rejected.  This means when we introduce a page which allows a publisher to see all their update requests, no matter what their application status, they will also see all their reapplications in the same list, because they are essentially the same thing.

I don't think this is bad, and it won't affect the behaviour of the system, it's just that some information that we previously hid from publishers in order to aid them with their workflow will now become visible again.

**Comment by richard-jones** [comment]
Let me know when you have decided for sure with regard to a read-only view of the application, and if you want one I can put it in.

**Comment by dommitchell** [comment]
> I don't think this is bad, and it won't affect the behaviour of the system, it's just that some information that we previously hid from publishers in order to aid them with their workflow will now become visible again.

Hmm, I am concerned that it will confuse them. We have announced the end of the Reapplications project and if they suddenly see these in their lists again they may start to worry. There is already the misonception out there that we are requiring re-applications 1 a year. I'd hate to add to that. 

Can we keep them hidden?

**Comment by richard-jones** [comment]
Yes, we can keep them hidden, but we need to decide then how to handle other update requests after they have been accepted or rejected - should they still appear in the publisher's list in the publisher area, so that they have a record of what updates they previously submitted?

Let's talk about this in our next call.  I suggest we take a step back and just try to determine what the process of submitting an update request from the publisher's side should look like, then we can work out how to fit the old reapplications into that.

**Comment by greboun** [comment]
I think that we should not  hide the previous reapps records. They are also sort of updates.
to avoid confusion  the list could show the status, so in your proposal the reapps will show as accepted
Can we rename reapplication into update ??  We could allow submitting publishers to  update  for application statuses pending and accepted
Furthermore I think that the publisher could update the contact information. It is something happening often. They should not be able to update name, ISSN

**Comment by richard-jones** [comment]
A couple of decisions from today's meeting:

1. We will have a read-only page for applications that the publisher can no longer edit

2. We will hide reapplications from the publisher's view.  This can most effectively be achieved by adding a date cut-off for what's being shown on their Update Requests page.

**Comment by richard-jones** [comment]
@dommitchell - Another question has come up about the behaviour of the workflow for publishers:

The API has the ability for publishers to delete an application they submitted (assuming it is not already in workflow).  Should we also support this behaviour in the UI?

**Comment by richard-jones** [comment]
One other question: if we receive an update request via the API which attempts to change the title, issns, or other protected fields, should we just ignore those fields and update everything else, or should we reject the update request?

**Comment by richard-jones** [comment]
Decisions from today's meeting:

* We will allow publishers to delete via the UI
* We will generate an error when the publisher submits a request to change an unchangeable field
