### ISSUE TITLE
Password reset not working

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1464]
A user received the following email when trying tor reset their password. When clicking on the link and it did not work as per attached screenshot. Do you think there might be a bug?
Many thanks!

A password reset request for account '20851103' has been received and processed.
Please visit http://doaj.org/account/reset/dde65ee71dbc40cf95d16362b6c99d4a and enter your new password.

If you are the user '20851103' and you requested this change, please visit that link now and set the password to something of your preference.

If you are the user '20851103' and you did not request this change, you can ignore this email.

Regards,

![image](https://user-images.githubusercontent.com/22593616/33763968-c5b53e8c-dc12-11e7-80fc-b97b7d8b80b4.png)

**Comment by richard-jones** [comment]
I don't see a reset token set on this account, so that's why the user is getting this error.  

I just checked with my own account, and password resetting is working fine.

It's possible the user left the link for too long without clicking it.  Could you ask them to try again?

**Comment by ClaraDOAJ** [comment]
Sure! I have asked now.
