### ISSUE TITLE
1st Feb 2018: remove sponsor logos from home page and re-order sponsors page

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1470]
TASK FOR CL:
- remove all logos from the home page as close as possible to start Feb 2018

We are changing the structure of our sponsorship so there are some changes needed to the home page and the sponsors page:

1) Dom to request all logos from sponsors as SVG files.
2) CL to remove all but 5 logos from the bottom of the home page. These 5 will be our 5 largest sponsors. Which ones those are is not yet confirmed so just retain space for 5 of them.
3) DM: Restructure the static sponsors page so that we have 4 separate tiers or sections: Gold, Silver, Bronze (tiers with images), Patrons (text only)

This work must be completed as close as possible to the start of 2018.

**Comment by Steven-Eardley** [comment]
Task for me: test SVG rendering on the DOAJ site.

**Comment by dommitchell** [comment]
Richard will do this on 29th Jan

**Comment by dommitchell** [comment]
> Task for me: test SVG rendering on the DOAJ site.

@Steven-Eardley emailed you one to play with. GitHub doesn't support that file type.

**Comment by Steven-Eardley** [comment]
It just drops right in. Gloriously clear!

<img width="1408" alt="screen shot 2018-01-11 at 12 39 19" src="https://user-images.githubusercontent.com/1446355/34825973-9db11120-f6cc-11e7-973e-39d5f4e87f44.png">

**Comment by dommitchell** [comment]
Wow! What a difference! Good news.

**Comment by Steven-Eardley** [comment]
@dommitchell @ClaraDOAJ I've done the groundwork on this - in ```app.py``` we now have the 5 tiers:
```python
SPONSORS = {
    'featured': {
        'cogent-oa': {'name': 'Cogent OA', 'logo': 'cogent-oa.gif', 'url': 'http://cogentoa.com/'},
        'copernicus': {'name': 'Copernicus Publications', 'logo': 'copernicus.gif', 'url': 'http://publications.copernicus.org/'},
        'frontiers': {'name': 'Frontiers', 'logo': 'frontiers.png', 'url': 'http://www.frontiersin.org/'},
        'hindawi': {'name': 'Hindawi Publishing Corporation', 'logo': 'hindawi.png', 'url': 'http://www.hindawi.com/'},
    },
    'gold': {
        'emerald': {'name': 'Emerald Publishing', 'logo': 'emerald.png', 'url': 'http://emeraldpublishing.com/'},
    },
    'silver': {
        'lund-university': {'name': 'Lund University', 'logo': 'lund-university.jpg', 'url': 'http://www.lunduniversity.lu.se/'},
        'mdpi': {'name': 'Multidisciplinary Digital Publishing Institute (MDPI)', 'logo': 'mdpi.gif', 'url': 'http://www.mdpi.com/'},
        'taylor-and-francis': {'name': 'Taylor and Francis Group', 'logo': 'taylor-and-francis.gif', 'url': 'http://www.taylorandfrancisgroup.com/'},
        'karger-oa': {'name': 'Karger Open Access', 'logo': 'karger-oa.jpg', 'url': 'http://www.karger.com/OpenAccess'},
    },
    'bronze': {

    },
    'patron': {
        'tec-mx': {'name': u'Tecnológico de Monterrey', 'logo': 'tecnologico_de_monterrey.png', 'url': 'https://tec.mx/es'},
        'cottage-labs': {'name': 'Cottage Labs LLP', 'logo': 'cottagelabs.gif', 'url': 'http://cottagelabs.com'},
    }
}
```
Only ```featured``` appear on the front page (it's not limited to 5, but we can avoid putting more than 5 in there). They are sorted alphabetically as before.

On the sponsors page, the titles will only appear if the category is populated, and the patrons are only displayed in text. For example:

<img width="1477" alt="screen shot 2018-01-26 at 14 58 42" src="https://user-images.githubusercontent.com/1446355/35445454-90483a7a-02a9-11e8-8a60-36830a206eb7.png">

How would you like me to make this look better?

**Comment by ClaraDOAJ** [comment]
Hi!

I think the classification is Gold, Silver, Bronze, Patrons... Am I right @dommitchell?

**Comment by Steven-Eardley** [comment]
ah, this is from how i've interpreted dom's spec at the top of the issue:

>CL to remove all but 5 logos from the bottom of the home page. These 5 will be our 5 largest sponsors. Which ones those are is not yet confirmed so just retain space for 5 of them.
DM: Restructure the static sponsors page so that we have 4 separate tiers or sections: Gold, Silver, Bronze (tiers with images), Patrons (text only)

So if the front-page featured are a subset of gold, I can just remove that title from the sponsors page, and duplicate entries those in the gold section.

If featured sponsors and gold sponsors are the same thing, I can remove the featured tier entirely and display that on the front page.
