### ISSUE TITLE
Speednames updating their nameservers

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1473]
We received this email from Speednames. Any action for Cottage Labs here?

DNS/Domain updates

If you are using our name servers, as part of the upgrade we will be changing your name servers to those below:

NS1.MEGANAMESERVERS.EU
NS2.MEGANAMESERVERS.EU
NS3.MEGANAMESERVERS.EU

This change will take place over the next 2-3 weeks, and unless contacted, there is no need for any action on your part.

If you have any questions please do not hesitate to contact us.

Sincerely,

The Speednames Team,

support@Speednames.dk

**Comment by Steven-Eardley** [comment]
Depends if this counts as being contacted or not...

When I tried to log into speednames, I got a notification that it's been migrated to https://portal.speednames.dk, but I couldn't use Lars' email and password to get into it there.

It's probably worth checking we can access our DNS!

**Comment by dommitchell** [comment]
@Steven-Eardley good job you tested. Will get the updated credentials from Lars!

**Comment by dommitchell** [comment]
I have new login details which I will email to you Steve. CLosing.
