### ISSUE TITLE
Question: SQL

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1478]
We have a large Chinese sponsor asking us if we can provide our data in SQL. Rather than just say 'no', is there something I can tell them that would help them, like converting the JSON? Any tech details would be helpful.

>Would there be any possible that DOAJ could offer metadata of the format of SQL? Or other formats like Oracle? MySQL?

**Comment by richard-jones** [comment]
The short answer really is "no".

The longer answer is that to do this would mean us developing a relational schema for DOAJ, and writing migrations from our current JSON to an SQL database, before providing a (massive) export.

Interestingly, we have talked about introducing a relational database, and it's perhaps something we'd consider much further down the line, if the circumstances and benefits are appropriate.  But the work to do so is fairly large, so not any time soon.

**Comment by richard-jones** [comment]
Oh, I suppose the most important bit of technical detail is that DOAJ is a "document oriented" system, meaning that the data is stored in highly de-normalised documents.  To convert this to a "relational" system such as those that can be expressed in SQL would be a lot of work.

**Comment by dommitchell** [comment]
Thanks Richard. That's what I needed.
