### ISSUE TITLE
Add new box to home page: SCOSS

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1485]
Please add a new box to the home page, in between the second and third boxes. The box should contain the text:

'SCOSS: facilitating funding for sustainable OA' and link to https://doaj.org/members

**Comment by dommitchell** [comment]
Can I just add the box myself here: https://github.com/DOAJ/doaj/blob/dcfdb66cc1fb8307f2dadbf61f41e3ccf76a56e8/portality/templates/sidebar.html ? @Steven-Eardley

**Comment by greboun** [comment]
why do you link to DOAJ.ORG/MEMBERS?
and not to the SCOSS website?

Dr. Tom Olijhoek
Editor-in-Chief  DOAJ
Support us: www.doaj.org/support

**Comment by dommitchell** [comment]
> why do you link to DOAJ.ORG/MEMBERS?
> and not to the SCOSS website?

Because eventually, all DOAJ-SCOSS supporters will have their own page which this will link to.

**Comment by dommitchell** [comment]
@Steven-Eardley can you put https://github.com/DOAJ/doaj/blob/dcfdb66cc1fb8307f2dadbf61f41e3ccf76a56e8/portality/templates/sidebar.html on a branch for me? I am getting the message: You must be on a branch to make or propose changes to this file.

Thank you!

**Comment by dommitchell** [comment]
Ignore me! Found it
