### ISSUE TITLE
Check counting for 'edited' report

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1488]
After the helpful discussion in #1379 where we laid out exactly how and who were included in the completed reports, I'd like to know the same for the 'edited' reports. I have reason to believe that they are not counting correctly, or at least how I remember the discussion: https://github.com/DOAJ/doaj/milestone/24?closed=1

For example, in the most recent, I see that Pascal and Tom are both reported as touching nothing in NOv and Dec but I *know* and have proof that they both touched records. 

Can you clarify *how* edits are counted and *who* is included? Thanks.

[Records edited by month.xlsx](https://github.com/DOAJ/doaj/files/1625663/Records.edited.by.month.xlsx)

**Comment by richard-jones** [comment]
@richard-jones to add information about how calculations are made to the Decision Log

**Comment by richard-jones** [comment]
I have updated the decision log, with a brief description of the details of how reporting is done.

**Comment by richard-jones** [comment]
I have also looked at the provenance data, and the reports do not appear to tie up with it, so something is wrong.  I can see 115 edits made by Pascal, for example.

@Steven-Eardley - could you re-run the reports for all time for me, and send over the data so I can compare?

I wonder if the index stability issues we had in Nov/Dec interfered with the report processing?

**Comment by richard-jones** [comment]
To run reports for all time:

python portality/scripts/reports.py -o [output file]

**Comment by dommitchell** [comment]
Hello. Can I have an update on this one please @richard-jones Thanks!

**Comment by dommitchell** [comment]
Can we have this fixed before the Jan reports are run?

**Comment by emanuil-tolev** [comment]
I'm looking into this.  A bit touch and go as to whether it can be fixed by end of tomorrow but I'll do my best.
