### ISSUE TITLE
Please upload logo and give me the URL

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#1499]
![cope-logo-web-100](https://user-images.githubusercontent.com/5955396/35443018-c2f49914-02a9-11e8-8171-3e9e7e39f2f0.jpg)

I want to insert it into the About page. Thanks!

**Comment by Steven-Eardley** [comment]
@dommitchell uploaded to static_pages branch. You can add it to a page with:

```html
<img src="{{ url_for('static', filename='doaj/images/cope.jpg') }}" alt="COPE - Member since 2017" title="COPE - Member since 2017"/>
```

**Comment by dommitchell** [comment]
Thanks! Closing
