### ISSUE TITLE
DOAJ data fails to download

### ISSUE THREAD

**Issue by ClaraDOAJ** [DOAJ/doaj#1502]
Hi Team,
                We are not able to download full data from DOAJ site. We are getting error while downloading data.
                  As we are getting this error from last 3-4 months. Can you please look into it. I have raised request 1 month back also.
                  Error is below:
 
                     <html>
        <head><title>503 Service Temporarily Unavailable</title></head>
        <body bgcolor="white">
        <center><h1>503 Service Temporarily Unavailable</h1></center>
        <hr><center>nginx/1.4.6 (Ubuntu)</center>
        </body>
        </html>
  ;503

**Comment by richard-jones** [comment]
Hi @ClaraDOAJ - could you open this issue on the doajPM repo instead please?

Also, is this for the csv download?  I've just checked it and is working fine.  503 is usually an intermittent connectivity issue to do with load on the servers.

**Comment by ClaraDOAJ** [comment]
Hi Richard,

Response below. Apparently the problem persists.



                I am using below URL’s to download data. I am using Talend tool to download data.

                In step 3 and 4 we are passing Tokens and identifiers. I need to download only medicine related data.

               

                URL:

Step1: Listsets

                https://doaj.org/oai.article?verb=ListSets

 

setp 2  FIND medicine

https://doaj.org/oai.article?verb=ListIdentifiers&metadataPrefix=oai_dc&set=RE9BSjpJbnRlcm5hbCBtZWRpY2luZQ~~

 

step 3   - resumption token

https://doaj.org/oai.article?verb=ListIdentifiers&resumptionToken=eyJzIjogIlJFOUJTanBKYm5SbGNtNWhiQ0J0WldScFkybHVaUX5-IiwgIm0iOiAib2FpX2RjIiwgIm4iOiA2MDB9

 

step  4

https://doaj.org/oai.article?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:doaj.org/article:fcb85b13cb3a44e6ab1f9dfa2fe605a6

**Comment by emanuil-tolev** [comment]
Migrated to private repo, see link that just appeared ^.
