### ISSUE TITLE
Search plugin

### ISSUE THREAD

**Issue by vossviola** [DOAJ/doaj#1594]
Offer a search engine plugin for Firefox and other browsers, using the OpenSearch format: https://developer.mozilla.org/en-US/docs/Web/OpenSearch.
The plugin should be available via the DOAJ website and directories like https://addons.mozilla.org/de/firefox/search/?q=search%20engine&sort=updated&type=search.
The plugin should offer the choice between "search journals", "search articles" and "search all". (Or different plugins for this distinction?)

The one listed here doesn't work: https://mycroftproject.com/search-engines.html?category=54, and I didn't manage to build one using http://ready.to/search/en/, probably due to the complex search string.

**Comment by dommitchell** [comment]
Thanks @vossviola! 

CL: query from Twitter.
