### ISSUE TITLE
New/updated lines required in public Journal "short view"

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#161]
Public journal short view is the way that a journal record is represented in search results for the public.

- Title
- Alternative title
- ISSN
- Subject: LCC classification linked to subject browser
- Keywords
- Web site: URL, hyperlinked
- Peer review: Type
- License: Image or text
- APCs: Yes, No
- Article metadata: Yes, No. This is not pulled from the Application form question but from whether article metadata is present for this journal in DOAJ.

**Comment by richard-jones** [comment]
Note that the removal will also be done as part of the priority work in #534

**Comment by dommitchell** [comment]
Updated task description with our final wishes for the journal short view

**Comment by richard-jones** [comment]
A couple of comments on the desired display:

* Keywords - are these sufficiently informative to users to be on the search page?  We could just put them on the ToC.  I'm concerned that they'll take up space without adding much.

* Article Metadata - unfortunately, we can't display this on the search results page, as it would mean issuing a second query for each record being displayed.

**Comment by richard-jones** [comment]
I've now done a preliminary implementation of this view.  Will be ready to review when the test server is available again

**Comment by dommitchell** [comment]
Change ISSN to ISSN(s)
Move subjects to the same line as Subject.
Change 'Subjects:' to 'Subject'
Even out the spacing between items on the right-hand side: The Tick, License, peer review text
Close spacing between journal icon and the text

> Keywords - are these sufficiently informative to users to be on the search page? We could just put them on the ToC. I'm concerned that they'll take up space without adding much.

Agree. Leave them out.

> Article Metadata - unfortunately, we can't display this on the search results page, as it would mean issuing a second query for each record being displayed.

Can we add a date instead? Article metadata last added?

**Comment by richard-jones** [comment]
> Even out the spacing between items on the right-hand side: The Tick, License, peer review text

I'm not sure what this means, sorry - they are all just on new lines (i.e. there is a line break after each one).

> Article Metadata - unfortunately, we can't display this on the search results page, as it would mean 
> issuing a second query for each record being displayed.

> Can we add a date instead? Article metadata last added?

Unfortunately that's basically the same query, so is equally expensive.

**Comment by dommitchell** [comment]
> I'm not sure what this means, sorry - they are all just on new lines (i.e. there is a line break after each one).

From the html: <img src="/static/doaj/images/tick_long.png" title="Accepted after March 2014" alt="Tick icon: journal was accepted after March 2014" style="padding-bottom: 3px"

Maybe reduce the padding by a pixel?

**Comment by dommitchell** [comment]
General question: how will this display work for those journals that do not have the new data set? Especially the journals which still have old values for the APC question?

**Comment by richard-jones** [comment]
Answer to the general question: basically the layout looks for the elements of data it is interested in and displays them.  Old records won't have some of that data, so it will just be omitted.  It's particularly obvious, I think, around licensing - many of the old records are missing the licence information, so there is just no licence icon associated with them.

I've just made these tweaks, and they'll be ready for review at the next PR

**Comment by dommitchell** [comment]
> It's particularly obvious, I think, around licensing - many of the old records are missing the licence information,

True but in that instance we can only ADD new info because it is indeed missing. I'm more concerned about what happens when we take info away. The APC facet shows counts from the old journal information:
![apc](https://cloud.githubusercontent.com/assets/5955396/6867665/99c5fdb8-d484-11e4-988e-60822e07a0eb.jpg)
and this info will disappear so the totals here are going to drop dramatically. Is that correct?

**Comment by dommitchell** [comment]
Dom to discuss with Lars.

**Comment by dommitchell** [comment]
> Dom to discuss with Lars.

We decided that this was indeed a message management task but we'd like to preserve the data, broken down by country, subject etc right before the PVOD goes live. I imagine doing this by extracting the data into a spreadsheet and then publishing it later in a blog post. Thoughts? Concerns?

Feedback on the journal short view:
- [ ] add 'opens in new window' icon next to journal URLs and open URL in new window.
- [ ] change ISSNs to 'ISSN XXXX-XXXX (Print); XXXX-XXXX (Online)'
- [ ] move the type of peer review under the journal URL, leaving space on the right for the DOAJ Seal when it arrives. Make type of peer review not bold.

**Comment by richard-jones** [comment]
Subjects are missing because of an apparent problem with the test server data migration that we ran last week, they'll appear as soon as that is sorted out.

**Comment by richard-jones** [comment]
I've implemented the last 3 points for the next UI Tweaks PR, but I've not done the "open in a new window" link, because I'm not sure that's the most user friendly behaviour.  Have raised it as a question for the next meeting.

**Comment by richard-jones** [comment]
Everything should be fine except subjects display, which needs to be resolved separately.

**Comment by dommitchell** [comment]
Decided not to open things in a new window so this one is all good once we get the subjects back.

**Comment by dommitchell** [comment]
Subjects are in. Looking good. Closing.

**Comment by dommitchell** [comment]
We're going to have to add the date added to DOAJ. Omitting this was an oversight on my part.

Please add in 'Date added to DOAJ:' in bold under Subject.

**Comment by richard-jones** [comment]
Fix for next PR

**Comment by dommitchell** [comment]
IN and looking good
