### ISSUE TITLE
A test issue

### ISSUE THREAD

**Issue by markmacgillivray** [DOAJ/doaj#1636]
This is an example issue.

The aim of this issue is not to achieve everything stated in it, but just to spend some time learning about the DOAJ code and to bring up some points of conversation. That can be however much time you have available, just keep track of how much that is, and what was done in the time available.

There are three stages to this issue:

## Stage 1 - using github

* fork this repo to your own public github repo
* clone your new fork to your development machine
* create a new branch for yourself in your fork, give it a nice name
* edit the front page template by adding your own hello message in it
    * (it is a jinja template, and it can be found in portality/templates/doaj/index.html)
* save your change and commit it
* push your change to your branch on github, so others can see it
* add a comment to this issue giving us a link to your change!

## Stage 2 - running the code

(We don't expect this to be fully achieved, as the code is not really designed for external people to run - but we are interested in how far it is possible to get, what problems arise, and what can be done about those problems)

(You can continue to stage 3 whether you get the app running or not, so don't worry)

* We require elasticsearch, so try installing that first - https://www.elastic.co/
    * NOTE we use an old version, v1.4.4, so you will need that - see https://www.elastic.co/downloads/past-releases#elasticsearch
* Also note you only need elasticsearch itself, none of the extra stuff, and it is free
* Try following our install doc (which we know is incomplete and out of date!)
    * NOTE you can ignore redis and the scheduled tasks stuff
    * Install doc can be found in the repo at docs/system/INSTALL.md

## Stage 3 - developing a simple change

(Again it is fine if this can't all be achieved - just document what can be done, what was tried, and what issues arise, or any other questions that come up, for later discussion).

(Note, you can do this part even if you don't get the app running in the previous stage)

We want to add a piece of embedded metadata to a page representing a journal article.  An example of such a page is: https://doaj.org/article/000011857dbc42afb0f1a8c7e35ab46f

The metadata is like this:

```
<meta name='citation_doi' content='[doi here]'>
```

To do this, we first need to find the page template that is responsible for this page.  You can do that by looking for a URL in the Flask view that handles this page; look in `portality/view/doaj.py` and find the web route which serves this page.

The function that serves the page ends with a line like `return render_template(....` where the first argument is the page template.  Find the page template in the directory `portality/templates`.

The page template is a Jinja2 template.  Near the top of the page you will find other `meta` tags that you can use as examples as to how to embed this new metadata.

The DOI is a kind of identifier, and it is held in an area of the article object model called the `bibjson`.  The system model object which handles this particular piece of metadata can be found in `portality/models/bibjson.py`, and is called `get_identifiers`.  To display the DOI, you should get the bibjson from the article object that is passed to the Jinja template (this is done for you in the template), and then request the identifiers of the correct type from the article (the type of the identifier is "doi").  There should only be one DOI or no DOI, but note that `get_identifiers` returns a list.

Use this information to add the new `meta` tag to the article page and/or talk to us about how you would have done it, and what your approach to understanding the code and figuring out the task was.

If you want to discuss with us at any time, feel free! Comment below, or email us.

**Comment by amdomanska** [comment]
Hi! Here you can find my branch with hello message to front page added. 
https://github.com/amdomanska/doaj/tree/testIssue
