### ISSUE TITLE
Question about public data dump fields

### ISSUE THREAD

**Issue by glauberm** [DOAJ/doaj#1643]
Hello, I'm currently developing [an application](https://github.com/glauberm/open_journals_classifier) that uses the public data dump of journals you provide. I'm transforming the JSON on Entities based on [this structure](https://github.com/DOAJ/doaj/blob/develop/docs/system/Journal.md), and I think I've figured out most of the fields, but I was wondering if there is someplace where I could find a detailed explanation of each one, especially `bibjson.active`. What does this value mean in the context of the DOAJ application? Thanks

**Comment by dommitchell** [comment]
Hi there! Leave this with us and we will respond as soon as we can! Thanks for opening this issue!

**Comment by richard-jones** [comment]
Just to let you know, we are working on some documentation for you, as that will be useful for others too.  In the mean time, you are following our internal Journal object model documentation, which doesn't map completely to an Application, and the version you can use over the API is slightly further reduced in terms of fields.  You don't need to use `bibjson.active` on the API model, that's an internal field, so you can ignore it.

**Comment by richard-jones** [comment]
Here is some detail documentation on the structure of an incoming application record: https://github.com/DOAJ/doaj/blob/develop/docs/system/IncomingAPIApplication.md

Please do let us have any feedback if anything could be clarified.

**Comment by richard-jones** [comment]
I realise I have slightly misunderstood this issue - I've given you documentation for an application, but you need it for a journal.  We'll put together some equivalent documentation for that too.

**Comment by richard-jones** [comment]
Here is the documentation you actually need: https://github.com/DOAJ/doaj/blob/develop/docs/system/OutgoingAPIJournal.md

Note that this is documentation for the API, so there are some fields which appear in there which will not appear in the public data dump, as the API is authenticated.  Some fields, such as `admin.owner` are only visible to the authenticated owner of the journal, for example.

**Comment by glauberm** [comment]
Thank you very much, @richard-jones! I've noticed that the `archiving_policy` field is also different from the one in the public data dump, which has the `known`, `nat_lib` and `other` properties, but not the `policy` one. I plan to extract the data weekly, so I wonder if there are plans to change the structure available on the public data dump, and if there is, there is some channel where I can be informed of those changes? Thanks again!

**Comment by richard-jones** [comment]
Hi @glauberm - actually the `archiving_policy` difference is something we should fix - it's related to a legacy data model, I will raise an issue for that in our team issue tracker, and we may well update that at some point to bring it into line with the API.

In the mean time, if you are interested in keeping up to date with changes related to the API and the data dump, you can join one or all of our mailing lists; see under "Help and support" on this page: https://doaj.org/api/v1/docs

**Comment by glauberm** [comment]
Thanks, @richard-jones. I subscribed to both announcement-only and public discussion groups. Thank you very much for your assistance.

**Comment by richard-jones** [comment]
No problem, happy to help.  Closing this issue off, feel free to re-open or open a new one if anything else comes up.
