### ISSUE TITLE
More advanced history handling

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#17]
For the purposes of the data migration, we are ok to import all the data, and write all of the history information manually.

In the future, there will be use cases such as a journal name change or a merge of two journals where we will need to be quite intelligent as to how the history gets written.

None of this second part has been considered in-depth yet.

**Comment by dommitchell** [comment]
@richard-jones is this linked to #145 and the PVOD project?

**Comment by richard-jones** [comment]
It is related, but this refers more to the management of continuations, which we haven't included in PVOD.

**Comment by richard-jones** [comment]
Adding this to continuations milestone so that it can be tracked and closed with that

**Comment by richard-jones** [comment]
Superseded by other issues, closing
