### ISSUE TITLE
Displaying the DOAJ Seal and the 'recently updated' logos

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#177]
Rules and images

1) Recently updated
Rules: to be displayed alongside all journals that have been updated within the last 3 months.
To be displayed in both:
  -  the 'short view' (search results) and
  -  the 'long view' (journal issue pages), top right hand corner under the CC logo

Short view: ![doaj_accepted_logo_mini](https://cloud.githubusercontent.com/assets/5955396/3014959/9903c3c8-df5d-11e3-9443-3c0c39dae045.png)

Long view: 
![doaj_accepted_text_logo_mini](https://cloud.githubusercontent.com/assets/5955396/3014979/c36f495c-df5d-11e3-9487-46b7699faa79.png)

2) DOAJ Seal
Rules: to be displayed for those journals who have had the 'DOAJ Seal' checkbox on their journal page checked (e.g. https://doaj.org/admin/journal/2ae83e2d8df84ada9a7702235d582d4f) 
To be displayed in both:
  -  the 'short view' (search results) and
  -  the 'long view' (journal issue pages), top right hand corner under the CC logo

Short view: 
![doaj_seal_logo_mini](https://cloud.githubusercontent.com/assets/5955396/3014983/d3715da4-df5d-11e3-8194-b2ab5069569d.png)

Long view: 
![doaj_seal_text_logo_mini](https://cloud.githubusercontent.com/assets/5955396/3014984/d9da1640-df5d-11e3-88c1-994056c86d77.png)

**Comment by richard-jones** [comment]
@dommitchell - just doing some issue tidying, and picked this one up.  The Tick is now implemented, and I've opened another issue #512 to cover the Seal, when we get around to tackling that one.  You can probably, therefore, close this one off.
