### ISSUE TITLE
Development list for DOAJ

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#18]
LAST UPDATED 4th September 2017

SEARCH/BROWSE
- select year [start] and [end] to filter e.g. New Titles added. X
- select year [start] and [end] as facet.
- exportable list by country and by year (as in current country table)
- exportable list of journals per country
- automated public list of pending applications from 19th March 2014 - Journal title and ISSN - or the ability to export such a list
- automated public list of journals added/removed XXX
- more sophisticated search capabilities: interface and functions. XXX
- personalisation features: X
   - user accounts to enable saved searches 
   - highlight search terms in search results 
   - export searches as file

DESIGN
- mobile-optimised site: responsive design, low bandwidth [designer review of the site?], accessibility changes and accessibility statement on site #472 XXX
- redesign the PayPal buttons, if possible. X
- display most recent Note first in journal and application records. XXX
- changing the layout of the Application form, including reordering of questions, Save progress in Application Form. Add new section to indicate continuation. Link out to underlying data ('Submisssion' and 'Display') #1049 XXX

USERS
- allow more than one account to be associated with a journal; or more than one email address associated with an account. XXX
- stronger security around authentication and checking that passwords are strong XXX 

FEATURES
[- export articles to EndNote, Reference Manager, BibTex #15 XX TO BE DISCUSSED]

METADATA
- point the metadata harvester to a new source (possibly #1043) XXX
- ORCID ID. (In metadata upload, search, download and facets; ORCID ID hyperlinked author name in short view.) XXX
- ability to upload external datasets, e.g ISSN, DEFER, BibPurls #1091, OADOI (https://oadoi.org/) XXX
- display article metrics (Altmetrics) XXX
- flag journals and user accounts internally to show that they are banned and how long for. XXX
- general data cleanup (see label in Github) XXX
- compatibility with multiple DTDs, especially MathML, JATS #1255 XXX
- Preferred Language plus Alternative Title support for multiple language article titles. #264 XXX
- support for delete in OAI-PMH #25 (Ask CL)
- greater visibility into the article corpus: who has uploaded what, when did they last upload etc #1371 XXX

METADATA QUALITY SYSTEM
- auto-checking for duplicate ISSNs in records of all statuses, user accounts, #383 XXX
- automatic pinging of URLs to check for accuracy XX
- ability for publishers log in and update their existing journal records or pending applications. Highlighting of changes in updated records to allow for ease of checking. XXX
- allow publishers to EDIT article metadata in situ #275 XXX
- flagging of journals, using time-stamp, where data is no longer up-to-date #1167 
- user accounts

API
- ability to search for Seal journals via API. #1082 XXX
- ability to retrieve Continuation information #1356 XXX

ASSOCIATE EDITOR WORKFLOW
*** expand Slack use for volunteers ***
- close down reapplication workflow XXX
- extra features for bulk editing in Applications (see Task #1316, #1338) XXX
- ability to impersonate other users in Admin #141  XXX

DATA VISUALISATION
- Time delimiters needed for reporting and analysis #544  X
- Statistics for the amount of data transferred/requested, ability to identify who is using our metadata (crawlers, aggregators, indexers etc) #265 XXX

CONTENT
- wysiwyg Page Admin Tool (CMS) XXX
  - image upload capability
  - DOAJ must be able to make their own changes live.

**Comment by ClaraDOAJ** [comment]
@dommitchell the time stamp issue I was talking about yesterday https://github.com/DOAJ/doaj/issues/1167
