### ISSUE TITLE
add doajArticle OAI format

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#180]
In the previous version of the system there was a doajArticle format, which has been lost in the migration to the new system.  This is essentially a doaj-native XML format (probably the same as the import format), and some users would like it back.

**Comment by emanuil-tolev** [comment]
Make sure to use xml escaping stuff that @richard-jones did for OAI. Use settext() instead of .text=

**Comment by richard-jones** [comment]
There's a bit more to this, too, that I'd forgotten to put down here.

We will also need to update the metadata formats response, since now we support more than oai_dc but only for the article.

If you want to assign this to me, @emanuil-tolev, when you have done the XML export, I can update the list of metadata formats - would be quicker than me explaining what that means, and how to do it :)

**Comment by emanuil-tolev** [comment]
@richard-jones what is the XML namespace that this sits in?

like when you define it in the settings

```
        "metadataPrefix": "oai_doaj",
        "schema": "https://doaj.org/static/doaj/doajArticles.xsd",
        "metadataNamespace": ""
```

OAI_DC has http://www.openarchives.org/OAI/2.0/oai_dc/ but we don't really have a page that describes it. I guess we've got http://doaj.org/features and this is where a friendlier explanation than the XSD itself would eventually go, but it's not a very unique URL. For now I'm using http://doaj.org/features/oai_doaj/1.0 (and will make a veeery simple page at that URL which just points out where the schema is, and refers to doaj.org/features where the schema is described for *importing* stuff). Any other ideas here?

**Comment by emanuil-tolev** [comment]
For intermediate discussion here, this is what /oai?verb=ListMetadataFormats responds with now:

```xml
<?xml version="1.0"?>
<OAI-PMH xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.openarchives.org/OAI/2.0/" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
<responseDate>2015-03-22T12:06:27Z</responseDate>
<request verb="ListMetadataFormats">http://localhost:5004/oai</request>
<ListMetadataFormats>
  <metadataFormat>
    <metadataPrefix>oai_dc</metadataPrefix>
    <schema>http://www.openarchives.org/OAI/2.0/oai_dc.xsd</schema>
    <metadataNamespace>http://www.openarchives.org/OAI/2.0/oai_dc/</metadataNamespace>
  </metadataFormat>
  <metadataFormat>
    <metadataPrefix>oai_doaj_article</metadataPrefix>
    <schema>https://doaj.org/static/doaj/doajArticles.xsd</schema>
    <metadataNamespace>http://doaj.org/features/oai_doaj/1.0</metadataNamespace>
  </metadataFormat>
</ListMetadataFormats>
</OAI-PMH>
```

Looks good, pending few clarifications from above.

**Comment by emanuil-tolev** [comment]
Hm, I think I've got a question about exactly how the doajArticle format and standard OAI format will mesh together. Will finish coding as I've started now and ask tomorrow, the namespace is the easiest thing of all to change.

It seems you can put Dublin Core in PMH, and you can put any other format you like too (which is what we're doing). But I can't read the PMH spec supposedly at http://www.openarchives.org/OAI/2.0/ according to our own code, since it's 403 Forbidden-ing me.

**Comment by emanuil-tolev** [comment]
potential problem: we don't actually know an article's language, we have the journal language**s**. But doajArticles.xsd specifies a single language. For now we're returning the first journal lang but maybe should discuss. Also I think people must be giving us the actual article lang via XML upload and manual form entry if it's in the schema, so we should probably use that if available - need to see where it's being recorded.

**Comment by emanuil-tolev** [comment]
We can specify language for each keyword. Currently we ask for the keywords to be in English on the forms but they sometimes aren't. Should we hold off on specifying keyword language entirely or set it to English for all keywords?

**Comment by emanuil-tolev** [comment]
```documentType``` is currently being ingested when people upload it as follows:

```python
# document type
        dt = _element(record, "documentType")
        if dt is not None:
            # FIXME: outstanding question as to what to do with this
            pass
```

Consequently, I ain't setting it either.

**Comment by emanuil-tolev** [comment]
> We can specify language for each keyword. Currently we ask for the keywords to be in English on the forms but they sometimes aren't. Should we hold off on specifying keyword language entirely or set it to English for all keywords?

Same thing, but question is for the article's title.

**Comment by emanuil-tolev** [comment]
> > We can specify language for each keyword. Currently we ask for the keywords to be in English on the forms but they sometimes aren't. Should we hold off on specifying keyword language entirely or set it to English for all keywords?
> Same thing, but question is for the article's title.

aaand the abstract.

**Comment by emanuil-tolev** [comment]
long issue is long .. note to self, check if the subject elem in the PMH **header** needs to have LCSH defined as vocab like in the body, or if that's not allowed. If not allowed or recommended, then can leave {scheme}:{term} as it is now.

**Comment by emanuil-tolev** [comment]
Example produced by work so far (which I daresay is almost complete, pending @richard-jones review) https://www.dropbox.com/s/ja7mbw9s1kp65rd/doajArticle_oai_example_2015-03-22_211607.xml?dl=0

**Comment by emanuil-tolev** [comment]
Lots of similarities between new format and DC article format. Should consider refactoring after other tasks are done. I wrote the new class separately since it was quite hard to begin with, and I had to go over the schema elements one by one, hence didn't know what the overlap and differences would be, but there definitely is some overlap.

**Comment by emanuil-tolev** [comment]
> @richard-jones what is the XML namespace that this sits in?

Inventing our own is fine, we should do that and we should use it in the metadata section.

> all the language attrib questions

Don't set that attrib. So, no change required.

> For intermediate discussion here, this is what /oai?verb=ListMetadataFormats responds with now:

- [ ] Mm, not quite,  /oai?verb=ListMetadataFormats should list only oai_dc. But /oai.article?verb=ListMetadataFormats should list both. This is the only change so far.

**Comment by emanuil-tolev** [comment]
OK now /oai?verb=ListMetadataFormats returns

```xml
<OAI-PMH xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.openarchives.org/OAI/2.0/" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
<responseDate>2015-03-24T20:31:30Z</responseDate>
<request verb="ListMetadataFormats">http://localhost:5004/oai</request>
<ListMetadataFormats>
<metadataFormat>
<metadataPrefix>oai_dc</metadataPrefix>
<schema>http://www.openarchives.org/OAI/2.0/oai_dc.xsd</schema>
<metadataNamespace>http://www.openarchives.org/OAI/2.0/oai_dc/</metadataNamespace>
</metadataFormat>
</ListMetadataFormats>
</OAI-PMH>
```

And /oai.article?verb=ListMetadataFormats

```xml
<OAI-PMH xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.openarchives.org/OAI/2.0/" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
<responseDate>2015-03-24T20:31:46Z</responseDate>
<request verb="ListMetadataFormats">http://localhost:5004/oai.article</request>
<ListMetadataFormats>
<metadataFormat>
<metadataPrefix>oai_dc</metadataPrefix>
<schema>http://www.openarchives.org/OAI/2.0/oai_dc.xsd</schema>
<metadataNamespace>http://www.openarchives.org/OAI/2.0/oai_dc/</metadataNamespace>
</metadataFormat>
<metadataFormat>
<metadataPrefix>oai_doaj</metadataPrefix>
<schema>https://doaj.org/static/doaj/doajArticles.xsd</schema>
<metadataNamespace>http://doaj.org/features/oai_doaj/1.0/</metadataNamespace>
</metadataFormat>
</ListMetadataFormats>
</OAI-PMH>
```

need to do a bit more around this and will do PR.

**Comment by emanuil-tolev** [comment]
This is now fully complete, PR pending to be merged.

**Comment by emanuil-tolev** [comment]
Example OAI_DC file as produced by this branch (with subject classifications done differently): https://www.dropbox.com/s/zochb2narapc6h8/oai_dc_article_example_2015-03-25_072345.xml?dl=0

Example OAI_DOAJ file so you can compare side by side to OAI_DC and see if the new XML is sensible: https://www.dropbox.com/s/c36l7wmzycve70a/oai_doaj_article_example_2015-03-25_072345.xml?dl=0

Incredibly and slightly unexpectedly for me given the initial difficulties I had with understanding where to change the response, I think it is - today was the first time I compared them side by side myself.

**Comment by emanuil-tolev** [comment]
Another final task here:

- [ ] write unit test validating the data produced by a single record as full of data as possible against doajArticles.xsd - "For the test, I would use the oai_doaj xwalk to produce an XML doc, and then validate that doc against the schema."

**Comment by dommitchell** [comment]
@emanuil-tolev  Can you review this page http://doaj.org/features and let me know if it needs any changes after your work here?

**Comment by richard-jones** [comment]
@dommitchell - another one which I think can be reviewed while we're still finishing up the details.  This affects only articles, and you can look at the output at:

https://doaj.cottagelabs.com/oai.article?verb=ListRecords&metadataPrefix=oai_doaj

@emanuil-tolev - what else remains to complete this task?

**Comment by dommitchell** [comment]
Hmm, not really sure what I am looking for?

@richard-jones, also see my comment to @emanuil-tolev 

> Can you review this page http://doaj.org/features and let me know if it needs any changes after your work here?

I think updates need to happen there.

**Comment by emanuil-tolev** [comment]
@dommitchell Yep, I think you're right. Let me just confirm something about the context of this whole issue and the docs changes I'm about to make: some DOAJ OAI users wanted the doajArticle XML *output* format back (after it went after Semper Tool) so they could ingest it again.

I'll add a bit to the section called "Article Feed" showing what an example record looks like, and clarify that there are now 2 formats supported for articles: oai_dc and oai_doaj. Let me know if there's any specific wording (e.g. "we're bringing this feature back") or any other updates to the page you would like.

**Comment by emanuil-tolev** [comment]
> what else remains to complete this task?

- [ ] the unit test with XSD validation

    made good progress - generating almost the right XML but lxml is having trouble producing elements with no namespace, it prefixes each by ns0, ns1, ns2, ns3 ... ns18 in sequence). I need to force its hand a bit more.

- [ ] the docs changes to /features as per https://github.com/DOAJ/doaj/issues/180#issuecomment-91175149 and any other OAI docs changes @dommitchell would like

**Comment by richard-jones** [comment]
@dommitchell - for your review task, just take a look at the link I sent and see if the metadata and XML elements look reasonable to you.

From a technical point of view we're virtually there in terms of testing, just giving you the opportunity to see it all before it's finished.

**Comment by dommitchell** [comment]
> Let me just confirm something about the context of this whole issue and the docs changes I'm about to make: some DOAJ OAI users wanted the doajArticle XML output format back (after it went after Semper Tool) so they could ingest it again.

Yes. To be sure, I showed https://doaj.cottagelabs.com/oai.article?verb=ListRecords&metadataPrefix=oai_doaj to the member of the community who first raised this and he said: "this is perfect, now I don't need to add a parser routine to process DOAJ article level metadata." so I'll take his word for it. :)

> Let me know if there's any specific wording (e.g. "we're bringing this feature back") or any other updates to the page you would like.

Please add to the top of the page, in bold, before 'DOAJ supports OAI-PMH feeds for both Journals and Articles, at different urls':

'Our OAI-PMH service was updated in April 2015. In that update we reinstated the doajarticle metadata tag and provided more granularity to the data. The notes below have been updated to reflect this change,'

**Comment by emanuil-tolev** [comment]
Docs updating, will soon be ready to review on test server when PR is merged. I added

> 'Our OAI-PMH service was updated in April 2015. In that update we reinstated the doajarticle metadata tag and provided more granularity to the data. The notes below have been updated to reflect this change,'

to top of page as requested, but have also added revision history for each OAI endpoint where we can record changes we make - you'll see it soon, it's rather simplistic but should do the trick.

**Comment by dommitchell** [comment]
Looking good. closing.
