### ISSUE TITLE
ISSN and eISSN [BUG]

### ISSUE THREAD

**Issue by zoranzdr** [DOAJ/doaj#1858]
**Contact details of bug reporter (or proxy of bug reporter)** 
Zoran Zdravkovski
Editor in chief Macedonian Journal of chemistry and Chemical Engineering

**User account you are logged in to when this occurred**
The account’s e-mail address or username
*please do not send us your password or API keys*
zoran@ukim.edu.mk

**Where this happened**
e.g. in the UI, API, OAI and which URL you were trying to access.  
*please do not send us your password or API keys*
https://www.doaj.org/publisher/uploadfile 

**When this happened**
What date and time; if it happened several times: a date range or all dates and times it happened. 
24 Feb 2021 07:23:14 UTC

**What happened**
- What were you trying to do? 
- What error message was received (do not paraphrase: write the exact message)? 
- Was the problem repeatable? Did you try several times with the same result? 

I tried to upload articles at  from the Macedonian Journal of Chemistry and Chemical Engineering with a DOAJ native XML file but got the following error message:
One or more articles failed to ingest; entire batch ingest halted (what does this mean?)
The following ISSNs in your article metadata are owned by you and another user. This is a problem at our end, please contact us with the details:
1857-5625, 1857-5552

**Expected behaviour**
- What did you expect to happen? 
I expected the articles to be uploaded

**How to reproduce**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 85.0.1 (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here, such as copies of the XML data you were trying to send.

**Comment by ClaraDOAJ** [comment]
Dear Zoran Zdravkovski,

We have fixed the problem in your journal's account. You should be able to submit metadata successfully now.

I will also copy this message to an email to zoran@ukim.edu.mk.

Thank you.
