### ISSUE TITLE
[BUG] XML not importing

### ISSUE THREAD

**Issue by hktang** [DOAJ/doaj#1893]
Hi, I encounter issues when uploading XML article data, and do not have sufficient error message to understand what went wrong. I would appreciate it if you could have a look further. Thank you! 

@hktang

**Contact details of bug reporter (or proxy of bug reporter)** 

@hktang
APN Secretariat

**User account you are logged in to when this occurred**

xdeng@apn-gcr.org

**Where this happened**

This happens on the XML upload page: https://doaj.org/publisher/uploadfile

**When this happened**

From 26 Apr 2021 06:11:21 UTC to 26 Apr 2021 06:25:03 UTC

**What happened**

- I tried to upload article XML files in Crossref 4.4.2 XML format.
- Error message: `Unanticipated error when importing articles (what does this mean?)`
- I tried three times, and receive the same error message. The status changed to "pending", and "processing failed" after refreshing.

**Expected behaviour**

- Seeing no XML format issues, I expect the XML files to be properly parsed and updated.

**Additional context**

A copy of the article XML is attached here: [1619421070.zip](https://github.com/DOAJ/doaj/files/6375031/1619421070.zip)

**Comment by dommitchell** [comment]
Hello, thanks for registering this with us. We will take a look at the information that you sent and will respond as soon as we can.

**Comment by dommitchell** [comment]
Hi there @hktang it doesn't look like your journal is indexed in DOAJ. I see that it applied in 2020 but that the application was in fact rejected.  Only journals which are in DOAJ may upload article metadata to us.

All the best, Dom

**Comment by hktang** [comment]
Hi @dommitchell, thanks for your reply. The journal [was approved](https://doaj.org/toc/2522-7971?source=%7B%22query%22%3A%7B%22filtered%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22terms%22%3A%7B%22index.issn.exact%22%3A%5B%222522-7971%22%5D%7D%7D%5D%7D%7D%2C%22query%22%3A%7B%22match_all%22%3A%7B%7D%7D%7D%7D%2C%22size%22%3A100%2C%22sort%22%3A%5B%7B%22created_date%22%3A%7B%22order%22%3A%22desc%22%7D%7D%5D%2C%22_source%22%3A%7B%7D%7D) on the 21st of April. Would it be likely that it takes time to populate this?

**Comment by dommitchell** [comment]
Apologies. I was looking at the old application.

Can you tell me whether you used 'Select a file' or 'Upload from a link'?
Can you confirm that you chose Crossref 4.4.2 from the File format section?
Can you send me a screenshot of the History of uploads area with any error messages expanded?

Thank you!

**Comment by hktang** [comment]
No worries! 

- I used "Select a file";
- Yes, I confirm "Crossref 4.4.2" was selected;
- Please find the screenshot below. It seems the XML has been validated but there's an unknown error.

![Screenshot_2021-04-26  Directory of Open Access Journals(1)](https://user-images.githubusercontent.com/2219830/116086298-a1a5a180-a6da-11eb-9e5b-5a3831bb9776.png)

Thank you in advance!

**Comment by hktang** [comment]
Hi again, I tried to break down the XML into 5-article chunks and three of them were not imported:

- [1619494432-10.xml](https://github.com/APN-ComDev/Crossref-Tool/blob/master/output/1619494432-10.xml) Failed with `Unanticipated error when importing articles`
- [1619494432-25.xml](https://github.com/APN-ComDev/Crossref-Tool/blob/master/output/1619494432-25.xml) Failed with `Unanticipated error when importing articles`
- [1619494432-30.xml](https://github.com/APN-ComDev/Crossref-Tool/blob/master/output/1619494432-30.xml) Failed with `One or more articles in this batch have duplicate identifiers` Although I can confirm there aren't any duplicates in this batch.

I tried uploading and using the URL feature.  Hope these information helps!

**Comment by dommitchell** [comment]
Thanks! Can you also attach one of the XML files that worked? That would be great.

**Comment by hktang** [comment]
Hi, here's a link to an XML that worked: https://github.com/APN-ComDev/Crossref-Tool/blob/master/output/1619494432-5.xml 

Other other files that worked (except those there mentioned earlier) can be found [here](https://github.com/APN-ComDev/Crossref-Tool/tree/master/output). Thanks again!

**Comment by hktang** [comment]
Upon further splitting the XML batches into 1 article files I found the culprit: it seems the system is rejecting authors with only "Surname" or "Given name" in the persone_name field.

Here's an example file that was rejected: https://github.com/APN-ComDev/Crossref-Tool/blob/master/output/1620350743-25.xml

In the example, two authors (Perdinan and Yonvitner) have only one name and do not have "given name" - "surname" pairs.

Hope this helps!

**Comment by dommitchell** [comment]
Thanks. This is helpful. I will need to check with Crossref and my developers if there is a difference in the way that we handle names.

**Comment by dommitchell** [comment]
Have you validated the XML files against the Crossref schema?

**Comment by hktang** [comment]
Thank you! I have validated the XML using https://www.freeformatter.com/xml-validator-xsd.html

The main part (journal_metadata) of the XML is retrieved using Crossref API, so I assume it is a valid Crossref 4.4.2 file.

**Comment by dommitchell** [comment]
Hello! Thanks for your patience while we investigated this. We found a bug and will have a fix in for that as soon as we can.

**Comment by dommitchell** [comment]
I forgot to follow up here but I can confirm that the bugfix was implemented. Closing.
