### ISSUE TITLE
Is there a way to strip HTML codes from submitted metadata?

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#195]
Question from publisher:
As editor and responsible of RICYDE. International Journal of Sports Science, I have uploaded all data (number by number, item by item) since October 2005, being able to shape the paragraphs of the texts of the abstracts, as the application allowed me to use HTML codes for justifying paragraphs, etc. Since the new application does not allow HTML codes, all (Spanish and English) texts of the abstracts have suffered a misconfiguration, mixing text and revealing, unnecessarily, HTML codes. I would be really grateful if you could help me to find another solution [other than reuploading all the metadata again by hand], so that the content of my journal is not impaired at the time of load.
/ends/

Can we help this publisher by stripping out HTML codes? Can we build something like that into the upload feature for ALL files?

**Comment by richard-jones** [comment]
I'm slightly unclear what we have decided to go for here.  We have talked about an "html cleaning" exercise, but I'm not sure what we should actually do under that heading - we could try stripping known HTML tags, but this might have unforseen consequences (like, if the abstract specifically talks about HTML, or if there are legitimate scientific uses of the same notation).

My inclination is just to escape any HTML in the UI (which is what we're already doing), and document the situation for the publisher.

**Comment by dommitchell** [comment]
I think we should go ahead and strip out known HTML tags. Common ones only, such as: bold, italic, para, break. Would it be possible to do a count and get a breakdown of how bad the problem is first? They are hard to search for.

**Comment by dommitchell** [comment]
Found one: https://doaj.org/article/613a262efa404309a42e8d19bde50879

**Comment by dommitchell** [comment]
This journal in particular seems to have problems with " "> https://doaj.org/toc/2074-7705

**Comment by dommitchell** [comment]
ET and RJ will discuss and ascertain size of problem.
