### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by VincentChollier** [DOAJ/doaj#1969]
Hi,
I uploaded a XML crossref in order to update articles metadata. In the former version, titles were encoded in "en" but in the new version titles are encoded in "fr". The problem is that titles are not encoded in the right iso-code now :
"Acteurs et formes d&#8217;investissement de la fronti&#232;re"
How can I fix the problem ?
Thx

**Comment by dommitchell** [comment]
Hello @VincentChollier 

Thanks for getting in touch. Please send us the following details:

- The time of the file upload
- Whether you are uploading a file or uploading from a link
- The exact error message as it appears in the “Notes” column of your upload area, including the text in the 'What does this mean?' section
- A screenshot of the error message
- Your publisher account ID or the account ID you are logged in with
- The file(s) you had problems with

Thanks so much!

**Comment by VincentChollier** [comment]
Dear @dommitchell 

The file has been uploaded on 31 Aug 2021 08:42:06, and it's a XML crossref for an entire issue
My account ID is bf927ee1
The uploaded file wich is problematic is 10.35562-frontiere-s-506.xml
I have no error message, but the display is:
![image](https://user-images.githubusercontent.com/43059602/131500297-561aaffe-ed78-478a-a601-0c10374c9ced.png)

**Comment by dommitchell** [comment]
Thanks @VincentChollier. These details are very useful!

We don't keep XML files after they are uploaded to us, so please zip it and attached it here. Thank you so much!

**Comment by VincentChollier** [comment]
Here it is :
[10.35562-frontiere-s-506.zip](https://github.com/DOAJ/doaj/files/7083871/10.35562-frontiere-s-506.zip)

**Comment by dommitchell** [comment]
Thank you I will get this over to the developers and get back to you shortly.

**Comment by VincentChollier** [comment]
Dear @dommitchell,
I have the same problem with two other files: 
uplaoded on
14 Sep 2021 10:26:30 UTC (10_35562-pratiques-et-formes-litteraires-144.xml) and 
14 Sep 2021 10:26:22 UTC (10.35562-pratiques-et-formes-litteraires-74.xml)
this time, it was the first upload.
Here is attached the zipped files:
[Downloads.zip](https://github.com/DOAJ/doaj/files/7161545/Downloads.zip)

**Comment by dommitchell** [comment]
Thank you!

**Comment by dommitchell** [comment]
Hi Vincent!

The developers looked at the XML and 

> In the former version, titles were encoded in "en" but in the new version titles are encoded in "fr".

In the first zip file you uploaded (https://github.com/DOAJ/doaj/files/7083871/10.35562-frontiere-s-506.zip), the language code in the files is 'fra' and this isn't valid. If you swap that out with 'fr' then the files should work. 

We are still working on the issue with the special characters. 

I will get back to you when I know more.

**Comment by VincentChollier** [comment]
Hi Dom,
Thank you for your answer.
My bad, the zip file I sent you is not the one I uploaded to the DOAJ : I tried to change the iso code to see if it worked better, but I forgot to correct it before sending it to you.
All other XML files are encoded in 'fr' as requested.

**Comment by dommitchell** [comment]
Hi Vincent

Just to let you know that this was a bug and it has now been fixed. Thanks for alerting us to this.

**Comment by VincentChollier** [comment]
Hi Dom,

Thanks a lot.
