### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by EduemLibrarian1** [DOAJ/doaj#1979]
Warning: don’t send us your passwords or API keys. 13fe2de385ca4d26bc725f88284c9dbc
i have but, it's not working with the key, it doesn't send... it was sending with xml... now not too. what should I do?

**Contact details of bug reporter (or proxy of bug reporter)** 

**User account you are logged in to when this occurred**
The account’s e-mail address
*please do not send password or API keys. this is a public ticketing system. if you do not want to put your email address here, please send the information below to us in an email instead.*

**Where this happened**
e.g. in the UI, API, OAI and which URL you were trying to access.  
*please do not send us your password or API keys*

**When this happened**
What date and time; if it happened several times: a date range or all dates and times it happened. 

**What happened**
- What were you trying to do? 
- What error message was received (do not paraphrase: write the exact message)? 
- Was the problem repeatable? Did you try several times with the same result? 

**Expected behaviour**
- What did you expect to happen? 

**How to reproduce**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here, such as copies of the XML data you were trying to send.

**Comment by dommitchell** [comment]
Thanks for logging this with us. Can you send us the URL and a screenshot of the problem that you are seeing?

**Comment by EduemLibrarian1** [comment]
obrigada Dommitchelll, vou entrar novamente..e entro em contato

**Comment by dommitchell** [comment]
No response. Closing.
