### ISSUE TITLE
Doaj xml import ERROR:SCHEMASV:SCHEMAV_ELEMENT_CONTENT: Element 'title'

### ISSUE THREAD

**Issue by murattkoc** [DOAJ/doaj#2050]
Hi Everyone,
I'm trying to load xml into doaj but getting header error. There are 2 languages in xml and the second one gives an error. Wasn't multi-language already optional?
Can you help me Please ?

![Screenshot from 2022-01-26 18-29-58](https://user-images.githubusercontent.com/74684467/151193498-f597625d-e49d-4f6b-a5e2-2e3f8fd5f9db.png)
[mk.txt](https://github.com/DOAJ/doaj/files/7942972/mk.txt)

**Comment by dommitchell** [comment]
Hello! It seems that two records have been merged into one. Have a look at https://doaj.org/docs/xml/#example-doaj-xml-file

Your XML is missing tags after the <abstract> tag and then the correct tags to start a new record are also missing.

Hope that helps!

**Comment by murattkoc** [comment]
I think I solved the problem. I placed the title tags one under the other and it worked.

**Comment by dommitchell** [comment]
Great! Thank you for letting me know.

**Comment by murattkoc** [comment]
you're welcome :)
