### ISSUE TITLE
[Validation message from schema 'crossref': 2:0:ERROR:SCHEMASV:SCHEMAV_CVC_ELT_1: Element '{http://www.crossref.org/schema/4.3.6}doi_batch': No matching global declaration available for the validation root.]

### ISSUE THREAD

**Issue by asadmath** [DOAJ/doaj#2071]
Warning: don’t send us your passwords or API keys.

**Contact details of bug reporter (or proxy of bug reporter)** 
Dr. Asad Ullah (dr.asadullah@kiu.edu.pk)

**User account you are logged in to when this occurred**
The account’s e-mail address: dr.asadullah@kiu.edu.pk
*please do not send password or API keys. this is a public ticketing system. if you do not want to put your email address here, please send the information below to us in an email instead.*

**Where this happened**
e.g. in the UI, API, OAI and which URL you were trying to access.  
*please do not send us your password or API keys*
https://doaj.org/publisher/uploadfile

**When this happened**
What date and time; if it happened several times: a date range or all dates and times it happened. 
On April 2, 2022

**What happened**
- What were you trying to do? 
- I was trying to upload article XML
- What error message was received (do not paraphrase: write the exact message)? 
-Validation message from schema 'crossref': 2:0:ERROR:SCHEMASV:SCHEMAV_CVC_ELT_1: Element '{http://www.crossref.org/schema/4.3.6}doi_batch': No matching global declaration available for the validation root.
- Was the problem repeatable? Did you try several times with the same result? 
- Yes 

**Expected behaviour**
- What did you expect to happen? 

**How to reproduce**

**Screenshots**

**Desktop (please complete the following information):**
Chrome on Windows

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here, such as copies of the XML data you were trying to send.
The time of the file upload: April 2, 2022
Whether the error happened once or repeatedly: Repeatedly
Whether you are uploading DOAJ or Crossref XML:  Crossref XML
Whether you are uploading a file or uploading from a link: File upload
The exact error message as it appears in the “Notes” column, including the detail under the 'show error details' link: Validation message from schema 'crossref': 2:0:ERROR:SCHEMASV:SCHEMAV_CVC_ELT_1: Element '{http://www.crossref.org/schema/4.3.6}doi_batch': No matching global declaration available for the validation root.
A screenshot of the error message
The DOAJ account ID that you are logged in with: 2518850X

**Comment by dommitchell** [comment]
Hello, you are trying to send us Crossref metadata corresponding to schema 4.3.6. DOAJ only accepted Crossref XML with schema 4.4.2

Please see https://doaj.org/docs/xml/#uploading-an-xml-file and then contact Crossref help for how to upgrade to the more recent schema. https://www.crossref.org/documentation/schema-library/
