### ISSUE TITLE
[BUG] Wrong error message

### ISSUE THREAD

**Issue by krminta** [DOAJ/doaj#2126]
Warning: don’t send us your passwords or API keys.

**Contact details of bug reporter (or proxy of bug reporter)** 

**User account you are logged in to when this occurred**
The account’s e-mail address
*please do not send password or API keys. this is a public ticketing system. if you do not want to put your email address here, please send the information below to us in an email instead.*
I can share the email privately.

**Where this happened**
e.g. in the UI, API, OAI and which URL you were trying to access.  
*please do not send us your password or API keys*

It happend in UI, i tried to upload bunch of articles and i got the following error message: "One or more articles did not contain either a DOI or a Fulltext URL"

**When this happened**
What date and time; if it happened several times: a date range or all dates and times it happened. 
Today 21.07.2022 ~9:40, or taking the time from UI `21 Jul 2022 06:41:09 UTC`

**What happened**
- What were you trying to do? 
Upload https://journals.pan.pl/dlibra/doaj-journal/?journal=137721 and https://journals.pan.pl/dlibra/doaj-journal/?journal=136940
- What error message was received (do not paraphrase: write the exact message)?
"One or more articles did not contain either a DOI or a Fulltext URL"
- Was the problem repeatable? Did you try several times with the same result? 
Yeah, i tried at least a few times - each time the same error message.

**Expected behaviour**
- What did you expect to happen? 
Articles should be uploaded.

**How to reproduce**

**Screenshots**
Not needed.

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Firefox]
 - Version [102.0.1]

**Additional context**
Add any other context about the problem here, such as copies of the XML data you were trying to send.
The error message says that "one or more articles did not contain either a DOI or a Fulltext URL", but as i checked xmls given earlier, each and every article contains both DOI and FullTextUrl. Some other articles were already uploaded without any issues, but somehow it fails for this ones.

**Comment by krminta** [comment]
UPDATE!
Turns out that "One or more articles did not contain either a DOI or a Fulltext URL" means that one or more articles did not contain ISSN/eISSN...
If possible, please fix the message :)

**Comment by dommitchell** [comment]
Hello @krminta thanks for submitting this ticket and for the update.

So, is the problem now resolved? You discovered a missing ISSN and that solved the issue?

**Comment by krminta** [comment]
Hello
Yeah, after adding missing ISSN it worked fine.

**Comment by dommitchell** [comment]
OK, thanks! I have reported this to the developers.

**Comment by dommitchell** [comment]
Hello @krminta Thanks for reporting this to us. I am pleased to say that the improvement to messaging is now being tested and will soon be released to the site. I will follow up here once that has been done.
