### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rabendaola** [DOAJ/doaj#2137]
Dear Sir, Or Madam,

My contact details are:

Aleksandra Rabenda-Nowak
login to DOAJ: wwr@edusfera.press
Journal: Wychowanie do Życia w Rodzinie

The account’s e-mail address: wwr@edusfera.press

There is no "bug" itself. I would like to start adding articles to our journal which is listed in DOAJ but it is not visible when I enter into DOAJ- MY DASHBOARD - MY JOURNALS. There is nothing, as if our journal was not assigned to out account in DOAJ. What should I do? How do I know at which point someone before me stopped adding issues to my journal? When I search in general search, I see our authors and their articles in the journal, but the journal is not listed in my account as my journal. The journal name is Family Upbringing or "Wychowanie w Rodzinie" in Polish. Should I just assume there were no articles added and start adding them from the beginning? And then I will see our journal in our dashboard? But it would not make sense, as we already added many articles in the past. Then we stopped for some time, and after recovering our account, there was nothing there. Does it mean our journal was deleted from the data base even though we still have an account? Sorry it is not a bug, but I am just trying to get in touch with you. Thank you.

My browser is Microsoft Edge, the latest version, but I guess it does not matter as it is a general problem.

I will be grateful for your help,

Aleksandra Rabenda-Nowak

**Comment by dommitchell** [comment]
Hello @rabendaola, the journal was removed in 2020 because, at that point, no issues had been published in the journal since 2018. That goes against our inclusion criteria. 

Has the journal started publishing again? Please send me the URL where we can see those articles. Thank you!

**Comment by rabendaola** [comment]
Hello Dom,

thank you for your message. Please note we are still publishing and we have
never stopped, but we just stopped adding articles to the base at some
point. However, we would like to go back to it. Please find the link to all
the volumes:

 http://www.wychowaniewrodzinie.uni.wroc.pl/en/tl-vol-en

How can we go back to the base?

Best
Ola

wt., 16 sie 2022, 09:48 użytkownik Dom Mitchell ***@***.***>
napisał:

**Comment by dommitchell** [comment]
Hello. Because it has been more than two years since the journal was withdrawn from DOAJ, you will need to submit a new application. Please read: our [Guide to applying](https://doaj.org/apply/guide/), particularly the Basic criteria.

You can submit a new application here: https://doaj.org/apply/

Many thanks!
