### ISSUE TITLE
Broken site link

### ISSUE THREAD

**Issue by tbryantwillis** [DOAJ/doaj#2139]
**Where this happened**
On the page https://doaj.org/article/f1c1bd73a33b4f75bbf401fa8155e294 the URL under Abstract to 'Read Online' is broken.  

**When this happened**
This is been the case for several weeks. 

**What happened**

**Page Not Found

Sorry, the page you were looking for was not found.**

**Expected behaviour**
- To be able to read content online 

**How to reproduce**
1. Go to https://doaj.org/article/f1c1bd73a33b4f75bbf401fa8155e294
2. Click on abstract to 'READ ONLINE' link:  http://journal.eahn.org/articles/78
3. See error

**Screenshots**
![Abstract to READ ONLINE](https://user-images.githubusercontent.com/111538632/185498437-b2701342-ecb2-4571-b035-8b7d811301c3.PNG)

![page not found](https://user-images.githubusercontent.com/111538632/185498471-2a8b33f0-5a74-4896-a043-dd0b0c8f0a94.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version 103.0.2

**Additional context**

**Comment by dommitchell** [comment]
Hi @tbryantwillis Thank you so much for alerting us to this problem. It seems as though the link has now been fixed.

We appreciate your contribution to DOAJ!

**Comment by tbryantwillis** [comment]
Thanks!
