### ISSUE TITLE
[BUG] Unable to upload article XML

### ISSUE THREAD

**Issue by dcousin3** [DOAJ/doaj#2165]
**Contact details of bug reporter (or proxy of bug reporter)**  denis cousineau

**User account you are logged in to when this occurred** 19134126
denis.cousineau@uottawa.ca

**Where this happened** https://doaj.org/publisher/uploadfile

**When this happened** 2022/10/27 20:13 EST

**What happened** As usual, I would upload an XML file from the web
https://www.tqmp.org/RegularArticles/vol18-3/doaj_issue.xml (with either http or https) and repeatedly obtained the "The URL could not be accessed [(what does this mean?)](https://doaj.org/publisher/help#explanations)"

The URL exists and contains valid XML as assessed by XML validators.

**Expected behaviour**
to upload 4 articles' xml data

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] win7
 - Browser [e.g. chrome, safari] firefox
 - Version [e.g. 22] 103.0.2

**Comment by dommitchell** [comment]
Hello @dcousin3

Thanks for your bug report. On our test site, I got the file to reference correctly, and the articles imported.

Can I ask you to try again, please?

If it doesn't work, please take a note of the time once again and leave those details here.

Many thanks!

Dom

**Comment by dcousin3** [comment]
I tried again and got the same error message on 28 Oct 2022 11:55:55 UTC.

**Comment by dommitchell** [comment]
OK, thank you. Are you able to send me a screenshot @dcousin3 ?

**Comment by dcousin3** [comment]
Uh? now at 28 Oct 2022 21:43:43 UTC it does work.  Well thanks for your prompt response.

**Comment by dommitchell** [comment]
Great! Thank you!
