### ISSUE TITLE
[BUG] Cannot access article on 'New Routes to Iran’s International Trade in the Safavid Era'.

### ISSUE THREAD

**Issue by siddunbi** [DOAJ/doaj#2203]
Warning: don’t send us your passwords or API keys.

**Contact details of bug reporter (or proxy of bug reporter)** 

**User account you are logged in to when this occurred**
I do not have a DOAJ account registered.

**Where this happened**
http://www.ai-journal.com/articles/124

**When this happened**
January 29, 2023, 21:04:15 UTC

**What happened**
I was/am trying to access the article New Routes to Iran’s International Trade in the Safavid Era.

I got an error when visiting www.ai-journal.com/articles/124.

Error code: 1020
Ray ID: 7914eb5038e527ae
Country: US
Data center: sea06
IP: 2600:6c55:7800:15b:b42c:3062:ffd2:eb7
Timestamp: 2023-01-29 21:04:15 UTC

It happens each time I click the article link.

**Expected behaviour**
I expected to be able to access the article and its contents,

**How to reproduce**
1. Go to 'https://doaj.org/article/0dbed7eb5f6e45db95e8856e7342cd37'
2. Click on 'Read Online' below 'Abstract' on the page.
3. See error.

**Screenshots**

![image_2023-01-29_131543204](https://user-images.githubusercontent.com/123904014/215356035-e811b3d5-9385-425e-8623-d2b7f5f396fe.png)

**Desktop (please complete the following information):**
 - OS: Windows.
 - Browser: Opera GX, Microsoft Edge.
-Version: Windows 10 Home

**Smartphone**
 - Device: iPhone SE (2020)
 - OS: 16.1.1
 - Browser: Safari
 - Version: Unsure.

**Comment by dommitchell** [comment]
Thank you @siddunbi for alerting us to this. We will contact the publisher and ask them to update their URLs in DOAJ. In the meantime, you can read the article via the DOI link https://doi.org/10.5334/aa.124
