### ISSUE TITLE
normalise journal license "type" field

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#23]
Hi @richard-jones 

The licenses on the journals - could we normalise the values in type? Instead of "CC by" or "CC by-nc" and the like, have "cc-by", like the open definition and the OpenArticleGauge ones. The Open Definition is a pretty good yardstick. (For anybody interested, http://licenses.opendefinition.org/ )

If that happens, we can put actual titles in the index - right now license.title == license.type.

**Comment by dommitchell** [comment]
Am thinking of closing this one because, much of this data will be cleaned up as we process and accept reapplications back into DOAJ. I am right, right?

**Comment by emanuil-tolev** [comment]
As long as there are two or more distinct values representing the same licence, I wouldn't close it. You are right that it should get a lot better with controlled vocabs now in use.

**Comment by dommitchell** [comment]
Richard, removing this one from Data Cleanup.

**Comment by dommitchell** [comment]
CLosing this now
