### ISSUE TITLE
Intermittent 500s on OAI resumption tokens

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#235]
Periodically people are hitting 500 errors when using the OAI interface.  Often the links they give us work fine, which suggests a possible environmental/load related issue.  We need to replicate and investigate further.

Propose the construction of an OAI test suite which can put the system through its paces.

**Comment by dommitchell** [comment]
Users experiencing similar issues with this again. Can you check newrelic and let me know?

"We have tried to response the below set.
https://doaj.org/oai.article?verb=ListIdentifiers&metadataPrefix=oai_dc&set=RE9BSjpJbnRlcm5hbCBtZWRpY2luZQ~~

The number of identifiers supposed to be (as listed below) 44264,  but in actual we are getting  only 300 identifiers.  Can you please help us here?

{<resumptionToken completeListSize="44264" cursor="0" expirationDate="2016-08-09T15:41:31Z">
eyJzIjogIlJFOUJTanBKYm5SbGNtNWhiQ0J0WldScFkybHVaUX5-IiwgIm0iOiAib2FpX2RjIiwgIm4iOiAzMDB9
</resumptionToken>}

**Comment by richard-jones** [comment]
300 is the page size, so perhaps there's just some confusion here?

I followed the link, and then used the resumption token, and it paged through a list of 44253 articles, 300 at a time.  Here is the resumption token entry for page 2:

```xml
<resumptionToken completeListSize="44253" cursor="600" expirationDate="2016-08-12T10:26:06Z">
eyJzIjogIlJFOUJTanBKYm5SbGNtNWhiQ0J0WldScFkybHVaUX5-IiwgIm0iOiAib2FpX2RjIiwgIm4iOiA5MDB9
</resumptionToken>
```

**Comment by dommitchell** [comment]
Thanks. Will see what they say.
