### ISSUE TITLE
[BUG]One or more articles failed to ingest; entire batch ingest halted

### ISSUE THREAD

**Issue by meirhebhude** [DOAJ/doaj#2427]
I attempted to upload my article in my indexed journal. I however, get the following error:

One or more articles failed to ingest; entire batch ingest halted [(what does this mean?)](https://doaj.org/publisher/help#explanations)
The following ISSNs in your article metadata do not appear in DOAJ, you cannot associate articles with them. If you believe these ISSNs should be associated with a journal you own, please contact us with the details:
0795-2384

**Comment by dommitchell** [comment]
Hello @meirhebhude thanks for logging this issue. I see that you closed the issue. Is the problem resolved?

**Comment by meirhebhude** [comment]
Not yet.

*Dr Martins E. Irhebhude, MNCS, MCPN, MAITP*
Professor (Associate) of Image Processing and Computer Vision
Asst Dean Postgraduate School,
Nigerian Defence Academy
ORCiD: https://orcid.org/0000-0003-3075-6741
Google Scholar: https://scholar.google.com/citations?user=tfUeKFEAAAAJ&hl=en
Web of Science: https://www.webofscience.com/wos/author/record/AGX-0979-2022
ScopusID: 56289752200

**Comment by dommitchell** [comment]
OK, thanks! Please provide the title and ISSN(s) of your journal so I can investigate further.

You will find the explanation for the error you see here: https://doaj.org/publisher/help

You should check which ISSN we hold for your journal.

**Comment by meirhebhude** [comment]
Academy Journal of Science and Engineering 
ISSN 0795-2384 print
eISSN 2734-3898

**Comment by dommitchell** [comment]
Hi again. We only have one ISSN on record for your journal: https://doaj.org/toc/2734-3898

You can't upload XML that contains ISSNs that we don't have. Either remove 0795-2384 from the XML or, if you believe that the ISSN should be added to our journal,  please email helpdesk@doaj.org and ask them about that. 

Closing.

**Comment by meirhebhude** [comment]
Many thanks
