### ISSUE TITLE
Statistics for the amount of data transferred/requested

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#265]
We used to have reports provided by Analog that showed us the amount of data requested, transferred, etc.

While Google Analytics is good at showing what _users_ do, it isn't so good at showing the sheer volume of traffic on the site.

We'd like to explore the possibility of installing Analog or something equivalent.

**Comment by dommitchell** [comment]
@richard-jones @emanuil-tolev There was already a task for this. I have updated the task description. Adding to tnm fully aware that it might be too big for that. Let me know

**Comment by richard-jones** [comment]
@emanuil-tolev - can you have a think about this and decide how much work it is and on what timescale it might be possible.

**Comment by dommitchell** [comment]
Can do Analog for sizes or do traffic via PHP. Could identify individual crawlers by finding out what the individual IP address is. 

Analog project is dead. Only a community keeping it alive.

Dom to consult Lars and come back.

**Comment by emanuil-tolev** [comment]
> Could identify individual crawlers by finding out what the individual IP address is.

I should note, as Richard did, that this is hardly feasible as crawlers' IPs could change at any moment without notice, and there is no definitive list. If Analog is capable of giving you its usual reports, but only analysing lines which contain known bot user agents (e.g. "Googlebot 2.1, facebookexternalhit", etc.), then that might work. I've not been able to find a plugin or a piece of functionality that allows this however.

We could do a really really bad one by getting a list of bot user agents from somewhere (I have one from a piece of software I run for another project), filtering logs ourselves and running analog only on the filtered logs. You're talking significant complexity though, basically a lightweight piece of software.

**Comment by dommitchell** [comment]
Leaving this for now.
