### ISSUE TITLE
Request to delete articles

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#278]
Please delete all these articles: http://bit.ly/1vJFKBb
Journal:  Vestnik MGSU

and these: http://bit.ly/1sO0YM9
Journal: Stroitel’stvo : Nauka i Obrazovanie

Both account: 23055502

**Comment by dommitchell** [comment]
@richard-jones are these waiting for Reapp release?

**Comment by richard-jones** [comment]
@emanuil-tolev @markmacgillivray - I recall thinking that you guys had run these.  Please could you let me / @dommitchell know the status

**Comment by emanuil-tolev** [comment]
Yes, will do now. It is best IMHO to do them before the reapp release.

**Comment by emanuil-tolev** [comment]
@dommitchell how are the articles now - have they been deleted? Apologies for the delay around this - mainly my fault I think. Should be fine to run such scripts from now on.

**Comment by emanuil-tolev** [comment]
@dommitchell might be a good idea to tag these issues with a new label "delete request" or similar.
