### ISSUE TITLE
Question: Top of the application form

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#279]
How easy would it be for you to give me access, via the templates, to the top header part (under the title) of the application form so that I can change the text there myself?

**Comment by dommitchell** [comment]
Can I repoen this and you give me the new URL? The one above is no longer valid. I want to edit the text at the top of https://doaj.org/application/new

**Comment by richard-jones** [comment]
I think the page you are looking for is this one: 
https://github.com/DOAJ/doaj/blob/master/portality/templates/formcontext/public_application_form.html

As before, be very cautious with this page, and limit edits to above line 16

**Comment by Steven-Eardley** [comment]
@dommitchell or rather, https://github.com/DOAJ/doaj/blob/static_pages/portality/templates/formcontext/public_application_form.html which is on the static pages branch
