### ISSUE TITLE
exploring subjects

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#28]
Some UX enhancement ideas for 2014 which came up during testing something else in the UI. We're not describing breaking problems here (the interface does provide a way to achieve what we want) but it would be good to think about the search UX a bit more with the heavily populated facets.

http://doaj.cottagelabs.com/search?source={%22query%22:{%22query_string%22:{%22query%22:%22*stress*%20*response*%20%22,%22default_operator%22:%22AND%22}}}

Stress response is studied a lot in biology / medicine. But also in psychology, there's just a lot less research on it from that PoV.

However, the biology papers (on this topic) are mostly useless to a psychology researcher / student. So, they might click on Subject and try to filter by Psychology.

As we said above, there's a lot **less** research on this topic in the psychology field, as in, quantity of papers. Thus, the "Psychology" value in the Subjects facet won't be visible since only the top 10 by count are displayed.

OK, we can reveal more values in the filter. Show 20, still dominated by biological sciences classifications (+ all sorts of levels from the subject classification are included, not just highest ones - e.g. "Medicine", "Medicine (General)", pollutes the facet).

Now what?
1. Sort by lowest count - no dice. Psychology may explore this topic lightly, but not as lightly as Archaeology or foreign languages! Still not in facet.
2. Click the sort values button again - sort alphabetically. A-Z is no help.
3. Sort Z-A, display 30 values. Nope...

Now, I was shown that there is actually an easy solution to this that a normal user (not developer, librarian, or other catalogue-loving types) would probably use.

Just type "stress response psychology". It searches all fields, incl. subjects. Subject facet immediately shows variety of relevant values.

Other suggested solutions:
- a mini-dropdown on the subjects facet: "Begins with:" the letters A-Z.
- mini-search, typing in part of subject filters the values in the facet much like the big search filters results. It could take the simple form of a text input field with a search icon on one end, taking the place of the first result in the facet if there are more than 20-30 values in the facet.

**Comment by richard-jones** [comment]
Plan for this is to have a page which lays out the full subject tree in a fairly linear fashion (probably not navigable like on the admin review pages), and which links through to the search results.

**Comment by richard-jones** [comment]
I've now done an implementation of this - go to the test server and you will now see a "Subjects" link in the navigation.

Originally the plan was to put all the subjects on the page in a big list in a similar style to an example we saw on Amazon.  Once I got into the details this turned out to be impractical, because the LCC classification is a relatively deep tree (4 or 5 layers) and the depth of the tree is different in different parts.  This was resulting in a really unbalanced and ugly interface that was also tricky to build!

So, instead I've adopted the mechanism from the admin area of the browsable tree, and made it such that you can drill down through the classification, and select a node you are interested in.  On select it tells you a bit more about that classification (basically, how many records there are), and gives you an option to go over and have a look via the search interface.

**Comment by dommitchell** [comment]
Will have feedback by Friday

**Comment by richard-jones** [comment]
> somewhere in github you commented that links in the subject facet would link out to the subject 
> browser which it doesn't do now. Or am I misremembering?

I don't recall this, no, sorry - it isn't in my plan for this project.  I'm not sure what purpose that functionality would serve, either - the intention of the subject browser is to go from the subject to the content, rather than the other way round.

**Comment by richard-jones** [comment]
> can we make the expand/collapse arrows bigger? They're too small now.

Unfortunately not - they are images that are part of the icon set for the javascript library.

**Comment by richard-jones** [comment]
I've made the text changes for the next UI Tweaks PR

**Comment by dommitchell** [comment]
Looking good. One thing: can you change 'Subjects' in the top nav to say 'Browse subjects'?

**Comment by richard-jones** [comment]
Done for next PR

**Comment by dommitchell** [comment]
Great! Closing.
