### ISSUE TITLE
Question: 146 titles merged into 1

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#280]
One of our publishers has merged 146 titles into 1. Can our system cope with that?

**Comment by dommitchell** [comment]
Notes from the call: might be able to do a script, DM will test. Maybe leave until after continuations go live

**Comment by dommitchell** [comment]
@ClaraDOAJ do you know what happened to the 146 Hindawi journals that merged into 1? I can no longer find them in the Admin.

**Comment by dommitchell** [comment]
Completed manually by Judith. Continuations system worked on this magnitude!

**Comment by ClaraDOAJ** [comment]
Thanks!
