### ISSUE TITLE
Change 'Country of publication' to 'Country of publisher'

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#286]
As per issue https://github.com/DOAJ/doaj/issues/233, label for 'Country of Publication' needs to be changed to 'Country of publisher' in search view and the facet.

**Comment by Steven-Eardley** [comment]
@dommitchell you can see this on test just now. We'll be rolling out the issues in the PVOD priority milestone as a set once they're all closed.

**Comment by dommitchell** [comment]
Yup, all good.
