### ISSUE TITLE
Explain why ISSNs have been removed from some journals

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#290]
Some journals are referenced by articles with an ISSN that they do not have in their own record.  They appear to have had this data in the past, so we need to check to see why they don't have it any more.

Example in staging right now is ISSN 1176-4120 / Journal of Applied Computing and Information Technology.  It only knows ISSN 2230-4398

**Comment by richard-jones** [comment]
I believe we've already removed orphaned articles, but we need to check on the status of that.

If we haven't, what action is required?  The only thing I could think to do would be to gather the issns of articles that are orphaned, so that DOAJ admins can check what action should be taken.

Given the age of this issue, I suspect it is superseded.

**Comment by dommitchell** [comment]
> The only thing I could think to do would be to gather the issns of articles that are orphaned, so that DOAJ admins can check what action should be taken.

I agree. This sounds sensible. Hopefully, this is superseded.

**Comment by dommitchell** [comment]
Every time the articvler synchroniser runs it would throw out an orphan . No longer relevant
