### ISSUE TITLE
Delete all articles from Statistica

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#292]
Please delete all articles, volumes 59 to 73, from Statistica:

https://doaj.org/toc/01eaee154d4b47f79abf421b0cd3eb20

https://doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%22Statistica%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22_type%22:%22article%22}},{%22term%22:{%22bibjson.journal.title.exact%22:%22Statistica%22}}]}}}}}

**Comment by dommitchell** [comment]
@richard-jones are these waiting for Reapp release?

**Comment by richard-jones** [comment]
@emanuil-tolev @markmacgillivray - I recall thinking that you guys had run these. Please could you let me / @dommitchell know the status

**Comment by emanuil-tolev** [comment]
423 deleted!
