### ISSUE TITLE
JournalInfo script to only take action if necessary

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#296]
So, when syncing journal info to articles, only update the article if the journal info changes.

Also, would be useful to check for articles whose parent journals can no longer be found, and warn about them.

**Comment by richard-jones** [comment]
@Steven-Eardley - a related issue to your journal info update script.  I don't think there's anything new here, except the email to the feedback address.  I'm not sure we actually want to do that for every article - perhaps the script can produce a digest of orphaned articles, and log them or mail them somewhere at the end?

**Comment by Steven-Eardley** [comment]
Issue superseded by #941, and the script checks orphaned articles, deletes them, and logs their IDs to file.
