### ISSUE TITLE
Legacy Data Archive Scripts: Applications

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#306]
The following scripts are required to handle legacy applications:

1. Reject all applications with created_date prior to 19 March 2014.  The script will change the status to “rejected” for each of these applications, and add a comment into the notes field indicating why this has happened.

2. Delete all rejected applications.  The second part to (1) and can be run at a later date.  This will delete all applications with status “rejected”.  No record will be kept of those applications by CL.

These should be written and run as early in the project as possible.

Although we won't keep a record of deleted applications, we should archive them off to file, and hand them over to the DOAJ for retention or disposal at their discretion.

*In advance of doing this, check that the date of 19th March 2014 is absolutely the cut off for when applications started using the new data model.*

**Comment by dommitchell** [comment]
Something strange has happened. The number of rejected applications has gone down to 1 and yet:

> Delete all rejected applications. The second part to (1) and can be run at a later date. This will delete all applications with status “rejected”. No record will be kept of those applications by CL.

I should have spotted this in testing but the very absence of rejections in the facet meant I didn't notice that the rejected facet was missing (which means there were none, right?)

**Comment by emanuil-tolev** [comment]
@dommitchell they were all gone when we did it. This one was maybe rejected just now? What does its record say :)?

Also yes, if there are no rejected apps the facet value will disappear. Maybe something to consider upgrading (getting the ability to have 0-val choices in facet) in the public view of data that's coming up.

**Comment by dommitchell** [comment]
> they were all gone when we did it.

Sure but my point is, I didn't think you were removing them until later:

> Delete all rejected applications. The second part to (1) and can be run at a later date.

**Comment by emanuil-tolev** [comment]
Yep, except that it was then agreed to remove them now. I can't quite recall the issue /cc @richard-jones ?

We've got an archive of them, so what we can do:
1. restore them if you need them
2. don't restore them and wait to see if you do have a need for them :)

**Comment by dommitchell** [comment]
DM to speak to team today.

**Comment by dommitchell** [comment]
Based on #546 I wonder if it possible to reinstate all applications back to March 2014 so that we have all of the most recent ones? I think there is too much discussion around some records for them to simply be wiped *unless* we can find some way of DOAJ accessing them in a JSON reader offline. In that case, we could have them our selves somewhere. Thoughts?

**Comment by emanuil-tolev** [comment]
A JSON reader wouldn't let you search very easily I don't think. Imagine reading 22 MB of XML. There are XML editors, but which of them will let you search and fetch just the record you need easily, not to mention ease of reading it (better with JSON, but still). So yes, can restore all apps with created_date after 01 March 2014.

**Comment by dommitchell** [comment]
@emanuil-tolev Can we do this? All applications with created date after 14 March 2014.

**Comment by emanuil-tolev** [comment]
Ah, yes, the final decision was to restore. I'll see if I can do today (otherwise probably just Monday at worst) so either way you'll get the reference materials soon :). And thanks for clarifying the condition.

**Comment by emanuil-tolev** [comment]
> @emanuil-tolev Can we do this? Restore all application data with created date after 14 March 2014.

Hi @dommitchell all difficulties have been resolved and rejected applications restored.

**Comment by dommitchell** [comment]
@emanuil-tolev Hi! We seem to have restored all applications from 2004 onwards rather than applications with a created date after March 2014.

**Comment by emanuil-tolev** [comment]
@dommitchell ah .. hm. The archive must have been all the rejected ones rather than throwing away only some of them. Can you find the data you need like this?

**Comment by dommitchell** [comment]
Yep
