### ISSUE TITLE
Sharing button on records

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#31]
Hi @dommitchell 

The sharing service the old site is using it telling me it wants an account to give me embeddable code.
https://www.addthis.com/get/sharing

I can get that code off the old site, but there doesn't seem to be anything DOAJ-specific in it (like account number with addThis or something).

Does DOAJ have an account with addThis to track sharing analytics?

Do you want me to add the button to journals too? It'd probably be used less, of course, but so what, if people want to share a journal they've found e.g with no APC then why not...

**Comment by dommitchell** [comment]
This seems to have disappeared from all records?

**Comment by dommitchell** [comment]
@richard-jones has this dropped off?

**Comment by richard-jones** [comment]
Hm, from the public interface?  It certainly doesn't appear to be there -
maybe that got dropped unintentionally during the PVOD project?  Or has it
vanished more recently?

**Comment by dommitchell** [comment]
I think it might have been dropped unintentionally but I only just noticed. Not entirely sure though.

**Comment by dommitchell** [comment]
I'd like an update on this one please.

**Comment by dommitchell** [comment]
I would still like to know what happened to this. BUt perhaps best revisited after the UI upgrade.
