### ISSUE TITLE
Email Lists for notifying start of re-application

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#314]
The following lists of emails will need to be generated, and we will have custom command line scripts for each one:

1. All contacts associated with applications which are moved into rejected status at the start of the process (see #306 ).
2. All publishers for whom 10 or fewer re-applications have been generated (i.e. for each journal for which we create a re-application, obtain the contact email of the owner, then de-duplicate at the end)
3. All publishers for whom 11 or more re-applications have been generated. (see #316 )

Note that each publisher may have custom information, in which case we will provide a spreadsheet of the email address, publisher name, and any custom information (such as URLs) to be included in a template email sent out by the DOAJ.

**Comment by dommitchell** [comment]
> All publishers for whom 10 or fewer re-applications have been generated (i.e. for each journal for which we create a re-application, obtain the contact email of the owner, then de-duplicate at the end)

Can you re-run this for me after #593 has been done?

**Comment by dommitchell** [comment]
I don't think I ever got these lists from the live db? I have an email from @emanuil-tolev on 24-Nov with lists from staging but nothing from live.

I need list 2 only. Can you run it and send it to me?

**Comment by dommitchell** [comment]
Can you tell me the exact date that these were generated?
