### ISSUE TITLE
Generate spreadsheet from list of re-applications

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#316]
To generate the speadsheet for use by the publisher we will want to crosswalk each re-application (after it has been generated by the initialisation routines) into a set of key/value pairs, where they keys are the questions (perhaps proxied by the question numbers) and the values are the current answers, or the empty string if not present.

Each set of key/value pairs will then form one column in the resulting output spreadsheet.  This will use a custom FormContext (see Application Form Refactoring), which is presented in more detail in Processing the Spreadsheet.

To provide an easy-to-use ordering for publishers, the columns should be assembled with the lowest ISSN first (using natural ordering), and ascending from there.  

See Optimised CSV Parsing for options around how we make this process scalable.

**Comment by dommitchell** [comment]
Closing for now
