### ISSUE TITLE
Access non-editable journal form from admin area

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#321]
In both admin and editor areas, Applications which have a link in their data to an existing journal record will display an “Open Journal Record” link on all relevant Applications tabs, which will open a full page detailing that journal’s metadata.  

See #313 for implementation of the form itself.

**Comment by dommitchell** [comment]
Please change the link so that it takes the Admin user to the live journal record and not the archived application.

**Comment by dommitchell** [comment]
Closing for now
