### ISSUE TITLE
Legacy Data Archive Scripts: Journals

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#323]
1. Automatically withdraw all items with incomplete re-applications.  This will be run only at some date to be specified by the DOAJ team.  All journals in the DOAJ which have an active re-application (which will be linked to by the journal record admin.current_application) and which do not have a re-application date in their metadata (last_reapplication) will be marked as in_doaj=False, along with all of their associated articles.  See #307 for data model details.
2. Archive all withdrawn journals and their associated articles (and those article’s histories).  For every journal with in_doaj=False, they should be copied, along with their article metadata, into a static (offline) archive and deleted without record from the DOAJ index.  The output of this script should be zipped up and delivered to the DOAJ to retain for as long as is necessary.

**Comment by Steven-Eardley** [comment]
@richard-jones Regarding part 2: 
* Are we deleting all journals with ```in_doaj = false```, or just the ones flipped in the first part?
* Similarly, to catch their articles, is it all with ```in_doaj = false``` or those found explicitly with ```journal.all_articles()```?

**Comment by richard-jones** [comment]
@Steven-Eardley.  After the first stage, the second stage is like this:

* for each journal in_doaj=False get all their articles and remove them
* for each journal in_doaj=False, remove the article

Is that what you were expecting?

**Comment by Steven-Eardley** [comment]
> for each journal in_doaj=False, remove the article

Yes, what I've expected (assuming you meant journal for that second 'article') - my quandary was that it could scoop up more than reapplication-specific stuff. By design, I hope.

**Comment by richard-jones** [comment]
yes, sorry - I'll correct the text.

It will - by design - remove any old journals and any old articles from the system that are no longer published, irrespective of whether they went through the reapplication process or not.

**Comment by richard-jones** [comment]
RJ to review during next testing cycle

**Comment by dommitchell** [comment]
@richard-jones Can this one be closed?

**Comment by emanuil-tolev** [comment]
This relates to the reapplication shutdown @dommitchell , which hasn't come about yet :)

**Comment by richard-jones** [comment]
reapplication has been shut down so this can be closed
