### ISSUE TITLE
Request to delete articles

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#334]
To be done asap after current dev project, or when time allows.

Journal: Acta Polytechnica
ISSNs: 1210-2709, 1805-2363
The URL of the journal in DOAJ: https://doaj.org/toc/4df438da4f314e3499e75257a765f2b0
The range of content to be deleted: Vol. 40, Issue 1 (2000) - Vol. 53, Issue 4 (2013)

2000: https://doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%221210-2709,%201805-2363%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22_type%22:%22article%22}},{%22term%22:{%22bibjson.year.exact%22:%222000%22}}]}}}}}

2001: https://doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%221210-2709,%201805-2363%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22_type%22:%22article%22}},{%22term%22:{%22bibjson.year.exact%22:%222001%22}}]}}}}}

2002: https://doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%221210-2709,%201805-2363%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22_type%22:%22article%22}},{%22term%22:{%22bibjson.year.exact%22:%222002%22}}]}}}}}

2003: https://doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%221210-2709,%201805-2363%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22_type%22:%22article%22}},{%22term%22:{%22bibjson.year.exact%22:%222003%22}}]}}}}}

2004: https://doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%221210-2709,%201805-2363%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22_type%22:%22article%22}},{%22term%22:{%22bibjson.year.exact%22:%222004%22}}]}}}}}

2005: https://doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%221210-2709,%201805-2363%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22_type%22:%22article%22}},{%22term%22:{%22bibjson.year.exact%22:%222005%22}}]}}}}}

2006: https://doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%221210-2709,%201805-2363%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22_type%22:%22article%22}},{%22term%22:{%22bibjson.year.exact%22:%222006%22}}]}}}}}

2007: https://doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%221210-2709,%201805-2363%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22_type%22:%22article%22}},{%22term%22:{%22bibjson.year.exact%22:%222007%22}}]}}}}}

2008: https://doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%221210-2709,%201805-2363%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22_type%22:%22article%22}},{%22term%22:{%22bibjson.year.exact%22:%222008%22}}]}}}}}

2009: https://doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%221210-2709,%201805-2363%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22_type%22:%22article%22}},{%22term%22:{%22bibjson.year.exact%22:%222009%22}}]}}}}}

2010: https://doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%221210-2709,%201805-2363%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22_type%22:%22article%22}},{%22term%22:{%22bibjson.year.exact%22:%222010%22}}]}}}}}

2011: https://doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%221210-2709,%201805-2363%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22_type%22:%22article%22}},{%22term%22:{%22bibjson.year.exact%22:%222011%22}}]}}}}}

2012: https://doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%221210-2709,%201805-2363%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22_type%22:%22article%22}},{%22term%22:{%22bibjson.year.exact%22:%222012%22}}]}}}}}

2012: https://doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%221210-2709,%201805-2363%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22_type%22:%22article%22}},{%22term%22:{%22bibjson.year.exact%22:%222013%22}}]}}}}}

**Comment by dommitchell** [comment]
@richard-jones are these waiting for Reapp release?

**Comment by richard-jones** [comment]
@emanuil-tolev @markmacgillivray - I recall thinking that you guys had run these. Please could you let me / @dommitchell know the status

**Comment by emanuil-tolev** [comment]
@dommitchell These have been run on live. All ok?
