### ISSUE TITLE
DELETE REQUEST for early FEB: delete ALL articles: account 18906729

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#353]
[Account: 18906729 - delete all articles.] As per #334 to be done after current dev project or when time allows. Can you give me a couple of days' forewarning?

Title: Borealis : An International Journal of Hispanic Linguistics
http://doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%221893-3211%22,%22default_field%22:%22index.issn.exact%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:%5B{%22term%22:{%22_type%22:%22article%22}}%5D}}}}}

Title: Nordlit : Tidsskrift i litteratur og kultur
http://doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%221503-2086%22,%22default_field%22:%22index.issn.exact%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:%5B{%22term%22:{%22_type%22:%22article%22}}%5D}}}}}

Title: Rangifer
http://doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%221890-6729%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22_type%22:%22article%22}}]}}}}}

Title: Nordisk Tidsskrift for Helseforskning
http://doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%221504-3614%22,%22default_field%22:%22index.issn.exact%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:%5B{%22term%22:{%22_type%22:%22article%22}}%5D}}}}}

Title: Nordlyd : Tromsø University Working Papers on Language & Linguistics / Institutt for Språk og Litteratur, Universitetet i Tromsø
http://doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%221503-8599%22,%22default_field%22:%22index.issn.exact%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:%5B{%22term%22:{%22_type%22:%22article%22}}%5D}}}}}

Title: Poljarnyj Vestnik
http://doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%221500-7502%22,%22default_field%22:%22index.issn.exact%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:%5B{%22term%22:{%22_type%22:%22article%22}}%5D}}}}}

Title: NAMMCO Scientific Publications
http://doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%221560-2206%22,%22default_field%22:%22index.issn.exact%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:%5B{%22term%22:{%22_type%22:%22article%22}}%5D}}}}}

**Comment by dommitchell** [comment]
This has now been requested for any day in early Feb. If I remind you nearer the time @emanuil-tolev is that something you can do for me then?

**Comment by emanuil-tolev** [comment]
Hm - yes, definitely, and feel free to remind me. Maybe bring it up in a meeting at some point then? I'll also put it on my todo list anyway for early feb.

**Comment by dommitchell** [comment]
@emanuil-tolev Hi this is your reminder! Publisher is happy to go ahead.

**Comment by emanuil-tolev** [comment]
OK, just to confirm - delete all articles belonging to the journals listed above. Initially you've said "belonging to account X" so might be worth double checking the account hasn't acquired any new journals in the meantime that we would also have to remove the article data for.

**Comment by dommitchell** [comment]
Yes, all articles for this account. @richard-jones has asked me to provide those search syntaxes for these types of requests but yes, all articles works too.

**Comment by emanuil-tolev** [comment]
Yes, the search URLs are important, that's all fine. I was just asking you if the list is still exhaustive since I can see the issue is a few months old - are there any more articles from this account you'd like deleted or are the search URLs above showing all the relevant articles?

**Comment by dommitchell** [comment]
Ah! I understand now. Yes, all good to go! The URLs are relevant.

**Comment by dommitchell** [comment]
@emanuil-tolev hi, can this be done today?

**Comment by emanuil-tolev** [comment]
sorry, didn't see this email - yes, will do asap

**Comment by dommitchell** [comment]
OK, thanks. Today would be great. The publisher was asking.

**Comment by emanuil-tolev** [comment]
Done now.

**Comment by emanuil-tolev** [comment]
> Title: Rangifer
> http://doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%221890-6729%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22_type%22:%22article%22}}]}}}}}

Added ISSN field to this one so we don't delete sth. else by accident.
