### ISSUE TITLE
DOAJ Data

### ISSUE THREAD

**Issue by kunjan21** [DOAJ/doaj#358]
Hi,
I m trying to make a federated search engine of all journals and articles. Since you have already helped many people in doing this then its no use of reinventing the wheel once again. Kindly help me taking out data from DOAj or any other website which has Article Level Metadata. I already have Journals List in csv format. Please help. Thanx in Advance.
regards,
Kunjan

**Comment by richard-jones** [comment]
Old, we responded, no further action required
