### ISSUE TITLE
OAI PMH very slow queries on live

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#374]
Override ELASTIC_SEARCH_HOST to be http://95.85.59.151:9200 and let me know so I can give you access. Then you can use the interpreter (make sure your code is on master!) but you will be touching the live data.

Note: @richard-jones did write an OAI PMH stress test. Not immediately useful but could be useful for investigating.

**Comment by richard-jones** [comment]
@emanuil-tolev - do we know if this is still an issue?  I have not encountered it when testing on live with the stress and coverage tests we wrote.

**Comment by emanuil-tolev** [comment]
In the last 24h it has taken the OAI-PMH endpoint 7 seconds on average to answer a request. Most of the time is spent handling exceptions.

If you'd like to view the data, https://rpm.newrelic.com/accounts/526071/applications/3171791/transactions?type=app#id=536843665 , I'll send you credentials. Otherwise let's put it in the pad and we can discuss during a technical meeting, I'll show you the Newrelic perf data.

**Comment by richard-jones** [comment]
oh wow, ok yes lets take a look

On 6 January 2015 at 18:04, Emanuil Tolev <notifications@github.com> wrote:

> In the last 24h it has taken the OAI-PMH endpoint 7 seconds on average to
> answer a request. Most of the time is spent handling exceptions.
>
> If you'd like to view the data,
> https://rpm.newrelic.com/accounts/526071/applications/3171791/transactions?type=app#id=536843665
> , I'll send you credentials. Otherwise let's put it in the pad and we can
> discuss during a technical meeting, I'll show you the Newrelic perf data.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DOAJ/doaj/issues/374#issuecomment-68904828>.
>



-- 

Richard Jones,

Founder, Cottage Labs
t: @richard_d_jones, @cottagelabs
w: http://cottagelabs.com

**Comment by richard-jones** [comment]
Ok, I've been taking a quick prod at this, and I don't think it's such a bad issue.

Actual legitimate requests to the OAI PMH endpoint seem to work fine, it's just if you give it a resumption token which is invalid in some way - this is what's causing the handle_error function in Flask to get hit.

Seems to be that we get a lot of such requests.

I just hit http://doaj.org/oai.article?verb=ListRecords&resumptionToken= and I got a 502, which would suggest that the process timed out.  Not sure why handling this particular error takes so long, though.  I can add a catch which looks for these dud resumption tokens and bounces with a BadRequest straight away, perhaps?

We should also wonder to ourselves why we get such a lot of these requests - perhaps there's something in the legitimate XML we produce which is prompting automated harvesting of such urls.

**Comment by emanuil-tolev** [comment]
> I just hit http://doaj.org/oai.article?verb=ListRecords&resumptionToken= and I got a 502, which would suggest that the process timed out. Not sure why handling this particular error takes so long, though. I can add a catch which looks for these dud resumption tokens and bounces with a BadRequest straight away, perhaps?

That sounds very reasonable. Is there any more info beyond what's available in Newrelic that we could capture that would help investigate this? Like HTTP referral info or similar..

> We should also wonder to ourselves why we get such a lot of these requests - perhaps there's something in the legitimate XML we produce which is prompting automated harvesting of such urls.

Yeah, that'd be a bad problem. How do we check this though? We already have a script which goes through the whole thing, and it doesn't catch anything. We could record all resumption tokens that we generate and then try them. This is non-trivial as I'm not sure we want this in ES and you can't e.g. just write to the same file, there's too many web server threads, but it could be achieved, e.g. by writing to files with randomised names - then easily ```cat```-ed together. Or perhaps using time-bounded logging, only log for e.g. next week - putting a week of tokens in ES won't be so bad.

**Comment by emanuil-tolev** [comment]
In terms of impact - I agree that if all of DOAJ's data is automatically harvestable (we don't generate invalid tokens) then this doesn't impact the correctness of the app. It does take up a web worker for those 7 seconds though, and we only have 9 workers. We do get 10-15'000 hits a day, so it is a bit of a concern for user experience - if a lot of errors occur at once, DOAJ may not be "down" but may be quite a bit slower.

**Comment by richard-jones** [comment]
Capturing the HTTP referrer probably wouldn't help - my guess is there's an
OAI library out there with a bug in it that's making these requests, rather
than a well behaved web browser.  So, perhaps user agent might give us a
clue?

I've taken a look at our output XML and it is completely valid, as far as I
can tell we never output an empty resumptionToken (thought more testing
around this is one thing I'll do).  If we can find someone who is making
these requests, we might be able to ask them why.

Good point regarding the amount of time wasted by the workers dealing with
this - either way I'll look at putting in a stop for an empty resumption
token earlier in the processing chain, which should speed up the failures
at least.


On 7 January 2015 at 09:59, Emanuil Tolev <notifications@github.com> wrote:

> In terms of impact - I agree that if all of DOAJ's data is automatically
> harvestable (we don't generate invalid tokens) then this doesn't impact the
> correctness of the app. It does take up a web worker for those 7 seconds
> though, and we only have 9 workers. We do get 10-15'000 hits a day, so it
> is a bit of a concern for user experience - if a lot of errors occur at
> once, DOAJ may not be "down" but may be quite a bit slower.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DOAJ/doaj/issues/374#issuecomment-69000776>.
>



-- 

Richard Jones,

Founder, Cottage Labs
t: @richard_d_jones, @cottagelabs
w: http://cottagelabs.com

**Comment by richard-jones** [comment]
One thing to add, is that I can't replicate this in my dev environment.  An empty resumptionToken results in an immediate BadRequest response.

**Comment by richard-jones** [comment]
Scratch that above comment - I can generate a server error fine when I'm paying attention :)

**Comment by richard-jones** [comment]
I've submitted a PR for this which covers the specific error that we're encountering.

I'd still be interested to know why we get so many of those requests, but I suspect that it is not something we're doing.  Who else uses OAI-PMH extensively?  Maybe we could ask the folks at arxiv.org if they see a lot of these?

**Comment by emanuil-tolev** [comment]
> If we can find someone who is making
> these requests, we might be able to ask them why.

Aha! I'll pick up some URLs from Newrelic and have a grep through the logs to see some IPs. IPs wouldn't tell us who's doing it, but we can at least see if it's mostly from one source or not. We can track a few of the worst sources to see if they map to organisations we can talk to.

**Comment by richard-jones** [comment]
I've been in contact with Simeon at Arxiv and he's had a look at their logs and doesn't see anything similar to what we're experiencing, so some further investigation is definitely required at our end.

In the mean time, though, he has identified a minor spec-compliance issue with our date granularity, and I'll open an issue to deal with that shortly.

**Comment by emanuil-tolev** [comment]
An example of the error (should be available for 24h): https://rpm.newrelic.com/accounts/526071/applications/3171791/traced_errors/2656689662

```
Error message
exceptions:SystemExit: 1

Request attributes
URL	/oai.article
resumptionToken	""
verb	"ListRecords"

Request environment
HTTP_USER_AGENT	Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)
REQUEST_METHOD	GET
Transaction metrics
Thread/Concurrency	1.0000
WSGI/Output/Time	30.0018
```

The worker timed out after 30 seconds of trying to respond to a request to /oai.article with verb=ListRecords.


Another error, again with a long timeout:

```
exceptions:ValueError: No JSON object could be decoded

Request attributes
URL	/oai.article
resumptionToken	""
verb	"ListRecords"

Request environment
HTTP_USER_AGENT	Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)
REQUEST_METHOD	GET
Transaction metrics
Thread/Concurrency	1.0000
WSGI/Output/Time	30.0199


Traceback (most recent call last):
File "/opt/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request rv = self.dispatch_request()
File "/opt/doaj/local/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args)
File "/opt/doaj/local/lib/python2.7/site-packages/newrelic-2.40.0.34/newrelic/hooks/framework_flask.py", line 40, in _nr_wrapper_handler_ return wrapped(*args, **kwargs)
File "/opt/doaj/src/doaj/portality/view/oaipmh.py", line 57, in oaipmh result = list_records(dao, request.base_url, **params)
File "/opt/doaj/src/doaj/portality/view/oaipmh.py", line 349, in list_records return _resume_list_records(dao, base_url, resumption_token=resumption_token)
File "/opt/doaj/src/doaj/portality/view/oaipmh.py", line 416, in _resume_list_records params = decode_resumption_token(resumption_token)
File "/opt/doaj/src/doaj/portality/view/oaipmh.py", line 101, in decode_resumption_token d = json.loads(j)
File "/usr/lib/python2.7/json/__init__.py", line 338, in loads return _default_decoder.decode(s)
File "/usr/lib/python2.7/json/decoder.py", line 366, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

No idea why it took it so long to decide "" is not valid JSON. This could even be an unrelated problem with the app or environment - but then again it only seems to affect OAI-PMH.


There's been 47 of each of these two errors in the last 35 minutes as I'm writing this (13:02). In the last 24 hours there have been ~2200 of each error.

I will try to find out who the client(s) making these requests is/are.

**Comment by emanuil-tolev** [comment]
In the last 10000 lines of access logging (measurement taken at 8 Jan 2015 19:50 GMT) there were quite a few hits with an empty resumptionToken.

I tried it on live, it does time out after 30s with Bad Gateway error (because gunicorn reaps its worker).

This is clearly an automated process, it hits every ~30 seconds. All attempts that I could see came from this IP http://who.is/whois-ip/ip-address/124.16.136.238 , registered to a Chinese scientific organisation.

**Comment by emanuil-tolev** [comment]
@richard-jones They have the real email address to contact? So no need to block yet I think..

```
remarks:        Please contact lihong@cstnet.cn if you have any
remarks:        questions regarding this object.
remarks:        Antispam mail please send to antispam@cstnet.cn.
```

**Comment by richard-jones** [comment]
ok, sure, if you're happy that it's not degrading the service.  But they
won't be getting any useful info out of these requests, so blocking it
might be worthwhile anyway.  Will leave it to you to decide.

On 9 January 2015 at 12:41, Emanuil Tolev <notifications@github.com> wrote:

> @richard-jones <https://github.com/richard-jones> They have the real
> email address to contact? So no need to block yet I think..
>
> remarks:        Please contact lihong@cstnet.cn if you have any
> remarks:        questions regarding this object.
> remarks:        Antispam mail please send to antispam@cstnet.cn.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DOAJ/doaj/issues/374#issuecomment-69329444>.
>



-- 

Richard Jones,

Founder, Cottage Labs
t: @richard_d_jones, @cottagelabs
w: http://cottagelabs.com

**Comment by emanuil-tolev** [comment]
OK we'll block the IP for now, they're not getting any data from us anyway

**Comment by emanuil-tolev** [comment]
Note for myself: I can't seem to block this ip with ```ufw```, need to see why it's still coming through, even though the order of the firewall rules is correct.

**Comment by emanuil-tolev** [comment]
Don't ban them for now, we'll have a fix rolled out next Monday.
