### ISSUE TITLE
Usability of Notes in the Application Form

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#385]
Improving the usability of Notes in the Application form:
- the Notes field is at the bottom, adding many Notes causes excessive scrolling and is confusing for the user. Can we find a way to alleviate this?
- is there a way to make all Notes' fields searchable in Admin? Not searching from within a record but the ability to search across all records.
- [x] a Man Ed should be able to delete duplicate Notes
- [ ] change the order so that the most recent Note is always at the top.
- [x] get rid of the duplication 'feature'

**Comment by dommitchell** [comment]
Adding to tnm. Note it is only the 3 with the checkbox that need to be attended to.

**Comment by richard-jones** [comment]
Ok, so just to be clear, the only thing that's outstanding is ensuring that notes are presented in the correct chronological order, most recent note first?

I've just done a refresher in my mind for how this all works, and it looks like admins can now delete notes, and I'm not sure what the "duplication feature" is, but it's ticked so I guess is good?

**Comment by richard-jones** [comment]
For my own purposes, this is what we need to do:

1. Change the UI so that "Add new Note" creates the note edit box at the top of the list
2. Change the form-context so that it checks the timestamp of each note, and ensures that it is added/transferred to the object in the correct order

**Comment by dommitchell** [comment]
> Ok, so just to be clear, the only thing that's outstanding is ensuring that notes are presented in the correct chronological order, most recent note first?

Correct! Please go ahead!
