### ISSUE TITLE
Application form - should not be possible to unlock a record without saving changes

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#386]
Is it possible to make changes to the form and then Unlock it, WITHOUT saving changes?

It would be good if clicking Unlock, automatically saved changes as well.

**Comment by richard-jones** [comment]
@dommitchell - If you want to articulate the requirements in a separate issue, or update this one, that would be fine.

So, people are clicking "Unlock and Close" when they mean "Save"?

We maybe even want 3 buttons:

"Save", "Save and Close", "Close without Saving"

Perhaps mentioning locking is confusing people in the first place?

We can implement whatever is needed, but a bit of UX-experienced input to give us the right answer would be good.

**Comment by emanuil-tolev** [comment]
> "Save", "Save and Close", "Close without Saving"

I like this a lot, the only problem being it doesn't tell the user they need to unlock the record, as you say. They might even just close the tab, not realising that won't release it. Which might be fine given the number of editors we have and the way they've taken on a specific slice of the journals (indeed only being able to edit a journal after specific assignment).

**Comment by dommitchell** [comment]
Still just thinking aloud here. How about just a prompt? Keep the UI exactly as it is but if someone clicks Unlock and Close without saving changes, they get a prompt that says: 'There are unsaved changes on this page. Continuing will close this record without saving your changes. Do you wish to continue?'

**Comment by dommitchell** [comment]
CLosing and moving to #137
