### ISSUE TITLE
Application form: textual changes

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#416]
- [x] Question 5. Change help text to 'Cannot be the same as the P-ISSN. Write the EISSN with the hyphen "-" e.g. 1234-4321.'
- [x] Add one extra word to Question 30:  'Does the journal provide *article* download statistics?'
- [x] Change the help text under Question 30 to 'If "No" proceed to question 32'
- [x] Add help text to Qu 34:  'Maximum 6. Keywords must be in English.'
- [x] Change the help text under Qu 41 to 'If "No" proceed to question 43'
- [x] Change the help text under Qu 45 to 'If "No" proceed to question 47'

**Comment by dommitchell** [comment]
@emanuil-tolev  Can we work these into a future round of updates? (I'm not suggesting today's!)

**Comment by emanuil-tolev** [comment]
Changing the description just on the web form is ok. Changing the question text though .. is this only on the web form, or should the question change in the csv too?

**Comment by dommitchell** [comment]
This is only changes to the help text, NOT the questions themselves.

**Comment by emanuil-tolev** [comment]
Ah yeah, sure. Is this kind of a hotfix thing that gets published asap like the static pages, or in any particular upcoming project? Or is that what you're asking :)? Yeah, happy to change q descriptions if this issue is not attached to a project. I'll put it on my todo and probably good to add to next meeting's agenda.

**Comment by dommitchell** [comment]
Yup, this isn't attached to any project. Thanks!

**Comment by dommitchell** [comment]
@emanuil-tolev If I had a priority, can you make this change asap? ;)

Add one extra word to Question 30: 'Does the journal provide article download statistics?'

**Comment by emanuil-tolev** [comment]
OK, pull request in for the changes above. Only really minor text changes so done.

**Comment by emanuil-tolev** [comment]
Will switch to ready for review once the PR is reviewed and I've rolled out the changes.

**Comment by richard-jones** [comment]
Actually, if we're making text changes to the application form, there's
another issue that we should do at the same time #529

Haven't had a chance to look at it yet, though

**Comment by emanuil-tolev** [comment]
It's just deleting 2 descriptions, done.

**Comment by dommitchell** [comment]
Should I review this anywhere?

**Comment by emanuil-tolev** [comment]
should be ready for review on live!

**Comment by dommitchell** [comment]
Looking good.
