### ISSUE TITLE
Terminology / UI: publishers & admin

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#428]
- [x] Change the terminology for 'Application Status' facet and the labels under it in the Publisher's view:

Application Status --> Status
reapplication --> pending
submitted stays as is

- [x] Change 'Updates in progress' to 'Reapplications'

- [x] Similarly, change 'Reapply' to 'CSV'.

- [x] Text in the blue sticky note will need to change to 'Since you have 10 or more journals associated with this account, we have created a [CSV file for you to download].' Hyperlink [ ]to the CSV tab.

![application](https://cloud.githubusercontent.com/assets/5955396/5168442/68804cf8-73ff-11e4-8fce-1f5505706a9f.jpg)

**Comment by emanuil-tolev** [comment]
For @richard-jones : Example of translating values in facetview 1: portality/static/doaj/js/facetview_results_render_callbacks.js file has a fv_author_pays function on line 3. Line 29 defines a mapping that the function uses (as an attribute of the function object itself, for elegance I presume):

```javascript
fv_author_pays.mapping = {
    "Y": {"text": "Has charges", "class": "red"},
    "N": {"text": "No charges", "class": "green"},
    "CON": {"text": "Conditional charges", "class": "blue"},
    "NY": {"text": "No info available", "class": ""},
}
```

**Comment by emanuil-tolev** [comment]
Then pass the function to fv as usual: as a render callback using a special field name, and add that field to the field definitions at the bottom of the facetview js file.

**Comment by emanuil-tolev** [comment]
Ah ... and if you need to translate **facet** values, not result values, then look at ```portality/static/doaj/js/customise_facetview.js``` lines 40 and 53. It uses the mapping defined in the other file, but here it's used to translate facet values, not just lines in the search results.

**Comment by emanuil-tolev** [comment]
I'd generally do a batch data change job, otherwise it will get confusing in the long run for us (facet says one thing, data says another thing, when you look directly at records you get confused). But appreciate we may not want to do that this late. If doing as part of public view of data I'd go with that approach though.

**Comment by richard-jones** [comment]
Great, thanks for that @emanuil-tolev - just the ticket.  We can't modify the name of the facet value, as it is widely used for workflow control, and also the display value for the publisher is the same as one of the other workflow states.  Nice and confusing!

**Comment by richard-jones** [comment]
All changes now made, just waiting for PR and deployment to test before reassigning

**Comment by dommitchell** [comment]
All looking good!
