### ISSUE TITLE
Ampersand causes search from home page to fail

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#432]
Try searching, from the home page for 'Big Data & Society'

http://doaj.org/search?source={%22query%22:%20{%22bool%22:%20{%22must%22:%20[{%22query_string%22:%20{%22query%22:%20%22big%20data%20&%20society%22}}]}}}#.VHQkuslZjVI

![ampersand](https://cloud.githubusercontent.com/assets/5955396/5178974/c37b76a6-7476-11e4-9288-83993dac858b.jpg)

**Comment by richard-jones** [comment]
This is just the URL not being properly escaped.  If you replace the & in the URL bar with %26 then the request works fine.  I will look into the fix shortly.

**Comment by richard-jones** [comment]
Just submitted a PR for this - will require a bit of testing with various inputs, but should be working fine.

**Comment by dommitchell** [comment]
All looking good. Closing!
