### ISSUE TITLE
Please add Google+ logo to homepage

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#438]
https://plus.google.com/114982932758789726160/posts

Is there a standard Google+ logo you can use?

**Comment by dommitchell** [comment]
@richard-jones can we squeeze this one into the PVOD?

**Comment by richard-jones** [comment]
@Steven-Eardley - ok to go ahead under tnm

**Comment by Steven-Eardley** [comment]
This is ready for review on live.

**Comment by dommitchell** [comment]
Brilliant!
