### ISSUE TITLE
Date added to DOAJ gets overwritten upon acceptance of reapplication

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#440]
Is there anyway to preserve the two dates:

- date added
- date reapplication accepted

This is a potential show stopper. We absolutely cannot lose the date that the journal was first added to DOAJ. At some point in the future we want to reintroduce the stats such as journals added per year etc.

**Comment by richard-jones** [comment]
@dommitchell - can you give us any more detail as to where this is occurring?

* is it when you edit an application?
* is it when you edit a journal?
* is it when you overwrite a journal with a new record from a reapplication?

**Comment by emanuil-tolev** [comment]
> is it when you overwrite a journal with a new record from a reapplication?

This is the original context in which this issue was raised.

**Comment by richard-jones** [comment]
ok, great, thanks - I have managed to replicate.  Just pondering on the
correct fix now.

**Comment by richard-jones** [comment]
PR submitted, will be ready for testing shortly

**Comment by emanuil-tolev** [comment]
> PR submitted, will be ready for testing shortly

@dommitchell This should be ready to test on test.doaj.cottagelabs.com . So basically, log in as a publisher, take note of the original journal "Date added to DOAJ", submit a reapp quickly (or do this after you do review one of the CSV upload issues) and then go accept it as a managing editor. The "Date added to DOAJ" should not change.

**Comment by dommitchell** [comment]
Having trouble testing because of problem with form: https://github.com/DOAJ/doaj/issues/448

**Comment by emanuil-tolev** [comment]
> Having trouble testing because of problem with form: #448

Could you try setting q13 and q17 to Yes, and then filling in q14 and q18? Should be OK to just test the DOAJ acceptance date problem.

**Comment by dommitchell** [comment]
Sorry @emanuil-tolev that was silly of me. 

Tested with Journal of Discrete Mathematics. Works well, date preserved but The Tick doesn't get added.

**Comment by emanuil-tolev** [comment]
Hahah, doesn't the tick get added only to journals "Added to DOAJ" after March 2014? Which is how it worked on all the *new* journals you guys were creating from suggestions. But now it's all about reapplications, and the "Date added to DOAJ" stays old. I assume you'd like the Tick added to all newly accepted reapplications @dommitchell ? This changes the "condition" of the Tick somewhat :).

**Comment by dommitchell** [comment]
But it works in staging: http://bit.ly/1waTqDl correctly

**Comment by dommitchell** [comment]
Yes, it needs to add a tick to journals accepted back into DOAJ under the new criteria.

**Comment by richard-jones** [comment]
ok, this is not a big change - I'll take a look at it this week.  We are
tracking the last_reapplied date, so we just need to check that when we
calculate the ticked-ness of the journal.

**Comment by richard-jones** [comment]
I have added a check in the calculate_tick function which takes the created_date and the last_reapplication date into account when calculating the tick.  As long as one of them is more recent than the tick threshold (march 14) then the record will be ticked.  

Bundled in the PR along with the continuations handling in reapp

**Comment by dommitchell** [comment]
OK for me to test?

**Comment by emanuil-tolev** [comment]
Not yet.. Very very soon!

**Comment by emanuil-tolev** [comment]
@dommitchell feel free to test this on http://test.doaj.cottagelabs.com now

**Comment by dommitchell** [comment]
Hmm. When I log in as Admin and accept a submitted reapplication, I get this screen:

![screen1](https://cloud.githubusercontent.com/assets/5955396/5756023/62868856-9cab-11e4-97fe-dbfdbb74c5b0.jpg)
![screen2](https://cloud.githubusercontent.com/assets/5955396/5756025/67149098-9cab-11e4-8aa7-6c281713b004.jpg)

If I hit Back on the browser and submit again, I get the message:

You cannot edit applications which have been accepted into DOAJ. 
Please note you cannot edit this application as it has been accepted into the DOAJ.

And neither journal appears in the list of Accepted journals: http://bit.ly/1wdfAF8

**Comment by richard-jones** [comment]
Damn.  Ok, I will look into this.

**Comment by richard-jones** [comment]
PR #524 submitted with fix.  Will be ready for review in a bit ...

**Comment by emanuil-tolev** [comment]
@dommitchell would you like to try this again on http://test.doaj.cottagelabs.com ?

**Comment by dommitchell** [comment]
Looking good!
