### ISSUE TITLE
Cell references in reapp error reports are wrong

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#446]
Migrated from #410 High Priority.

Cell references in large error reports can be wrong.

- This CSV: https://www.dropbox.com/s/pb3y2x3f4p98e7a/1110662x.csv?dl=0
- Produces this error report: https://www.dropbox.com/s/01bzs8r755qr6zp/reapplication_errors_20141121.csv?dl=0
- Row 4523 in the error report says that q31 is missing for journal 2090-4029 in cell H36.
- q31 is on row 34 in the original CSV, not 36.
- journal 2090-4029 is in column GP in the original CSV, not HP

- The very last question with an error is also off by 2 rows and 26 columns.

- The very first question with an error has the correct column ref in the error report (B) - so the right journal in the right column. Its row is also correct - row 10.
- The last question of the first journal is referenced by the correct column (B) but the wrong row (58, the right is 56).

**Comment by emanuil-tolev** [comment]
@dommitchell this is ready for review - can you try reuploading the sheet linked to in the first comment and check the error report is OK?

**Comment by dommitchell** [comment]
@emanuil-tolev upload returns error The list of questions in the csv has been modified; spreadsheet is invalid which makes sense I guess. Can I test by downloading a new sheet?

**Comment by emanuil-tolev** [comment]
@dommitchell Oh yes, you have to download a new sheet in fact (as you can tell). Then it should reach the stage of individual error reports for each journal. This will be emailed to mailtrap.io - if you don't know the credentials or anything else, let me know so I can direct you there.

**Comment by dommitchell** [comment]
All good!
