### ISSUE TITLE
Intermittent internal error when adding journals: no email sent to customer

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#447]
Every now and then, when a journal is accepted and added into the DOAJ, we receive an internal error. When we click back and try again, the message says that the journal has already been added. Unfortunately, under these circumstances, NO automated email gets sent to the journal contact advising them that their journal has been added.

Last report of this happening was on Friday 28/11/14 at between 3-3.30 UK for journal 1909-7786

**Comment by richard-jones** [comment]
Just going to add a catch around the email sending so that it doesn't kill the request.  Might have to flash a message saying what happened, though.
