### ISSUE TITLE
Application form: Add a URL field for Qu 13 and 16

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#448]
Please add fields for URLs to Questions 13 and 16

Does the journal have article processing charges (APCs)? * Yes No

If Yes:
13a) Enter the URL where this information can be found*: 
14) Amount *
15) Currency *

16) Does the journal have article submission charges? * Yes No

If Yes:
16a) Enter the URL where this information can be found*: 
17) Amount *
18) Currency *

**Comment by richard-jones** [comment]
Opened #501 to cover displaying this data in to ToC

Otherwise, PR just created which makes the URL field required irrespective of the status of the APC/Submission field.

**Comment by dommitchell** [comment]
Cannot submit a form now as questions 14 and 18 are required but are not visible when one selects 'No' to questions 13 and 17.

**Comment by richard-jones** [comment]
Could be cached javascript again. Could you shift+reload and try again for
me?

**Comment by dommitchell** [comment]
Yep, you're right. Working well and looking good.
