### ISSUE TITLE
Error CSV: error messages for country, currency, language

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#450]
The specific error messages for questions: 12 (country), 15, 17 (currency) and 33 (language) need to refer the user to the code lists.

Error message says just: FRE' is not a valid choice for this field*

Should say: 'FRE is not a valid choice. Refer to code lists downloadable from the Reapply tab in the Publishers' Area.'

*NB the extraneous apostrophe that appears next to a language code. This needs to be removed.

**Comment by richard-jones** [comment]
@dommitchell - we didn't follow up on the contents of the error messages in today's meeting.  Was there any further feedback on this from the testers?

**Comment by dommitchell** [comment]
Not from the testers, no but I'm still concerned that there is no connection at all between the csv and the codelists. I think I'm trying to cut down on emails to us but happy to leave this for now and come back to it if need be. Leave open but will remove from this project.

**Comment by dommitchell** [comment]
No longer needed. Cancelled.
