### ISSUE TITLE
Metadata upload: allow either or both ISSNs to be present in journal record

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#451]
Due to the current matching on DOAJ, we are having to remove an ISSN from some journal records to allow publishers to successfully upload the metadata. This is often because the publisher only sends the eISSN in their XML. 

We need to allow either ISSN to be present OR both.

**Comment by richard-jones** [comment]
Look into this and find out what the amount of work required is.

**Comment by dommitchell** [comment]
@richard-jones 
>1.  It might be confusing for users to see an article with an issn which doesn't correspond to a journal in the DOAJ
>2.  Those unmatched ISSNs in articles could be junk - we may want to strip them
>3.  Those unmatched ISSNs in articles could be new information - we may want to attach them to journals.

Not bothered about (1) but could you expound on 2 and 3?

Also, are there knock-on effect of this for people collecting our metadata via OIA, OpenURL, the CSV etc?

**Comment by dommitchell** [comment]
We established that a journal may have two ISSNs and article metadata only one, and a successful upload will take place 
BUT
An article may not have two ISSNs and a journal only one. A failure will result.

Is this something that we can work into one of the coming development cycles? Also, are there knock-on effect of this for people collecting our metadata via OIA, OpenURL, the CSV etc?

**Comment by richard-jones** [comment]
Ok to go ahead under tnm

**Comment by richard-jones** [comment]
This change has now been implemented, and a PR is pending.  To be clear about the behaviour we now have, here are the various import conditions, and the results of them.

In particular pay attention to (5) as it explores a particular oddity that may need to be revisited.

1/ a journal with 2 issns which don't appear anywhere else in the index and an article with the same 2 issns will result in a successful import
2/ a journal with 2 issns which don't appear anywhere else in the index and an article with the 1 matching issn and no other issns in the record will result in a successful import
3/ a journal with 1 issn which doesn't appear anywhere else in the index and an article with 2 issns, one of which matches that journal and the other of which doesn't match anything will result in a successful import
4/ a journal with 1 issn which doesn't appear anywhere else in the index and an article with 1 issn which matches that journal will result in a successful import
5/ a journal with 2 issns which don't appear anywhere else in the index and an article with 2 issns, only one of which matches the journal, and the other of which doesn't match anything, will result in a successful import
6/ 2 journals with the same 1 or 2 issns but different owners will result in an import failure
7/ 2 journals with 1 different issn each and different owners, and an article with 2 issns, which each match a different one of the journals will result in an import failure
8/  2 journals with 1 different issn each and the same owner, and an article with 2 issns, which each match a different one of the journals will result in a successful import
9/ 2 journals with 2 different issns each and different owners, and an article with 2 issns which each match a different one of the journals will result in an import failure

@dommitchell - this isn't ready for review of the running code, but if you could look over the above conditions and make sure that everything looks right, that would be great.

**Comment by emanuil-tolev** [comment]
@richard-jones I've deployed the bit you had a PR for

**Comment by dommitchell** [comment]
@richard-jones bit confused by what "which doesn't appear anywhere else in the index" means?

**Comment by richard-jones** [comment]
It means that the issn attached to that journal doesn't appear attached to any other journal either in the public doaj or in the withdrawn space.

**Comment by dommitchell** [comment]
Dom to re-read

**Comment by dommitchell** [comment]
> 5/ a journal with 2 issns which don't appear anywhere else in the index and an article with 2 issns, only one of which matches the journal, and the other of which doesn't match anything, will result in a successful import

@richard-jones OK. Yes, (5) could be a problem. Can it be tightened up? If a journal has 2 ISSNs then it must be assumed that they are both correct. That means that the 'odd' ISSN in the article is probably an error. I would prefer it (5) resulted in an error....

And then 6-9 talk about journals only. I am not sure how they fit in here since this is about uploading article metadata but I know I am missing something. Can you help?

**Comment by richard-jones** [comment]
Ok, I'll put this task back on the todo list and implement the rule for (5).

In the mean time 6 should be interpreted as having that behaviour irrespective of the combinations of issns that come in with the article uploads.  So, it doesn't matter if the article has one or other or both of the issns, with the journals that get matched in the described situation defined in there, the import will fail.

7-9 do talk about articles, so maybe (6) just threw you off? ;)

**Comment by dommitchell** [comment]
> 7-9 do talk about articles, so maybe (6) just threw you off? ;)

Good job someone's on the ball!

> 8/ 2 journals with 1 different issn each and the same owner, and an article with 2 issns, which each match a different one of the journals will result in a successful import

Which journal will the article be assigned to? I presume it won't duplicate and be attached to both?

**Comment by richard-jones** [comment]
The article isn't assigned to a journal as such - the connection happens dynamically via the ISSN.  So, in this case the article would appear in search listings and ToCs for both journals.

**Comment by dommitchell** [comment]
OK, all good. Thanks for helping me through this one!

**Comment by dommitchell** [comment]
Not sure how I can test this one? Any advice?

**Comment by emanuil-tolev** [comment]
> Not sure how I can test this one? Any advice?

Hm. I guess consider the original issue?

> Due to the current matching on DOAJ, we are having to remove an ISSN from some journal records to allow publishers to successfully upload the metadata. This is often because the publisher only sends the eISSN in their XML.
> 
> We need to allow either ISSN to be present OR both.

Do you still have to remove an ISSN from some journal records to allow publishers to upload metadata? There's no concrete example in the original post, but you and the other editors might have an idea of which journals had this problem?

**Comment by dommitchell** [comment]
I have now tested this in testdoaj. This is good to go. Please make live as soon as you can.

**Comment by emanuil-tolev** [comment]
@dommitchell this should be released :)

**Comment by richard-jones** [comment]
Need to revisit rule (5)

**Comment by richard-jones** [comment]
I've now implemented an enhanced check for point (5), in an upcoming PR

**Comment by richard-jones** [comment]
@dommitchell this is now on the test server.

Testing it is pretty difficult, basically you'll need to do the following:

1. Select a journal that has 2 ISSNs associated with it
2. Upload an article which has 1 of those ISSNs and another random one that isn't in DOAJ at all

The submission should be rejected.

**Comment by dommitchell** [comment]
I don't think I can test that. I shall put it in writing here: happy to go live without testing. I trust you.
