### ISSUE TITLE
Changes to journal home pages: ISSNs, language, publication charges

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#454]
- [ ] Move the ISSNs, currently listed under the journal title into the left box on the journal home page above Publisher:
http://doaj.org/toc/ff3420e5c3184cfe80609af9d33a2660

- [ ] Translate language into proper noun. 

- [ ] Change 'Language(s)' to 'Language(s) of full text'

- [ ] Move to left box: Article processing charges (APCs): Yes/No

**Comment by richard-jones** [comment]
This issue is superseded by #585, so closing this off
