### ISSUE TITLE
Specify OpenGraph metadata for Facebook

### ISSUE THREAD

**Issue by Steven-Eardley** [DOAJ/doaj#455]
In issue #266 it was noted the wrong image appears when DOAJ is shared on Facebook:

![karger](https://cloud.githubusercontent.com/assets/5955396/5187163/69b4bc86-74cb-11e4-9ae1-099cdf88f190.jpg)

* This could be fixable by specifying og tags, per https://blog.kissmetrics.com/open-graph-meta-tags/
* Inferred open graph data can be searched via https://developers.facebook.com/tools/debug/og/object/
* facebook's wisdom on URL migrations https://developers.facebook.com/docs/sharing/opengraph/using-objects#update

**Comment by Steven-Eardley** [comment]
@dommitchell after the pull request is merged, the share dialogue should look like that shown below (apart from the demo URL):

![screen shot 2015-03-12 at 20 39 32](https://cloud.githubusercontent.com/assets/1446355/6627881/393086b2-c8f9-11e4-9dbd-8b2c6c8f9297.png)

Let me know if you'd like something different!

**Comment by dommitchell** [comment]
This is great! Very happy with this.

**Comment by Steven-Eardley** [comment]
This can best be reviewed once it's live at the end of the PVOD project.

**Comment by emanuil-tolev** [comment]
@dommitchell does it work from http://doaj.cottagelabs.com ?

**Comment by dommitchell** [comment]
Yep!

![fb](https://cloud.githubusercontent.com/assets/5955396/6820586/e74a8eba-d2d0-11e4-8982-da5ff51d954a.jpg)

**Comment by emanuil-tolev** [comment]
Alright, cool, it'll definitely work on Live then.

**Comment by dommitchell** [comment]
Hi, this seems to have switched back showing the Karger logo.
![fb](https://cloud.githubusercontent.com/assets/5955396/7315918/6242b954-ea72-11e4-9c86-a14ec09684af.jpg)

**Comment by Steven-Eardley** [comment]
@dommitchell I confirmed your issue using the object debugger, checked the tags are properly set (they are), and asked it to refresh the scraped data. The correct image and text appears there now for www.doaj.org, https://doaj.org, http://doaj.org. (it's a caching thing on their end)

@emanuil-tolev - it seems facebook isn't quite as smart as we hoped. Changing the canonical url to https has changed the entity resolved:

**results for now**
Fetched URL	http://www.doaj.org/
Canonical URL	https://doaj.org/ (23 likes, 24 shares)

**when last fetched**
April 17 at 7:04pm	http://doaj.org/ (7368 likes, 4944 shares)

This doesn't affect how it appears in the share dialogue, but I don't know if there's any other consequence of losing thousands of likes and shares. To solve this I can hard-code the canonical URL for OpenGraph back to http, since all it does is aggregates shares, likes and comments.

**Comment by Steven-Eardley** [comment]
@dommitchell, try sharing again, and let me know if you'd like me to make the change to get your thousands of 'likes' back.

**Comment by emanuil-tolev** [comment]
> @emanuil-tolev - it seems facebook isn't quite as smart as we hoped. Changing the canonical url to https has changed the entity resolved:

Ah hm .. it is going to be https from now on I think, which does pose an important question: if we revert the OG metadata back to http, we will have to remember and keep it that way. Not too terrible I guess, with a comment. I'd be happy to make the change. What are you relying on, BASE_URL? Since we can't change that in the config, that's used elsewhere (in emails and scripts). Maybe a OPENGRAPH_CANONICAL_URL or sth - I'd be happy to merge a hotfix like that.

Btw, if you merge/deploy any hotfixes (e.g. if I'm not around) with the DOAJ fabric file in the sysadmin repo (fab deploy_live:tag=blahblah), make sure to git pull the sysadmin repo first. The fabric script still works with the exact same syntax but has changed considerably to reflect the new infrastructure.

**Comment by dommitchell** [comment]
![fb2](https://cloud.githubusercontent.com/assets/5955396/7317447/3d84805c-ea81-11e4-918c-cd6564c6a4ac.jpg)

Looking good! Closing
