### ISSUE TITLE
Error message in error report needs to be changed

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#461]
Question 45: the answer Other is not allowed. It currently returns a message in the error csv file:

You have selected "Other" but have not provided any details.

It should say: Other is not valid. You must write your license's name

**Comment by richard-jones** [comment]
@dommitchell - another one: we didn't follow up on the contents of the error messages in today's meeting. Was there any further feedback on this from the testers?

**Comment by dommitchell** [comment]
Closing. Have added specific notes to documentation
