### ISSUE TITLE
Extraneous apostrophe in error message

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#466]
When an invalid language code via CSV upload is entered, the error report message includes an erroneous trailing apostrophe:

    FRE' is not a valid choice for this field

Why is this happening?  Fix it :)

**Comment by richard-jones** [comment]
Unable to reproduce.  Mine says:  

    'FRE' is not a valid choice for this field

with the correct quote marks.

@dommitchell - if you can replicate this again, let me know.

**Comment by dommitchell** [comment]
OK, closing for now
