### ISSUE TITLE
change the captcha method

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#47]
ReCaptcha by Google is nice, accessible and very widely used. It's also used by the DOAJ app right now through Flask-WTForms with almost no effort.

However, the challenges are simply too hard. I can't solve about 20% of them because they're just way too distorted or there's too much noise.

Also, apparently you can input only one of the words. I have confirmed this, it does work, but not always (I probably enter the "wrong" word, i.e. not the very difficult one but the readable one, and Google does not consider this solving the Captcha). This is just ridiculous as I can't even instruct our users to enter only one of the words if they're having trouble.

It is possible to get a new captcha without reloading the page (there's a button) + it's fine in most cases, so I'm not going to spend any more time on making this easier at the moment.

I have looked at alternatives, but they all require more time than Recaptcha to integrate with.

Best alternative so far for later implementation: http://opencaptcha.com/

**Comment by richard-jones** [comment]
We may require this for #764 - may make that more effort than originally thought

**Comment by emanuil-tolev** [comment]
> Best alternative so far for later implementation: http://opencaptcha.com/

This service may no longer be operational, I get a 500 server error when I try to get an image.

Alternatively we could use a Python library https://github.com/lepture/captcha - we would need to keep track of the string we generate, come up with good strings (e.g. words from a "simple english" dict or just random 4 or 5 digit numbers) and validate the user's answer to the challenge. We need to store what the challenge was in the session (currently none of our pages have "state" like this that needs to be kept secret, but it shouldn't be hard to do even for anon users).

Say about a day in total with unit tests. (Obviously we can't solve the captcha automatically, or rather it's besides the point here, so we'll just test if it's being generated and if a correct response means we pass and wrong response means we fail the challenge.)

**Comment by richard-jones** [comment]
We've removed captcha from the site, and we're not going back to it.  There is a suggestion elsewhere to use hidden fields to trap the bots, rather than getting users to validate themselves.  So, I'm going to close this issue off, as no longer relevant.
