### ISSUE TITLE
Remove all articles from account

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#470]
Please delete all articles from Saudi Medical Journal:

http://bit.ly/1wbR5ey (5607 articles)

**Comment by dommitchell** [comment]
@richard-jones are these waiting for Reapp release?

**Comment by richard-jones** [comment]
@emanuil-tolev @markmacgillivray - I recall thinking that you guys had run these. Please could you let me / @dommitchell know the status

**Comment by markmacgillivray** [comment]
@emanuil-tolev was to run them before christmas after we discussed, don't know if he did or not though. I will re-assign these to him to track properly, should have done that at the time.

**Comment by emanuil-tolev** [comment]
> should have done that at the time

And I thought I had, no less. But there's no mistaking it, the articles *are* on live. I must have run this on staging (as it was at the time..). I am quite certain they are being run properly now.

5607 articles deleted here.

**Comment by dommitchell** [comment]
Not quite. There are still two volumes left: http://doaj.org/toc/2d74d57b5d6b4815ba167ebf8ddc04fe

**Comment by dommitchell** [comment]
http://doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%221658-3175%22,%22default_field%22:%22index.issn.exact%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:%5B{%22term%22:{%22_type%22:%22article%22}}%5D}}}}}

**Comment by emanuil-tolev** [comment]
Done! (again)
