### ISSUE TITLE
Comma as delimiter in CSV file

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#476]
User testing has shown that file upload is failing because questions have been modified.
Upon further examination, this was all questions that have a comma in them.

Pages 2 and 3 https://docs.google.com/document/d/1nh5fCgDdM6rP6ubwbvCOsUtzn-JJhUnDSF-E7sFnJpE/edit?usp=sharing state that the separators should be a comma and the delimiter inverted commas.

- [ ] will questions be truncated in this way because the user hasn't set the delimiter as "" upon resave?

- [ ] would it be better to remove this possibility by removing all commas from the questions?

**Comment by richard-jones** [comment]
@dommitchell - after looking at the csv you sent me, I couldn't see any issues.  It looked like one downloaded from the site, and it opened fine.  I think that the documentation is the only way to tackle this particular issue, though.  Let me know if there's anything more you want me to look at.

**Comment by dommitchell** [comment]
Closing. No longer needed.
