### ISSUE TITLE
Request to delete ALL articles

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#477]
http://doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%22RUSC%20\\:%20Universities%20and%20Knowledge%20Society%20Journal%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22_type%22:%22article%22}}]}}}}}

635 articles

**Comment by dommitchell** [comment]
Any movement on this one?

**Comment by richard-jones** [comment]
No, sorry, not had a chance to get near it.  Will be focussing on the reapp for the rest of this week, so will look at it after.

**Comment by emanuil-tolev** [comment]
@dommitchell is it a good idea to delete by name like that? Why not ISSN, and maybe even search specifically in the ISSN field (select from the dropdown next to the search box)?

Could easily be run, but a bit worried there isn't much of a way to be sure we're deleting only the things we should be deleting.

Like this:

http://doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%221698-580X%22,%22default_field%22:%22index.issn.exact%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22_type%22:%22article%22}}]}}}}}

(if the link doesn't open properly - something we should fix in the public view of data project btw - limit to articles, select ISSN from the field dropdown, and put 1698-580X into the search box).

Now this is 635 articles again, but I'm much more confident it's the right 635 articles. Is this ok to delete with that query?

**Comment by dommitchell** [comment]
@emanuil-tolev Thanks, go ahead!

**Comment by emanuil-tolev** [comment]
Done.
