### ISSUE TITLE
Move reapplication as well when a journal is reassigned

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#492]

**Comment by dommitchell** [comment]
Tested:

Moved two journal in test from one account to another, confirmed associated applications moved in publisher admin view and logged in as publisher.

Closing

**Comment by dommitchell** [comment]
What about moving articles when ownership changes? Is that included? Will it be applied retroactively to the live site?

**Comment by richard-jones** [comment]
Articles are bound to journals rather than user accounts, so provided the ISSN remains the same the articles will be linked to the correct journal.

**Comment by dommitchell** [comment]
Thank you!
