### ISSUE TITLE
Initialising reapplication process for a single account

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#493]

**Comment by richard-jones** [comment]
Scripts can now be run with the following arguments

   -d

Regenerate reapplications for the whole DOAJ.  This will remove everything from the BulkReapplications index, and all Suggestions with status "reapplication" or "submitted".  Running this will literally start the re-application from scratch, so any changes which have not made it through to the DOAJ journal index will be lost.  Reapplications will be generated for all journals in_doaj, and CSVs for all accounts with 11 or more reapplications.

    -a [account id]

Regenerate reapplications for this account.  This will remove the account's record from the BulkReapplications index, and all of that account's Suggestions in status "reapplication" or "submitted".  Same warnings as above - this resets the reapplication for that account back to the beginning, so any changes not already accepted will be lost.  Reapplications will be created for all journals in_doaj and a CSV will be generated if necessary.

   -j [journal id]

Regenerate this journal's reapplication, and regenerate the CSV it is part of if relevant.  Usual warnings - will reset the reapplication for this journal back to the beginning, irrespective of its workflow state.


Note: if a publisher has reapplications that are in the editorial workflow, these will cause problems with the regeneration of the reapplication, so care should be taken to return all journals to the publisher area (status "reapplication") before running this task.

**Comment by richard-jones** [comment]
@emanuil-tolev - assigning this to you for review.  Not something I think that @dommitchell can review directly, so you can either keep this on your list for the deployment, or close it as you see fit.

**Comment by emanuil-tolev** [comment]
It doesn't have to wait till deployment and I reviewed the pull req for this. But I would like to:

- [ ] generate all reapplications locally since -d switch will now be what's used to start the whole process
- [ ] regenerate reapplications for an account
- [ ] regenerate one journal's reapp
    - check what happens if a reapp is in the editorial workflow and this gets run

Most of the time just checking the data is as I'd expect it to be, so shouldn't take very long.

**Comment by emanuil-tolev** [comment]
Yeah, used the script every which way by now, closing this enhancement.
