### ISSUE TITLE
Diacritic characters as ??? in CSV file

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#50]
Feedback from the site:

/start/
This morning I downloaded the metadata from the CSV file you provide from your web site, however, every title that contains diacritics translates into question marks.

For example, title, Морфологіa (ISSN 1997-9665) comes out as, ??????????.

Title, ΕΠΙΣΤΗΜΟΝΙΚΑ ΧΡΟΝΙΚΑ (ISSN 1791-1362) comes out as, ???????????? ???????.
/end/

Is this a user error?

**Comment by richard-jones** [comment]
Has this issue resolved itself?  I can't see any problems on the linked page.

If not, how do we resolve?  Do we just want to look for those kinds of characters and strip them from the data?

**Comment by dommitchell** [comment]
It seems that many have been fixed by the UTF change.

Also, browsers seem to be handling these things better?? Possible?

There are still anomalies but not diacritic ones. Again, it would be helpful to ascertain the size of the problem. Something you can do?

**Comment by richard-jones** [comment]
This is some kind of problem with the CSV export:

 Journal für Klinische Endokrinologie und Stoffwechsel
  Journal fÃ¼r   Klinische Endokrinologie und Stoffwechsel
