### ISSUE TITLE
APC/Submission charges URLs on ToC

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#501]
Please add the URL information to the journal homepage, for example: http://test.doaj.cottagelabs.com/toc/ff73e5bc37764e369c279f09813e703a

Applicant has answered Yes:
APC: Yes. [currency] [amount] [URL]
Submission Charges: Yes. [currency] [amount] [URL]

Applicant has answered No:
APC: No. [URL]
Submission Charges: No. [URL]

**Comment by richard-jones** [comment]
Now the APC field is always displayed along with the URL, and then the currency/cost is displayed if available.

This can also handle legacy records where the URL is not available, so will work throughout the transition of the reapplication.

**Comment by dommitchell** [comment]
Two tweaks
Lose the space between the currency and the amount? It looks confusing. Or do you have any other suggestions to make it more obvious that it's a currency value?
Change APC to: "Author Processing Charges (APCs)"

**Comment by richard-jones** [comment]
What I've done is remove the space and reverse the order of the price and currency, so it would come back as, for example:

27GBP

**Comment by dommitchell** [comment]
And this: Change APC to: "Author Processing Charges (APCs)"  please

**Comment by richard-jones** [comment]
Yup, that is also done.  Code is currently in PR, will be out on the test server when it is merged.

**Comment by Steven-Eardley** [comment]
Merged pull request #571 for this now

**Comment by dommitchell** [comment]
Looks good!

**Comment by dommitchell** [comment]
please "Author Processing Charges (APCs)" to "Article Processing Charges (APCs)" My mistake!

**Comment by richard-jones** [comment]
done in PR, will be live shortly

**Comment by Steven-Eardley** [comment]
Ready on live.
