### ISSUE TITLE
Store all timestamps using UTC rather than local timezone

### ISSUE THREAD

**Issue by Steven-Eardley** [DOAJ/doaj#506]
In `dao.py`, the DomainObject superclass of the models, the timestamps are written using `datetime.now()` which is dependent on server's physical location. In order to prevent headaches with localisation and migration between servers, these should all be UTC, i.e. using `datetime.utcnow()`.

Advantages:
- timestamps will follow chronological order (currently daylight savings time could affect this)
- localisation will be more straightforward
- moving server to a different timezone will not render timestamps incorrect

**Comment by Steven-Eardley** [comment]
Additionally, a change to UTC would mean the notation already used for timestamps throughout the site will be correct ('Z' on the the end means UTC - see [ISO_8601](http://en.wikipedia.org/wiki/ISO_8601#UTC))

**Comment by richard-jones** [comment]
I'm tempted to have a go at this during the Continuations project.  I will look at the feasibility and make a judgement call once the code is underway.

**Comment by richard-jones** [comment]
I did not do this as part of the continuations project - we need to put in place a central date/time service for the app, and migrate all the code over to it.  Seemed to cut too much across the other refactoring, so I've left it.

**Comment by dommitchell** [comment]
@Steven-Eardley Can we have a 'refactoring' label and label this with it?
