### ISSUE TITLE
Question: extract list of publishers who supply us with article metadata?

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#509]
Theoretical question: is it possible to extract a list of all journals who supply us with article metadata?

**Comment by emanuil-tolev** [comment]
> Theoretical question: is it possible to extract a list of all journals who supply us with article metadata?

That are supplying us with article metadata now, or that have supplied us with such data in the past?

The DOAJ homepage says "6,045 searchable at Article level" out of about 10'000. So yes, we can give you *which* those 6'045 are relatively easily. I'm just wondering if you mean "actively supplying data" which is a bit narrower.

**Comment by dommitchell** [comment]
OK, thanks both. I thought so. Closing for now.
