### ISSUE TITLE
DOAJ Seal

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#512]
Rules: to be displayed for those journals who have had the 'DOAJ Seal' checkbox on their journal page checked (e.g. https://doaj.org/admin/journal/2ae83e2d8df84ada9a7702235d582d4f) 
To be displayed in both:
  -  the 'short view' (search results) and
  -  the 'long view' (journal issue pages), top right hand corner under the CC logo

Short view: 
![doaj_seal_logo_mini](https://cloud.githubusercontent.com/assets/5955396/3014983/d3715da4-df5d-11e3-8194-b2ab5069569d.png)

Long view: 
![doaj_seal_text_logo_mini](https://cloud.githubusercontent.com/assets/5955396/3014984/d9da1640-df5d-11e3-88c1-994056c86d77.png)

**Comment by richard-jones** [comment]
DOAJ Seal:
* Changes to core data model to support new info
* Updates to relevant administrator web forms to allow Seal
to be applied by checkbox
* Updates to search interface to facet by Seal, and present
Seal alongside other Journal data
* Updates to Table of Contents to present Seal
* Essential data migration and roll-out

**Comment by Steven-Eardley** [comment]
@dommitchell, I'd like you to make sure you're happy with how the various badges are placed on the page. So far I have this, after following the instructions above:

![screen shot 2015-05-25 at 14 20 29](https://cloud.githubusercontent.com/assets/1446355/7808780/a1e8fd32-038d-11e5-929f-60162b1935c6.png)

![screen shot 2015-05-25 at 14 20 48](https://cloud.githubusercontent.com/assets/1446355/7808788/a94d5a5a-038d-11e5-991a-c9b0a6ccf7c9.png)

RJ has suggested the following changes:
* in the facetview results use the 'short view' seal and place it under the journal type icon on the left of the text
* on the TOC page, place the seal on the same line as the tick, side-by-side.

I'd just like to know if you have any different suggestions before I go ahead.

**Comment by dommitchell** [comment]
@Steven-Eardley I think I had imagined it as you have it pretty much. I'd be interested to know @richard-jones reasons for the alternative display? Are there things that I am not taking ito consideration?

Can you show me one in facet view, as you have the layout now, and that has the APC charge as well?

I think the Seal should go above the license image and under the Tick in both views.

**Comment by richard-jones** [comment]
@dommitchell - no strong reasoning, just thinking about the aesthetics of a column of icons on the right vs distributing them between the left and the right.  There's no right answer, that's just personal preference, so we're happy to do them whichever way you like

**Comment by Steven-Eardley** [comment]
@dommitchell - I've shifted the seal above the license, and here's a screenshot with the APC:
![screen shot 2015-05-26 at 18 32 12](https://cloud.githubusercontent.com/assets/1446355/7818941/8992713e-03d6-11e5-89b6-bffa4257d780.png)

the toc looks like this:
![screen shot 2015-05-26 at 18 32 34](https://cloud.githubusercontent.com/assets/1446355/7818953/96ea1922-03d6-11e5-9bf9-380ff3d08094.png)

**Comment by greboun** [comment]
I really like the view with Seal under tickmark and above license info.
for me the facet and the Toc layout are fine this way.
I am not so happy with the readability of the text in the Seal. perhaps the DOAJ SEAL text could be more made lookiing like an imprint, with sort of an outline But perhaps I just have missed the discussions around design issues

**Comment by Steven-Eardley** [comment]
I agree with you @greboun - I too have concerns about the seal image. I'm not a fan of the vague colours, the squint text or the smudge in the bottom part (it's too harsh). @dommitchell do you have the assets on hand to change it, are you okay with it for now, or should I see what I can do on the .png?

I'd like to lighten the smudge, straighten the text, and darken the text on the graphic.

**Comment by dommitchell** [comment]
How about this?

![doaj_seal_text_logo_mini_touched](https://cloud.githubusercontent.com/assets/5955396/7860279/f093431e-0547-11e5-8c9d-8737034cf395.gif)

**Comment by Steven-Eardley** [comment]
I think the 'DOAJ seal' text is still too difficult to read, and the off-kilter angle of 'seal' exacerbates that. All you can easily see at a glance is the 'for open access journals' part, which doesn't make a huge amount of sense on its own. 

Although, if a user is interested in what it means they can see the mouseover text.

**Comment by dommitchell** [comment]
Here are the original pngs. I wonder if we should go with the Seal without the black text and so use the larger one? Anyhoo, see if you can do something with them. The image has been approved by Lars so we can't change it too much.

![doaj_seal_logo_small](https://cloud.githubusercontent.com/assets/5955396/7861151/986df09c-054e-11e5-99e3-9843660f3d53.png)
![doaj_seal_text_logo_mini](https://cloud.githubusercontent.com/assets/5955396/7861149/986a2b60-054e-11e5-8a5a-f7a3e5846aaf.png)
![doaj_seal_text_logo_small](https://cloud.githubusercontent.com/assets/5955396/7861150/986c5606-054e-11e5-81c3-8534ae1481b0.png)

**Comment by Steven-Eardley** [comment]
Thanks Dom. Another question - which roles should see the 'DOAJ Seal' checkbox on their journal forms?

**Comment by dommitchell** [comment]
@Steven-Eardley only  Admin.

**Comment by greboun** [comment]
Hi


I would be in favor of using the larger picture of the Seal and omit the
text for open access journals.
The description of what the Seal is is sufficient and the users will be
quick to recognize the pcture as the DOAJ Seal.

TOM

Dr. Tom Olijhoek
Editor-in-Chief  DOAJ

**Comment by Steven-Eardley** [comment]
Another question - where should the tick-box go, and would you like some descriptive text? Currently I've put the tick box in the 'editorial' group on the managing editors form. See:

![screen shot 2015-06-01 at 10 08 01](https://cloud.githubusercontent.com/assets/1446355/7909735/7c9f2192-0846-11e5-9a89-d8c974acf44a.png)

**Comment by dommitchell** [comment]
Hi @Steven-Eardley We're happy to go ahead with the Seal logo without the text. You said it will look a little odd so can we try the license image first, then the Tick, then the Seal?

Regarding the check box: we'd like the check box to sit in the DOAJ Seal information box which is currently on every application. If possible, can it sit next to the 'The qualifiers for the DOAJ Seal' title?

**Comment by Steven-Eardley** [comment]
@dommitchell thanks, do you know where you'd like the checkbox to go on the journal review form? It currently has no container for information about the seal. Shall I add the same container to that form?

**Comment by Steven-Eardley** [comment]
@dommitchell @greboun Here's another chance for feedback. Seal without text in facetview results:
![screen shot 2015-06-05 at 14 03 21](https://cloud.githubusercontent.com/assets/1446355/8006444/d9d2bcdc-0b8b-11e5-9eb0-2294dfe40084.png)
seal on toc (it should be on a new line, but you get the idea from the image above):
![screen shot 2015-06-05 at 14 04 18](https://cloud.githubusercontent.com/assets/1446355/8006445/d9d41c4e-0b8b-11e5-8cb7-f40680e5e03c.png)
seal tickbox on form (I put it at the bottom so it replaces the 'can apply for...' text since the ManEd doesn't need to know that.
![screen shot 2015-06-05 at 14 06 20](https://cloud.githubusercontent.com/assets/1446355/8006480/4975b602-0b8c-11e5-8760-e631b0095c8b.png)

also, I did add the whole seal information box to the ManEd's application review form, as i asked above. The checkbox is indented because it's the class as the other questions on the form, and changing that to be left aligned isn't easy.

**Comment by dommitchell** [comment]
> do you know where you'd like the checkbox to go on the journal review form?

@Steven-Eardley can it go next to the title of that box, at the top of that box? It's a bit lost where it is now. Can you change the wording to 'Qualifies for Seal?'

I think the placement of the logo is fine. Is there anyway we can swap out the Tick so that it is just the image here #177 without the words?

**Comment by dommitchell** [comment]
@Steven-Eardley as decided on the call, we can leave the tickbox where it is.
