### ISSUE TITLE
Add sponsor logo and updated static pages

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#515]
Please add the following to the home page and the sponsors page.

- [x] Add ProQuest logo
![proquest](https://cloud.githubusercontent.com/assets/5955396/5718072/e05e0482-9b09-11e4-9f9d-183baa31ebe5.gif) http://www.proquest.com/

- [x] Remove the INASP logo.

- [x] Add ExLibris logo 
![exlibris](https://cloud.githubusercontent.com/assets/5955396/5722766/44977372-9b3f-11e4-80c5-1a6e51d0ecf4.gif) http://www.exlibrisgroup.com/

- [x] Add Nature logo
![nature](https://cloud.githubusercontent.com/assets/5955396/5759537/dfea79a6-9cce-11e4-991f-891eb401641c.gif) http://www.nature.com/npg_/index_npg.html

- [x] Add Palgrave logo
![palgrave](https://cloud.githubusercontent.com/assets/5955396/5759543/ebd09a70-9cce-11e4-9ac3-f7b75cc27ab8.gif)  http://www.palgrave.com/

- [x] Update static pages

- [x] destroy and recreate a fresh static_pages branch after reapplication roll-out on 19th Jan

**Comment by emanuil-tolev** [comment]
@dommitchell done all these. It was only ProQuest when I first looked at it :)! Congratulations on getting more sponsors, and such big names too.

**Comment by emanuil-tolev** [comment]
Can't update the static pages right now as there's a conflict - a file we have deleted in ```develop``` has been modified by you. If I go ahead, on Monday your changes might be lost - maybe they have to actually be made to some other file. The file in question is ```portality/templates/doaj/suggestion.html```.

We should talk about it briefly on our Monday meeting and see how things are - I'll give you more details about what your change is and we'll decide where to put it.

**Comment by dommitchell** [comment]
@emanuil-tolev, that's OK. Go ahead. I opened the file by mistake but didn't make any changes.

**Comment by emanuil-tolev** [comment]
Oh ok, so if it's just been reformatted (all the newlines) but you don't actually want to keep any changes, I can just throw away your changes (since they're just reformatting it) and let the file be deleted by the reapplications codebase. The stuff for the app form is in a different place now.

**Comment by emanuil-tolev** [comment]
@dommitchell 

> Go ahead. I opened the file by mistake but didn't make any changes.

That's not quite true :).

```diff
 <p>Currently, it is not possible to save your progress or for us to send you a confirmation email. We have
 <a href="{{ url_for('doaj.faq', _anchor='application') }}">created a spreadsheet version of the form</a> and some other
-tips to help you. Guides to completing the form are available in <a href="{{ url_for('doaj.translated') }}">other
-languages</a>.</p>
+tips to help you. Guides to completing the form are available in <a href="{{ url_for('doaj.translated') }}">
+are available in other languages (中文, فارسی, Polski, Português, Русский, Español, Türkçe)</a>.</p>
```

No worries, I'll port the change over to the right file now.

**Comment by dommitchell** [comment]
Ahh! Yes, I added those languages. Where can I make that change then to the top of the Application Form? http://doaj.org/application/new

**Comment by emanuil-tolev** [comment]
For the current live system, the place you made the change is correct.

From Monday on it will be in portality/templates/formcontext/public_application_form.html .

For now I've transferred the change over myself to the 2 versions of the code (the one now live, and the one under development).

We should update the static_pages branch to reflect the new codebase. I will destroy it and recreate it after we roll out the system to live - so you will be working from a fresh copy of all the .html files. Let's leave this issue open for that, and I'll put it on my todo too.

**Comment by emanuil-tolev** [comment]
The most recent changes to static pages have been rolled out to live too.

**Comment by dommitchell** [comment]
Smashing! Thank you!
