### ISSUE TITLE
Serve static files with timestamp in the query string to prevent caching

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#516]
Best way of illustrating what this means:

http://doaj.org/static/doaj/js/customise_facetview.js - will get cached. Then if the file changes it will take a while for changes to show up for all users.

http://doaj.org/static/doaj/js/customise_facetview.js?version=20150113093600 - will get cached. Then if the file changes the automatically generated version parameter will change, and will force everybody to update their JS.

Flask-Assets might be able to do this. We should probably do this as part of the public view of data project and get rid of those pesky Ctrl+Reload moments. /cc @richard-jones

**Comment by emanuil-tolev** [comment]
Initially I had the idea of doing this via an asset manager, but we can just change the links we generate and it will be a very effective cache buster! See 2 example links above.

**Comment by richard-jones** [comment]
Did this as part of PVOD
