### ISSUE TITLE
Restrictions on DOAJ use/Google in China

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#517]
/starts/
I have tried what you suggested (pressing Ctrl + F5 to force a browser reload) using three kinds of browsers, i.e. IE, Firefox, and Google Chrome, and the attached are the screenshots showing what happened, respectively. You can see that it still did not work.

You may have known that Google as an searching engine has been restricted in China for years. Is your website developed based on or close related to Google? If this is true, I guess what happened to us may have happened to many Chinese journals.
/ends/

Chrome
![google](https://cloud.githubusercontent.com/assets/5955396/5735819/c514f5c8-9bcc-11e4-82bd-ad55eb92054b.JPG)

Firefox
![firefox](https://cloud.githubusercontent.com/assets/5955396/5735820/c51e1e50-9bcc-11e4-8c05-6bcc7ef26097.JPG)

IE
![ie](https://cloud.githubusercontent.com/assets/5955396/5735821/c51eadf2-9bcc-11e4-9c1e-0376847a8758.JPG)

Thoughts on how we can give access to China please.

**Comment by emanuil-tolev** [comment]
Ah, this is my absolute favourite topic. Can you do this (or ask the person who did it to do it) again with developer tools open in Chrome (just press Ctrl+Shift+I), and set to the "Console" tab?

**Comment by dommitchell** [comment]
What are they looking for?

**Comment by emanuil-tolev** [comment]
Good question - it's a bit hard to tell actually. I'm looking for network errors. (If they're technically savvy lines in red in the Network tab may help as well.) But they probably won't be your normal 404 Not Found or 500 Server Error if they're being blocked by the great firewall in some fashion. Maybe Connection Reset or some other kind of unexpected error?

(There is the possibility this is just a problem with the code obviously, though that's far less exciting.)

**Comment by richard-jones** [comment]
We do use google's content distribution network for the page dependencies, and without them the site certainly won't work.

Interesting one!

I'm not really sure what the answer is, tbh.  Lobby the Chinese government, perhaps :)

The only technical answer we have for this is to look for another cdn that's not blocked or to distribute the dependencies ourselves, but the latter will cause a fairly significant hike in our bandwidth usage and server load (which we had problems with back at the start of last year when we started hosting, so would probably be an issue again).

Also, I wonder what the impact on google analytics is?

**Comment by emanuil-tolev** [comment]
Yeah, I'd like to know exactly what's causing it first. Might try some good Chinese proxies later today.

We can't be the only ones with the Google CDN problem if that's what's causing it, so solutions may hang around in the internet..

**Comment by dommitchell** [comment]
Have asked the user to send info from the developers console in Chrome. Let's see what comes back first.

**Comment by dommitchell** [comment]
Screenshots from our colleague in China

![1](https://cloud.githubusercontent.com/assets/5955396/5773935/9f6d13c6-9d68-11e4-939b-2d66bab5645f.JPG)
![2](https://cloud.githubusercontent.com/assets/5955396/5773940/b1c57f5e-9d68-11e4-9a72-a7959cb2942e.JPG)
![3](https://cloud.githubusercontent.com/assets/5955396/5773938/b1c0ca0e-9d68-11e4-9b7d-74f43d56fa38.JPG)
![4](https://cloud.githubusercontent.com/assets/5955396/5773939/b1c4beb6-9d68-11e4-9797-e03c216a8870.JPG)

**Comment by richard-jones** [comment]
Yup, not being able to load jQuery (second screenshot in red) will pretty
much kill everything.  Definitely a GFW problem; I'm pretty surprised that
google analytics works, though - must be too useful to block.

**Comment by dommitchell** [comment]
OK, good to know. I'd like to explore this further but will wait to see what response comes back from Yizhuan

**Comment by emanuil-tolev** [comment]
Yeah, agreed with @richard-jones's diagnosis. We can just start using another Cloud Delivery Network, it's no big deal, there's plenty of fast world-wide ones.

**Comment by emanuil-tolev** [comment]
Wow, this is ridiculous.

> Nop . It is can not be refereed to as "available" nor "reliable" .

> undependable, untrustworthy, irresponsible, fickle, capricious, irregular, erratic, unpredictable, inconstant, mutable, slippery, fragile and arbitrary might be more accurate description ( all together and also each separately ).

> China´s internet and communications regulations and laws are vigorously implemented by provincial political branches of state-owned ISPs, business companies, and organizations - each implementing it´s own censorship systems as it see fit .

> These systems are also periodically updated in relation to current political or geopolitical events. For example, in the week of a party summit , the censorship is much more strict and the systems get "hardened". Another example is the transition period between governments ( also local ) or the hosting of world wide events like the olympics, Asia games etc . again - those changes are LOCAL and PERIODICAL.

I'm going to start serving a minified version of jquery to people who *fail* to get it from the Google CDN (and additionally I might change the CDN to another good one, to try to avoid having to serve jQuery to everybody in China ourselves).

Even if it does result in somewhat increased bandwidth, I do strongly feel we should at least give it a go and simply monitor the bandwidth situation.

**Comment by dommitchell** [comment]
Maybe DOAJ needs to join CERNET? http://en.wikipedia.org/wiki/CERNET

**Comment by emanuil-tolev** [comment]
some tech notes on what to fix:

- [ ] change external JS provider so it's not Google (just make sure it's an equally good one..)
- [ ] serve jQuery and all the external JS files locally if they're not defined after trying to load them externally - there is a standard pattern for this
- [ ] serve google analytics via a server-side route (like doaj.org/backup_ga) if it's not defined after trying to load it (there is a standard way to detect that AFAIK). I'm tempted to run it through an obfuscator as well, but let's not modify code on the fly for little potential gain.
    - the page itself shouldn't break even if analytics loads so at least users should be able to search / use DOAJ, they just won't appear in G Analytics

**Comment by dommitchell** [comment]
@richard-jones I'd like to include this one in the next round of work please.

**Comment by richard-jones** [comment]
This is being partially covered by #721 - is there anything else we need to do right now?

**Comment by dommitchell** [comment]
Nope. Removing from tnm until we have an answer for #721

**Comment by dommitchell** [comment]
We would like to have DOAJ moved off the Google Java services before 15th June. Please comment.

**Comment by emanuil-tolev** [comment]
Hiya @dommitchell an update here, I'm looking into the details here, but for an overall plan, I think the one I wrote a few months ago is still pretty good: https://github.com/DOAJ/doaj/issues/517#issuecomment-71444213 .

**Comment by emanuil-tolev** [comment]
It would be nice to be able to test whether the changes are actually successful or not for your use case though. I will test using Chinese proxies, which are hard to find (in a working state). But the only way to guarantee your new addition to the team will be able to access the site is to actually have them try - maybe have them try testdoaj.cottagelabs.com before we make the changes, and after. That obviously depends on how far in the selection process you are, i.e. if you've already hired somebody we can just ask them for feedback.

**Comment by greboun** [comment]
We have actually hired xin bi  who has signed his contract
You can ask him on site accessibility
xin.bi@xjtlu.edu.cn

Tom

**Comment by dommitchell** [comment]
If Xin's institution doesn't experience problems with Google then Dom will find someone else.

GA problem will take 2nd place to the other fixes.

**Comment by emanuil-tolev** [comment]
The non-Google Analytics stuff is all rolled out now, so we can ask testers to tell us what they see and if they can access /search etc.

**Comment by dommitchell** [comment]
Feedback from the library at the Chinese National Academy of Science:
I am glad to tell you that now my library can access DOAJ successfully and the results of your tests are correct. But, as your understanding, up to that point the majority in China did not use DOAJ because of its Google-hosted javascript services.

Hurray!

**Comment by dommitchell** [comment]
More feedback:
It works well in Guangdong province.
This site works well in Shanghai as well, with out using VPN. So generally I would be rather confident to conclude it works well in China.
