### ISSUE TITLE
Numbers in form disappear in Mozilla 5

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#518]
Not sure there is much we can do about this but it's worth you knowing anyway. For some users, the hyperlinked numbers in the form disappear under an orange square. Note that this user has her station locked down by her employer so is unable to upgrade.

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

https://doaj.org/editor/suggestion/c26af5ab671249e8b4ac77158deda5f9

![orange_squares](https://cloud.githubusercontent.com/assets/5955396/5735959/81494526-9bcf-11e4-99f2-73b0403ef2c1.jpg)

**Comment by emanuil-tolev** [comment]
@dommitchell This is Google Chrome 39, a very recent version of the browser - the latest is 39.0.2171.99, and hers only has the very last digit changed to .95.

About why it says Mozilla 5:
> MozillaProductSlice. Claims to be a Mozilla based user agent, which is only true for Gecko browsers like Firefox and Netscape. For all other user agents it means 'Mozilla-compatible'. In modern browsers, this is only used for historical reasons. It has no real meaning anymore

**Comment by dommitchell** [comment]
Ah ok. Probably needs looked at then.

**Comment by emanuil-tolev** [comment]
Can't reproduce on browserstack.com using Windows 7 (as indicated by Windows NT 6.1 in the user agent string) and Chrome 39, 40 (current beta) or 41 (current development). Chrome 38 on Linux (mine) doesn't have this issue either. Unless it's an extremely specific issue down to that particular version of the browser .. which is not impossible, if it's a browser rendering bug it'll get fixed pretty quickly.

**Comment by dommitchell** [comment]
By the community you mean?

**Comment by emanuil-tolev** [comment]
> By the community you mean?

Chrome is 99% open-source, so in all likelihood the bug was going to be in the 99% bit. But if not the open source community, then google engineers..

**Comment by dommitchell** [comment]
Great!
