### ISSUE TITLE
DELETE REQUEST

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#522]
https://doaj.org/admin/admin_site_search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%222036-0967%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22_type%22:%22article%22}}]}}}}}

Please delete 243 articles.

**Comment by emanuil-tolev** [comment]
Done!

Added ISSN field. (So the query will only look in the ISSN field.) to avoid potentially deleting other things.
