### ISSUE TITLE
blank out certain questions in the csv

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#525]
If possible, don't put in default values of No policy in place and No for q13, q16, q23, q26, q35, q49. This will force users to fill them in as they're required.

RJ: unfortunately, for each of these questions, omission of a field means "No", and presence of a field means "Yes". So it is impossible to tell the difference between a deliberately missing field, and a field that has not yet been completed. That means we either stick with the current situation, or we wilfully blank out these questions in the CSV, whether they were previously populated or not (and maybe they wouldn't be?). It will be much much harder to do the same thing for the UI (thought not impossible).

Decision: we will blank out the values of these questions in the CSV

**Comment by dommitchell** [comment]
Questions to be blanked:
Does the journal have article processing charges (APCs)?
Does the journal have article submission charges?
Does the journal have a waiver policy (for developing country authors etc)?
What digital archiving policy does the journal use?
Which article identifiers does the journal use?
Please select the review process for papers
With which deposit policy directory does the journal have a registered deposit policy?
With which deposit policy directory does the journal have a registered deposit policy?

**Comment by emanuil-tolev** [comment]
> What digital archiving policy does the journal use?

I assume this should only be blanked if we have no data. If we actually have data on this in store there's no need to blank the question as no confusion can arise between "No policy" and "DOAJ doesn't know what policy there is".

**Comment by emanuil-tolev** [comment]
> > What digital archiving policy does the journal use?
> I assume this should only be blanked if we have no data. If we actually have data on this in store there's no need to blank the question as no confusion can arise between "No policy" and "DOAJ doesn't know what policy there is".

Actually this should already be blank if no policy is present, and a comma-separated list of the policies otherwise. I can't see anything in the code that would output "No policy" in the event of missing data. I'll double check with an actual spreadsheet but leaving this one alone for now.

**Comment by emanuil-tolev** [comment]
> Which article identifiers does the journal use?

Same here, this should either be empty or a list of the identifiers, no other option seems possible.

**Comment by emanuil-tolev** [comment]
> Please select the review process for papers

There isn't anything that we're doing to convert the answer to None, but I think there might be a clash between the Python programming keyword None and the human word "None" which is a valid option. Have now taken care to *blank* the question and only put "None" when it was actually selected.

**Comment by emanuil-tolev** [comment]
> With which deposit policy directory does the journal have a registered deposit policy?

Again, this should already be blank if no policy is present, and a comma-separated list of the policies otherwise. I'ma review this since either I'm missing something or the 3 questions with this problem shouldn't have wrong "default" answers, they should be correct in all cases. (blank == no info, comma-sep list otherwise)

**Comment by dommitchell** [comment]
> I assume this should only be blanked if we have no data. If we actually have data on this in store there's no need to blank the question as no confusion can arise between "No policy" and "DOAJ doesn't know what policy there is".

> Which article identifiers does the journal use?
> 
> Same here, this should either be empty or a list of the identifiers, no other option seems possible.


> With which deposit policy directory does the journal have a registered deposit policy?
> 
> Again, this should already be blank if no policy is present, and a comma-separated list of the policies otherwise.

These are all new questions if I remember correctly and every reapplication I have looked at has these filled to 'No,', 'None' or 'No policy in place' which looks to me as if the form is defaulting to it. How is this being prepopulated? Can you find an example where these questions are answered with any other value?

**Comment by emanuil-tolev** [comment]
OK, so that's what shouldn't happen. It doesn't look like the code is doing this, but clearly it seems to be (or it was) doing it at one point. I'm investigating this atm using the sheets on the test server, and I may regenerate one of the test accounts too.

**Comment by emanuil-tolev** [comment]
Hm, where is this value coming from..

**Comment by emanuil-tolev** [comment]
Alright, got it, so the crosswalk from an application record into an application WEB form puts that in. So when "No policy in place" appears in the CSV it needs to be specifically blanked out. Same for the other 2 cases, except it's just the word None then. Fixing now.

**Comment by emanuil-tolev** [comment]
> Does the journal have article processing charges (APCs)?
> Does the journal have article submission charges?
> Does the journal have a waiver policy (for developing country authors etc)?

Note:
1/ I'll only blank this if it's a No. A Yes is unambiguous here, and it will look quite strange to have an APC currency and a blank field for the main question.

* * *

Note specifically for these:

> Does the journal have article processing charges (APCs)?
> Does the journal have article submission charges?

2/ Not blanking the associated URL and currency fields, there's no confusing default values that could go in there and make our lives difficult.

**Comment by emanuil-tolev** [comment]
> Please select the review process for papers

This one's been fixed along the way, latest sheet correctly list a blank.

**Comment by emanuil-tolev** [comment]
> Does the journal have article processing charges (APCs)?
> Does the journal have article submission charges?

Er, all the CSVs have Yes for all the journals here. I'm going to switch one of the test journals to No and regenerate its reapplication.

**Comment by emanuil-tolev** [comment]
> Er, all the CSVs have Yes for all the journals here. I'm going to switch one of the test journals to No and regenerate its reapplication.

Oopsie. Bug caught. They're all set to Yes even when the DOAJ (and its user interface) clearly state the journal has no processing charges.

**Comment by emanuil-tolev** [comment]
> Oopsie. Bug caught. They're all set to Yes even when the DOAJ (and its user interface) clearly state the journal has no processing charges.

Because "False" == True ;). obj2form returns strings, not python objects.

**Comment by emanuil-tolev** [comment]
I have regenerated the reapps on the test server, but noticed that actually more questions had this problem (like, it doesn't make sense to say that no journals embed the license info in their pages - we just don't know, let's not assume ;)). So as soon as #528 is merged and deploys, I'll mark ready for review again.

**Comment by emanuil-tolev** [comment]
This was approved and has been deployed to live and the reapp generated, so closing this issue.
