### ISSUE TITLE
Browser Compatibility: Search results not being returned

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#53]
Same symptoms as last time (we discussed it briefly on our last call when you said I should log all bugs anyway). Something to do with IE you supposed. If prevalent, worth adding something to FAQs?

See screenshot. Email from customer:

The search facility does not appear to be working.  I’ve tried a variety of searches and no results are retrieved – the following screen appears after running a search.  
![image001](https://f.cloud.github.com/assets/5955396/1832598/9866427a-73b9-11e3-9a61-61f9af237098.png)

**Comment by emanuil-tolev** [comment]
Quite possibly .. I've no idea what they do to passing web requests as they go through the firewall, or how that IE9 was modified. It should definitely work in IE9, I'll give it a quick try this week.

**Comment by emanuil-tolev** [comment]
I've tested on browserstack.com, IE9 works fine. This is some kind of problem related to access from China again. @dommitchell add any further details you get (from this person) to #517 .
