### ISSUE TITLE
[u'...'] appearing on journal homepages

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#531]
https://doaj.org/toc/0d518f1f25fa4de8a94bdc9345ac9897

Archiving Policies: CLOCKSS, Portico, [u'A national library', u'British Library']

**Comment by dommitchell** [comment]
@richard-jones Just raising the profile of this one as I have just seen it in test too: http://test.doaj.cottagelabs.com/toc/94abf8e0c1414777b726fab5747d80aa

Archiving Policies: [u'Other', u'CrossRef'] (http://www.jpsionline.com/archive.php)

**Comment by richard-jones** [comment]
Fix applied and PR made - should be rolled out to live shortly.

**Comment by Steven-Eardley** [comment]
On live now.
