### ISSUE TITLE
4 journals don't have an owner set?

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#532]
Found out during reapplication init (still in progress). Need to go back and investigate which ones. And why.

**Comment by richard-jones** [comment]
@emanuil-tolev - is this still active?

**Comment by emanuil-tolev** [comment]
Actually there's 1679 such journals: https://doajgate.cottagelabs.com/doaj/journal/_search?q=_missing_:admin.owner

But yeah, there are 4 which are in DOAJ with a missing owner field: https://doajgate.cottagelabs.com/doaj/journal/_search?q=_missing_:admin.owner%20AND%20admin.in_doaj:true

**Comment by richard-jones** [comment]
It looks like there's only one of these left now:

https://doaj.org/admin/admin_site_search?source=%7B%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%22df03af1d5dea472eb05a20ad128d0344%22%2C%22default_operator%22%3A%22AND%22%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D

@greboun - assigning to you for a decision as to what should be done.

**Comment by dommitchell** [comment]
No longer an issue. Journal withdrawn from DOAJ as it failed the reapplication process.
