### ISSUE TITLE
Remove some values from the public results display

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#534]
REMOVE:
X Provider
X Date added to DOAJ
X Journal Country,
X Started publishing Open Access content in:

**Comment by richard-jones** [comment]
I notice that Journal Country isn't a field, but Country of publisher is, but is covered by the other PR.  @dommitchell - let us know if you meant something different.  Otherwise all looks good, will merge in a moment.

**Comment by dommitchell** [comment]
> I've also removed the field labelled 'Stopped publishing Open Access content in' because I thought that made sense in light of the above instructions

This was correct.

> Journal Country isn't a field, but Country of publisher is, but is covered by the other PR.

Yeh, sorry this one's a bit old. The other PR covers it.

Looking good on test.

**Comment by dommitchell** [comment]
Is there any way we can change 'Journal Country' in the application view to be 'Country of publisher' as well?

http://test.doaj.cottagelabs.com/admin/journals?source={%22query%22:{%22match_all%22:{}}}

**Comment by richard-jones** [comment]
@Steven-Eardley - do you want to look at that last tweak, or shall I?

**Comment by Steven-Eardley** [comment]
I'll get right on it.

**Comment by Steven-Eardley** [comment]
@dommitchell Just to clarify -

There are various places the string 'Journal Country' remains.
* admin_journals_and_articles.js - the administrative site search
* associate_journals.js - editor
* associate_suggestions.js - editor
* group_journals.js - editor
* group_suggestions.js - editor
* journals.js - admin
* reapplications.js - admin
* suggestions.js - publisher

Do you only want the text change in ```reapplications.js``` and ```journals.js``` as indicated above, or in more of them?

**Comment by dommitchell** [comment]
I'd like to change them all please. Sorry, I hadn't accounted for all the diff instances.

**Comment by Steven-Eardley** [comment]
@dommitchell this can be reviewed on the test server now.

**Comment by dommitchell** [comment]
Looking good!
