### ISSUE TITLE
Shortened facetview display for journals

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#537]
In the search interface, produce a journal-specific short-view, similar to the article view #538

**Comment by dommitchell** [comment]
@richard-jones what's this one?

**Comment by richard-jones** [comment]
Just updated the description - there will be different views for articles and journals - this will allow us to customise to the specific data each one holds, but also help make a clearer distinction for the user when browsing.

**Comment by richard-jones** [comment]
Superseded by #161
