### ISSUE TITLE
New/updated facets required in Public Search interface

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#539]
- [x] change facet label 'Publication charges' to 'Article processing charges (APCs)'
- [x] change facet label 'Journal language' to 'Language of full text'

*Natural state*
- Journals or articles: Journals, Articles. Fixed ordering.
- Subject (?) - unsure of how this one behaves when we add the subject browser. Do we remove this altogether? Can we discuss?
- Article processing charges (APCs): Yes, No
- Journal license: CC BY, CC BY-NC, CC BY-NC-ND, CC BY-NC-SA, CC BY-SA, CC BY-ND, None, Not CC-like, Publisher's own
- Publisher: publisher names in full. Default sorting: descending numeric order
- Country of publisher: country names in full, not in code. Default sorting: descending numeric order
- Peer review: Editorial review, peer review, blind peer review, double blind peer review, open peer review
- Full text format: PDF, HTML, ePUB, XML. Default sorting: descending numeric order

*'Journals' selected*
- Subject (?)
- The Seal: Yes, No
- Article processing charges (APCs)
- Journal license
- Publisher
- Country of publisher
- Language of full text: languages in full, no codes.
- Peer review
- Article identifiers: None, DOI, Handle, ARK. Default sorting: descending numerical order.
- Waiver policy: Yes, No
- Archiving Policy: Yes, No
- Plagiarism policy: Yes, No
- Machine-readable license: Yes, No
- Deposit policy: Yes, No
- Year journal added to DOAJ: 2015, 2014, 2013, 2012... Default sorting: descending chronological order.

*'Articles' selected*
- Subject (?)
- Journal title
- Article processing charges (APCs)
- Journal license
- Publisher
- Language of full text
- Peer review
- Archiving policy
- Machine-readable license
- Year of publication (articles): 2015, 2014, 2013, 2012... Default sorting: descending chronological order.

- [x] The addition of these facets presents us with a usability problem. We would like to install a [More/Less] button that would Reveal/Hide further facets.

**Comment by dommitchell** [comment]
Note to self: affiliation

**Comment by richard-jones** [comment]
Some comments on the facets as I work through them the first time (will update as I go):

* APC: Yes/No - this is now a bit tricky, as there is no "there is an apc" field; we know there is an APC based on whether there is an apc_url, but this can't be trivially faceted on.  We would probably want to add to the "index" portion of the object an APC Yes/No field.

**Comment by emanuil-tolev** [comment]
From meeting: overall support for showing different facets for journals and articles, with fewer facets shown at initial search.

**Comment by richard-jones** [comment]
I have an alternative proposal for the layout of the facets.  It is motivated by the discussion we had earlier about performance and user behaviour.  A lot of the facets listed in the main issue, while clear properties of a journal/article, may not actually be useful for end-user discovery of content.  Will users, for example, really search for journals based on whether they have a waiver policy or not?

I suggest instead sticking to the big things that identify a journal/article, and begin by showing users only aspects which are relevant to both, and then show them additional fields which are specific to a type if that type is selected:

Initially:
* Journal vs Article: open by default
* Subject
* Journal licence
* Publisher
* Country of publication
* Language of fulltext

Journal selected:
* Peer review
* Year added to DOAJ
* The Seal (though note this is not yet present in the data)
* APC (see note above, though)

Article selected:
* Journal Title
* Year Published

If a user has navigated down to, say, a Journal with a specific peer-review type, and then they remove the Journal filter, then we would also then remove the peer-review filter.

@dommitchell - I'm happy to have a go at doing this this week, to see how it looks; let me know what you think.

**Comment by richard-jones** [comment]
I've done an implementation of my proposal above, which will be ready for review once the test server is ready and my PR merged.

**Comment by dommitchell** [comment]
Feedback:

> this is now a bit tricky, as there is no "there is an apc" field; we know there is an APC based on whether there is an apc_url, but this can't be trivially faceted on. We would probably want to add to the "index" portion of the object an APC Yes/No field.

1) How difficult is this? We definitely need APCs as a facet

2) Change labels in Journals vs Articles facet, 'Journal' 'Article' to 'Journals' 'Articles'
3) Subject facet: how does this interact with the new subject browser? 
4) Change 'Fulltext language' to 'Full Text language'
5) Translate all language codes into full labels, eg EN (23)
6) In peer review, 46 results are blank (with 'Journals' selected). Where is that coming from?

**Comment by richard-jones** [comment]
Responses where necessary:

1) How difficult is this? We definitely need APCs as a facet

No problem, but I need to run a batch migrate task over the data to make it work, so I need to write that code and run it before you'll be able to see anything.

3) Subject facet: how does this interact with the new subject browser? 

The subject browser will just construct a search for that subject and direct the user to the search page, so the subject facet will be pre-selected for them when they arrive.  They will then be able to just carry on searching as normal.

5) Translate all language codes into full labels, eg EN (23)

Are you seeing a lot of these?  I thought they had all been translated already at the index level, so if they haven't all been translated, there may be a bug.  I'll look into it.

6) In peer review, 46 results are blank (with 'Journals' selected). Where is that coming from?

It seems there are 46 records with blank values for that field - not sure why that would be, though.  An example of one is 0f94e962a557406d8fad573ff6220d75, which I need to look at in the test index ( @emanuil-tolev - how do I go about doing that in the new infrastructure?)

**Comment by emanuil-tolev** [comment]
> ( @emanuil-tolev - how do I go about doing that in the new infrastructure?)

mail me your ip, I'll mail you a url. It'll be of the form of <cluster gateway ip>:9200 and obviously you can edit your /etc/hosts to alias the IP to a name, make it more memory-friendly.

**Comment by dommitchell** [comment]
Feedback on the facets present under the current treatment. Questions really.
*'Journals' selected*
We're concerned that the missing facets essentially mean that this information cannot be surfaced in any other easy way. I wonder if there is a way to allow the user to choose to load/display more facets themselves? This way, there wouldn't be such a problem displaying so many? Secondly, are in there in fact other ways that someone could surface this information? We're collecting it so it seems a wasted opportunity to not allow people to filter on it. (I agree that we don't know whether people actually want this or not.) Would this sort of info be pullable via the CSV or an API?

*'Articles' selected*
This is basically OK as it's not far from my original request. Country of publisher can be removed.
Can you make the list follow the order I put above? ie 
Subject
Journal title
Article processing charges (APCs)
Journal license
Publisher
Language of full text
Year of publication (articles): 

/Note to self/
Under the current treatment, the current pieces of data are still missing:
Article identifiers: None, DOI, Handle, ARK. Default sorting: descending numerical order.
Waiver policy: Yes, No
Archiving Policy: Yes, No
Plagiarism policy: Yes, No
Machine-readable license: Yes, No
Deposit policy: Yes, No


> 5) Translate all language codes into full labels, 
> 
> Are you seeing a lot of these?

Yes, in the Full Text language facet. 
EN (582)
ES (134)
PT (74) etc

**Comment by richard-jones** [comment]
6) In peer review, 46 results are blank (with 'Journals' selected). Where is that coming from?

I've not got a definitive answer on this, but basically it is when there is a blank value for that field.  That could possibly happen when someone edits a Journal in the public dataset and checks the "don't validate" box.

I could prevent empty strings from being offered in facets, if that is the best solution?

**Comment by richard-jones** [comment]
> We're concerned that the missing facets essentially mean that this information cannot be surfaced in
> any other easy way. I wonder if there is a way to allow the user to choose to load/display more facets 
> themselves? 

The information will be available on the ToC page, so the information is certainly not for nothing.

Theoretically we could allow the user to switch to an "advanced" mode, which has more facets, but experience tells us that users rarely use advanced modes, so unless there's a compelling reason to do so I wouldn't go this way.

> This way, there wouldn't be such a problem displaying so many? 

The queries would still be expensive, but if there were less of them that would be much better, yes.

> Secondly, are in there in fact other ways that someone could surface this information? 

Via the ToC page seems the best place.

> We're collecting it so it seems a wasted opportunity to not allow people to filter on it. (I agree that we
> don't know whether people actually want this or not.) 

It depends why you are collecting it and what your search interface is attempting to provide.  There are many things that we could facet on, but just because we could doesn't mean we should :)

> Would this sort of info be pullable via the CSV or an API?

It's a good point that updates to the CSV are not included in this PVOD project.  But yes, that would definitely be a place to put them.  Also, in any future API all this information would be available.

**Comment by richard-jones** [comment]
Otherwise, I've made a bunch of tweaks based on the above which will be ready for review at next PR

**Comment by richard-jones** [comment]
Question about Country of Publisher: you say this can be removed, but under the section on "Article selected".  Does this mean it should only appear when Journal is selected?  Or can it be removed in total?

**Comment by dommitchell** [comment]
> I could prevent empty strings from being offered in facets, if that is the best solution?

Yes, please!

> Question about Country of Publisher: you say this can be removed, but under the section on "Article selected". Does this mean it should only appear when Journal is selected? Or can it be removed in total?

Yes, should only appear when Journal is selected

**Comment by dommitchell** [comment]
Decision: please add 1 more facet to the journal level: Archiving. The rest is good as is and can be made live.

How easy will it be to add new facets in the future?

**Comment by dommitchell** [comment]
Looking great. Nearly there.

- [ ] please add 1 more facet to the journal level: Archiving. The rest is good as is and can be made live. We'll live without Waiver policy, Plagiarism policy, Machine-readable license, Deposit policy. How easy will it be to add new facets in the future?

- [ ] change APCs to Article processing charges (APCs)

- [ ] prevent empty strings from being offered in facets

- [ ] Translate all language codes into full labels, eg EN (23)

**Comment by richard-jones** [comment]
I've added the new facet and changed the APC display label in the next UI Tweaks PR.

The empty strings should already be omitted from the display - which facets are you seeing these in, @dommitchell ?  

Language codes should have been translated already, seems to have been a problem with a migrate script - no more changes necessary to fix this, just need to check why the migrate didn't work correctly.

And to answer your question:

> How easy will it be to add new facets in the future?

It depends on what the facet is over.  If it's over a piece of data that is in the model, then adding new facets is quick and easy, but if it is over some information that can be inferred from the model, then data migration may be necessary to set up the index to provide the data for the facet.  To clarify, the APC is a good example:

The model contains information about the APC: the amount, currency, and reference URL.  To provide a facet over, say, the currencies of APCs is therefore easy.  But, to say whether a journal has an APC or not can only be inferred by whether there is an APC field or not in the data, and you can't build a facet over that.  Instead we have to run a task which populates a bit of the model (specifically designed for the purposes of the search interfac)e with a flag to say whether APC is set or not, so that we can then build a facet over that flag.

**Comment by dommitchell** [comment]
> The empty strings should already be omitted from the display - which facets are you seeing these in, @dommitchell ?

6) In peer review, 46 results are blank (with 'Journals' selected). Where is that coming from?
![peer](https://cloud.githubusercontent.com/assets/5955396/7019654/a580e99c-dd12-11e4-9834-5175c9a8eb6a.jpg)

**Comment by richard-jones** [comment]
ok, something weird is up with the test server - you and I are seeing
different things; we'll cover it in the meeting this morning.

On 7 April 2015 at 09:41, dommitchell <notifications@github.com> wrote:

> The empty strings should already be omitted from the display - which
> facets are you seeing these in, @dommitchell
> <https://github.com/dommitchell> ?
>
> 6) In peer review, 46 results are blank (with 'Journals' selected). Where
> is that coming from?
> [image: peer]
> <https://cloud.githubusercontent.com/assets/5955396/7019654/a580e99c-dd12-11e4-9834-5175c9a8eb6a.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DOAJ/doaj/issues/539#issuecomment-90465380>.
>



-- 

Richard Jones,

Founder, Cottage Labs
t: @richard_d_jones, @cottagelabs
w: http://cottagelabs.com

**Comment by dommitchell** [comment]
Still seeing language codes under full text language for journals and articles

![codes](https://cloud.githubusercontent.com/assets/5955396/7022369/5db60016-dd2b-11e4-9430-73c4ea9d1d79.jpg)

https://doaj.cottagelabs.com/search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22journal%22}}%2C{%22term%22%3A{%22index.language.exact%22%3A%22EN%22}}]}}%2C%22query%22%3A{%22match_all%22%3A{}}}}%2C%22from%22%3A0%2C%22size%22%3A10}


> It depends on what the facet is over. If it's over a piece of data that is in the model, then adding new facets is quick and easy,

Yep, I was thinking specifically of the ones we are leaving out at this time. Sounds like they will be easy to add though.

**Comment by richard-jones** [comment]
The language codes are a symptom of a problem with an upgrade script that we're currently working on under #637

**Comment by dommitchell** [comment]
Great! Closing.
