### ISSUE TITLE
OAI DC metadata review

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#542]
- [x] repoint dc:identifier to journal toc
- [x] repoint dc:identifier to article page (which doesn't yet exist)
- [x] On article OAI data, put link to journal TOC page in dc:relation

**Comment by emanuil-tolev** [comment]
Simple / Basic DublinCore - just check if the 15 fields are populated appropriately with the data we have

**Comment by emanuil-tolev** [comment]
- [ ] Look into specifying vocabulary for where Subject is coming from (currently LCC). Somehow put this info ( http://dublincore.org/documents/dcmi-terms/#H4 ) into the scheme
- [ ] Add keywords to Subject (and tag if possible to show they're human-sourced non-formal)

**Comment by emanuil-tolev** [comment]
Year guessing algorithm may break currently, needs to deal with 2 chars that are not digits (@emanuil-tolev writing it)

**Comment by emanuil-tolev** [comment]
Maybe we should tell people about the changes on the FAQ site and perhaps a blog item. Perhaps even in advance (*gasp*). They're not big changes at all but if anybody's relying on anything (and OAI-PMH is a public interface) it'll change under their feet obviously.

**Comment by dommitchell** [comment]
@emanuil-tolev  Can you review this page http://doaj.org/features and let me know if it needs any changes after your work here?

**Comment by richard-jones** [comment]
@dommitchell - not sure if you've had a chance to review this yet, but I believe the new DC metadata is all now available, so you should be able to check it at (for example):

https://doaj.cottagelabs.com/oai?verb=ListRecords&metadataPrefix=oai_dc

@emanuil-tolev - do you have any outstanding tasks around this still to do?

**Comment by dommitchell** [comment]
Again, not sure what I am looking at. Would be good to go through these two on a Hangout. Also,

> Can you review this page http://doaj.org/features and let me know if it needs any changes after your work here?

**Comment by richard-jones** [comment]
If you go to that link above you should see the OAI Dublin Core output - just check it over to see if the metadata in the XML looks reasonable.

Otherwise, yes, we can talk through on Monday.

**Comment by dommitchell** [comment]
Yes, looks good. Am happy to close this but assigning to @emanuil-tolev just in case this needs changes to /features.

**Comment by emanuil-tolev** [comment]
> Yes, looks good. Am happy to close this but assigning to @emanuil-tolev just in case this needs changes to /features.

It did, I'll assign back for docs review after PR is merged.

**Comment by richard-jones** [comment]
You should be able to review the text on the /features page shortly

**Comment by dommitchell** [comment]
@richard-jones are the text changes in?

**Comment by dommitchell** [comment]
Ignore me. Seen them. Closing.

**Comment by emanuil-tolev** [comment]
> @richard-jones are the text changes in?

Yeah, quite a few changes visible on https://doaj.cottagelabs.com/features ?

**Comment by dommitchell** [comment]
Yup. Just looking at this now. 

@emanuil-tolev Shouldn't 'Revision history - Article OAI-PMH DOAJ format' include the recent change of adding the doajarticle tag back in?

**Comment by emanuil-tolev** [comment]
> Shouldn't 'Revision history - Article OAI-PMH DOAJ format' include the recent change of adding the doajarticle tag back in?

Ah, no. It's actually the first time it's ever been available. That section wasn't there before, that's the bulk of the new docs I added wrt #180 . The revision history's wrong :). It should say "20 April 2015 Initial release". I'll update that (and update 13 april to be 20 april everywhere in the introduced history)

**Comment by emanuil-tolev** [comment]
updates to the history should be in shortly

**Comment by dommitchell** [comment]
Great. Perfect!
