### ISSUE TITLE
Upgrade facetview2 for ES 1.x

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#543]
probably this will work out of the box, but will need a bit of testing

**Comment by Steven-Eardley** [comment]
I think it might require a wee bit more work - some of the notation has changed, e.g. facets / aggregations.

**Comment by richard-jones** [comment]
First signs look good.  I have set up an fv2 locally running over a 1.4 ES and everything seems to behaving.  Next I need to make a (partial) clone of the DOAJ data in my local 1.4 system so that I can check everything is working over our data as it currently stands.
