### ISSUE TITLE
Email character limit too short in Users

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#545]
We have email addresses of more than 35 characters. Please increase this limit to 45.

![email](https://cloud.githubusercontent.com/assets/5955396/5915481/8ba137a4-a606-11e4-84a8-5180944b0e56.jpg)

**Comment by dommitchell** [comment]
This should be a quick and easy change

**Comment by Steven-Eardley** [comment]
45 is also quite an arbitrary cut-off. I don't see why we shouldn't allow the maximum an email address could be - 254 characters. Unless @emanuil-tolev knows from when it was written?

**Comment by dommitchell** [comment]
@Steven-Eardley sounds good to me as long as no-one else objects

**Comment by emanuil-tolev** [comment]
@Steven-Eardley's work on this has been deployed just now.
