### ISSUE TITLE
All reapplications have the same Applied date

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#547]
http://bit.ly/1y2PHtt

Is it the Last updated date we should be sorting on if we want to reach those journals that reapplied first?

Shouldn't the Date applied date be generated when they submit there reapplication?

**Comment by richard-jones** [comment]
Date Applied is the "created date", so it is generated when the record is created, which is the date the reapplication began.

**Comment by richard-jones** [comment]
This may relate to our discussion about provenance data from yesterday.

**Comment by dommitchell** [comment]
OK, I understand now. I think 'Date submitted' would be more helpful here. Yes, maybe a provenance thing.
