### ISSUE TITLE
Fine tune searching on ISSN: ISSN should be treated as a single entity

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#550]
A search on ISSN 1818-1023 returns 142 articles
https://doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%221818-1023%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:%5B{%22term%22:{%22_type%22:%22article%22}}%5D}}}}}

I know that the publisher, Instituto de la Familia Guatemala, of 1818-1023 has published 137 articles only. If I select one of the other publishers, IUCN Otter Specialist Group, I see that the ISSN there is 1023-9030. This suggests to me that the ISSN is being broken into two by the dash maybe? This shouldn't happen.

**Comment by richard-jones** [comment]
In the default search box anything you enter in there is interpreted as non-specific text, analysed and searched across the whole dataset.  So the text (issn in this case) will be tokenised (broken on the "-") and matched across all searchable fields in all documents, so actually if "1818" appears somewhere else (say the article page number), it will also return.

If you want to explicitly search only ISSNs exactly, select "ISSN" from the pull-down next to the search box, and it will behave exactly as you want it to (not tokenising, only looking in the ISSN field).
