### ISSUE TITLE
Request to delete articles: Revista Internacional de Psicología

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#551]
Please delete all articles from Revista Internacional de Psicología

http://bit.ly/1uzXjSS

**Comment by emanuil-tolev** [comment]
Done. Dom, I clicked on the "ISSN" field first. That way 137 were deleted. If you just search for the ISSN across all metadata, 142 show up. Let me know if you need the other 5 deleted too (or you could delete using admin interface).
