### ISSUE TITLE
Add new sponsor logo

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#552]
Linked to http://www.qscience.com

![qscience](https://cloud.githubusercontent.com/assets/5955396/5935857/90df882c-a6df-11e4-96cf-e102eef3057c.gif)

And update the static pages, please.

**Comment by dommitchell** [comment]
@emanuil-tolev can you do this once you are back from the conf?

**Comment by emanuil-tolev** [comment]
yep sure (am back but due to start a few meetings so may be rolled out a bit later today)

**Comment by Steven-Eardley** [comment]
Ready for review on live, including static changes.
