### ISSUE TITLE
New OpenURL endpoint

### ISSUE THREAD

**Issue by Steven-Eardley** [DOAJ/doaj#558]
Create endpoint for OpenURL at ```/openurl```. 
* This should give the request string to the parser (see #555) for analysis.
  - To handle the legacy 0.1 syntax, hand off to a function (#556) to translate into 1.0 syntax and give a 301 (permanent redirect) response. 
* Using the object from the parser, query the index (#557), and display page of result.
* If no result or malformed URL, return 400 (bad request).

**Comment by richard-jones** [comment]
@richard-jones to review

**Comment by richard-jones** [comment]
I've now carried out a thorough review of this and made a few tweaks, mostly around preventing responses where the request didn't provide enough information to warrant one.

I've also prepped it for integration with the new continuations-aware ToC pages

**Comment by richard-jones** [comment]
@Steven-Eardley assigning back to you to close off when you are ready.

I did open an issue based on my review #640 which we should discuss, and there's still the documentation outstanding.

**Comment by Steven-Eardley** [comment]
This is fulfilled; any problems or enhancements with openurl will have their own issue.
