### ISSUE TITLE
OpenURL documentation

### ISSUE THREAD

**Issue by Steven-Eardley** [DOAJ/doaj#560]
Documentation for OpenURL work as required.
* How-to for using OpenURL 1.0 with DOAJ

**Comment by Steven-Eardley** [comment]
Rather than writing a tutorial on how to use OpenURL - which while interesting might be irrelevant to most users of this service - the documentation in ```openurl/help``` is more geared towards background info and taking steps to get results.

**Comment by Steven-Eardley** [comment]
Is there anything more you'd like to add? Please review at http://testdoaj.cottagelabs.com/openurl/help

The file is at ```portality/templates/openurl/help``` and it can be linked to via 
```<a href="{{ url_for('openurl.help') }}">OpenURL help</a>```

**Comment by dommitchell** [comment]
Looks good! Closing.
