### ISSUE TITLE
Update link at top of public application form

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#562]
I can't find the file to update this myself. Can you change the link under 'created a spreadsheet version of the form' from http://doaj.org/faq#application to http://doaj.org/publishers#application

Also, let me know where I can access this please.

**Comment by dommitchell** [comment]
Sorry, I need to bump this up in priority.

**Comment by dommitchell** [comment]
https://github.com/DOAJ/doaj/blob/static_pages/portality/templates/formcontext/public_application_form.html

**Comment by emanuil-tolev** [comment]
@dommitchell @Steven-Eardley has made a hotfix for this. We'll release it in 15 min.

**Comment by Steven-Eardley** [comment]
This hotfix is rolled out to live.
