### ISSUE TITLE
Support DOAJ button in IE is grey

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#570]
Can you change the support doaj button to orange? It's invisible as it is now.
Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; MASMJS; rv:11.0) like Gecko

![button](https://cloud.githubusercontent.com/assets/5955396/6095529/19b6b2c2-af61-11e4-82d8-bff0dee9c3fb.jpg)

**Comment by richard-jones** [comment]
huh, weird.  Looks fine on my browser.  @emanuil-tolev can you replicate on browserstack?

**Comment by emanuil-tolev** [comment]
yep, will check now

**Comment by emanuil-tolev** [comment]
yeah, it's broken, I'll submit a hotfix in a sec

**Comment by emanuil-tolev** [comment]
And by "submit" I meant I'll deploy a hotfix..

Should be OK now @dommitchell .

**Comment by dommitchell** [comment]
Yup, fixed!
