### ISSUE TITLE
Add new status to Associate Editor workflow

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#572]
Add new Application status, for all roles, 'On Hold'. Visible for applications and reapplications.

**Comment by dommitchell** [comment]
Yep. All good.!

**Comment by dommitchell** [comment]
Sorry. Can you make it 'invisible' for Associate Editors so it doesn't appear in their list?

**Comment by richard-jones** [comment]
Done for next PR

**Comment by dommitchell** [comment]
Great! Closing.
