### ISSUE TITLE
Unable to delete article

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#573]
Article appears on journal ToC page: https://doaj.org/toc/ed39a6dfebf2414c8557c246898ab9a3/16-1 (Presentación, Diana Lan) but is not available in Journal and Articles Admin view to delet: http://bit.ly/1CdhlWj

Can you remove it for us?

**Comment by emanuil-tolev** [comment]
This is the article: http://bit.ly/1vC6vMG

I found it by putting in double quote, the full-text url to the pdf listed on the toc page, followed by another double quote into the omni-search box.

```"http://media.wix.com/ugd/59a6db_fd0ce8f631cf43ad9d1f45ed669946d8.pdf"```

**Comment by emanuil-tolev** [comment]
Reason it was not appearing is maybe because of the ISSN you had specified in your query. The only one in the article record is 1853-4392.

**Comment by emanuil-tolev** [comment]
@dommitchell forgot to say I didn't delete it - since I could find it I thought it was better you tried to delete it, make sure it all works :).

**Comment by dommitchell** [comment]
Thanks @emanuil-tolev !
@richard-jones is this task already done #451 ? How can the publisher have uploaded an article with only one ISSN when the journal record has two present?
