### ISSUE TITLE
Questions 14 and 18, make them optional for AssEds

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#574]
Can you make questions 14 and 18 optional? It's causing problems.

**Comment by emanuil-tolev** [comment]
Ouch. In the spreadsheets too, I imagine?

**Comment by dommitchell** [comment]
@emanuil-tolev I don't think so (but am not sure) because the publishers have to submit the CSV and therefore have the chance to add the information to the web sites and provide the URLs BEFOREHAND.

This problem is caused specifically by those applications that were submitted between March 2014 and when we added the two new questions in January. Because I made the URL fields compulsory, people are unable to save the applications without entering something. They might indeed be waiting on the publisher to add that information to the sites and then get back to them with the URLs. But they can't save the form.

**Comment by emanuil-tolev** [comment]
> people are unable to save the applications without entering something

You mean publisher staff or our editors?

**Comment by dommitchell** [comment]
Specifically AssEds. Sorry. Should have been clearer. See #529 which basically the hotfix that I requested

**Comment by emanuil-tolev** [comment]
Aha! So #529 did it for managing editors but it is now needed for associate editors (and normal editors) as well /cc @richard-jones .

**Comment by richard-jones** [comment]
Ok, so just to be clear, so I do the right thing here:

1. remains required in public application form, publisher's reapplication form, publishers CSV
2. Is not required for managing editors, editors and associate editors

@dommitchell - if you could confirm, I'll get on it.

**Comment by dommitchell** [comment]
@richard-jones that is correct. Thank you!

**Comment by richard-jones** [comment]
Ok, fixed and added to PR - should be rolled out to live shortly.

**Comment by Steven-Eardley** [comment]
on live
