### ISSUE TITLE
How many journals/applications have submission charges?

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#577]
Can you run a query to tell me how many journals and applications have submissions charges? (Question 17 on application form)

**Comment by emanuil-tolev** [comment]
In Public View of the Data there will be a review of facets and APC should be reviewed, so you'll get a count soon(ish) I hope! Currently a bit hard since both the old and new APC structure exist.

**Comment by dommitchell** [comment]
@emanuil-tolev this isn't APCs but submission charges, which is a new question. APCs is question 13.

**Comment by emanuil-tolev** [comment]
Ah, hm. Is a facet for this planned in this project?

**Comment by dommitchell** [comment]
Nope.

**Comment by dommitchell** [comment]
Closing

**Comment by emanuil-tolev** [comment]
You can see this for live journals at https://doaj.org/search?source=%7B%22query%22%3A%7B%22filtered%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22term%22%3A%7B%22_type%22%3A%22journal%22%7D%7D%5D%7D%7D%2C%22query%22%3A%7B%22match_all%22%3A%7B%7D%7D%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D (APCs facet), and similarly for applications. Did introducing those facets answer your original question @dommitchell or does the UI still not contain enough data to answer it? (and I've misunderstood it in that case)
