### ISSUE TITLE
Publisher CSV stuck in submission

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#578]
Account 14248220.

CSV uploaded stuck at In submission

![mdpi](https://cloud.githubusercontent.com/assets/5955396/6210555/397642be-b5d1-11e4-8a38-91b1a8bb92da.png)

**Comment by emanuil-tolev** [comment]
The task wasn't running when the new server was set up, slight oversight. Corrected now, it should work. We have received 7 CSV upload attempts (could be all from the same publisher, hence "attempts"). These should all be processed now, in order of uploading I believe.

**Comment by emanuil-tolev** [comment]
Hm, all of them seem to have failed with various errors. Emails would have been sent out now.
