### ISSUE TITLE
Generate query for 'no edgroup'

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#580]
Please generate a list of all applications received, with status 'pending' or 'in progress' that have not been assigned to an editorial group.

What format will the list be in? Just thinking about how useable it will be for going through the records in DOAJ

**Comment by dommitchell** [comment]
@richard-jones could you do this one? I think you said it was fairly straight forward? It would help us tackle our current backlog

**Comment by richard-jones** [comment]
Generated and sent over

**Comment by dommitchell** [comment]
Thanks! Are they in any order?

**Comment by dommitchell** [comment]
Closing.
