### ISSUE TITLE
Keywords duplicated as Subjects in Applications

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#581]
Not sure this has always been like this but 'Keywords' in application records are duplicated as 'Subjects'. eg: https://doaj.org/admin/applications?source={%22query%22:{%22match_all%22:{}},%22sort%22:%5B{%22suggestion.suggested_on.exact%22:{%22order%22:%22desc%22}}%5D}

Applications don't have Subjects assigned so these values are being erroneously generated

**Comment by dommitchell** [comment]
@richard-jones any thoughts on this one?

**Comment by richard-jones** [comment]
I guess some applications do have subjects, as they are assigned by editors prior to conversion to a journal?

But either way, yes, this is weird - we are going to change all these interfaces in PVOD, so I'll add that to that milestone, and we'll resolve it as we go along, if it's not too urgent?

**Comment by dommitchell** [comment]
> I guess some applications do have subjects, as they are assigned by editors prior to conversion to a journal?

@richard-jones  Do you mean that subjects should be added AFTER an application is accepted as a journal?

**Comment by richard-jones** [comment]
No no, I mean that while something is an application, the subjects get set, so there will be some applications that have subjects and some that don't.

**Comment by richard-jones** [comment]
Across the board there has been some confusion between Subjects, Keywords and Classifications.  I have done the following to make things clearer:

* In the public search interface, the term "Subject" is used, and the values of this field are the LCC subject classification names, as a list.  There is no mention of LCC itself, though.
* In all other search interfaces, the term "Classification" is used, and the values of this field are the LCC subject classification names, as a list.  In addition, there is another field "Keywords" which contains all the publisher-provided keywords, as a list.

Hopefully this is much clearer, and is now consistent across all interfaces.

**Comment by dommitchell** [comment]
@richard-jones can you go through this with me?

**Comment by dommitchell** [comment]
@richard-jones so to go back to my original question, the changes you made on 12 Mar should take care of this? 

I'm looking at https://doaj.cottagelabs.com/admin/applications?source={%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22\%22International%20Journal%20of%20Women%27s%20Health%20and%20Reproduction%20Sciences\%22%22%2C%22default_operator%22%3A%22OR%22}}%2C%22from%22%3A0%2C%22size%22%3A10} compared to https://doaj.org/admin/applications?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%222330-4456%22,%22default_field%22:%22index.issn.exact%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22admin.application_status.exact%22:%22pending%22}}]}}}},%22sort%22:[{%22suggestion.suggested_on.exact%22:{%22order%22:%22desc%22}}]} and I think so but san you confirm?

**Comment by richard-jones** [comment]
Yup, that's right.  So in the new one you have "Classifications" and "Keywords" which are different lists, whereas the current one you have "Subjects" and "Keywords" and they are overlapping.

**Comment by dommitchell** [comment]
Happy with this. Closing.
