### ISSUE TITLE
Application form: text changes

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#582]
This is the task for Application Form text changes. Not to be confused with #137 which is functionality changes

- [x] Question 26: please change Help text to 'This field is optional if you selected "No policy in place".'
- [x] Question 27: change question text to 'Does the journal allow software/spiders to automatically crawl the journal content (also known as text mining)?'
- [x] Question 36: change help text to 'A journal must have an editor and an editorial board. Only in the case of Humanities journals we will accept a form of editorial review using only two editors and no editorial board. Where an editorial board present, at least 5 of its members must be clearly identifiable  with their affiliation information.'
- [x] Question 42: add help text:  'The URL should state that the journal *actively* checks for plagiarism and detail how this is done.'

- [x] In the section about the DOAJ Seal, please change the last sentence of (5) to read:  'If CC BY-ND, CC BY-NC-ND, 'No' or 'Other' is selected the journal will not qualify for the Seal.'

**Comment by dommitchell** [comment]
@emanuil-tolev do you think we might be able to squeeze these textual changes in with the PVOD work, or before?

**Comment by emanuil-tolev** [comment]
yes, shouldn't be a problem, you've done all the assignment/milestone stuff so I'll pick it up after doing the other things

**Comment by richard-jones** [comment]
Note that the changes here won't affect the CSV which will have the old question text, in the event that a change is specified above.

**Comment by richard-jones** [comment]
We can't trivially remove "Other" from 52 and 54, as this will create a difference between the application form and the csv, and affects how the underlying data is managed.

We could look into the work required to make this change, though note that it /may/ affect the reapplication.

Other text-only changes have been made for the next PR

**Comment by dommitchell** [comment]
All looking good. Question @richard-jones is there somewhere in the template editor I can edit the contents of the Seal box on https://doaj.cottagelabs.com/application/new myself?

**Comment by richard-jones** [comment]
You'll be able to edit the text here:

https://github.com/DOAJ/doaj/blob/static_pages/portality/templates/formcontext/_base_application_form.html

Though note that the static_pages version probably isn't up to date with what we'll roll out, so don't make any changes there just yet.

**Comment by dommitchell** [comment]
@greboun just assigning this to you for the record. If we have new text changes, you should probably open a new task
