### ISSUE TITLE
CC BY-NC-SA appears as a facet option but has dropped off the application form

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#583]
http://doaj.org/search?source={%22query%22:{%22match_all%22:{}}}

CC BY (609848)
CC BY-NC (319462)
CC BY-NC-ND (115356)
CC BY-NC-SA (57116)
CC BY-SA (9830)
CC BY-ND (7530)
Not CC-like (2154)
None (814)
Publisher's own license (252)
CC-BY-NC-SA (33)

Note the "duplication" of CC BY-NC-SA, one with a hyphen, one without. So I opened up the journal record with the hyphen: https://doaj.org/admin/journal/ff2069d96721495789b6da721d7f2b7a and question 44 in that record reads:
CC BY
CC BY-NC
CC BY-NC-ND
CC BY-ND
CC BY-SA
No
Other: CC-BY-NC-SA

which brings me back to #137 where the addition of CC BY-NC-SA had been ticked off as completed and yet then I thought hadn't been done: https://github.com/DOAJ/doaj/issues/137#issuecomment-71436259

Is it possible that this change has somehow dropped off the form? Because we do have journals added with CC BY-NC-SA: http://bit.ly/1vSCOXW

**Comment by dommitchell** [comment]
@emanuil-tolev can you look into this?

**Comment by emanuil-tolev** [comment]
> @emanuil-tolev can you look into this?

This https://doaj.org/admin/journal/ff2069d96721495789b6da721d7f2b7a was the only journal with this license. Should be updated now.

**Comment by emanuil-tolev** [comment]
Also form has been updated live!

**Comment by emanuil-tolev** [comment]
> This https://doaj.org/admin/journal/ff2069d96721495789b6da721d7f2b7a was the only journal with this license. Should be updated now.

Also the 32 articles have had their journal info part updated so the license will be CC BY-NC-SA instead of with the dash CC-BY-NC-SA. Gone from facet now.
