### ISSUE TITLE
New/updated lines required in public Article "short view" 

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#584]
Public article short view is the way that an article record is represented in search results for the public.

- Title: linked to full text
- Journal: linked to journal ToC page (long view)
- Citation: Date, Vol, Iss, Page
- DOI
- Journal license: Image or text | URL
- Abstract: expand/collapse

**Comment by richard-jones** [comment]
Just a couple of comments about this:

* Title - I think the link should be to the article page that we're also building, so it is consistent with the journal display.  We should also have the fulltext link in the short display, though.

* Abstract - given that this is the shortened view, are we certain we want the abstract, still?

**Comment by richard-jones** [comment]
I've done a first pass on this, which we can review when the test server is up again.

**Comment by richard-jones** [comment]
Note, that one of the things that I've done is add a speculative link to the article pages - which don't exist yet.  When #540 is complete, we will need to make sure the links work.

**Comment by dommitchell** [comment]
DRAFT Thoughts:
- close up the space between the article icon and the text
- change 'fulltext' to 'Full Text'.
- hyperlink the words 'full text' and remove the URL in full.
- DOIs aren't displaying

**Comment by richard-jones** [comment]
I know your thoughts are still in draft, but just a quick one about the spacing between the icon and the text: do you mean right-align the icon in the current space on the left of the article, or reduce the overall space on the right?

**Comment by dommitchell** [comment]
I mean reduce the overall space if possible.

**Comment by dommitchell** [comment]
Feedback complete

**Comment by richard-jones** [comment]
Ok, all of these changes made, and ready for inclusion for next PR

**Comment by dommitchell** [comment]
This is all looking so good!
Feedback
DOAJ will follow the Vancouver style for citations
- [ ] change all citations to Journal name. YYYY;32(4):489-98. So the first three articles http://bit.ly/1LhY9Rg would look like
The Hidden Advantage in Shoot/Don’t Shoot Simulation Exercise for Police Recruit Training
Amanda Davies
Salus Journal. 2015;3(1):16-30.
Applied Thinking for Intelligence Analysis: A Guide for Practitioners
Trista M. Bailey
Salus Journal. 2015;3(1):48-50.
What is the Association of Cannabis Consumption and Cardiovascular Complications?
Ioannis M Panayiotides
Substance Abuse : Research and Treatment. 2015;2015(9):1-3.
NB the punctuation and lack of spacing between each item.

- [ ] put Abstract and Full Text on the same line, Abstract first, separated by |
- [ ] remove [] from around Full Text and add an 'opens in new window' icon next to the words Full Text. Open in new window. They kind of icon they use on Wikipedia is fine.
- [ ] move DOI to same line as citation. For example: 
Public accounting and its challenges: the case of Hungary
JOZSEF SIMON
Journal of Education Culture and Society. 2013;2013(2):124-133. DOI 10.15503/jecs20132-124-133
Abstract | Full Text

**Comment by richard-jones** [comment]
Are we sure about opening things in new windows?  Overall this is considered Bad for user experience.

**Comment by richard-jones** [comment]
Everything except opening fulltext in new window implemented for next UI Tweaks PR

**Comment by dommitchell** [comment]
One thing: remove the : after DOI

DOI 10.15503/jecs20132-124-133

**Comment by richard-jones** [comment]
Done for next PR

**Comment by dommitchell** [comment]
Good! Closing.
