### ISSUE TITLE
Priority: numbers of applications received and rejected

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#589]
We need some figures for an interview:

How many applications have we received through the new application form?

How many of those have been rejected?

Can we get those by Monday?

**Comment by emanuil-tolev** [comment]
@dommitchell we could delete all rejected apps that were created before 19 March 2014 ( #306 ) easily - I think you were saying yesterday in #306 that the data older than that is actually not of any use to you? Then you could track these numbers at all times.

(Not that I don't want to run the queries but you're going to need to know this again shortly ;).)

**Comment by dommitchell** [comment]
@emanuil-tolev yep, ok. Thanks

**Comment by emanuil-tolev** [comment]
This has been done. Currently on a train so will be able to answer queries tomorrow but it all looks to have gone OK. All applications created before 14 March 2014 (date from #306) are gone so you'll be able to count properly. We've got backups of course and happy to restore records if there's been a mistake.
