### ISSUE TITLE
Script to remove orphaned reapplications

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#593]
We have received a lot of data lately from an aggregator. This shows that many journals need to be removed from DOAJ because they fail to meet our guidelines. We have started removing them.

Can you run a script that will remove all reapplications that have no journal in DOAJ?

**Comment by richard-jones** [comment]
Yup, we will be able to do that.  We can revisit towards the end of the reapplication process.

**Comment by dommitchell** [comment]
How easy is it to do on a regular basis? We remove journals continuously for a variety of reasons.

**Comment by dommitchell** [comment]
Dom to test

**Comment by dommitchell** [comment]
This can be closed now right?
