### ISSUE TITLE
Examples of OpenURLs that must be managed

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#595]
After today's call, I thought it might be helpful to provide this list, extracted from Google Analytics. You can see that there are no hyphens in the ISSNs. Hopefully, some of these may point out other "uses cases" too. I have access to hundreds of sample URLs so let me know if you need more.

/doaj?func=openurl&genre=journal&issn=15196186	
/doaj?func=openurl&issn=18581447&genre=journal	
/doaj?func=openurl&issn=19475500&genre=journal	
/openurl?genre=article&issn=
/doaj?func=openurl&genre=article&issn=10913734&date=2008&volume=13&issue=1&spage=	
/doaj?func=openurl&genre=journal&issn=15593053
/doaj?func=openurl&genre=journal&issn=21467374	
/doaj?func=openurl&genre=article&issn=08332207&date=2004&volume=82&issue=1&spage=	
/doaj?func=openurl&issn=15944077&genre=journal	
/doaj?func=openurl&issn=1303734X&genre=journal	
/openurl?genre=journal&issn=20652194	
/doaj?func=openurl&genre=article&issn=20444621&date=2011&volume=2&issue=10&spage=45
/doaj?func=openurl&genre=article&issn=09768165&date=2012&volume=III&issue=III&spage=1	
/openurl?genre=journal&issn=23200936	
/doaj?func=openurl&issn=10288880&genre=journal	
/doaj?func=openurl&genre=article&issn=15245039&date=2001&volume=3&issue=1&spage=	
/doaj?func=openurl&issn=02585960&genre=journal&uiLanguage=en	
/openurl?genre=journal&issn=1662680X&volume=6&issue=3&date=2014&spage=291
/doaj?func=openurl&genre=article&issn=16796101&date=2012&volume=9&issue=1&spage=47
/doaj?func=openurl&genre=article&issn=19909128&date=2010&volume=4&issue=2&spage=41
/doaj?func=openurl&genre=article&issn=21470626&date=2013&volume=2&issue=2&spage=221
/doaj?func=openurl&genre=article&issn=22006591&date=2012&volume=2012&issue=0&spage=
/doaj?func=openurl&genre=article&issn=13334395&date=2006&volume=5&issue=2&spage=165
/doaj?func=openurl&genre=article&issn=18333850&date=2012&volume=7&issue=24&spage=	
/doaj?func=openurl&genre=article&issn=22307850&date=2013&volume=3&issue=10&spage=1	
/doaj?func=openurl&genre=journal&issn=16940784	
/doaj?func=abstract&id=187603&openurl=1
/doaj?func=openurl&issn=0120386X&genre=journal&uiLanguage=en	
/doaj?func=openurl&issn=15840409&genre=journal
/doaj?func=openurl&genre=article&issn=16968360&date=2013&volume=&issue=&spage=	
/doaj?func=openurl&genre=article&issn=19164742&date=2009&volume=2&issue=4&spage=	
/doaj?func=openurl&genre=article&issn=19231555&date=2013&volume=6&issue=1&spage=132
/doaj?func=openurl&genre=article&issn=20941188&date=2009&volume=20&issue=2&spage=	
/doaj?func=openurl&genre=journal&issn=18447007
/doaj?func=openurl&genre=journal&issn=20691025
/doaj?func=openurl&issn=10113924&genre=journal&uiLanguage=en	
/doaj?func=openurl&issn=14112027&genre=journal&uiLanguage=en	
/doaj?func=openurl&issn=19947887&genre=journal	
/openurl?genre=journal&issn=1516215X	
/doaj?func=openurl&genre=article&issn=17128358&date=2005&volume=1&issue=2&spage=28	
/doaj?func=openurl&genre=journal&issn=19069294&volume=2&issue=1&date=2011&uiLanguage=en	
/doaj?func=openurl&issn=20677693&genre=journal
/doaj?func=openurl&genre=article&issn=2066575X&date=2009&volume=9&issue=Special+Number&spage=29	
/doaj?func=openurl&genre=article&issn=22315063&date=2013&volume=2&issue=9&spage=1	
/doaj?func=openurl&issn=1222569X&genre=journal	
/doaj?func=openurl&issn=20477031&genre=journal&uiLanguage=en
/doaj?func=openurl&genre=article&issn=19231555&date=2013&volume=6&issue=1&spage=107	
/doaj?func=openurl&genre=article&issn=21527180&date=2012&volume=03&issue=06&spage=457	
/doaj?func=openurl&genre=article&issn=2249894X&date=2012&volume=I&issue=IV&spage=49	
/doaj?func=openurl&genre=journal&issn=22476377

**Comment by dommitchell** [comment]
@Steven-Eardley wanted to check that for a journal that has a continuation #145 we are matching the correct information in our OpenURL solution, that a user following a URL to an article from a previous/older version of a journal will be taken to that article under its old title and not the new title.

Also, for a user following a URL to an old version of a journal, where will they end up?

**Comment by Steven-Eardley** [comment]
Right now this isn't the case; in fact I don't think there's any consideration of continuations at all. Once I've seen how the toc pages handle continuations it should be possible to issue the correct query to display them via openurl.

**Comment by richard-jones** [comment]
@dommitchell - assigning this to you for testing purposes

**Comment by dommitchell** [comment]
The following URLs from above do not work:

/openurl?genre=article&issn= (I can't see how this would ever be called)

All items with page numbers, for example: 
/doaj?func=openurl&genre=article&issn=19231555&date=2013&volume=6&issue=1&spage=132
/openurl?genre=journal&issn=1662680X&volume=6&issue=3&date=2014&spage=291
/doaj?func=openurl&genre=article&issn=16796101&date=2012&volume=9&issue=1&spage=47
/doaj?func=openurl&genre=article&issn=19909128&date=2010&volume=4&issue=2&spage=41
/doaj?func=openurl&genre=article&issn=21470626&date=2013&volume=2&issue=2&spage=221
/doaj?func=openurl&genre=article&issn=22006591&date=2012&volume=2012&issue=0&spage=
/doaj?func=openurl&genre=article&issn=13334395&date=2006&volume=5&issue=2&spage=165
/doaj?func=openurl&genre=article&issn=18333850&date=2012&volume=7&issue=24&spage=

This one linking to an abstract:
/doaj?func=abstract&id=187603&openurl=1

This one:
/doaj?func=openurl&genre=article&issn=2066575X&date=2009&volume=9&issue=Special+Number&spage=29

**Comment by richard-jones** [comment]
Regarding this one:

> /doaj?func=abstract&id=187603&openurl=1

I don't think we need to support this going forward.  Apart from being a very odd sort of URL, it is requesting an object by internal id from the old system, so we would never be able to respond to it.

Otherwise, a few tweaks to the query parameters should resolve the issues above, although note that a "not found" is a legitimate response where the user has not provided enough information or has provided too much information (making an exact match impossible).

**Comment by dommitchell** [comment]
Assuming this can be closed now`?

**Comment by Steven-Eardley** [comment]
Yup, I reckon so. Further examples and problems can have a new Issue.
