### ISSUE TITLE
Add new sponsor logo - Neurensics - update static pages

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#597]
Please add Neurensics to the sponsors page and home page. 

![neurensics](https://cloud.githubusercontent.com/assets/5955396/6583721/42e00faa-c766-11e4-8c36-3ceebafb6886.jpg)

and link to http://www.neurensics.com/en/

Please update the static pages

**Comment by Steven-Eardley** [comment]
Merged PR but deployment pending, see #599.

**Comment by emanuil-tolev** [comment]
Rolled out. Thanks @Steven-Eardley . Feel free to use the deploy_live task in the sysadmin fabric script for DOAJ (it just takes a tag name) to roll out minor hotfixes to live. The new infrastructure won't be in use for live DOAJ until about a month from now, so the fabric script should work till then.

@dommitchell ready for review :) (with static_pages changes in)

**Comment by dommitchell** [comment]
Smashing! Thank you both!

**Comment by dommitchell** [comment]
Sorry. Sponsor has asked we change link to http://www.neurensics.com/. Thanks!

**Comment by Steven-Eardley** [comment]
On live now. Should be Dutch.
