### ISSUE TITLE
Staging URLs appearing in Google search 

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#598]
5th one down. Neither staging nor test should appear in Google

![staging](https://cloud.githubusercontent.com/assets/5955396/6593793/cf415bdc-c7db-11e4-8324-7f3b6719c3b7.jpg)

**Comment by emanuil-tolev** [comment]
Hm, strange. I've no idea how they've indexed that. I can't tell them what to index though :). But I might be able to tell them not to index something, I'll check the various ways of doing that.

Maybe we'll need to put up a basic authentication shield so only humans with a simple user and password combo can see test and staging. I assume this OK with you?

**Comment by Steven-Eardley** [comment]
Do we use a ```robots``` file to determine crawler access? Making test and staging stricter than live should help. 
http://en.m.wikipedia.org/wiki/Robots_exclusion_standard

**Comment by emanuil-tolev** [comment]
Don't think we serve a specific one. But yes, this will be the solution unless I can somehow tell Google just not to crawl and never index this and this URL (which we can prove we own). I didn't want to introduce more environment-specific differences in the repo at first if possible :).

**Comment by emanuil-tolev** [comment]
I've a solution (password-protecting) but my main internet connection's down, currently awaiting repairs, and the mobile is making it very difficult to do anything over the secure link required to implement the password thing. I'll try this tomorrow. (+ I'll need to figure out exactly how to ask google to remove the already indexed pages from the search results, I don't fancy removing them one by one in webmaster tools... they will go away in probably 1-2 weeks after the password protection is in, but still)

**Comment by emanuil-tolev** [comment]
... this has been obsoleted by the fact staging.doaj.cottagelabs.com no longer works (redirects to cottagelabs.com) due to the new infrastructure slotting into place. We won't have staging for a little while so this should not be an issue. However @dommitchell I'll leave this issue open so we can *remember* to lock test and staging with a password.

**Comment by emanuil-tolev** [comment]
@richard-jones added to PVOD project milestone just so we don't forget to do it (and that's likely the next project that will use test and staging servers).

**Comment by emanuil-tolev** [comment]
#646 and #647 take care of the issues that arose here.
