### ISSUE TITLE
Publisher CSV files submitted: deliver to DOAJ

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#604]
Is it possible to make submitted publisher CSV files available to DOAJ for us to use when we review the bulk reapplications?

**Comment by richard-jones** [comment]
The submitted CSV files are automatically deleted after processing, so we'd need to make a change to the reapplication code if you wanted to be able to do this.

**Comment by dommitchell** [comment]
Nope. Leave as is.
