### ISSUE TITLE
For right-to-left text, bracket placed incorrectly

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#607]
دانشکده دندانپزشکی دانشگاه علوم پزشکی مشهد (191)

![arabic](https://cloud.githubusercontent.com/assets/5955396/6665459/0eae9d78-cbda-11e4-9ec2-40d5d6101f9a.jpg)

**Comment by richard-jones** [comment]
Can you give me a search that will expose this, then I will take a look.

Hadn't considered RTL languages - not sure what the fix is, but will be interesting to find out.

**Comment by dommitchell** [comment]
https://doaj.cottagelabs.com/search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22index.publisher.exact%22%3A%22%D8%AF%D8%A7%D9%86%D8%B4%DA%A9%D8%AF%D9%87%20%D8%AF%D9%86%D8%AF%D8%A7%D9%86%D9%BE%D8%B2%D8%B4%DA%A9%DB%8C%20%D8%AF%D8%A7%D9%86%D8%B4%DA%AF%D8%A7%D9%87%20%D8%B9%D9%84%D9%88%D9%85%20%D9%BE%D8%B2%D8%B4%DA%A9%DB%8C%20%D9%85%D8%B4%D9%87%D8%AF%22}}]}}%2C%22query%22%3A{%22match_all%22%3A{}}}}%2C%22sort%22%3A[{%22created_date%22%3A{%22order%22%3A%22desc%22}}]%2C%22from%22%3A0%2C%22size%22%3A10}

**Comment by richard-jones** [comment]
Slight change to that search to give us the facet:

https://doaj.cottagelabs.com/search?source=%7B%22query%22%3A%7B%22filtered%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22term%22%3A%7B%22_type%22%3A%22article%22%7D%7D%5D%7D%7D%2C%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%22Journal%20of%20Mashhad%20Dental%20School%22%2C%22default_operator%22%3A%22AND%22%7D%7D%7D%7D%2C%22sort%22%3A%5B%7B%22created_date%22%3A%7B%22order%22%3A%22desc%22%7D%7D%5D%2C%22from%22%3A0%2C%22size%22%3A10%7D

maybe something to do with how RTL languages wrap text

**Comment by dommitchell** [comment]
Dom to ask Ghane

**Comment by dommitchell** [comment]
We have good feedback:

- for the facets. the bracket position is incorrect. It should be:
![facet](https://cloud.githubusercontent.com/assets/5955396/6819376/73a9c364-d2c0-11e4-8557-03a8c772906b.jpg)
The same logic would apply for the article titles.

- another error has been detected where non-Cyrrilic mixes with Cyrillic. So compare article 1, 3, and 6 here: http://bit.ly/1CNOQD0 with this image:

![correct_texts](https://cloud.githubusercontent.com/assets/5955396/6819406/f8089f54-d2c0-11e4-9813-c3c96182f614.jpg)

**Comment by richard-jones** [comment]
Ok, so I think that all we can do is tell the browser to render the text using its "auto" direction detection and leave it at that.

Note that text wrapping works differently in rtl as it does in ltr, and we won't have any control over it :)

**Comment by richard-jones** [comment]
Ok, I've done the following:

* added dir="auto" to all facet values, which will render them the right way round
* added dir="ltr" to all facet counts
* added dir="auto" to the main results table

This is approximately in-line with the recommendations from the w3c:

http://www.w3.org/International/questions/qa-html-dir

It does appear to resolve all the text directonality problems in my limited test, although the numbers are appearing on the right rather than the left, but this is consistent with the rest of the interface, so hopefully that makes sense to everyone.

Due in next PR

**Comment by richard-jones** [comment]
I should add that the dir="auto" directive in HTML which is responsible for this is implemented patchily across browsers.  It is unlikely to work correctly in IE and Opera, and may or may not work in Safari.  Support should be full in Firefox and Chrome.  There is, unfortunately, nothing we can do about it :(

**Comment by dommitchell** [comment]
Still seeing دانشکده دندانپزشکی دانشگاه علوم پزشکی مشهد (191) in the facet and no change in article titles

**Comment by richard-jones** [comment]
What browser are you looking at it with?  It is working for me in Chrome.

Unfortunately, if the browser doesn't implement the html "dir" attribute, which is what's required to get this right, then we don't have any other options for resolving this.  The big challenge is that the data in doaj is a mixture of rtl and ltr, so we rely on the browser detecting this on a case-by-case basis and rendering it correctly.

We could still separate the facet count from the facet value by changing the layout slightly, which would separate the (191) from the text, but I the text would still be incorrectly rendered (i.e. backwards) and the article titles would remain wrong.

**Comment by dommitchell** [comment]
I am using Firefox and Chrome. And have tried Ctrl + F5 to force browser refresh and a new browser

**Comment by dommitchell** [comment]
This is looking good. Closing.
