### ISSUE TITLE
2 new static pages and linking | change order

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#608]
- [x] Create a new static page /volunteers, editable via https://github.com/DOAJ/doaj/tree/static_pages/portality/templates/doaj
and place a link to it in the right-hand nav.
![rhn](https://cloud.githubusercontent.com/assets/5955396/6824449/a7658210-d2f2-11e4-97be-c54e4138253b.jpg)
Change the order of the right-hand nav items so they are in alphabetical order:
Our members
Our publisher members
Our sponsors
Our volunteers

- [x] Create a new static page /rights, also editable via static_pages and place a link to it next to or under the section heading 'Content Licensing' in the application form (all instances)

**Comment by dommitchell** [comment]
@richard-jones is this something Steve could do fairly quickly?

**Comment by dommitchell** [comment]
Wait until end of PVOD

**Comment by Steven-Eardley** [comment]
The pages are located at ```portality/templates/doaj/volunteers.html``` and ```portality/templates/doaj/rights.html```. Currently just placeholder text.

The rights page opens in a new tab.

To add content before pull request for this (#789) is merged (so the placeholders don't go live), you can switch to the branch [hotfix/issue_608_new_static_pages](https://github.com/DOAJ/doaj/tree/hotfix/issue_608_new_static_pages) and make your HTML changes to the above files.

**Comment by dommitchell** [comment]
@Steven-Eardley can I see the link on the application form?

**Comment by Steven-Eardley** [comment]
@dommitchell it looks like this (directly below heading):

<img width="1217" alt="screen shot 2015-07-06 at 10 09 12" src="https://cloud.githubusercontent.com/assets/1446355/8519026/2b7e6286-23c7-11e5-82c4-61c8f5f51599.png">

**Comment by dommitchell** [comment]
@greboun can you have a think about the wording for the link in the screenshot above?

**Comment by greboun** [comment]
suggest: copyright&Licensing help

**Comment by dommitchell** [comment]
> The pages are located at portality/templates/doaj/volunteers.html and portality/templates/doaj/rights.html. Currently just placeholder text.

@Steven-Eardley can you add them to my branch so I can edit them?

https://github.com/DOAJ/doaj/tree/static_pages/portality/templates/doaj

**Comment by Steven-Eardley** [comment]
@dommitchell they're in static_pages now!

**Comment by dommitchell** [comment]
Both pages now submitted with text. Sorry for the delay! This can go live now.

**Comment by dommitchell** [comment]
@Steven-Eardley not seeing this on test yet

**Comment by Steven-Eardley** [comment]
@dommitchell Just reviewed this locally - your volunteers page says:

>  more than XX applications or reapplications and a new certificate will be awarded for every XX applications thereafter.

Would you like to replace the placeholder before I do the work to merge it all into the main branch?

**Comment by dommitchell** [comment]
Sorry. Please do not make live yet.

**Comment by dommitchell** [comment]
@emanuil-tolev @Steven-Eardley Please can you make this live now (the link on the home page and the link in the Application Form)?

**Comment by Steven-Eardley** [comment]
This has been released to live now.

**Comment by dommitchell** [comment]
Perfect! Thanks!

**Comment by dommitchell** [comment]
@Steven-Eardley would it be at all possible to repeat the link 'Copyright & Licensing help' (https://doaj.org/rights) under the next section 'Copyright and Permissions' as well?

@richard-jones happy to add further tnm, of course.

**Comment by Steven-Eardley** [comment]
@dommitchell Live now, with your added link from static_pages too.

**Comment by dommitchell** [comment]
Wow! Superfast! Thanks!
