### ISSUE TITLE
Question: which is the correct ISO code for Chinese? 

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#609]
http://en.wikipedia.org/wiki/List_of_ISO_639-2_codes

A user tried chi and chi* and zho, all these failed. She took instruction from http://doaj.org/features

**Comment by emanuil-tolev** [comment]
While .. filling out a journal application I assume.

**Comment by emanuil-tolev** [comment]
No wait, you just select "Chinese" in the language field, you don't need to know the code.

**Comment by dommitchell** [comment]
Nope, tagging the language in XML: http://doaj.org/features#xml_upload

**Comment by emanuil-tolev** [comment]
Ah, the ingest there. Hm, not sure off the top of my head which list this uses (it should use the ISO list we have - chi, zho and zh are all in the list). I'll investgate.

**Comment by emanuil-tolev** [comment]
> A user tried chi and chi* and zho, all these failed

There is no validation on the incoming language tag at all. (We might wanna add that in the future ..)

Can you put / email details on who the user is so we can double-check the upload failure messages? Might be worth asking her for the XML files she's trying to process at the same time.

**Comment by emanuil-tolev** [comment]
> There is no validation on the incoming language tag at all.

This field is an article-level field which says what the journal's language is. Obviously they can't modify journal info via article XML upload.

**Comment by dommitchell** [comment]
Emailed.

**Comment by emanuil-tolev** [comment]
> Emailed. If there is no validation then it is likely that there is a problem elsewhere in their XML. Let me ask that question of them first,

@dommitchell Sorry, I made a mistake here. There is validation insofar the schema itself is concerned, and one of the few things the schema specifies is that the code must be a valid 3-char language code.

'[aar, abk, ace, ach, ada, afa, afh, afr, aka, akk, alb, ale, alg, amh, ang, apa, ara, arc, arg, arm, arn, arp, art, arw, asm, ast, ath, aus, ava, ave, awa, aym, aze, bad, bai, bak, bal, bam, ban, baq, bas, bat, bej, bel, bem, ben, ber, bho, bih, bik, bin, bis, bla, bnt, bos, bra, bre, btk, bua, bug, bul, bur, cad, cai, car, cat, cau, ceb, cel, cha, chb, che, chg, chi, chk, chm, chn, cho, chp, chr, chu, chv, chy, cmc, cop, cor, cos, cpe, cpf, cpp, cre, crp, cus, cze, dak, dan, dar, day, del, den, dgr, din, div, doi, dra, dua, dum, dut, dyu, dzo, efi, egy, eka, elx, eng, enm, epo, est, ewe, ewo, fan, fao, fat, fij, fin, fiu, fon, fre, frm, fro, fry, ful, fur, gaa, gay, gba, gem, geo, ger, gez, gil, gla, gle, glg, glv, gmh, goh, gon, gor, got, grb, grc, gre, grn, guj, gwi, hai, hau, haw, heb, her, hil, him, hin, hit, hmn, hmo, hun, hup, iba, ibo, ice, ido, iii, ijo, iku, ile, ilo, ina, inc, ind, ine, inh, ipk, ira, iro, ita, jav, jpn, jpr, jrb, kaa, kab, kac, kal, kam, kan, kar, kas, kau, kaw, kaz, kbd, kha, khi, khm, kho, kik, kin, kir, kmb, kok, kom, kon, kor, kos, kpe, kro, kru, kua, kum, kur, kut, lad, lah, lam, lao, lat, lav, lez, lim, lin, lit, lol, loz, ltz, lua, lub, lug, lui, lun, luo, lus, mac, mad, mag, mah, mai, mak, mal, man, mao, map, mar, mas, may, mdr, men, mga, mic, min, mis, mkh, mlg, mlt, mnc, mni, mno, moh, mol, mon, mos, mul, mun, mus, mwr, myn, nah, nai, nap, nau, nav, nbl, nde, ndo, nds, nep, new, nia, nic, niu, nno, nob, non, nor, nso, nub, nya, nym, nyn, nyo, nzi, oci, oji, ori, orm, osa, oss, ota, oto, paa, pag, pal, pam, pan, pap, pau, peo, per, phi, phn, pli, pol, pon, por, pra, pro, pus, qaa-qtz, que, raj, rap, rar, roa, roh, rom, rum, run, rus, sad, sag, sah, sai, sal, sam, san, sas, sat, scc, sco, scr, sel, sem, sga, sgn, shn, sid, sin, sio, sit, sla, slo, slv, sma, sme, smi, smj, smn, smo, sms, sna, snd, snk, sog, som, son, sot, spa, srd, srr, ssa, ssw, suk, sun, sus, sux, swa, swe, syr, tah, tai, tam, tat, tel, tem, ter, tet, tgk, tgl, tha, tib, tig, tir, tiv, tkl, tli, tmh, tog, ton, tpi, tsi, tsn, tso, tuk, tum, tup, tur, tut, tvl, twi, tyv, uga, uig, ukr, umb, und, urd, uzb, vai, ven, vie, vol, vot, wak, wal, war, was, wel, wen, wln, wol, xho, yao, yap, yid, yor, ypk, zap, zen, zha, znd, zul, zun]'

The correct code **is** chi.

**Comment by emanuil-tolev** [comment]
> The correct code is chi.

So her problem was elsewhere, since she tried chi.

**Comment by dommitchell** [comment]
OK, great. I told her that and received no response. Closing.
