### ISSUE TITLE
Question about OAI and BibJSON | error

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#610]
On Github

https://github.com/DOAJ/doaj#article-data-model

you describe the BibJSON model you use. In particular, I need access
to article-level fields
"volume", "number", "year", "month", "start_page", and "end_page".

In your current format oai_dc, these are missing. dc:source contains
the unformatted information.
It would be a pity to have a pattern matching process running for data
that is already
formatted in your service.

So my question is: is it possible to add these fields to OAI? Maybe
the BibJSON model?

For my use case, as an alternative to OAI, it would also be sufficient
to create regular BibJSON article data file dumps for download.

I also noticed the following error at your service.

Example:

http://doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22match_all%22:{}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22id%22:%224426c82660e44ac78d83a5ce8df5edb5%22}}]}}}}}#.VQYTdGSRM4R

There is a line

    Authors: Serdar Bozdag, Aiguo Li, Mehmet Baysan, null, Howard A. Fine

where a "null" appears as author. This seems not correct.

In OAI, it seems this field is not converted correctly. The fields
"dc:subject" and "dc:creator" seem affected
by this error in several documents. I can prepare an OAI ID list of
records where I encounter this kind of error
if you prefer.

**Comment by emanuil-tolev** [comment]
> For my use case, as an alternative to OAI, it would also be sufficient
> to create regular BibJSON article data file dumps for download.

I think you and @richard-jones might have discussed a DOAJ API. This would give this person access to the bibjson.

For his alternative, getting this info from the OAI endpoint, #180 deals with this. Specifically it deals with following the old doajArticle format, which hopefully contains all the fields he wants. I suspect we can add them if not without much hassle, as this is under development right now.

**Comment by emanuil-tolev** [comment]
So to respond, feel free to tell him he'll be getting that info via OAI via a new "doajArticle" format in mid-April.

**Comment by richard-jones** [comment]
Just picking up on this null issue:

"null" is a keyword meaning "no value here" in several programming languages, but (interestingly) not in any of the languages that we are using.  Python uses the word "None" and JavaScript uses "undefined", so my guess is that these nulls are actually in the data, produced by someone else's system and erroneously provided to the DOAJ as plain text.

Just a theory, though, I haven't investigated in detail.
