### ISSUE TITLE
The status 'Ready' should only be available to Editors and Managing Editors.

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#613]
The status 'Ready' should only be available to Editors and Managing Editors.

**Comment by dommitchell** [comment]
Can we make this change soon? It's causing problems with our workflow.

**Comment by richard-jones** [comment]
The decision we made at the start of the PVOD project to migrate to ES 1.4 means that we will only be able to roll out all this new functionality at the end of the project when the live server is ready for upgrade, sorry.  Only a couple of weeks to go...

**Comment by dommitchell** [comment]
Yes, ok. Thanks!

**Comment by dommitchell** [comment]
Yep all good. Closing

**Comment by dommitchell** [comment]
I have evidence that this isn't quite working as it should. 

https://testdoaj.cottagelabs.com/editor/your_applications?source={%22query%22%3A{%22match_all%22%3A{}}%2C%22from%22%3A0%2C%22size%22%3A10}

user: fei // password emailed to you.

https://testdoaj.cottagelabs.com/account/fei - is definitely an editor and yet cannot see the Ready status.

**Comment by richard-jones** [comment]
This user is the Editor of one group, and an Associate Editor in another group.  The problem journal mentioned belongs to her as an Associate, not as an Editor.

**Comment by dommitchell** [comment]
@greboun Please delete 'English2' as a group and only use 'English 2'. Reassign the two application that are with English2 to English 2.

**Comment by greboun** [comment]
the editor is only editor for DOAJ of one group. No ifo on ass editor
function.
Could be that she was having ass editor status in English 2, perhaps.
I have reallocated applications from English 2 (only 5 + 2 on holds) to
English2, and now we do not have any more applications in English 2
The group is not in the database so I did not have to selete anything.

Dr. Tom Olijhoek
Editor-in-Chief  DOAJ
Support us: www.doaj.org/support

**Comment by emanuil-tolev** [comment]
@dommitchell OK, so basically this seems to work as expected by all of us :). Maybe worth thinking about somehow showing the editor what rights they have (e.g. in this application you are an associated editor of this group in a permanent blue alert at the top). I'd create new issues for those sorts of things though and close this one.

**Comment by dommitchell** [comment]
Great. Closing.
