### ISSUE TITLE
Weighting of search results

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#620]
What is the current configuration for the weighting of search results?

If you do a simple search, it's always the same articles that float to the top: http://doaj.org/search?source={%22query%22:{%22query_string%22:{%22query%22:%22clinical%20medicine%22,%22default_operator%22:%22AND%22}}}

I think that there is an artificial weighting being created by all the keywords that are duplicated. Would that be correct?

**Comment by richard-jones** [comment]
The search results are returned in whatever order Elasticsearch feels like when there is nothing else to order them by.  Essentially under the hood the search engine scores every result against your query, but for simple queries like this, with a lot of results, the scores are basically the same for all the results.  So it returns them in whatever order it wants, and my guess would be that it's the order that it comes across them in the database.

**Comment by emanuil-tolev** [comment]
The default analysers we use in ES may well have a scoring algorithm. At least "how many times do query tokens appear in doc". It sounds very much like ES to do that.

**Comment by dommitchell** [comment]
Do we know what that scoring algorithm is? I'm looking to make sense of why search results are returned how and when they are

**Comment by emanuil-tolev** [comment]
Not straight off - it does do some kind of default ordering, but I guess it's best described as "relevance". Might take a bit of digging to find out but we could check. @markmacgillivray actually, any idea about what the default sort order is?

**Comment by markmacgillivray** [comment]
It's not clear what you mean. The default sort order of doaj is whatever we
set it to, if configured. If not, then the first search is a match all,
technically ordered on relevance but relevant to anything. Once a search
term is entered it is relevance to that search term. The way that is
calculated will depend on what sort of term it is, and what fields it is
checked against. If a simple string against _all then it is roughly
occurrences of that string in _all and then also occurrence of stems in
analysed fields in _all.

Mark

**Comment by dommitchell** [comment]
This is very useful.

Is there a default sort order set already? Can you detail that here?

**Comment by markmacgillivray** [comment]
The sort orders that are possible are listed in the box to the left of the
search box on the main search page, there it shows that the first search
order is relevance and that is the one applied when first hitting that
page. So unless a user selects a different sort order from that box, they
will be getting back search results ordered by relevance to the search
terms they type in to the search box. By default it also is searching _all,
so it will be looking for strings in all fields in the records. The next
box by the search box allows for selecting which fields to search in, in
which case the relevance match will only be to occurrences of the search
terms in the chosen field.

**Comment by dommitchell** [comment]
Closing
