### ISSUE TITLE
Journals that are neither in nor out of DOAJ

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#622]
A couple more of these: think we had one before.

https://doaj.org/admin/journal/19a034dfd7d941df9269258711f6c7fd
https://doaj.org/admin/journal/e500a798e3264d26932d86118bc0ee83

They are neither in or out of DOAJ AND have no reapplication records associated. Can you fix? The publisher is asking why his journals aren't in DOAJ. I wonder how many more of these there are?

**Comment by dommitchell** [comment]
Sorry to up the priority. The publisher has contacted us again.

**Comment by emanuil-tolev** [comment]
Set in_doaj to True for these 2.

There are 3 more such journals:
86f3b575e5924014909dc58ab2cc7f2c
b356da3a55ab414ca7d3a755b516ce88
1b4f5507c768494ea17c5cdcb4fe9099

just stick the ID in the admins' journal search, they should come up. I'm happy to set them to whatever value they should be. No idea what caused this, except that they all seem to have been edited in December 2014 (see their notes) - perhaps an old bug no longer present?

**Comment by richard-jones** [comment]
You should be able to just use the button in the admin area to set these to the appropriate setting.

**Comment by dommitchell** [comment]
Yes but the problem is that they do not have reapplication records and I can't generate those. Are you able to do that?

**Comment by richard-jones** [comment]
I think this is resolved; reassigning to @dommitchell to close or comment
