### ISSUE TITLE
Search lets you order Journals by "Article: Publication Date"

### ISSUE THREAD

**Issue by Steven-Eardley** [DOAJ/doaj#627]
![screen shot 2015-03-28 at 15 30 21](https://cloud.githubusercontent.com/assets/1446355/6881637/bdc2078a-d55f-11e4-9c00-2babc3f5b1bf.png)

**Comment by richard-jones** [comment]
Yes, that's a bit odd, but there's no option in fv2 to modify those pull-downs dynamically.  Would require additional coding.

**Comment by richard-jones** [comment]
duplicated in #672
