### ISSUE TITLE
Question: using the test site as a training ground

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#634]
We would like to let our new volunteers loose on the test site before we allow them to work on the live site. Any one have any objections to that? Thoughts?

**Comment by Steven-Eardley** [comment]
The test site is in a state of flux, so the advantage of them working on somewhere 'safe' may be hampered by experimental or partial changes on test, and likewise development tests may be hampered by the data doing strange things.

On the other hand, more ways to break it is usually a good thing - more eyes to find issues, more in-depth testing of the site. It would require more administration though.

Also, how much do we guarantee the test server to be up and available @emanuil-tolev?

**Comment by emanuil-tolev** [comment]
Test server should really be up most of the time. I'd probably say a staging site is better for this kind of thing though.

What's the idea @dommitchell ? Are they testing ongoing developments, or just training in the current live system? Staging is always much closer to live, the only time they differ is like for a few days before a big release to live. @markmacgillivray we are going need to set up Staging on similar infrastructure to Test quite soon for the PVOD+OpenURL release anyway.

**Comment by dommitchell** [comment]
The idea is that they (associate editors and editors) might be able to 'train' on a couple of applications/reapplications/creating accounts before switching to the live site.

**Comment by emanuil-tolev** [comment]
Right, so they're not focussing on new developments, they're focussing on being able to use the live site. So to answer @Steven-Eardley's earlier q, staging seems like a better idea when it's up. When would you like to train the guys Dom?

**Comment by dommitchell** [comment]
@emanuil-tolev I have no hard start date. It can be whenever is convenient for you guys. And if the site is unavailable for a while, that's no problem either. It would just be an added bonus if we OK to use it.

The training wouldn't be of any pre-determined length, duration, etc. The idea is that every time we take on a new Associate Editor (currently about 5 a month), we 'let them loose' on the straging site first to play around.
