### ISSUE TITLE
Legacy OpenURL requests via func=openurl require multiple tries on Test server

### ISSUE THREAD

**Issue by Steven-Eardley** [DOAJ/doaj#635]
When running some queries via the old endpoint, the 404 page is displayed while the correctly rewritten query is placed in the navigation bar. One only needs to hit enter to then reach the right page. Seen in chrome.

steps to reproduce:
* open new tab
* go to a page with https://doaj.cottagelabs.com/doaj?func=openurl&... (see #595)
* click in the nav bar and hit enter

**Comment by Steven-Eardley** [comment]
It sometimes works eventually - this is acting a bit strangely and inconsistently, so I've written the issue for posterity.

**Comment by richard-jones** [comment]
I haven't been able to reproduce locally.  Probably a browser oddity.

**Comment by richard-jones** [comment]
@Steven-Eardley could you try to reproduce this on live now, and if not seen close off this issue?

**Comment by Steven-Eardley** [comment]
Unable to reproduce on live, closing.
