### ISSUE TITLE
Question: data protection policy

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#639]
A question has come in: which country's data protection policy governs our data? Would it be the UK's because that's where the data sits?

**Comment by richard-jones** [comment]
passing over to @emanuil-tolev who will know where the servers actually are...

**Comment by emanuil-tolev** [comment]
London.

> A question has come in: which country's data protection policy governs our data? Would it be the UK's because that's where the data sits?

This is a legal question, not necessarily a technological one. Cottage Labs has to adhere to UK data protection law as far as I know, and this includes DOAJ data. Whether the DOAJ as an organisation is bound by any other laws would depend on national law in countries the DOAJ operates in.

Also I'm not clear which countries the DOAJ operates in (i.e. where is your HQ)?

> Infrastructure Services for Open Access C.I.C. (is4oa) is a Community Interest Company based in the United Kingdom. Incorporated in England. Company registration no. 8307499. VAT no: DK 35153470

Your address is

> IS4OA, Postbox 60, DK-2770 Kastrup, Denmark

But if you're only registered as a CIC in the UK, then it's probably only UK law that applies to you (i.e. it's like you have an office in Denmark but are a UK company) - again, wild non-lawyer speculation.

If you are legally established in the UK and in Denmark I really can't tell you, I can't even begin to guess.

* * *

Summary: DOAJ data should be afforded the protection of *at least* UK law. I am not certain about other countries.

**Comment by emanuil-tolev** [comment]
> This is a legal question, not necessarily a technological one.

Just to underline this as an important distinction: you know accounting and taxes? There *is* a relationship between cash in the bank and taxes, but it's rarely straightforward. This is the same deal, there is a relationship between where the data actually is and the law, but it's not that simple.

**Comment by dommitchell** [comment]
OK. I shall check with Lars then. Thanks for this info. It is very useful.

**Comment by dommitchell** [comment]
Closing for now.
