### ISSUE TITLE
Querying OpenURL by volume/issue

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#640]
At the moment volume and issue aren't used to query the index in OpenURL.  But they are used to route the user to the appropriate ToC page, which can result in some unexpected behaviour.

**Comment by richard-jones** [comment]
Not sure what the right thing to do about it is, yet.  Either not query by volume and issue and then be more careful when we write the URLs, or find a way to query by them, and be more rigid about what we return to the user (i.e. exact volume and issue matches will be required)

**Comment by Steven-Eardley** [comment]
However, the journal index does not contain vol/issue information, does it? How are these queries handled elsewhere in the site nowadays?

**Comment by Steven-Eardley** [comment]
This is done.
