### ISSUE TITLE
Finalisation and eventual sign off of hosting agreement

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#654]
See email conversation. Awaiting feedback from @richard-jones and @markmacgillivray

**Comment by richard-jones** [comment]
No specific feedback from me, @markmacgillivray is handling

**Comment by dommitchell** [comment]
Can I have an update here? Thanks!

**Comment by richard-jones** [comment]
I believe this is now handled - can we close?

**Comment by emanuil-tolev** [comment]
Yes
