### ISSUE TITLE
Article metadata input: split author names

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#659]
Change https://doaj.org/publisher/metadata so it asks for [First Name], [Last Name].

Specification to be added here.

**Comment by richard-jones** [comment]
@dommitchell - I'm pondering whether we need to do this before the refactor, or indeed at all.

Overall, I'd recommend against this.  There is a general principle that programmers (should) follow that you don't try to do anything clever with splitting out users names - just ask them for their name as a single piece of text that they control the format of.  As soon as you go down the "first name"/"last name" route you open up a can of worms (I can link you a moderately hilarious blog post about it).

That said, I have been in discussions where different name forms are important, such a the form used for citation.  Is this the motivation for splitting out the names like this?  If so, I'd suggest that we ask the publisher to provide the names as they should appear in the citation format(s) we want to support instead.

**Comment by dommitchell** [comment]
Yes, and we have discussed this before. I am with you on the name thing (Spanish and Chinese names being a particular bugbear). I think the request, however, came from Google Scholar who require clear first name, last name denoters to be able to match and process article authors etc. (Except they can't past our javascript-based ToCs anyway so....)

I think the idea is vaguely attractive too because we currently have all sorts of name formats for the same author. Maybe this is why we need ORCID IDs as well?

I'd like a 3rd opinion really, maybe someone from the metadata world. I'll see if I can get that. Thanks for flagging this again.
