### ISSUE TITLE
Bitly key for live service

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#662]
@dommitchell - could you register DOAJ with bit.ly and get us an API key that we can use for the URL shortener on the live service?  See: https://github.com/DOAJ/doaj/issues/51#issuecomment-78250633 for details.

**Comment by dommitchell** [comment]
@richard-jones  what should I enter for:

Application name
Application link
Redirect URIs ?

**Comment by richard-jones** [comment]
Are they all required? I don't recall filling out the last one, but the
first two should probably be DOAJ and doaj.org

On 16 April 2015 at 13:30, dommitchell <notifications@github.com> wrote:

> @richard-jones <https://github.com/richard-jones> what should I enter for:
>
> Application name
> Application link
> Redirect URIs ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DOAJ/doaj/issues/662#issuecomment-93722439>.
>



-- 

Richard Jones,

Founder, Cottage Labs
t: @richard_d_jones, @cottagelabs
w: http://cottagelabs.com

**Comment by dommitchell** [comment]
Redirect URIs is required too.

2015-04-16 14:47 GMT+02:00 Richard Jones <notifications@github.com>:

> Are they all required? I don't recall filling out the last one, but the
> first two should probably be DOAJ and doaj.org
>

**Comment by richard-jones** [comment]
Hm, don't know.  I guess http://doaj.org

**Comment by richard-jones** [comment]
I've now done this
