### ISSUE TITLE
View Journals link doesn't work

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#664]
Clicking on the 'View Journals' link from a User record returns all journals.

https://testdoaj.cottagelabs.com/account/?source={%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22versita%22%2C%22default_operator%22%3A%22OR%22}}%2C%22from%22%3A0%2C%22size%22%3A25}

opens

https://testdoaj.cottagelabs.com/admin/journals?source={%22query%22%3A{%22match_all%22%3A{}}%2C%22from%22%3A0%2C%22size%22%3A10}

**Comment by richard-jones** [comment]
Yup, good point - haven't updated the call to work with the new facetview

**Comment by richard-jones** [comment]
Fixed for next PR
