### ISSUE TITLE
Reapplications don't load in publisher account

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#665]
Logged in as a publisher and the reapplications tab doesn't load:

https://testdoaj.cottagelabs.com/publisher/progress?source={%22query%22%3A{%22match_all%22%3A{}}%2C%22from%22%3A0%2C%22size%22%3A10}

![loading](https://cloud.githubusercontent.com/assets/5955396/7198803/e719b458-e4ef-11e4-968d-9c0eea2dc7be.jpg)

**Comment by richard-jones** [comment]
Do you mind if I reset the password for this account and log in?  I don't see the problem on my own account, but I don't have any reapplications, so would be useful to look at an account where the problem manifests.

**Comment by dommitchell** [comment]
Please do. I had just reset it myself. Maybe that was the problem?

**Comment by richard-jones** [comment]
Fixed for next PR

**Comment by dommitchell** [comment]
@richard-jones What was the problem here and how can I test it is fixed?

**Comment by richard-jones** [comment]
If, as a publisher, you can see the list of reapplications, then this is fixed

**Comment by dommitchell** [comment]
Tested! Closing.
