### ISSUE TITLE
Changing order by relevance dropdown doesn't work

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#666]
Changing the item in the dropdown to Date Applied produces page loading bar but page doesn't load

![datechanged](https://cloud.githubusercontent.com/assets/5955396/7201645/e476a0d4-e509-11e4-930a-8e9130986ea7.jpg)

**Comment by richard-jones** [comment]
Replicated.  The configuration for the sort is just slightly wrong.  I'm going to do a quick review of all of the admin/publisher area facetviews and make sure that they are up to date with all the latest data model changes (e.g. the title sorting, etc)

**Comment by richard-jones** [comment]
Fixed in next PR

**Comment by dommitchell** [comment]
Great, Closing
