### ISSUE TITLE
Subjects display in search results

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#67]
Currently, search results for journals display all the subjects that a journal is categorised in. So, for example, for the International Journal of Advances in Computing and Information Technology:

http://www.doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%22International%20Journal%20of%20Advances%20in%20Computing%20and%20Information%20Technology%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22_type%22:%22journal%22}}]}}}}}#.UtPqBbQWT7k

the following subjects are displayed:

Information technology, Industrial engineering. Management engineering, Technology (General), Technology, Computer Science, Technology and Engineering, Electronic computers. Computer science, Instruments and machines, Mathematics, Science, Computer Science, Technology and Engineering

Some work is needed to make this display more intuitive. The wish is that only the LCC codes are displayed and everything else is suppressed. All codes should be retained for future reference however.

EDIT by @emanuil-tolev: it's been decided that all DOAJ codes should be simply dropped, wrt the last sentence above.

**Comment by richard-jones** [comment]
In the current preview version of the journal display, I have just displayed the subjects as a list in whatever order they have been stored.  This might not meet our requirements, but I'm unsure what the "right" solution is.

The only thing that I have in my head is that we could put the subjects in an expand/collapse block like we do with the article abstracts, and within that block show the subjects as a (nested) list, which mimics their position in the subject tree.  Users without an understanding of the subject tree might not understand this.

Perhaps a discussion at the next meeting required?

**Comment by richard-jones** [comment]
Use only subject.terms for display, where subject.schema=LCC

**Comment by richard-jones** [comment]
This is basically the same issue as #581 which should now be resolved.

**Comment by dommitchell** [comment]
If possible, I'd like to find a simple way of denoting two things:
1) that Political science (General) is a child of Political science. Can we separate then with a colon?
Open Political Science Journal
ISSN: 1874-9496
http://bentham.org/open/topolisj/
Subjects:
Political science (General), Political science

becomes
Open Political Science Journal
ISSN: 1874-9496
http://bentham.org/open/topolisj/
Subject Political science: Political science (General)

(Note: 'Subjects:' on its own line, becomes 'Subject' on the same line, no colon.

2) where two categories are distinctly different eg
DETUROPE
the Central European Journal of Regional Development and Tourism
ISSN: 1821-2506
http://www.deturope.eu
Subjects:
Urban groups. The city. Urban sociology, Recreation. Leisure

becomes
DETUROPE
the Central European Journal of Regional Development and Tourism
ISSN: 1821-2506
http://www.deturope.eu
Subject Urban groups. The city | Urban sociology, Recreation. Leisure

**Comment by richard-jones** [comment]
Hm, that should be possible, though some fiddly code required.  Leave it with me for the moment and I'll see what I can do.

**Comment by richard-jones** [comment]
I've opted for an on-save calculation of the classification, to save having to load the LCC data into the user's browser to do the work.

Will be ready for review in my next major PR later this week.

**Comment by dommitchell** [comment]
Subjects are missing completely from search results #161

**Comment by richard-jones** [comment]
Yup, problem with data migration this week - will appear when that's resolved

**Comment by richard-jones** [comment]
See #637 - will be resolved when that is resolved

**Comment by richard-jones** [comment]
This should now be fixed

**Comment by dommitchell** [comment]
Good! Closing!
