### ISSUE TITLE
Old version of public application form

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#670]
We seem to be running an older version of the application form. Questions 14 and 18 are not required and have no asterisk next to them:

https://testdoaj.cottagelabs.com/admin/suggestion/00059927f5a148bfa87ca97258a50432#first_problem

**Comment by dommitchell** [comment]
Ignore me....

**Comment by richard-jones** [comment]
Phew.  That one raised a bit of panic, as we haven't really touched that
bit of code (just the text changes)!

On 17 April 2015 at 13:37, dommitchell <notifications@github.com> wrote:

> Ignore me....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DOAJ/doaj/issues/670#issuecomment-93977652>.
>



-- 

Richard Jones,

Founder, Cottage Labs
t: @richard_d_jones, @cottagelabs
w: http://cottagelabs.com
