### ISSUE TITLE
Remove status from AssEd view

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#671]
Can we hide 'Reapplication in progress' from the Assed view of the re/application form as well?

So then Asseds will only see 'Reapplication submitted' Pending and In progress

**Comment by richard-jones** [comment]
@dommitchell - just to be clear, we'll be removing the ability for the Associate Editor to see or set the status "Reapplication in Progress" in their edit interface.  As we've already seen, there's a minor issue here in that if someone without permission to see the current status of the application looks at it, it will show them the wrong thing (I can't find the related issue, sorry!).

I propose the following, then:

1. Make the change as described above in this issue

2. Make it such that if an application is in a status not visible to the current user that the pull-down is fully disabled/invisible, and shows the correct status.

How does that sound?

**Comment by dommitchell** [comment]
The idea is to remove the confusion caused by 'Reapplication in progress' and 'In progress' for AssEds. AssEds shouldn't worry about the difference here. Question first:

> Make it such that if an application is in a status not visible to the current user that the pull-down is fully disabled/invisible, and shows the correct status.

But will the AssEd still be able to then switch the status once they are finished their review?

**Comment by richard-jones** [comment]
> But will the AssEd still be able to then switch the status once they are finished their review?

If that's the requirement, then we'll figure out a way for that to happen.  Might be a bit more fiddly, but I'll let you know how we get on.

**Comment by dommitchell** [comment]
@greboun Tom, in the current workflow, when an Assed is finished with their review, they don't change the status do they? They simply alert the Editor to let them know it is ready.

**Comment by greboun** [comment]
That is correct, but the request was that ass editors can alert their
editors that they are finished reviewing by introducing a new status review
completed or something like that.
We have discussed this a few weeks ago

TOM

Dr. Tom Olijhoek
Editor-in-Chief  DOAJ

**Comment by dommitchell** [comment]
Tom to work out the naming of all statuses.

**Comment by dommitchell** [comment]
Closing and transferring to #801
