### ISSUE TITLE
'Article: pub date' shouldn't be available when Journal is selected

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#672]
Not a bug per se and probably not related to PVOD

![artpubdate](https://cloud.githubusercontent.com/assets/5955396/7202341/be237da0-e511-11e4-8193-bf308b23747f.jpg)

**Comment by richard-jones** [comment]
This will require some relatively tricky fiddling about with facetview2, which could take a a day or more.  @dommitchell up to you whether you want to prioritise this or not.

**Comment by dommitchell** [comment]
Nope. Removing from tnm.
