### ISSUE TITLE
Special characters in facets

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#673]
Do we know why some special characters in facets are unable to render but they render fine in the journal long view?

![facet](https://cloud.githubusercontent.com/assets/5955396/7202470/e4c89dae-e512-11e4-8a6b-486e09245bcf.jpg)

In this example the ?? is ó https://testdoaj.cottagelabs.com/toc/1415-6555/14

**Comment by richard-jones** [comment]
Huh, weird.  I can see this on the server, but locally it is working fine.  Will do some digging.

**Comment by richard-jones** [comment]
https://testdoaj.cottagelabs.com/search?source=%7B%22query%22%3A%7B%22filtered%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22term%22%3A%7B%22_type%22%3A%22article%22%7D%7D%2C%7B%22term%22%3A%7B%22index.publisher.exact%22%3A%22ANPAD%20-%20Associa%C3%A7%C3%A3o%20Nacional%20dos%20Programas%20de%20P%EF%BF%BD%EF%BF%BDs-gradua%C3%A7%C3%A3o%20em%20Administra%C3%A7%C3%A3o%22%7D%7D%5D%7D%7D%2C%22query%22%3A%7B%22match_all%22%3A%7B%7D%7D%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D

**Comment by emanuil-tolev** [comment]
Link to server data: https://doajgate.cottagelabs.com/doaj/journal/cd79aaf6f6e34b7ba54167061786a1b3

**Comment by emanuil-tolev** [comment]
article id 6b110106ed5a416b863b2f5a8496909a for search

**Comment by emanuil-tolev** [comment]
https://testdoaj.cottagelabs.com/query/journal,article/_search?&callback=jQuery19106188695630989969_1429285473729&source=%7B%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%226b110106ed5a416b863b2f5a8496909a%22%2C%22default_operator%22%3A%22AND%22%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%2C%22facets%22%3A%7B%22_type%22%3A%7B%22terms%22%3A%7B%22field%22%3A%22_type%22%2C%22size%22%3A102%2C%22order%22%3A%22reverse_term%22%7D%7D%2C%22index.classification.exact%22%3A%7B%22terms%22%3A%7B%22field%22%3A%22index.classification.exact%22%2C%22size%22%3A110%2C%22order%22%3A%22count%22%7D%7D%2C%22index.license.exact%22%3A%7B%22terms%22%3A%7B%22field%22%3A%22index.license.exact%22%2C%22size%22%3A110%2C%22order%22%3A%22count%22%7D%7D%2C%22index.publisher.exact%22%3A%7B%22terms%22%3A%7B%22field%22%3A%22index.publisher.exact%22%2C%22size%22%3A110%2C%22order%22%3A%22count%22%7D%7D%2C%22index.language.exact%22%3A%7B%22terms%22%3A%7B%22field%22%3A%22index.language.exact%22%2C%22size%22%3A110%2C%22order%22%3A%22count%22%7D%7D%7D%7D&_=1429285473730

**Comment by emanuil-tolev** [comment]
this is coming back from /query

jQuery19108369465197902173_1429285637790({"hits": {"hits": [{"sort": ["cd79aaf6f6e34b7ba54167061786a1b3"], "_type": "journal", "_source": {"index": {"publisher": ["ANPAD - Associa\u00e7\u00e3o Nacional dos Programas de P\u00f3s-gradua\u00e7\u00e3o em Administra\u00e7\u00e3o"], "schema_subject": ["LCC:Social Sciences", "LCC:Management. Industrial management", "LCC:Industries. Land use. Labor"], "license": ["CC BY-NC-ND"], "classification": ["Industries. Land use. Labor", "Social Sciences", "Management. Industrial management"], "title": ["Revista de Administra\u00e7\u00e3o Contempor\u00e2nea"], "country": "Brazil", "issn": ["1982-7849", "1415-6555"], "unpunctitle": "Revista de Administra\u00e7\u00e3o Contempor\u00e2nea", "has_apc": "No", "language": ["Portuguese", "English"], "homepage_url": "http://anpad.org.br/periodicos/content/frame_base.php?revista=1", "classification_paths": ["Social Sciences: Industries. Land use. Labor: Management. Industrial management"], "schema_code": ["LCC:HD28-70", "LCC:HD28-9999", "LCC:H"], "asciiunpunctitle": "Revista de Administracao Contemporanea", "subject": ["Industries. Land use. Labor", "administration", "Social Sciences", "Management. Industrial management"]}, "last_updated": "2015-04-16T14:07:38Z", "admin": {"owner": "19815700", "ticked": false, "in_doaj": true, "current_application": "bf380e65ed654e948b45c37ef2635b2d"}, "created_date": "2008-04-14T16:38:38Z", "id": "cd79aaf6f6e34b7ba54167061786a1b3", "bibjson": {"publisher": "ANPAD - Associa\u00e7\u00e3o Nacional dos Programas de P\u00f3s-gradua\u00e7\u00e3o em Administra\u00e7\u00e3o", "author_pays": "N", "license": [{"type": "CC BY-NC-ND", "title": "CC BY-NC-ND"}], "language": ["Portuguese", "English"], "alternative_title": "RAC", "author_pays_url": "http://www.scielo.br/revistas/rac/iinstruc.htm", "country": "BR", "title": "Revista de Administra\u00e7\u00e3o Contempor\u00e2nea", "oa_start": {"volume": "1", "number": "1", "year": "1997"}, "keywords": ["administration"], "link": [{"url": "http://anpad.org.br/periodicos/content/frame_base.php?revista=1", "type": "homepage"}], "provider": "ANPAD", "active": true, "oa_end": {}, "identifier": [{"type": "pissn", "id": "1415-6555"}, {"type": "eissn", "id": "1982-7849"}], "subject": [{"scheme": "LCC", "term": "Management. Industrial management", "code": "HD28-70"}, {"scheme": "LCC", "term": "Industries. Land use. Labor", "code": "HD28-9999"}, {"scheme": "LCC", "term": "Social Sciences", "code": "H"}]}}, "_score": null, "_index": "doaj", "_id": "cd79aaf6f6e34b7ba54167061786a1b3"}], "total": 1, "max_score": null}, "_shards": {"successful": 6, "failed": 0, "total": 6}, "took": 25, "facets": {"index.country.exact": {"_type": "terms", "total": 1, "terms": [{"count": 1, "term": "Brazil"}], "other": 0, "missing": 0}, "_type": {"_type": "terms", "total": 1, "terms": [{"count": 1, "term": "journal"}], "other": 0, "missing": 0}, "index.publisher.exact": {"_type": "terms", "total": 1, "terms": [{"count": 1, "term": "ANPAD - Associa\u00e7\u00e3o Nacional dos Programas de P\u00f3s-gradua\u00e7\u00e3o em Administra\u00e7\u00e3o"}], "other": 0, "missing": 0}, "bibjson.editorial_review.process.exact": {"_type": "terms", "total": 0, "terms": [], "other": 0, "missing": 1}, "index.has_apc.exact": {"_type": "terms", "total": 1, "terms": [{"count": 1, "term": "No"}], "other": 0, "missing": 0}, "index.language.exact": {"_type": "terms", "total": 2, "terms": [{"count": 1, "term": "Portuguese"}, {"count": 1, "term": "English"}], "other": 0, "missing": 0}, "index.license.exact": {"_type": "terms", "total": 1, "terms": [{"count": 1, "term": "CC BY-NC-ND"}], "other": 0, "missing": 0}, "created_date": {"_type": "date_histogram", "entries": [{"count": 1, "time": 1199145600000}]}, "index.classification.exact": {"_type": "terms", "total": 3, "terms": [{"count": 1, "term": "Social Sciences"}, {"count": 1, "term": "Management. Industrial management"}, {"count": 1, "term": "Industries. Land use. Labor"}], "other": 0, "missing": 0}, "bibjson.archiving_policy.policy.exact": {"_type": "terms", "total": 0, "terms": [], "other": 0, "missing": 1}}, "timed_out": false})

**Comment by richard-jones** [comment]
We've looked into this, and it's because some of the articles have broken publisher data.  There's unfortunately nothing we can do about it - it's a data cleanup task!

**Comment by dommitchell** [comment]
The publisher data displayed in the article view is the data, as it is uploaded by the publisher and not the name of the publisher that you see displayed in the journal homepage.

**Comment by dommitchell** [comment]
No longer an issue. Closing
