### ISSUE TITLE
Will Chinese characters break the CSV upload?

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#680]
A publisher has presented a theory that Chinese characters are breaking the CSV upload:

"With respect to the guidance file, I have read them carefully and didn’t do anything that may invalidate the CSV file. I am wondering if [the problem] is caused by the Chinese alternative titles I filled in question 3. My problem at present is like the following:

If I open the CSV via MS EXCEL and change the file to be in the Unicode UTF8 format, the status will change to be like the screenshot below and no feedback will come to me:

![image1](https://cloud.githubusercontent.com/assets/5955396/7247307/7cf3bcec-e808-11e4-89a2-098f6984d977.jpg)

If I open the CSV via MS EXCEL, and save it as it is in ANSI format, the status will be:

![image2](https://cloud.githubusercontent.com/assets/5955396/7247319/9e5d326e-e808-11e4-8727-742a5bae4c54.jpg)

I really don’t know how to do with the CSV file. I didn’t change the issns but it seems that DOAJ’s system just can’t process my reapplication file."

Does this theory sound plausible? The blank ISSN in the first image looks suspicious.

**Comment by emanuil-tolev** [comment]
There could be various problems, such as the way the file is encoded (I did note they say they use UTF-8). Obvious question of the day, could they send you the file that they are trying to submit?

**Comment by richard-jones** [comment]
Very unlikely to be the chinese characters.  

The second error is entirely expected - if the CSV is not UTF-8 it can't be read (correctly).  

The first error looks like a problem with the column headings - we'd need to run the csv through the csv reader to find out exactly what, but my guess would be an extra column, possibly with something in the header row that isn't an issn (could even be whitespace).

**Comment by dommitchell** [comment]
After our meeting in London, we agreed that I would analyse the ISSNs in the spreadsheet. I logged in as the publisher and tried to download their CSV file but it returned a 404 Not Found error:

https://doaj.org/publisher/bulk_download/21607311.csv

Could that be causing the problem here?

**Comment by dommitchell** [comment]
p.s no whitespaces or oddities in the publisher-edited csv file as it stands now

**Comment by emanuil-tolev** [comment]
> Could that be causing the problem here?

Looking at the code it looks at who the **current** user is and thus who is allowed to download the file. So you would need to be that publisher to see the file.

Those files are meant only as a way of starting the reapplication process, I don't think they are required in any fashion during processing of CSV uploads - the code knows what format the CSVs should follow.

**Comment by emanuil-tolev** [comment]
> Looking at the code it looks at who the current user is and thus who is allowed to download the file. So you would need to be that publisher to see the file

OK, thanks for the credentials. I can download this file now - there was something which might have caused you (and the publisher) to be unable to download it but that should be fixed now. So you can get the file if you try again. 

I still don't think this is the cause for the issue as these files are not read in by the DOAJ system - they are only served to publishers. Publishers fill them out, then upload the modified versions to DOAJ - and that is what we deal with when processing.

**Comment by richard-jones** [comment]
@dommitchell - assigning this back to you for the moment.  Let me know as and when you need us to look at it.

**Comment by dommitchell** [comment]
on hold

**Comment by dommitchell** [comment]
This was fixed with #861
