### ISSUE TITLE
Some things we want the API to enable/facilitate

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#681]
*DISCOVERY*
Finding (and retrieving) articles, journals on DOAJ
Publisher: journal, article, applications
Search on author affiliation
APCs: range query
Author names
No faceting via the search interface
Wrapper

CRUD
Create Retrieve Update Delete

Bulk applications
Bulk article metadata upload ("ability to send the XML in a programmatic way. Web API" " to develop and publish an API to allow the implementation of a 100% automated metadata submission process."

"We want to build a web form to check the eligibility criteria; hereby we want to interrogate the journal to be listed in the DOAJ (via ISSN). Something like that, of another university: https://www.ruhr-uni-bochum.de/oa/apply/" This is a simple ISSN query.

"Is the DOAJ available as federated search, via an API, or other open protocols such as Z39.50 or other ways of incorporate the DOAJ into search-portals such as Ex Lbris’ Metalib?" We would rather just offer the API and then see if this specific use-case still exists.

"We need an API which works or can be used like a web service (e.g. REST)."

**Comment by richard-jones** [comment]
Adding this to the API milestone so it can be tracked and closed off alongside

**Comment by dommitchell** [comment]
Closing
