### ISSUE TITLE
View user's journal doesn't return results

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#683]
https://doaj.org/account/21608288 where [View a list of this user's journals] returns all journals in DOAJ https://doaj.org/admin/journals?source={%22query%22%20:%20{%22bool%22%20:%20{%22must%22%20:%20[{%22term%22%20:%20{%22admin.owner.exact%22%20:%20%2221608288%22}}]}}}

**Comment by richard-jones** [comment]
Ah damn, sorry, missed that one

**Comment by richard-jones** [comment]
in forthcoming hotfix
