### ISSUE TITLE
Better crawl error response for the OAI endpoint

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#684]
Some errors for OAI produce a 502 error. We should have a better response.

https://www.google.com/webmasters/tools/crawl-errors?hl=en&siteUrl=http%3A%2F%2Fdoaj.org%2F&pli=1&authuser=1

and

https://www.google.com/webmasters/tools/crawl-errors?hl=en&siteUrl=http%3A%2F%2Fdoaj.org%2F&pli=1&authuser=1#t1=0&t2=1

**Comment by richard-jones** [comment]
These requests are erroneous requests to the OAI endpoint - the callers aren't using the "set" parameter correctly, which is causing the error.

The 502 is unfortunate - we should have a better error response

**Comment by dommitchell** [comment]
Just adding this to the other OAI stuff under tnm. Don't think this would be tnm though, right?

**Comment by richard-jones** [comment]
I'm not sure if this was done with the other OAI stuff, so just putting it back under tnm to investigate

**Comment by richard-jones** [comment]
This was an issue whereby invalid set parameters being passed in by users using the OAI-PMH endpoint incorrectly where causing a complex character encoding issue.

In summary, an arbitrary string can be a valid base64 encoded string, but when decoded produces a string with unicode characters which may be invalid.  On conversion from a string to unicode, a unicodedecodeerror would be thrown, causing the 502 the users were experiencing.

This has now been replaced by a more methodical detection of encoding problems in the set parameter, and a suitable badargument exception in line with the OAI-PMH spec is sent.
