### ISSUE TITLE
Default search operator is OR from home page and doesn't switch to AND

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#685]
Two things:
- [x] The default operator from the home page quick search is OR and should be AND. Beilstein Journal of Organic Chemistry from the homepage returns:
Journals (7175)
Articles (1620937)

https://doaj.org/search?source={%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22Beilstein%20Journal%20of%20Organic%20Chemistry%22%2C%22default_operator%22%3A%22OR%22}}%2C%22from%22%3A0%2C%22size%22%3A10}#.VUomCZN2N64

- [x] I carry out the search above, from the home page, and get taken to the URL above. I then click into the search box and hit enter to do the search again and the search results stay the same but the URL changes to https://doaj.org/search?source={%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22Beilstein%20Journal%20of%20Organic%20Chemistry%22%2C%22default_operator%22%3A%22OR%22}}%2C%22from%22%3A0%2C%22size%22%3A10}. If I then clear all search settings and do the search again, I get this URL https://doaj.org/search?source={%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22Beilstein%20Journal%20of%20Organic%20Chemistry%22%2C%22default_operator%22%3A%22AND%22}}%2C%22from%22%3A0%2C%22size%22%3A10} with these results:
Journals (1)
Articles (1467)
which is the more correct and precise search result I was looking for. Is this a bug?

**Comment by dommitchell** [comment]
DRAFT: ignore for now. I might come back to this.

**Comment by richard-jones** [comment]
Default operator has been set to AND site-wide already, and seems to be working fine for me.

**Comment by dommitchell** [comment]
Updated the original comment. Have pinned down what I was seeing before that I couldn't quite fathom

**Comment by richard-jones** [comment]
Oh, I see - it's just the search link from the front page which is specifying OR rather than AND.  Should be a trivial fix, I'll sort that out soon.

**Comment by dommitchell** [comment]
Great!
