### ISSUE TITLE
Google's perception of DOAJ's mobile friendliness

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#692]
Here's a tool to test any page for mobile friendliness in Google's almighty eyes:

https://www.google.com/webmasters/tools/mobile-friendly/?url=https%3A%2F%2Fdoaj.org%2F

I tested our journal (toc) and article pages and they found absolutely no problem, as well as no problem on the homepage. They did, as expected find some stuff on the /search , no idea how important _they_ think that page is to our site - clearly they have tens of thousands (now will go into millions) of other URLs from us which are "friendly".

**Comment by emanuil-tolev** [comment]
Mobile dev guidelines by Google: https://developers.google.com/webmasters/mobile-sites/mobile-seo/?hl=en-US&utm_source=MFT&utm_medium=incoming-link&utm_campaign=MFT

(very technical so probably not extremely useful to you Dom, but to devs, very useful - one of the best darn mobile dev guidelines pages I've ever seen)

**Comment by richard-jones** [comment]
Is any further action required on this?

**Comment by emanuil-tolev** [comment]
Not immediate, we continue to get a 100 score for most pages but the search page could use some improvements - not necessarily by a designer, though that would help. It's more about using it for 30-60 min in various ways on a phone and tablet, and fixing the problems, auch as libnks a little too close (Google detects this too), page scrolls when you hit next page of results, anything else detected by Google. Just a placeholder for later work when there are resources for it.
