### ISSUE TITLE
OpenURL does not respect in_doaj

### ISSUE THREAD

**Issue by Steven-Eardley** [DOAJ/doaj#694]
OpenURL requests are successfully finding the item in the journal index on search, redirecting to the TOC page, which doesn't render (because in_doaj is false) so the normal 404 page is shown. 

e.g. https://doaj.org/doaj?func=openurl&genre=journal&issn=15593053

Fix with a filter for ```in_doaj = True```

**Comment by richard-jones** [comment]
@Steven-Eardley - is this now working in live?

**Comment by Steven-Eardley** [comment]
Yes, the OpenURL part works as intended. However, I might've uncovered another issue with the TOC!
