### ISSUE TITLE
Bug in Toc generation: page numbers incorrect

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#703]
Unfortunately the ToCs are showing the incorrect page range. The first page is repeated and the last page is missing. This is not a problem in search results or on the article homepages. Only the ToCs. For example:

'After you launched the new design of your website we noticed that the page range for all published articles become 1-1, would you please check and correct? https://doaj.org/toc/2314-5234'

https://doaj.org/toc/2013-0953

https://doaj.org/toc/2014-4806

![screeny shot 27-4-2015 12 26 28](https://cloud.githubusercontent.com/assets/5955396/7387839/e38a938c-ee60-11e4-9909-158a993981fc.png)

**Comment by richard-jones** [comment]
@markmacgillivray could you take a look at this one relating to the code that you added to the ToC page please

**Comment by markmacgillivray** [comment]
In this line of this file:

https://github.com/DOAJ/doaj/blob/develop/portality/templates/doaj/toc.html#L491

the two instances of start_page should say end_page

@richard-jones @emanuil-tolev do you want me to start a separate branch for this and send in a pull request or does one of you want to incorporate it into any current work you have? If I am to start a separate branch, where should I branch from? e.g. are you running develop at the moment or do you want it from master, or somewhere else?

**Comment by emanuil-tolev** [comment]
> If I am to start a separate branch, where should I branch from?

Just from develop. So pull latest develop, branch, code, PR (your new branch against develop).

**Comment by richard-jones** [comment]
fixed in develop, will be ready for review on live shortly

**Comment by richard-jones** [comment]
@emanuil-tolev can you assign this to @dommitchell when it's been rolled out for me.

**Comment by richard-jones** [comment]
gah, github auto-closing issues.

**Comment by emanuil-tolev** [comment]
Ready for review on live! looks like it's worked

**Comment by dommitchell** [comment]
Smashing!
