### ISSUE TITLE
Admins can't view some ToCs because ToCs require in_doaj

### ISSUE THREAD

**Issue by Steven-Eardley** [DOAJ/doaj#705]
If you look for a journal with ```in_doaj = False``` via the admin search, the ToC will not appear (404), because it's not ```in_doaj```.

**Comment by emanuil-tolev** [comment]
Mmh. I'd argue tocs are part of the public part of the site. I understand the point of this issue but I'm not sure it's a great idea to let admins see different things that are explicitly not under the /admin URLs. They'd have to log out of their accounts all the time to investigate user queries, and might forget, etc. 

Also what would be the use of them being able to see a ToC the public can't see? If there's a problem with a ToC usually everybody can see it and it gets corrected, er, while in the public spotlight, so to speak. Can't really think of any other use cases... ultimately up to @dommitchell if he considers that admins should be able to view ToCs that aren't public.

**Comment by Steven-Eardley** [comment]
Good points - I was in two minds about whether it's a bug or by design.

**Comment by richard-jones** [comment]
Admins couldn't view tocs for not public pages before, so this is
definitely not a bug.  If admins need to see withdrawn journal tocs, then
it's a new feature :)
