### ISSUE TITLE
Question: Add text to APC facet

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#706]
Just a question for now: is there a way to add text to a facet that will permit a link out to explanatory information on what the facet does and doesn't show?

**Comment by richard-jones** [comment]
Yes, technically no problem, but the current software doesn't have a "space" for this kind of information, so we'd need to make modifications to how it worked to support it.

**Comment by emanuil-tolev** [comment]
Also I would consider a tooltip over a linkout. In this case accessibility is not an issue (a usual problem with tooltips) since the whole interface is Javascript-based + there are really easy to use tooltip components around now.
