### ISSUE TITLE
Review the help text on the search page

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#71]
See #70 . Looks like the help has outdated information. We should review it and remove that info, it confuses users, understandably.

**Comment by richard-jones** [comment]
In the new version of facetview, the help button "?" has been removed, because it was far too technical for end users.  Therefore, for this issue what we should consider is what on-page/hover text help we should provide; most of the buttons already provide hover-text, so we just need to review that.  Then, do we need any additional text permanently displayed on the page to help users?

**Comment by dommitchell** [comment]
DM to review this once the new interface is up.

Change default from OR to AND.

**Comment by richard-jones** [comment]
Decision: switch the default operator to AND to reduce search results

**Comment by richard-jones** [comment]
All I've done is switch the default operator - let me know if that's sufficient for improving the results.

Also, note that I've only done this on the public search - the admin/editor/publisher searches still us OR as the default operator; let me know if you also want them switched.

**Comment by dommitchell** [comment]
> what on-page/hover text help we should provide; most of the buttons already provide hover-text, so we just need to review that.

What scope is there for developing this further, so that pop-ups display if users hover over for slightly longer?

Can we add a link 'Help with searching', under the search box, that links to a static page?

**Comment by richard-jones** [comment]
At the moment the popups are "tool tips" implemented by the browser (you just give the html element the text to use).  If we wanted popups that appear only after a certain amount of time, that would be a bit more work, as we'd need to add the javascript and new layout elements to handle this.

Note to self: Here are a couple of useful resources if we need to go this route:
http://jsfiddle.net/qSe6t/3/
http://stackoverflow.com/questions/15694235/popup-window-on-hover-using-jquery

We could also add a "Help with searching" link that goes to a static page, but experience tells us that no one will ever read it.  Instead the public search should be as straightforward as possible, and any buttons that might be ambiguous or difficult to immediately understand should have tool-tips.

**Comment by dommitchell** [comment]
Did you only change to AND on test, or in live too? Between the two I am only seeing a marginal difference and am not sure if that's the switch to AND or just that the test site has less content. I was hoping the switch to AND would have a greater effect.

https://doaj.cottagelabs.com/search?source={%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22International%20Journal%20of%20Medical%20Science%22%2C%22default_operator%22%3A%22AND%22}}%2C%22from%22%3A0%2C%22size%22%3A10}
vs
http://doaj.org/search?source={%22query%22:{%22query_string%22:{%22query%22:%22International%20Journal%20of%20Medical%20Science%22,%22default_operator%22:%22AND%22}}}

or
https://doaj.cottagelabs.com/search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22journal%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22journal%20of%20advanced%20science%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
vs
http://doaj.org/search?source={%22query%22:{%22filtered%22:{%22query%22:{%22query_string%22:{%22query%22:%22journal%20of%20advanced%20science%22,%22default_operator%22:%22AND%22}},%22filter%22:{%22bool%22:{%22must%22:[{%22term%22:{%22_type%22:%22journal%22}}]}}}}}

**Comment by richard-jones** [comment]
Yes, it seems like we'd already set live to AND a while back, and then forgot about it!

In which case we should consider what other changes we could implement.  To recap, we have already considered the following:

1. Context sensitive help on constraining the search - if the user has text in the search box and more than X results, show them a "how to reduce your results" help text

2. Any additional help text required on hover over buttons

**Comment by dommitchell** [comment]
@richard-jones first, I'd like to be able to do a comparison. Is test on AND too? Ideally, test and live will be different so I can compare effectiveness.

**Comment by dommitchell** [comment]
Something for later..

**Comment by richard-jones** [comment]
New facetview rolled out which makes this issue obsolete
