### ISSUE TITLE
122 double values with OAI_PMH calls wth resumptiontokens

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#712]
Other 121 examples sent in email

/start/
f.i. we get issn 0048-7651 in set with call cursor 5900 and in set with call cursor 6000

5900 eyJtIjogIm9haV9kYyIsICJuIjogNjAwMH0= 0048-7651
6000 eyJtIjogIm9haV9kYyIsICJuIjogNjEwMH0= 0048-7651

Cursor 5900

https://doaj.org/oai?verb=ListRecords&resumptionToken=%20eyJtIjogIm9haV9kYyIsICJuIjogNjAwMH0=

 

<record>

  <header>

    <identifier>oai:doaj.org/journal:6cb2c289a6814a948381dc7077092a27</identifier>

    <datestamp>2015-04-22T01:21:06Z</datestamp>

    <setSpec>TENDOkxhbmd1YWdlIGFuZCBMaXRlcmF0dXJl</setSpec>

    <setSpec>TENDOkxpdGVyYXR1cmUgKEdlbmVyYWwp</setSpec>

  </header>

  <metadata><oai_dc:dc xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">

    <dc:title>Revista Chilena de Literatura</dc:title>

    <dc:identifier>0048-7651</dc:identifier>

    <dc:identifier>0718-2295</dc:identifier>

    <dc:identifier>https://doaj.org/toc/0718-2295</dc:identifier>

    <dc:relation>http://www.revistaliteratura.uchile.cl/index.php/RCL/about/submissions#authorGuidelines</dc:relation>

    <dc:publisher>Universidad de Chile</dc:publisher>

    <dc:relation>http://www.revistaliteratura.uchile.cl/</dc:relation>

    <dc:publisher>OJS</dc:publisher>

    <dc:date>2005-08-24T13:01:05Z</dc:date>

    <dc:type>journal</dc:type><dc:subject>literature</dc:subject>

    <dc:subject xsi:type="dcterms:LCSH">Language and Literature</dc:subject>

    <dc:subject xsi:type="dcterms:LCSH">P</dc:subject>

    <dc:subject xsi:type="dcterms:LCSH">Literature (General)</dc:subject>

    <dc:subject xsi:type="dcterms:LCSH">PN1-6790</dc:subject></oai_dc:dc>

  </metadata>

</record>

 

--cursor 6000

https://doaj.org/oai?verb=ListRecords&resumptionToken=eyJtIjogIm9haV9kYyIsICJuIjogNjEwMH0=

<record>
  <header>
    <identifier>oai:doaj.org/journal:6cb2c289a6814a948381dc7077092a27</identifier>
    <datestamp>2015-04-22T01:21:06Z</datestamp>
    <setSpec>TENDOkxhbmd1YWdlIGFuZCBMaXRlcmF0dXJl</setSpec>
    <setSpec>TENDOkxpdGVyYXR1cmUgKEdlbmVyYWwp</setSpec>
  </header>
  <metadata><oai_dc:dc xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
    <dc:title>Revista Chilena de Literatura</dc:title>
    <dc:identifier>0048-7651</dc:identifier>
    <dc:identifier>0718-2295</dc:identifier>
    <dc:identifier>https://doaj.org/toc/0718-2295</dc:identifier>
    <dc:relation>http://www.revistaliteratura.uchile.cl/index.php/RCL/about/submissions#authorGuidelines</dc:relation>
    <dc:publisher>Universidad de Chile</dc:publisher>
    <dc:relation>http://www.revistaliteratura.uchile.cl/</dc:relation>
    <dc:publisher>OJS</dc:publisher><dc:date>2005-08-24T13:01:05Z</dc:date>
    <dc:type>journal</dc:type><dc:subject>literature</dc:subject>
    <dc:subject xsi:type="dcterms:LCSH">Language and Literature</dc:subject>
    <dc:subject xsi:type="dcterms:LCSH">P</dc:subject>
    <dc:subject xsi:type="dcterms:LCSH">Literature (General)</dc:subject>
    <dc:subject xsi:type="dcterms:LCSH">PN1-6790</dc:subject></oai_dc:dc>
  </metadata>
</record>
Is this an error in DOAJ-protocol?

/ends/

**Comment by richard-jones** [comment]
One reason this could happen is that journals get added in between requests, which shifts the paging over the result set.  But that does seem like a lot of duplicate entries.  I'll take a closer look, it could just be an overlap in the paging parameters, causing the bottom of one list to appear at the top of the next.

For the record, I can't reproduce the first example now.

**Comment by dommitchell** [comment]
From the customer:

Neither do I. The problem with 122 seems to be vanished. I can’t reproduce.
Now I get only one double ISSN = '2008-1359'

But this also occurs in the ‘static’ download file. Feel free to close.
