### ISSUE TITLE
Request to delete articles: Hindawi

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#713]
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222015%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%201687\\-0042%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222014%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%202314\\-503X%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222015%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%202314\\-503X%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222014%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%202090\\-9071%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222015%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%202090\\-9071%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222014%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%202314\\-6753%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222015%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%202314\\-6753%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222014%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%201687\\-4129%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222015%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%201687\\-4129%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222014%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%202314\\-4858%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222014%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%202090\\-0716%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222014%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%201687\\-8469%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222015%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%201687\\-8469%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222014%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%202090\\-0058%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222015%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%202090\\-0058%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}

https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222014%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%201687\\-7268%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222015%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%201687\\-7268%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222014%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%202314\\-4939%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222015%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%202314\\-4939%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222014%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%201563\\-5147%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222015%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%201563\\-5147%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222014%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%201466\\-1861%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222015%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%201466\\-1861%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222015%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%201875\\-905X%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222014%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%201687\\-5605%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222014%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%201687\\-5443%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222015%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%201687\\-5443%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222015%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%202090\\-1437%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222014%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%201942\\-0994%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222015%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%201942\\-0994%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222014%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%202042\\-0080%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222015%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%202042\\-0080%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222014%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%201687\\-4765%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222014%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%201687\\-6083%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222015%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%201687\\-6083%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222015%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%201875\\-919X%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222014%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%201687\\-9678%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222015%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%201687\\-9678%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222014%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%201537\\-744X%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222015%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%201537\\-744X%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}

**Comment by dommitchell** [comment]
I have these in a spreadsheet. Would that be easier?

**Comment by dommitchell** [comment]
Can we please schedule this for a fixed date so that the publisher can start uploading new content as soon as the deletes are ready? Thanks!

**Comment by emanuil-tolev** [comment]
Done, finally. Review? (I did by clicking all the links, all seem gone.)
