### ISSUE TITLE
Request to delete articles: Caligrama

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#714]
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%220103\\-2178%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}

550 articles

**Comment by richard-jones** [comment]
@dommitchell - bouncing this back to you for action when the bulk delete is rolled out

**Comment by dommitchell** [comment]
Done
