### ISSUE TITLE
iOS highlighting ISSNs as phone numbers

### ISSUE THREAD

**Issue by Steven-Eardley** [DOAJ/doaj#719]
I came across this when testing on my iPad - apparently Apple uses a fairly unintelligent way to highlight phone numbers so that they can be called directly on the phone, which also catches ISSNs. I've looked into this; apparently it can be fixed with a meta tag in the header (which is shared across all pages):

```<meta name="format-detection" content="telephone=no" />```

i.e. turning the format detection for phone numbers off.
@dommitchell, please let me know if you'd like this change to be applied. If there are any phone numbers you *would* like to be highlighted, this will disable those (but I can't see any).

**Comment by dommitchell** [comment]
@Steven-Eardley hello! Yes, if this can be done quickly and without cost then please do go ahead. Always good to eliminate confusion for the user.

**Comment by Steven-Eardley** [comment]
Done and deployed to live. I've confirmed my devices no longer highlight the ISSNs as phone numbers.
