### ISSUE TITLE
Display within restricted access university domain

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#721]
/starts/
We have limited-access workstations that we use for teaching in our
> libraries, which are managed with a whitelist.  We have an entry
> *doaj.org in our whitelist.  While we get to your site and can use it,
> the page display is off- the header doesn’t display properly, and some
> links and portions of the screen overlap, causing confusion.  Is there
> an additional address we should add to the whitelist to improve access to your site?
/ends/

![doajresults](https://cloud.githubusercontent.com/assets/5955396/7772452/91e32e36-009e-11e5-8b87-1296bb905b4c.JPG)
![doajhome](https://cloud.githubusercontent.com/assets/5955396/7772453/91e93614-009e-11e5-8997-f75535c4de32.JPG)

**Comment by richard-jones** [comment]
They're missing some of the css, though difficult to say which.  Probably
the ones served by the google cdn, so a similar problem to your Chinese
users.

**Comment by dommitchell** [comment]
Thanks! Is there a URL or something that they can add to their safelist that will allow the css to work?

**Comment by emanuil-tolev** [comment]
Ideally all URLs under

http://netdna.bootstrapcdn.com
https://netdna.bootstrapcdn.com
http://ajax.googleapis.com/
https://ajax.googleapis.com/

Though why you'd block these is beyond me.

**Comment by emanuil-tolev** [comment]
Serve all JS and CSS locally. Also update China issue when this is done to see what needs to eb done there above and beyond serving libraries locally.

**Comment by richard-jones** [comment]
@emanuil-tolev - ok to go ahead under tnm for this one.  We don't have a proper process for this yet, but if you could let me know how long you spend on it, I'll start up a sheet to track that information.

**Comment by dommitchell** [comment]
Awaiting feedback from librarian

**Comment by richard-jones** [comment]
Changed the name of the issue to pertain to what we need to do to fix

**Comment by dommitchell** [comment]
Have now had confirmation from the library that those URLs you provided fixed the display issues:

> http://netdna.bootstrapcdn.com
> https://netdna.bootstrapcdn.com
> http://ajax.googleapis.com/
> https://ajax.googleapis.com/

**Comment by emanuil-tolev** [comment]
OK that's good actually because we know for certain that if are able to remove all references to external sites (I'll have to think very carefully about google analytics here) it works fine - important for China and other workplaces with restrictions like this library. Excellent news.
