### ISSUE TITLE
Add new sponsor: JMIR Publications Inc

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#731]
Link logo to http://jmirpublications.com/

![jmir](https://cloud.githubusercontent.com/assets/5955396/7832300/3a2ef44a-045e-11e5-8297-ad76257b8604.gif)

**Comment by dommitchell** [comment]
@Steven-Eardley can we get this one done today?

**Comment by Steven-Eardley** [comment]
we can! on it.

**Comment by Steven-Eardley** [comment]
Done, check on live.
