### ISSUE TITLE
Update user accounts module

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#734]
- new user role "api" - without it you're pretty much banned from the API
- [x] add api_key to user acc
- [x] UI for retrieve/reset api key
- [x] data migration to add api role to all users and generate api keys
- [x] modify existing account creation code to add api role automatically (and maybe add a key automatically - users can make a key themselves, but can't add the role, and we don't want that much manual management)

**Comment by Steven-Eardley** [comment]
@emanuil-tolev close if happy with this :)

**Comment by emanuil-tolev** [comment]
Yep let's close - if problems arise we can reopen. But looks good and it's got tests and a UI and all, so doubt it.
