### ISSUE TITLE
CRUD API - Applications

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#740]
- [ ] create [registered users, publishers]. **Not reapplications**.
- [ ] retrieve [registered users, publishers]. Publishers can see their reapplications.
- [ ] update [registered users, publishers] - until such time as they move into editorial review.
- [ ] delete [registered users, publishers] - until such time as they move into editorial review. **Reapplications may not be deleted**.

All operations which can modify data will need to support a "dry run" parameter where the operation is attempted and the same result is returned as if data had been saved (including any validation errors), but nothing actually gets written to the index. This will be available to users and should be documented, but also will be used by the Bulk API.

**Comment by emanuil-tolev** [comment]
@richard-jones Currently we're only supplying "keywords" back to the publisher who fetches a journal. I think we should include the DOAJ Editor-generated "subject" classification as well. Any reason you didn't include it in the application data object? If not I'll just add it.

**Comment by emanuil-tolev** [comment]
> publisher who fetches a journal

* who fetches an application, sorry.

**Comment by richard-jones** [comment]
I don't mind the subjects being exposed, just remember then that they still won't be able to supply those subjects themselves, so we'll have to either have an asymmetric in/out data model or just ignore any subjects they give us when they deposit (see, for example, what I've done with id, created_date, last_updated")

**Comment by emanuil-tolev** [comment]
Yeah, when ensuring parity between in/out I already had to make sure that applications on update do ignore some more fields (like suggester object and suggested_on) - presumably you were relying on the schema being stricter before. So I'll add subject as well. They can see "Classification" both on the public UI and their private facetviews so it should be displayed in the API.

**Comment by richard-jones** [comment]
@emanuil-tolev - assigning this over to you for close when you are ready.
