### ISSUE TITLE
API - Documentation framework

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#742]

**Comment by emanuil-tolev** [comment]
Docs will ideally be written by whoever is not coding that element. A framework for docs should be put in place and instructions put here to make it easy for anybody coding a part of the API to just add their section in with minimal effort, and still gain any styling, demo functionality (if there is any) and consistency with the other sections.

**Comment by emanuil-tolev** [comment]
If @Nimphal is available (TBA), I just need to do a bit of brainstorming with her about the API docs look, feel, location, then she can take over making a nice foundation page to which we easily add bits.

**Comment by emanuil-tolev** [comment]
> If @Nimphal is available (TBA)

she is working on this now, confirmed

**Comment by emanuil-tolev** [comment]
@Nimphal the next steps after #783 is merged are:

- integrate swagger-ui's dist folder into the DOAJ somehow. We can pair on this if you want, but roughly the whole dist folder should probably go under /portality/static/portality/vendor/swagger-ui . Then the index.html from the dist folder needs to be converted to a DOAJ page if possible - move index.html from the dist folder to a template - portality/templates/api/v1/docs.html might be good (does not exist now). Take care of any CSS and JS includes - the DOAJ's base.html **should** have a way of inserting these already. Then change the portality/view/api_v1.docs view function to render the new template.
- customise the docs like e.g. the colours should probably be DOAJ's and some of the swagger branding will go from the top and bottom. Essentially integrate it into the DOAJ's visual look and feel. I expect this to be quite smooth but if you run into incompatibilities (e.g. DOAJ overrides their styles or vice versa) let me know - there is an option to host this as a totally separate page and just apply DOAJ branding sparsely to the top. We can integrate it "properly" later, for now it's important to just get it working.

FYI I've written a proper swagger config for the search route (not one from a POST example) and the live demos work!! So you can GET /api/v1/search/{search_type}/{search_query} directly from the swagger ui, and it works, which is quite exciting.

**Comment by emanuil-tolev** [comment]
@Nimphal , @richard-jones makes a good point here https://github.com/DOAJ/doaj/pull/787#issue-92634389 . There is usually some space in API docs to have some blurb of text and examples. Overall comments as per call today.

**Comment by richard-jones** [comment]
@emanuil-tolev can this one be closed?
