### ISSUE TITLE
CRUD API - Publisher pilot

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#743]
Talk to publishers while developing the API, make sure it meets their DOAJ automation needs.

**Comment by dommitchell** [comment]
Alf, PeerJ:  yes, we would be interested in testing the new API - currently we haven't been keeping the metadata submission up to date, as I had to upload the data manually.

If there's some documentation already written that I could look at, that would be great.

**Comment by dommitchell** [comment]
Dietrich and Bastien, MDPI: As soon as you have some basic documentation ready, just send
it over to my and my colleague

**Comment by dommitchell** [comment]
Markus, Springer: keep me in the loop on the development progress, I appreciate it!

**Comment by dommitchell** [comment]
Alec, PKP/OJS: we maintain the current DOAJ import/export toolset and it sounds like this would replace it with a better method, so it may not even be a net gain of code for us to maintain. Do you have some details written up? I'd love to see it.

**Comment by dommitchell** [comment]
Andy Byers, Ubiquity Press

**Comment by dommitchell** [comment]
Fabio Batalha Cunha dos Santos, Scielo:
It will be a pleasure for us to help you in testing the CRUD API.

We just need to previously have any kind of direction about how the tests will be conduct to check our availability.
