### ISSUE TITLE
Javascript widget - Simple search

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#746]
Simple search widget that will point people towards /search on DOAJ, no embedded search results.

**Comment by emanuil-tolev** [comment]
Potential load issues, but #747 would be far worse. Thoughts on server load placed there.

**Comment by Nimphal** [comment]
This is now on test, the code sample on test can be embedded wherever you like for testing pleasure :)

**Comment by Nimphal** [comment]
Actually, it seems to be having some https issues on test, so not ready yet.

**Comment by Nimphal** [comment]
Okay, not it is ready and an example can be viewed here https://testdoaj.cottagelabs.com/widgets

**Comment by emanuil-tolev** [comment]
@dommitchell looking good at URL above?

**Comment by dommitchell** [comment]
Thanks! I like it!! It looks great.

First thing I did is try to embed it in my wordpress blog and it didn't work. I know that, for example, Slideshare has Wordpress specific embed code for Wordpress. Is the code you provide at https://testdoaj.cottagelabs.com/widgets universal?

**Comment by Nimphal** [comment]
How did you include it in your wordpress? Did you edit your theme? Or did
you paste into a blogpost? If the latter, then you'd need something like
this to make it work https://wordpress.org/plugins/html-javascript-adder/ .
WordPress does not take kindly to random JS scripts in blogposts generally.
The widget is as general as they get, just some JS to be loaded. It works
when included in HTML pages (as you can see on the example page, it's
included as the example code shows). WordPress is not a standard platform
in that case and requires a bit more legwork to make custom widgets work.

2015-10-21 13:31 GMT+01:00 dommitchell <notifications@github.com>:

**Comment by dommitchell** [comment]
> Did you edit your theme? Or did you paste into a blogpost?

Yup, just pasted it in. Thanks for the guidance!

I think that this widget is good to go live whenever the time comes. Thanks @Nimphal !

**Comment by emanuil-tolev** [comment]
The live documentation page is pointing to the test server's widget, it should point to the production one.

**Comment by Steven-Eardley** [comment]
Should the we consider a transparent background (or a border) for the DOAJ logo in the widgets? This is how it looks when I chuck the simple search into a hero unit:

<img width="307" alt="screen shot 2015-10-29 at 20 56 32" src="https://cloud.githubusercontent.com/assets/1446355/10831831/be460d68-7e7f-11e5-8383-96a061231d2a.png">

**Comment by dommitchell** [comment]
Er, what's a hero unit? Sounds like Black Hawk Down.

I can ask the designer to provide?

**Comment by Steven-Eardley** [comment]
@dommitchell It's just a fancy ```div``` which is used in bootstrap css to make some content stand out: http://getbootstrap.com/2.3.2/components.html#typography

I have no idea why it was named such, and in fact it's called 'jumbotron' in the newer versions, which is apparently what those large TV displays at stadiums or concerts are called. Makes a bit more sense, but it's still a funny word.

**Comment by dommitchell** [comment]
I'm thinking we need to have the DOAJ logo on a white background since that's almost part of our colour scheme, if you will, and if we have it invisible it will disappear on non-white backgrounds. Can the border be added with html/css or should I have the designer make one?

(jumbotron... hilarious!)

**Comment by Steven-Eardley** [comment]
I think we'll just set a white background for the widgets in html/css so it covers the whole region. Are you happy to do this for yours, @Nimphal?

**Comment by dommitchell** [comment]
Sounds good to me!

**Comment by emanuil-tolev** [comment]
Sounds reasonable to set a white box for the entire widget, yes, at least until we decide to offer more design flexibility. If so we should also mention this on /widgets.
