### ISSUE TITLE
Javascript widget - controllable widget

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#747]
No freetext box, but is programmatically controllable via Javascript (passing in parameters at least) to show embedded search results from the public API.

**Comment by emanuil-tolev** [comment]
Potential source of high load. Some thoughts on the matter:

* * *

@dommitchell re: the load issue, it's actually quite hard to know that. I expect we can only reasonably see how the load is while our pilot friends are using the newly minted widget - that is to say without doing heavier-duty scalability testing, which can take quite some effort to set up. Currently my plan regarding load is:

see how pilot publishers "load" the site
from that, make some judgements on how to improve scalability (e.g. can we simply buy a third data server, can we segregate API requests somehow) if that needs to happen
let it go live if there are no major concerns, and keep monitoring the load - if there are concerns we'll discuss them during the project.
ultimately we can always shut the widgets down in emergencies. A widget means the code for it is actually downloaded from doaj.org and then that code also queries DOAJ - stop serving the widget, stop all the widget requests. Of course that'll break it on widget users' websites.
The alternative is to simulate the kind of load the widget will generate which is just too much effort for a widget. At the end of the day it's only a smallish part of the API project. Of course if load from it becomes a sticking point we'll have to discuss options of handling that - and don't forget that beyond what we can do, we can always simply ask those whose sites are too big for us to handle, to remove the widget temporarily while we work with you to decide if we want increased capability + exposure on the very high traffic site, or go without that exposure and expenditure. That way smaller widget users can keep using it and we deal specifically with problematic users, it's not an all or nothing.

**Comment by Steven-Eardley** [comment]
1. first step - copy current widget

2. functionality:
take a JS variable DOAJ_WIDGET_QUERY = "string as per Discovery API docs"
take a JS variable DOAJ_WIDGET_DOCTYPE = journal|article
display a facetview after loading all necessary libraries - JS libraries can be loaded in the JS part of the widget (use current jQuery loading as example) and CSS can be loaded in the HTML part of the widget - the less CSS files the faster the display on other websites

3. design:
        * we don't know outright how much space we have - but we might not have to think about this if facetview design works OK on smaller spaces. If it doesn't work OK we will need a new FV theme "smallwidth" or something.
        + fixed width? 200px?
        + minimum width approach? i.e. assume we at least x, but allow it to expand. Recommend a width
    * go for fixed width first, then see if we can enhance it easily or allow steps of width (140, 200, 260 etc. BS spans)
    * getting bootstrap - we create a search_widget.css as a copy of the minified Bootstrap 2 CSS, add our CSS to the bottom of that file, and pull it over like simple search does jquery
    * write an available_facetview and include it like in templates/_js_includes.html, along with the facetview2 and doaj themes

**Comment by Steven-Eardley** [comment]
The widget layout for journals (removed tick, APC, subjects, date added)

<img width="552" alt="screen shot 2015-12-02 at 14 01 38" src="https://cloud.githubusercontent.com/assets/1446355/11532712/99b355c6-98fd-11e5-8814-d72f75bc4b6a.png">

**Comment by dommitchell** [comment]
This is great!

**Comment by Steven-Eardley** [comment]
This is live now - the widgets are found on https://doaj.org/widgets and can be configured from https://doaj.org/search via the ```share | embed``` button. If you're testing the widget embedding, you can use the following template (a skeleton html page) copy in the widget code, then open it in a browser:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>widget</title>
</head>
<body>
<!-- WIDGET CODE GOES HERE -->
</body>
</html>
```

**Comment by emanuil-tolev** [comment]
Yeah, that's what I did locally to test it too. So I assume when you tried embedding the live DOAJ one that worked?

I had to split the files per environment (like Nev had done with the simple search one). It is a bit of a premature optimisation, but it does mean we don't worry about how it's served and can focus on optimising the /query endpoint in case the traffic becomes too much for us at any point.

You can leave comments directly on the code: https://github.com/DOAJ/doaj/commit/3b6d217e6a1d07481844ba95519225111cf67280 . We can rectify any problems with hotfix PRs.

**Comment by dommitchell** [comment]
When I created a test page and inserted the java code, the journal titles, which should be linked to their respective ToC page had URLs like this: 

file:///toc/2043-7129
file:///toc/1944-9771
file:///toc/1996-1944

and so on. Can you fix those?

**Comment by emanuil-tolev** [comment]
Aah, hmm. I can confirm, didn't notice that. I don't believe it's a change I made @Steven-Eardley (though see commit ref above for full details). Let me know if you're trying to fix it in here, otherwise I might have a bit of time this afternoon or tomorrow morning.

**Comment by Steven-Eardley** [comment]
I'll look now. Thanks for pointing it out, @dommitchell - I'm sure that it worked at some point!

**Comment by Steven-Eardley** [comment]
That's sorted and released. Thanks for testing, @dommitchell!

**Comment by dommitchell** [comment]
Great! Working well!
