### ISSUE TITLE
Discovery API - Pilot

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#750]
Put details here (be mindful this is a public page, don't put email addresses) of people we need / could get in touch with from the community to test our public discovery API.

**Comment by emanuil-tolev** [comment]
KVK is one. What are advantages of new API over private query endpoint? @emanuil-tolev to follow up.

**Comment by emanuil-tolev** [comment]
Uwe from KVK

- [ ] respond to "what are advantages of new API over private query endpoint KVK is currently using"
- [ ] send specs when they're up on github
- [ ] actually give URLs to the evolving api and its documentation on our test server

**Comment by dommitchell** [comment]
Dietrich and Bastien, MDPI: As soon as you have some basic documentation ready, just send
it over to my and my colleague

**Comment by dommitchell** [comment]
Markus, Springer: keep me in the loop on the development progress, I appreciate it!

**Comment by dommitchell** [comment]
Alec, PKP/OJS: we maintain the current DOAJ import/export toolset and it sounds like this would replace it with a better method, so it may not even be a net gain of code for us to maintain. Do you have some details written up? I'd love to see it.

**Comment by dommitchell** [comment]
Stephanie, ScienceOpen: We would certainly be very interested in helping to test the DOAJ API. We do not have the capacity to do so however until the end of the summer. Does that still fit into your plans?

**Comment by emanuil-tolev** [comment]
Yeah, that's fine of course, just that changes they suggest (that are not bugs) will probably go on a feature list and be prioritised for development. The CRUD API has much more scope really for piloting and changes (at least 5 days worth of such changes). But of course feedback is welcome at any stage, end of summer being just fine. We should probably set up a Google Group for API users actually, possibly one for authenticated use and one for public.

**Comment by emanuil-tolev** [comment]
OK I've got some groups now!

- an announcement-only group (e.g. we release an improved API version or we end-of-life a version): https://groups.google.com/forum/#!forum/doaj-api-announcements
- a public discussion group for the public api, so people can benefit from a public archive: https://groups.google.com/forum/#!forum/doaj-public-api
- a private discussion group for the private api, for publishers and others who can submit applications automatically or modify article metadata directly: https://groups.google.com/forum/#!forum/doaj-private-api

@dommitchell these can all be publicized. Obviously the private invite-only group is of little interest to people who don't have a DOAJ account, so feel free to send that on to those who enquire about a problem they're having with the private API.

I'm going to take the approach of copy/pasting questions I get via email into either the public or the private group, respond there, and send the asker a link to the response - that way everybody can see and search the archive if they have the same problem later.

Also I'm happy to make the private API group readable to the public, I just thought it might encourage private integrators to use it more readily if it was private. If it were publicly readable DOAJ could potentially reap the benefit of being able to convince publishers to use the private API more easily, as they would be able to see what kind of questions others had before them. Leaving that up to you - for now I'd recommend we see what feedback we get from publishers who pilot the API and post on the group (I will encourage them to do that instead of email us).

**Comment by emanuil-tolev** [comment]
Ah also todo I need to add us all as managers etc. I know I need to use @cottagelabs.com addresses for Steve and Richard, is your Google work address dom@doaj.org @dommitchell ?

**Comment by emanuil-tolev** [comment]
FYI, although it's of no use to this issue (except maybe if you want to reblog or tweet/share @dommitchell ?) our first external organic blog post about the API by the developer of "Bento Search" :). https://bibwild.wordpress.com/2015/09/23/doaj-api-in-bento_search-1-5/

**Comment by dommitchell** [comment]
> these can all be publicized.

Would it make sense to add links to them to https://doaj.org/api/v1/docs somewhere? I don't think I have access to that page via GitHub.

I have added links to all three groups in faqs.html and publishers.html.

> the private invite-only group is of little interest to people who don't have a DOAJ account

True but I have chosen to include  alink to it becausde it might fire up people's interest.

> I just thought it might encourage private integrators to use it more readily if it was private

I agree!

> being able to convince publishers to use the private API more easily, as they would be able to see what kind of questions others had before them

We could grant them access for a 'taster' to see if it met their expectations and requirements.

> is your Google work address dom@doaj.org

Yep!

**Comment by emanuil-tolev** [comment]
> to https://doaj.org/api/v1/docs somewhere

yeah, definitely

* * *

- [ ] add links to google groups on api docs page
- [ ] add Dom, Richard, Steve as group owners.

**Comment by dommitchell** [comment]
@emanuil-tolev can we get the links to google groups up soon?

**Comment by emanuil-tolev** [comment]
Yep, added to my todo - there's the dedupe stuff I'm dealing with, one small but important sysadmin upgrade that deals with a subtle bug, and I've got more enhancements due for the CRUD API docs - I'll put on the links with those I think.
