### ISSUE TITLE
Discovery API - Documentation

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#752]
- [ ] docs for #735 , the public search over journals and articles
- [ ] docs for #751 , the authenticated search for applications

**Comment by emanuil-tolev** [comment]
Biggest question here for me now is - should the lump of text related to search be:

A. below the live demos
B. if it remains in the main description above the live demos, should it be collapsible? Thinking that eventually we'll have CRUD routes in there as well and the search notes don't apply to those.

**Comment by emanuil-tolev** [comment]
Another big note to make is that I've decided to leave the API docs public - including for the private routes. I was about to hack flask-swagger to let us have one public docs page with 2 routes and one private docs page for publishers with all the rest of the routes, but actually this is not usual. I would recommend leaving the docs open and fielding the occasional question "how do I use this route", "how do I get an API key" - I think it's important to expose what the DOAJ *can* do and be aware of what people might want to do with it.

If we keep the docs for the authenticated APIs private we'll never know what people might want to do with it. It may well be that DOAJ decides to create a publisher account for a particularly enthusiastic researcher, OA advocate, or developer from a non-publisher organisation like a repository manager and let them submit data to DOAJ. Additionally there may be considerable interest in the applications that DOAJ fields from the public.

@dommitchell I'd love to hear your thoughts on this (and everybody else of course). It is possible to keep the authenticated API pages private as well, though a bit more difficult. The usual case is that the documentation for an entire API is published, and then you may or may not have a key and may or may not have rights to do certain things (but can still read related docs).

**Comment by dommitchell** [comment]
@emanuil-tolev happy with this approach but let me get this clear: DOAJ would still have to assign the API role to someone for them to get a key to use the API right?

**Comment by dommitchell** [comment]
> DOAJ would still have to assign the API role to someone for them to get a key to use the API right?

API role is assigned automatically
