### ISSUE TITLE
Javascript widget - controllable widget - Documentation

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#762]
Docs and good behaviour guide for #747

**Comment by Steven-Eardley** [comment]
Widgets are introduced on https://doaj.org/features which leads to the widgets page at https://doaj.org/widgets. 

There is some specific documentation for the 'controllable widget' - fixed query widget - there. It should contain enough information to understand what it does, and what it's for, with a useful explanation of the configuration instructions.

**Comment by dommitchell** [comment]
Great!
