### ISSUE TITLE
Ability of users to provide feedback on journals

### ISSUE THREAD

**Issue by greboun** [DOAJ/doaj#764]
![image](https://cloud.githubusercontent.com/assets/12031556/7932055/c2eefbd4-0915-11e5-817d-5a4606642a86.png)

the idea is that we have a way that users of the site can comment on a journal. The  request for comments could look like in the fig above and shoud be in the search result page for a journal
It should tell people that they have to login but that their comments will be kept private by DOAJ.
The login requirement is a problem since no login is required to access the site. Perhaps we could have the possiblity to let users login using google account or twitter or another easy way?
The result should be aggregated in a folder arranged by ISSN number

**Comment by dommitchell** [comment]
Actually, I don't think people need to log in. All we need is to add a [Send comments about this journal] link next to every journal entry. This would take people to a feedback form, where the title and ISSN are pre-populated. Name and email address are both compulsory (but we make it very clear that comments will not be published and all feedback is anonymous). Submitting the form sends an email to feedback@doaj.org with the subject title: 'User comments on [journal title]'

What do you think @greboun ?

**Comment by greboun** [comment]
I think this would be sufficient, but we have to make sure that we cannot
be spammed with comments

TOM

Dr. Tom Olijhoek
Editor-in-Chief  DOAJ

**Comment by richard-jones** [comment]
With regard to the login, I think it's right to avoid having people log in - otherwise you'll either need to allow anonymous account registration, or auto-create accounts based on a login from google/twitter/facebook (the latter, btw, is easy for the end user, but a significant bit of dev on our side to allow that to happen!).

Adding a plain old email link is the easiest possible option, but would likely result in an increase in spam.

Adding a contact form is the next best option, though you will undoubtedly get a small amount of spam through it (we could add a captcha to make sure that that is rarer).

There are also a variety of user feedback services that you could use, but a quick google about seems to indicate that they are quite expensive (e.g. User Voice)

**Comment by dommitchell** [comment]
@richard-jones can you price me for the first two options?

1) adding an email link and 2) a form?

**Comment by richard-jones** [comment]
Ok, here are the 2 options

1/ Adding an email link
* place some text of your choosing on the ToC, containing a mailto link which will automatically set the subject in the user's mailer to the ISSN of the journal

Easy to do, would be between 1 and 2 hours via tnm, I'd expect

2/ Contact form
* Replace the current Contact Us page with an actual contact form, which can take the subject as a url parameter.
* place some text of your choosing on the ToC, containing a link to the Contact Us page with the subject set to the ISSN of the journal
* Implement the mailer in the back-end for the Contact Us page
* Optionally add reCAPTCHA support

Without recaptcha, I'd expect this is about a day to a day and a half
With recaptcha, probably going on 2 days - I've not implemented it before myself; it doesn't look too hard but it looks like you have to do some front-end and some back-end things to get it to work.  I know @emanuil-tolev has done this before, so he might have a better idea.

**Comment by emanuil-tolev** [comment]
Putting in reCaptcha is easy, but the challenges can be quite difficult, thus discouraging feedback as per #47 . At the point where we scrapped the captcha, I had to click 3-4 times to get something that I could read.

Alternative suggested and estimated at https://github.com/DOAJ/doaj/issues/47#issuecomment-130727012 .

**Comment by dommitchell** [comment]
For both options:
What about on search results too?

2/

> with the subject set to the ISSN of the journal

But for other users submitting normal feedback, going straight to the form, the subject line would be blank?

> Implement the mailer in the back-end for the Contact Us page

We must have a mailer already for the auto-notifications, right?

> Optionally add reCAPTCHA support

I think we will have to have this if we implement an online form, no?

> thus discouraging feedback

That's not a problem for us.

**Comment by dommitchell** [comment]
OK, here's our final wish. Going for Option 2:

- links on ToCs ONLY (changed my mind about adding to search)
- contact us form with mailer out to feedback@doaj.org
- some form of spam filter, not recaptcha

**Comment by dommitchell** [comment]
OK to do under TNM

**Comment by richard-jones** [comment]
Use a hidden input form as a spam filter approach, and send email to feedback+contactform@doaj.org

**Comment by richard-jones** [comment]
Adding this to the continuations project to do under that milestone, as it will fit nicely with the "Suggest a Continuation" feature

**Comment by greboun** [comment]
You are right!
Thanks

Tom

**Comment by richard-jones** [comment]
Hi @dommitchell - you've assigned this one back to me, but I'm not sure what action to take.  Is this related to the question on #837 ?

**Comment by dommitchell** [comment]
Yep, closing this one as we are discussing #837 over there.

**Comment by dommitchell** [comment]
@Steven-Eardley kindly turned off the commenting link (via email request) on each journal for us but is it possible that it still exists in some views/versions/cached versions somewhere?

We have never had so many journal-specific/related enquiries as we are getting now. See email I fwded to you.

Can you investigate?
