### ISSUE TITLE
Enable alt attributes in sponsor images

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#769]
Even though I can see the alt attributes in the html code, they are not showing up in SEO browsers:

http://seo-browser.com/index.php?address=https%3A%2F%2Fdoaj.org%2F&button0.x=49&button0.y=11 where only the image names appear.

Can we fix this?

**Comment by Steven-Eardley** [comment]
@dommitchell I've pushed this to live now - ready for review. Thanks for the pointers!

**Comment by dommitchell** [comment]
Checked in an SEO browser. This is great!
