### ISSUE TITLE
Question: columns in static pages

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#773]
Will the static pages support more advanced html coding like arranging the content in columns?

we want to rearrange the membership pages.

**Comment by richard-jones** [comment]
``html
<div class="row-fluid">
    <div class="span4">col 1</span>
   <div class="span4">col 2</span>
   <div class="span4">col 3</span>
</div>
```

There are a total of 12 grid spaces per row, so use spanX to specify the width of the column in those spaces
