### ISSUE TITLE
Add new sponsor: Dove

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#774]
Please add the new sponsor logo and link to http://dovepress.com/

NEW LOGO:
![dove-transparent-background](https://cloud.githubusercontent.com/assets/5955396/8426259/b169cf24-1f0e-11e5-8ef9-7412023edfa7.jpg)

**Comment by dommitchell** [comment]
Trying to get better logo

**Comment by Steven-Eardley** [comment]
> Trying to get better logo

Shall I hold off until you've done so?

**Comment by dommitchell** [comment]
Yep, ta.

**Comment by dommitchell** [comment]
New logo above. Ready to go.

**Comment by Steven-Eardley** [comment]
Ready for review now on live.
