### ISSUE TITLE
Add feature toggles to DOAJ

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#781]
All features listed in in a config var called FEATURES will be considered "on". If the feature is missing it's "off" and any related code should not be imported or run.

Feature toggles are for easing development of parallel projects and they must be taken out at the end of a project - the code must be fully integrated. (There is no situation in which the live DOAJ will need to be missing a feature.)

**Comment by richard-jones** [comment]
This is now in
