### ISSUE TITLE
Admin area feature to bulk remove articles and journals

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#782]

**Comment by richard-jones** [comment]
I've added a feature to the Administrative Site Search in the admin are which provides two buttons: Delete Selected Articles and Delete Selected Journals.

These buttons are disabled by default, and each will only become active once you have selected either "journals" or "articles" from the Journals vs Articles facet at the top on the left.

Once active, when pressed, the button will delete all of the articles/journals which are in the current search result set (all of them, not just the ones on the particular page you are looking at).

Both buttons will warn you repeatedly before doing any actual deleting.  They will both say "are you sure?" initially, then if you say "OK", they will go off and ask the server to confirm what will happen when you delete.  For an article delete, this will tell you how many articles will be deleted; for a journal this will tell you how many journals will be deleted and how many articles will also be deleted.  If you select "OK" here, then it will action your delete request, give you a pop-up confirming everything went ok, and then refresh the search page, at which point you should see your result set become empty.

Deleted articles and journals are all placed in the history index, but re-instating them is a matter of last-resort, as there is no procedure for doing this yet (as we haven't had to).  So, be careful what you delete!

@emanuil-tolev - propose we roll this out to test for a short period of testing, probably on the real delete requests required by @dommitchell

**Comment by dommitchell** [comment]
> Deleted articles and journals are all placed in the history index, but re-instating them is a matter of last-resort, as there is no procedure for doing this yet (as we haven't had to). So, be careful what you delete!

This is no different to now, right?

**Comment by dommitchell** [comment]
@emanuil-tolev @richard-jones I have just received another 60 delete requests. Can we get this on to testing please so I can test and then get it rolled out?

**Comment by dommitchell** [comment]
What's the status of this?

**Comment by emanuil-tolev** [comment]
> What's the status of this?

Sorry I hadn't seen your previous question.

> @emanuil-tolev @richard-jones I have just received another 60 delete requests. Can we get this on to testing please so I can test and then get it rolled out?

This should be on test now. https://testdoaj.cottagelabs.com .

**Comment by dommitchell** [comment]
Tried on live. Works great
