### ISSUE TITLE
 Both Managing Editors and Editors should be able to assign or remove AssEds to/from applications

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#785]
Both Managing Editors and Editors should be able to assign or remove AssEds to/from applications

**Comment by richard-jones** [comment]
Before approving this for TnM just a note that this is a non-trivial bit of work.  Probably would take upwards of a day to do.  Ok, to add to the list?

**Comment by dommitchell** [comment]
Yes please!

**Comment by dommitchell** [comment]
@richard-jones wouldn't this be better as part of the workflow project that @Steven-Eardley is doing?

**Comment by richard-jones** [comment]
I've done a review of the work to be done here, and remember why this was a bit fiddly.  It's to do with the managing editor's update workflow.  We need to support the following actions in the ManEdApplicationFormContext:

* Addition of an Editor Group where there was previously no group.  This should then enable the Editor select box to allow the selection of an editor from that group

* Removal of an Editor Group, where there was previously a group.  This should clear the Editor select box entirely, and set the value to the empty string.

* Change an Editor Group from one group to another.  This should set the Editor value to the empty string and allow the selection of a new editor from that group.

Probably the best way to achieve this is to introduce some more jquery into the maned form, which will monitor the editor_group field for changes, and carry out the appropriate modifications to the editor select box.  This will include an ajax call to a new endpoint that we'll need to create which will give back the editors in a given editor group, which will then be used to populate the select box.

It may be necessary to validate the editor against the editor_group on form submission, in case there's a problem with the javascript in the front end.  So check that the specified editor actually appears in the specified editor_group, and return an error if not.

I don't think that any changes are required to the Editor's form context - they can already modify the assigned editor, and they can't change the editor group.

@Steven-Eardley - does that all make sense to you?

**Comment by Steven-Eardley** [comment]
> I don't think that any changes are required to the Editor's form context - they can already modify the 
> assigned editor, and they can't change the editor group.

Isn't the above functionality all this issue requests for the Managing Editors too? Group management within the forms seems above and beyond!

**Comment by richard-jones** [comment]
@dommitchell - we've been talking more about this, and actually have realised we may have got the wrong end of the stick with regard to what is needed here.  Could you tell me which of the following you are after:

1/ Managing Editors should be able to change the Associate Editors assigned to an application

2/ Editors should be able to add users with the role "associate_editor" or "editor" to their editorial group (or remove them).

**Comment by dommitchell** [comment]
> 1/ Managing Editors should be able to change the Associate Editors assigned to an application
> 
> 2/ Editors should be able to add users with the role "associate_editor" or "editor" to their editorial group (or remove them).

Hmm, neither actually. We want Admins to be able to assign an associate editor when they are logged in as Admin. Currently, only editors can assign asseds.

**Comment by richard-jones** [comment]
Ok, we have clarified what work needs to be done, and it is as described in my comment above: https://github.com/DOAJ/doaj/issues/785#issuecomment-140437072

**Comment by dommitchell** [comment]
Just out of interest, what's the ETA on this one? (It's less urgent than the rest BTW.)

**Comment by emanuil-tolev** [comment]
@dommitchell Actually, let us review all TnM issues and put a (new if necessary) order to them the coming Tuesday. Then it'd be easier to give ETAs for all of them, since we only need to consider API Phase 3, any final Workflow stuff and all TnMs.

**Comment by Steven-Eardley** [comment]
@dommitchell good news! this is live now and ready for your perusal.

**Comment by greboun** [comment]
Hi

Saw it working on an application form today!
Works like a dream  Great   thanks a lot



Dr. Tom Olijhoek
Editor-in-Chief  DOAJ
Support us: www.doaj.org/support
