### ISSUE TITLE
OAI earliest date question

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#786]
/start/
The following request:
https://doaj.org/oai?verb=Identify
executed today, returns:
<earliestDatestamp>2015-06-10T15:10:50Z</earliestDatestamp>

However, the following request, which I'd expect to return all records in the database:

https://doaj.org/oai?verb=Listrecords&metadataPrefix=oai_dc&from=2015-06-10T15:10:50Z

only returns completeListSize="289", which clearly is far less than the expected 10000+ journals!

On the other hand, without date range:

https://doaj.org/oai?verb=Listrecords&metadataPrefix=oai_dc

returns completeListSize="10344", which seems more plausible.

I suspect something similar is wrong with oai.articles. I hope you can fix this, as our OAI harvester relies on this earliest date.
/end/

**Comment by richard-jones** [comment]
Certainly used to work, so I expect that something else we changed for another project has had a knock-on effect, so this will just require an update.

**Comment by richard-jones** [comment]
The exact reason for this has eluded me - it seems that there's some kind of issue with how dates are handled in statistical and terms facets which causes them to be different from the values actually stored, with regard to the time zone.  Basically, the earliest date was being reported as an hour later than the actual earliest date, causing a mismatch in the results.

I've altered the query to get the dates reliably, and that's in an upcoming PR

**Comment by dommitchell** [comment]
I don't know how to text these. @richard-jones will test

**Comment by dommitchell** [comment]
Seen it on the call. Closing.
