### ISSUE TITLE
Update Journal CSV

### ISSUE THREAD

**Issue by Steven-Eardley** [DOAJ/doaj#790]
Add the extra fields from the reapplication to the CSV created regularly, covering all journals by ISSN.

**Comment by dommitchell** [comment]
Feedback:

- blank line between each entry needs to go
- two missing columns: The Tick, The Seal
- country of publisher and currency needs to be written in full, not the codes

**Comment by Steven-Eardley** [comment]
I'm not seeing any blank lines (libreoffice) - does anyone else see them?

**Comment by dommitchell** [comment]
I am using OpenOffice. I don't see blank lines on the existing CSV that I downloaded from the live site.
![csv](https://cloud.githubusercontent.com/assets/5955396/8521996/d8ccdb8a-23e9-11e5-9ceb-5188bcf9219b.jpg)

**Comment by Steven-Eardley** [comment]
We think the new-lines are a product of me generating the example on my mac - Richard confirmed they were there in the file I emailed, but not present when he generated them on his machine.

So I'll make the other changes then I'll send another sample, this time generated from a system on the same platform as the live site.

**Comment by Steven-Eardley** [comment]
@dommitchell this is now live, can you check there are no blank lines issues with the CSV it's generated?

**Comment by dommitchell** [comment]
Looking good!

**Comment by dommitchell** [comment]
Could you update the column heading for column AW which currently says 'Open Access'? Can it be changed to: 'Does the journal allow readers to 'read, download, copy, distribute, print, search, or link to the full texts' of its articles?'

**Comment by dommitchell** [comment]
@Steven-Eardley  Can you take care of the former comment above and please could you add in the subject classification column, as it is currently missing.

**Comment by dommitchell** [comment]
Hey @Steven-Eardley can I get an update on this one?

**Comment by dommitchell** [comment]
> Does the journal allow readers to 'read, download, copy, distribute, print, search, or link to the full texts' of its articles?

change to:

'Does this journal allow unrestricted reuse in compliance with BAOI?'

**Comment by emanuil-tolev** [comment]
> BAOI

It's BOAI btw :) Budapest Open Access Initiative

**Comment by dommitchell** [comment]
Ha! Cheers!

**Comment by Steven-Eardley** [comment]
@dommitchell shall I include subjects with the schema, as in ```schema_subject```, or without, as in ```classification```? And shall I add another additional column for the codes?

```json
"schema_subject": [
    "LCC:Technology",
    "LCC:Chemical technology",
    "LCC:Biotechnology"
],
"classification": [
    "Biotechnology",
    "Technology",
    "Chemical technology"
],
"schema_code": [
    "LCC:T",
    "LCC:TP248.13-248.65",
    "LCC:TP1-1185"
]
```

**Comment by dommitchell** [comment]
We only need to include the ones that are actually displayed on the site and I reckon that is the classification but @richard-jones could verify. No need to include the codes. Thanks!

**Comment by Steven-Eardley** [comment]
This is on live now.

**Comment by dommitchell** [comment]
Great work! Closing.

**Comment by dommitchell** [comment]
Column BG, 'Content in DOAJ' shows as 'Yes' for all journals which is not correct. Please can you fix?
[doaj_20151002_0830_utf8.xlsx](https://github.com/DOAJ/doaj/files/6616/doaj_20151002_0830_utf8.xlsx)

**Comment by emanuil-tolev** [comment]
I assume some confusion occurred here, perhaps that column was taken to mean "is the journal in DOAJ". What's is it supposed to show, whether any articles have been uploaded for that journal? I.e. is there article metadata in DOAJ.

**Comment by Steven-Eardley** [comment]
Yup, that column is straight from the old spreadsheet columns, which is just showing the value of ```in_doaj``` for each journal, which will always be 'Yes' because we only publicly provide those!

@dommitchell I don't think it's needed as-is - shall I just remove the column, or shall I repurpose it as Emanuil is asking? (if repurposing, please open a separate tnm issue with new requirements.)

**Comment by dommitchell** [comment]
Thanks both. Articles upload is already taken care of in column AB: Article level metadata in DOAJ
so please go aheasd @Steven-Eardley and delete column BG. Thanks!

**Comment by Steven-Eardley** [comment]
The changes are now live, and the CSV will be re-generated on the hour.

**Comment by dommitchell** [comment]
Great! Closing

**Comment by dommitchell** [comment]
Sorry, now column AB is completely blank.

[doaj_20151008_1330_utf8.xlsx](https://github.com/DOAJ/doaj/files/10057/doaj_20151008_1330_utf8.xlsx)

**Comment by Steven-Eardley** [comment]
goodness gracious. I don't see how my changes could have done that! thanks - I'll see what's up.

**Comment by Steven-Eardley** [comment]
Aha - it's been blank all this time, because journals do not in fact have the ```article_metadata``` property - i.e. they don't have the information to populate the column at all, only Applications do. The reason it's there is because I borrowed the code from the reapplication CSV, which does contain that information. 

Once again, @dommitchell, you have the choice between removing it from the form, or opening a new piece of work to populate it with something meaningful. It also might be worth double checking the form for any other blank columns that may have appeared for the same reason.

**Comment by dommitchell** [comment]
Please remove the column

**Comment by Steven-Eardley** [comment]
This change is live

**Comment by dommitchell** [comment]
Great!
