### ISSUE TITLE
Test static pages

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#794]
Take the server app out of the BDD tests branch (or any of the recent projects that have use a LiveServer class to spawn an app for target practice) and use requests to get all static pages. It's fine / better to use introspection to e.g. get all routes under app.py and portality.view.doaj since these are all supposed to be public, and it would mean not having to add new tests when new pages are added, they will be covered automatically. Then just check that a 200 is returned and perhaps the word DOAJ or the phrase Directory of Open Access Journals is mentioned, if that is something that is true for all those pages.

This then goes into the build, which means that for any commit by @dommitchell to the static_pages branch we can see if the build succeeded or failed before we roll out the latest static pages changes. This should take about 2, max 3 hours to set up, but should be well worth it as it takes only seconds to check the build and push the pages with a much greater confidence.

I don't think this is high priority right now with regards to TnM ordering.

**Comment by richard-jones** [comment]
@emanuil-tolev @dommitchell - we probably need to briefly cover this in a meeting so that we know whether it is truly a tnm task, or just something to leave until a suitable project requires it.

**Comment by emanuil-tolev** [comment]
It probably is, as this is about releasing broken static pages (or preventing that) regardless of a running project. Doesn't have to use cucumber, requests is fine, just to check the status code and a basic page content check. Doesn't even have to spawn a separate app in a separate process, flask's own support is enough (as used by @Steven-Eardley in recently written tests for the API auth decorators).

**Comment by richard-jones** [comment]
agreed with @dommitchell to go ahead under tnm
