### ISSUE TITLE
Display bug truncating article list

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#795]
In trying to delete duplicate records from the admin view, the list of 387 articles (makes no difference if you set article list to a smaller number) truncates after the 3rd:

https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222003%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%221020\\-4989%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22sort%22%3A[{%22index.unpunctitle.exact%22%3A{%22order%22%3A%22desc%22}}]%2C%22from%22%3A0%2C%22size%22%3A387}

![truncated](https://cloud.githubusercontent.com/assets/5955396/8539904/03be3428-2481-11e5-8c19-dee53f856f3f.jpg)

**Comment by dommitchell** [comment]
It seems it is that article 6cbf05c9d272482c9633e88c877fa8d0 which is breaking something. Can you investigate?

**Comment by richard-jones** [comment]
Sorry, this slipped by me - I've done a fix for this, and there is a PR in ready for review.

**Comment by emanuil-tolev** [comment]
Rolled out

**Comment by dommitchell** [comment]
Great!
