### ISSUE TITLE
Bring facet labels and statuses in line with each other

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#801]
So the final list in the Admin view of either an Application or a Reapplication will look like this:

'reapplication in progress' changes to 'reapplication pending' (only visible to admin and publishers)
reapplication submitted (only visible to admin and publishers)
pending (only visible to asseds, editors, admin)
in progress (only visible to asseds, editors, admin)
completed (NEW - only visible to asseds, editors, admin)
ready (only visible to editors and admin)
accepted (only visible to admin)
rejected (only visible to admin)
on hold (only visible to admin)

The facet under the Application tab in the Admin view will look the same, with the following mapping:

'reapplication' changes to 'reapplication pending'
'submitted' changes to 'reapplication submitted'
pending
in progress
completed (NEW)
accepted
rejected
on hold
ready

**Comment by greboun** [comment]
the facets in the admin interface for applications are **reapplications**, 
,**submitted** , pending, in progress , ready, accepted, rejected,  on hold.
In this **reapplications**=**reapplications pending** with the publisher, **submitted**= reapplications submitted by a publisher the others are statusses with the editorial team
In the dropdown of the application form we have **reapplication submitted**, **reapplication in progress**, pending,in progress , ready, accepted,rejected on hold.
![image](https://cloud.githubusercontent.com/assets/12031556/8617403/bf1119e6-2703-11e5-93b7-ad4d0f6ce9d5.png)

**reapplication in progress** means that the reapplication is in progress with the publisher, and not yet submitted. _We should change this to **reapplication pending**_ in line with the facet view
Once the reapplication has been submitted the maned will change the status to **pending** and allocate to an editor..(S)he starts working and the reapplications gets status **in progress*
NOTE from hereon we can only see that we work with a reapplication if we have put in a remark in the notes section, or indirectly when there already is a username filled in in the form.
ANY OTHER WAY YOU CAN THINK OF TO DISTINGUISH REAPPLICATIONS FROM NEW APPLICATIONS IN THE FORM??

**Comment by dommitchell** [comment]
> ANY OTHER WAY YOU CAN THINK OF TO DISTINGUISH REAPPLICATIONS FROM NEW APPLICATIONS IN THE FORM??

@greboun all reapplication records get a 'View original record' link at the top.

**Comment by dommitchell** [comment]
@greboun can you complete the task description so it clearly states what the changes are that we want? Thanks!

**Comment by greboun** [comment]
what we want is in the application view dropdown
 reapplication pending, reapplication submitted, pending,in progress , completed, ready, accepted, rejected on hold. 
Only editor can set status to ready
ass editor can set status from pending to in progress or completed,
Editor and ass editor cannot see reapp pending,reapp submitted in application dropdown
man ed can see and set status reapplication pending, reapplication submitted

for the facet view we need it to show the same statusses as above

**Comment by dommitchell** [comment]
@greboun and the list in the dropdown, and who can see what, will be the same whether it is an application or a REapplication. That is OK, yes?

Please review and approve what I have written below and we can sign this off for Steve:

So the final list in the Admin view of either an Application or a Reapplication will look like this:

'reapplication in progress' changes to 'reapplication pending' (only visible to admin and publishers)
reapplication submitted (only visible to admin and publishers)
pending (only visible to asseds, editors, admin)
in progress (only visible to asseds, editors, admin)
completed (NEW - only visible to asseds, editors, admin)
ready (only visible to editors and admin)
accepted (only visible to admin)
rejected (only visible to admin)
on hold (only visible to admin)

The facet under the Application tab in the Admin view will look the same, with the following mapping:

'reapplication' changes to 'reapplication pending'
'submitted' changes to 'reapplication submitted'
pending
in progress
completed (NEW)
accepted
rejected
on hold
ready

**Comment by greboun** [comment]
Agreed.   Looks good to me

**Comment by dommitchell** [comment]
Thanks! @Steven-Eardley task description now updated and signed off by us. Over to you!

**Comment by richard-jones** [comment]
Agreed that this should be part of the Workflow project, so we've added it to that milestone.

The straightforward task of relabelling the facets and drop down options is covered by that project, so there'll only be any tnm cost if we need to change any behaviour regarding the visibility of the various options ( @Steven-Eardley will keep track).

**Comment by dommitchell** [comment]
The list of different statuses is looking good! However:

> 'reapplication in progress' changes to 'reapplication pending' (only visible to admin and publishers)

Logged in as an editor, I can see this status.

> reapplication submitted (only visible to admin and publishers)

Logged in as editor, I can see this.

> on hold (only visible to admin)

Logged in an editor, I can see this.

The list of facets under the Application Status facet is looking good.!

**Comment by dommitchell** [comment]
@greboun Tom, in advance of this being ready, please update the training documentation as soon as possible to include descriptions/screenshots of the new facets, the new 'completed' status and the new workflow that incorporates the 'completed' status. Would be good if it could be updated to coincide with this going live. Please coordinate with @Steven-Eardley 

We should send a mail out to all volunteers alerting them of this too. I will do that after the changes have gone live.

**Comment by dommitchell** [comment]
All good! Ready to go live!
