### ISSUE TITLE
Question: how difficult to regenerate a CSv file for an extra large publisher?

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#809]
A publisher will over 300 journals has now had their 4 accounts merged and would like us to regenerate their CSV. How possible/difficult/ expensive will this be?

**Comment by dommitchell** [comment]
@richard-jones Just putting this on your radar. I'd like to be able to reply to the publisher in the next couple of weeks.

**Comment by richard-jones** [comment]
Can you mail me the publisher's new account details and the 4 previous accounts so I can take a look.

Doing this is relatively straightforward, so we should be able to generate the csv and their reapplications quite quickly, but it will depend on the state of the applications at the moment, and I'll need to check that I know what will happen.

Also, this will "reset" their reapplication spreadsheet, so they'll have to start again.  Assuming they're happy with that, this should be fine.

**Comment by dommitchell** [comment]
Emailed details to you.

**Comment by dommitchell** [comment]
Closing. Publisher has submitted them all.

**Comment by dommitchell** [comment]
Actually, question: the publisher has 24 reapplications left. Can they create a CSV of those 24 and submit that? @richard-jones

**Comment by emanuil-tolev** [comment]
Ahm, this will probably need reapp csv regeneration.. the original CSV probably expects loads of reapplications so the ISSNs will still be in there. @richard-jones sorry, I've forgotten this detail - can a publisher submit partial CSVs, like just bunk off a bunch of ISSNs and submit only e.g. 10% of all their reapplications? If this doesn't get picked up soon-ish @dommitchell ping me (just write in here) and maybe state the publisher account as well.

**Comment by dommitchell** [comment]
Answer is yes. Closing.
