### ISSUE TITLE
Add new record to models: "human last updated"

### ISSUE THREAD

**Issue by Steven-Eardley** [DOAJ/doaj#811]
- [x] Update Journals / Suggestions to include a field recording when a person last updated it
- [x] Add a facet on admin search on this field
- [x] Migration to add field to journals / suggestions
- [x] Tests

related: #689

**Comment by Steven-Eardley** [comment]
@dommitchell I'm deciding what to initialise this field to - would it be useful to have an initial value to this field such as 'None' or 'Never'? (which of these makes more sense?)

I've chosen to name it 'Last manual update' so it will appear in the admin facetview results as:

**Last manual update:** None

Until it's been saved by a form, of course.

**Comment by dommitchell** [comment]
@Steven-Eardley how about 'Never'

**Comment by dommitchell** [comment]
How will this be differentiated from the automatic update? what will that line say?

**Comment by Steven-Eardley** [comment]
I've left that as 'Last updated' which will contain both manual and automatic changes (i.e. whenever something is saved back into the index)

**Comment by dommitchell** [comment]
> I've left that as 'Last updated' which will contain both manual and automatic changes (i.e. whenever something is saved back into the index)

Great! And then we must be able to sort search results on that new line. 'Last updated' should be repointed to the Last manual update date, if that makes sense?

![sort](https://cloud.githubusercontent.com/assets/5955396/8728284/96b6e210-2be4-11e5-913f-2b87474a94ab.jpg)

**Comment by Steven-Eardley** [comment]
It does make sense, thanks!

**Comment by Steven-Eardley** [comment]
> 'Last updated' should be repointed to the Last manual update date

@dommitchell I don't really want to have the sort field 'Last updated' named after the old field but pointed to another - the sort option for the new field will be called 'Last manual Update' in the drop-down. Do you want me to keep 'Last updated' too, or remove it?

**Comment by dommitchell** [comment]
@Steven-Eardley this only appears in the admin view. We have always used 'last updated' in the way that 'last manual update' will be used now. We won't use the existing 'Last updated' at all now so it can go. If we *can* retain just 'last updated' that is going to be much better from a UI point of view.

**Comment by Steven-Eardley** [comment]
Ah, good point - thanks for clarifying. I'll re-point the 'last updated' drop down label to the new field like you say. I'll try to make it clear in code comments to avoid confusion down the line.

**Comment by emanuil-tolev** [comment]
@Steven-Eardley 

The migration has run on testdoaj.cottagelabs.com . Here's the output:

```
(doaj)cloo@doaj-test:~/repl/test/doaj/src/doaj$ DOAJENV=test python portality/upgrade.py -u portality/migrate/workflow/journal_provenance.json
Running in test
Loaded final config from /home/cloo/repl/test/doaj/src/doaj/test.cfg
Upgrading journal
/home/cloo/repl/test/doaj/src/doaj/portality/datasets.py:594: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if variant.lower() == r:
writing  500 to journal
writing  500 to journal
writing  500 to journal
writing  500 to journal
writing  500 to journal
writing  500 to journal
writing  500 to journal
writing  500 to journal
writing  500 to journal
writing  500 to journal
writing  500 to journal
writing  500 to journal
writing  500 to journal
writing  500 to journal
writing  500 to journal
writing  500 to journal
writing  500 to journal
writing  500 to journal
writing  500 to journal
writing  500 to journal
writing  500 to journal
writing  500 to journal
writing  500 to journal
writing  500 to journal
writing  500 to journal
writing  500 to journal
writing  500 to journal
writing  188 to journal
Upgrading suggestion
writing  500 to suggestion
writing  500 to suggestion
writing  500 to suggestion
writing  500 to suggestion
writing  500 to suggestion
writing  500 to suggestion
writing  500 to suggestion
writing  500 to suggestion
writing  500 to suggestion
writing  500 to suggestion
writing  500 to suggestion
writing  500 to suggestion
writing  500 to suggestion
writing  500 to suggestion
writing  500 to suggestion
writing  500 to suggestion
writing  500 to suggestion
writing  500 to suggestion
writing  500 to suggestion
writing  500 to suggestion
writing  500 to suggestion
writing  500 to suggestion
writing  500 to suggestion
writing  500 to suggestion
writing  500 to suggestion
writing  500 to suggestion
writing  500 to suggestion
writing  500 to suggestion
writing  500 to suggestion
writing  500 to suggestion
writing  381 to suggestion
```

**Comment by emanuil-tolev** [comment]
(seems fine to have run fine)

Taking a journal out of DOAJ does not seem to update Last Updated: I tried https://testdoaj.cottagelabs.com/admin/journal/555b7bdaaf674f299e1caa0a75e3df62 and it still said "never" after I took it out and put it back in. Probably an update needed to the journal activate and deactivate endpoints, I think must be in views.admin .

**Comment by emanuil-tolev** [comment]
It did work when I saved the record, so actually you'll need to try with another one that currently says Never!

**Comment by dommitchell** [comment]
I just changed the status on a record from Submitted to In progress.

The time changed from 'Never' to 2015-10-06 14:48:33
https://testdoaj.cottagelabs.com/admin/suggestion/09aafe52507d4f14a998a6612196f96d

Great! Good to go!

**Comment by dommitchell** [comment]
@Steven-Eardley @emanuil-tolev Can you let me know when this went live to the site? I am interested in knowing how long records that have 'Never' against their Last Updated date have been that way.

**Comment by Steven-Eardley** [comment]
I think it was the 16th October 2015 - it's in https://github.com/DOAJ/doaj/releases/tag/2015-10-16_1615T_workflow_and_api_phase2_release

**Comment by dommitchell** [comment]
Genius. Thank you!
