### ISSUE TITLE
Opengraph URL

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#813]
og:url seems to override any other metadata provided

http://stackoverflow.com/questions/7830846/ogurl-is-driving-me-crazy

So anything you share will only ever have the homepage's metadata, rather than the data from a specific article / journal page. So if I go here https://doaj.org/toc/1307-4733 and share it, it'll just say "Directory of Open Access Journals", not have _that_ page's title.

og:url is a override - you want the scraper to scrape the metadata from a page different than the URL being shared in the first place. Dunno why they'd have that, but there must be a use case. So we either need to set it to request.url (the current url) or omit it.

**Comment by Steven-Eardley** [comment]
Is this causing a particular problem? I set the og:url because it's 'required' by Facebook - it means the entity for DOAJ is always resolved properly for all page shares.

**Comment by emanuil-tolev** [comment]
No, just I guess not what we'd have expected? If we set it just to request.url it will scrape the right tags.

I guess it makes all our tags except og:url useless basically, since FB just always looks at the homepage. og:url overrides anything else you put on your page, and then it goes and looks at OpenGraph on whatever page og:url points to.

**Comment by richard-jones** [comment]
Is there any action to be taken on this?

**Comment by emanuil-tolev** [comment]
Yeah, set og:url to request.url (as in from Flask import request) since it ignores the other tags if this one is present. It is quite a small job (say 30 min with testing and submitting it for review) but should result in much nicer shares of DOAJ pages - maybe worth bringing up at next Mon meeting for inclusion in T&M?
