### ISSUE TITLE
Change green 'Save application' button to read just 'SAVE'

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#817]
This change should happen across ALL instances of the application and reapplication form in Admin.

**Comment by Steven-Eardley** [comment]
@dommitchell Should there be any change to the edit journal form in Admin, which currently says 'Save journal'?

You've specified Admin, so do you mean for no changes at all to the Editor and Associate Editor forms? These will continue to say 'Save application' and 'Save journal'.

**Comment by dommitchell** [comment]
Ah, sorry for not being clear. I mean ALL instances of the button across all instances of the form, Editor, AssEd, Admin, etc. Thanks for checking!

**Comment by Steven-Eardley** [comment]
Done; you can see all of the changes I've made via the pull request here: https://github.com/DOAJ/doaj/pull/850/files

**Comment by dommitchell** [comment]
Can I check it in testdoaj....?

**Comment by Steven-Eardley** [comment]
On live now (finally) - I'd missed a comment that it was ready for deployment a couple of weeks ago!

**Comment by dommitchell** [comment]
Seen it. It looks great! Thanks.
