### ISSUE TITLE
Report: CSV report of email addresses - reapplication reminders

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#819]
Run a report to generate a single CSV of email addresses and account numbers where:

- all accounts with <11 journals that have a journal in DOAJ and a pending Reapplication record.

Will need to be run in Sept, Nov and Dec

**Comment by dommitchell** [comment]
#314

**Comment by richard-jones** [comment]
Me to develop a script, then fire over to @emanuil-tolev to deploy and run on production.

Do this as a hotfix

**Comment by richard-jones** [comment]
Target for being run: 23rd September

**Comment by richard-jones** [comment]
@emanuil-tolev - I've created a PR for this, so you are clear to merge and run whenever suits.

**Comment by emanuil-tolev** [comment]
Output:

6300 accounts with between 1 and 10 journals in the DOAJ
4824 accounts with at least one outstanding reapplication
4551 accounts appear in both lists

CSV: https://www.dropbox.com/s/p2cs07o5stvkys6/reappreport_20150915_1905.csv?dl=0

**Comment by dommitchell** [comment]
> 6300 accounts with between 1 and 10 journals in the DOAJ
> 4824 accounts with at least one outstanding reapplication
> 4551 accounts appear in both lists

Hello! Can you  help me understand this? It means that 4551 accounts have one or more reapplication to submit, right?

Have you taken into account this: "that have a journal in DOAJ". We have removed a lot of journals so it is important that we only send email to those who still have journals *IN* DOAJ.

**Comment by richard-jones** [comment]
Yes, so the script builds two lists:

1/ of accounts with between 1 and 10 journals that are in_doaj=True (6300
such accounts)

2/ of accounts with one or more outstanding reapplications (4824 such
accounts)

It then looks for the intersection of those two lists, which in this case
contains 4551 account names.

Are these numbers much higher than you were expecting?

**Comment by dommitchell** [comment]
> Are these numbers much higher than you were expecting?

Nope. Was just checking before I worked the list into SurveyMonkey. Thanks!

**Comment by dommitchell** [comment]
What's happening to this?

**Comment by emanuil-tolev** [comment]
https://www.dropbox.com/s/hz5njwv9ustpmsl/reappreport_20151117_1041.csv?dl=0 :)

**Comment by emanuil-tolev** [comment]
Output:

```
Running in production
Loaded final config from /home/cloo/repl/production/doaj/src/doaj/production.cfg
6354 accounts with between 1 and 10 journals in the DOAJ
4283 accounts with at least one outstanding reapplication
3985 accounts appear in both lists
```

**Comment by dommitchell** [comment]
Thank you! All good. Until December...

**Comment by emanuil-tolev** [comment]
Output:

```
Running in production
Loaded final config from /home/cloo/repl/production/doaj/src/doaj/production.cfg
6414 accounts with between 1 and 10 journals in the DOAJ
3637 accounts with at least one outstanding reapplication
3338 accounts appear in both lists
```

**Comment by dommitchell** [comment]
CLosing

**Comment by dommitchell** [comment]
Please run this again before COB 4pm UK time 7th Jan

**Comment by dommitchell** [comment]
Please run this again before COB 4pm UK time 6th Jan

**Comment by emanuil-tolev** [comment]
For my own reference: run ```(doaj)cloo@doaj-app-1:~/repl/production/doaj/src/doaj$ DOAJENV=production python portality/scripts/reappreport.py -o ~/reapp_report_`date +%F_%H-%M-%S`.csv```

**Comment by emanuil-tolev** [comment]
Output:

```
Running in production
Loaded final config from /home/cloo/repl/production/doaj/src/doaj/production.cfg
6464 accounts with between 1 and 10 journals in the DOAJ
3239 accounts with at least one outstanding reapplication
2935 accounts appear in both lists
```

File sent by email.

**Comment by emanuil-tolev** [comment]
Ah, also, I just realised there's another way to interpret your request - do you want me to run that report again *just before* close of business on 6th Jan? I'll rerun it then if that's the case.

**Comment by dommitchell** [comment]
Nope, this is perfect! Thank you!
