### ISSUE TITLE
Add Slideshare icon to homepage

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#834]
![slideshare_icon](https://cloud.githubusercontent.com/assets/5955396/9194256/38a1aa12-401a-11e5-94ea-2f21b3a2d0fe.png)

URL: http://www.slideshare.net/doaj/

**Comment by dommitchell** [comment]
Can you resize to match the others?

**Comment by emanuil-tolev** [comment]
Deployed live, thanks @Steven-Eardley - very nice work, good to update those frontend bits to latest versions alongside the new icon.

**Comment by dommitchell** [comment]
Very nice. Thanks!
