### ISSUE TITLE
New continuations facets for admin area

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#838]
Provide facets to allow filtering by discontinued and/or continued journals. Will require minor updates to the journal save function to make this data facetable.

**Comment by richard-jones** [comment]
The continuations facets have not been working on the test server, as they create a facet over a field which does not have any data in it yet.  This means that there's no mapping in the index for that field, which in turn throws an error when you query it.

I've fixed this by adding a migrate script to push a mapping update - that will be in an upcoming PR.

**Comment by dommitchell** [comment]
Looking good!
