### ISSUE TITLE
Present continuations metadata on ToC

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#839]
To replace the existing functionality.  Display the active period, and the previous/subsequent journal instances

**Comment by richard-jones** [comment]
There was a UX oddity on the test server whereby the user would be presented with a link to a previous or subsequent journal, and on clicking on that journal would be presented with an error/not found page.

Actually, the not found page was the correct response, as the journal was marked in_doaj=False.

I have modified the ToC renderer to not provide links (only titles and issns) for journals which are in_doaj=False, and have appended the text "(not available in DOAJ)".  This maintains the continuations infrormation without confusing the user. An example would be for ISSN 1756-3305.

PR coming shortly.

**Comment by dommitchell** [comment]
Not sure this is working correctly. If I look at https://testdoaj.cottagelabs.com/toc/2338-5510 I see the correct articles displayed for this version of the journal.

If I click on the continuation link, https://testdoaj.cottagelabs.com/toc/1978-3043, I see the same articles; those from the previous incarnation of the journal.

**Comment by richard-jones** [comment]
I can see what the problem here is, but I'm not yet sure why.  The article has the issns from all of the journal continuations in its index.issns field, which is causing it to match in both contexts.  The ToC page itself is doing the right thing, and the article's actual bibliographic record is correct, so I suspect something to do with the article_cleanup_sync script, which is next on my list of things to look at.  I expect that once we've reviewed that, this problem will go away.

**Comment by richard-jones** [comment]
I've reviewed the script, and I think that all that's happened here is that the article_cleanup_sync script has not been run on the test server since the continuations migration has been done.

@Steven-Eardley - could you run your script on the test machine, and then we'll review?

**Comment by Steven-Eardley** [comment]
Run now. That took a loooong time.
```
Done. 2577341 articles updated, 4571 remain unchanged, and 0 deleted.
2016-05-23 16:32:13.218392 - 2016-05-24 15:04:30.761903
```

**Comment by dommitchell** [comment]
+Looking good!
