### ISSUE TITLE
Search interface continuations info

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#840]
Search interface should make it clear when a journal has continuations.

What form exactly should this take?

Propose: if discontinued date, display a flag saying "discontinued" (possibly on the left with the other icons), and in the main search text have a link to the ToC for the replacing journal

**Comment by richard-jones** [comment]
There are a number of complications in showing a link to the replacing journal in the search interface:

* The journal only knows the ISSN of the replacing journal, so we can't display something that meaningful to the user.  To display more than ISSN we'd either need to do a separate query from the UI (painful and expensive) or pre-load that data into the journal record

* A journal may know the ISSNs of its replacement, but that doesn't guarantee that the replacement is in the DOAJ, so a link is not always appropriate

* A journal may know both the ISSNs for its replacement, but rendering a link to both would be odd.  But we have no way of knowing if the 2 ISSNs refer to a single journal, or two separate ones (which could happen if the journal split).

* A journal could theoretically have a long list of replacements (though unlikely, of course), and it might be bad for the UI to display them all.

So, for the moment I've left out this information from the search interface.  Instead, the user can see the record has been "Discontinued", and the ToC page for the journal will contain the full chain of preceeding and succeeding continuations.

**Comment by dommitchell** [comment]
It seems that all journals that have the Discontinued tag have a Date Added to DOAJ date of 27th April which I presume is when this went live on the site. I hope that this won't be replicated to the live site? The Date added to DOAJ date must not be touched. http://bit.ly/1TFMquj

**Comment by richard-jones** [comment]
Ah, ok, good point/question.

These journals which are marked as "Discontinued" have been created from history records in other journals (if you go into their ToC you should see that they all specify "subsequent titles").

So,their date added to the DOAJ is the day that we ran the script, because before that they were not explicitly in the DOAJ.

The question, then, is what /should/ the date be for those records?  I note that for some (perhaps all?) journals records, the continuations history data has dates attached to them, so I think we should probably use that as the created_date?  If no such date exists for a record, should we use the created date of the parent journal record?

Note that no records have had their dates modified, so that's not an issue here - only records that are created during the migration have this date.

See, for example:
http://testdoaj.cottagelabs.com/toc/1696-1137
which is replaced by
http://testdoaj.cottagelabs.com/toc/1886-3655

@dommitchell - I'm going to make some changes to the migration to implement the use of dates described above, but if you have any comments in the mean time let me know.

**Comment by richard-jones** [comment]
Oh, also, I notice that the created date for the history records is probably when we migrated from the last version of DOAJ, so might be equally un-meaningful as the current date.  We don't have any other source of date information for those records, though.

**Comment by dommitchell** [comment]
> So,their date added to the DOAJ is the day that we ran the script, because before that they were not explicitly in the DOAJ.

So they had no 'Date Added to DOAJ' originally?

So any journal that was previously removed but is then added back in by us because it is a continuation, will get this date? Or are these the journals where a continuation existed already and if someone typed in their ISSNs they were taken to the newer incarnation of the journal?


> The question, then, is what /should/ the date be for those records? I note that for some (perhaps all?) journals records, the continuations history data has dates attached to them, so I think we should probably use that as the created_date? If no such date exists for a record, should we use the created date of the parent journal record?

I am unclear on this. Why don't they have an original Date added to DOAJ date?

One for our call tomorrow. Let's leave this until then.

**Comment by dommitchell** [comment]
OK to go ahead. We clarified on the call. TO BE REVIEWED.

**Comment by dommitchell** [comment]
Seen in test. Closing
