### ISSUE TITLE
Attempt to delete articles returns error

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#844]
https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22bibjson.year.exact%22%3A%222014%22}}%2C{%22term%22%3A{%22_type%22%3A%22article%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%221687\\-0409%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}

![error](https://cloud.githubusercontent.com/assets/5955396/9299589/ca0e2e74-44bd-11e5-8067-d5c7cd255a9c.jpg)

https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22bibjson.year.exact%22%3A%222014%22}}%2C{%22term%22%3A{%22_type%22%3A%22article%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%222314\\-6141%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}

https://doaj.org/admin/admin_site_search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22article%22}}%2C{%22term%22%3A{%22bibjson.year.exact%22%3A%222015%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%222314\\-6141%22%2C%22default_field%22%3A%22index.issn.exact%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}

**Comment by emanuil-tolev** [comment]
Holy smokes these are really big deletes

**Comment by emanuil-tolev** [comment]
Heh, it took almost 4 min to run them! Should be done now

**Comment by dommitchell** [comment]
Perfect! Closing.
