### ISSUE TITLE
Bug when manually assigning roles on account creation vs. roles added automatically

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#849]
There's a bug in the system which means that every new user created manually gets the api role. Even if you remove that role and assign another before hitting submit, only the removed api role sticks. You have to go to the new record, remove API and add the role you want.

![api1](https://cloud.githubusercontent.com/assets/5955396/9382999/cf22febe-4745-11e5-950d-4992375dc699.jpg)

![api2](https://cloud.githubusercontent.com/assets/5955396/9383010/d7511134-4745-11e5-9f81-5c375d6882c1.jpg)

![api3](https://cloud.githubusercontent.com/assets/5955396/9383015/db92c22e-4745-11e5-952c-a736ed1db6e7.jpg)

API role should only be added to user accounts that have a publisher role allocated to them, whether those accounts are created automatically upon acceptance of an application *or* manually.

How does this work for the user accounts of reapplications?

**Comment by emanuil-tolev** [comment]
> How does this work for the user accounts of reapplications?

They're "publisher" aren't they?

**Comment by emanuil-tolev** [comment]
#846 deals with "only assign api role automatically to users with role publisher" but you seem to have found some other sort of bug where you specify a certain role or multiple roles, but it gets overwritten when the account should have the "api" role added (currently doing that for every new account).

**Comment by dommitchell** [comment]
> How does this work for the user accounts of reapplications?
> 
> They're "publisher" aren't they?

They are but they have existing accounts. Actually, I just remembered that we will apply the api role to all publisher accounts. All good.

**Comment by Steven-Eardley** [comment]
@dommitchell The fix for this is now live.

In brief, I've fixed the functionality such that the 'api' role is auto-filled as a suggestion on the form, but when it's removed it'll actually be removed from the account! It will also pay attention to which other role(s) you enter in the form now.

That sounds about right to me - I've no idea what I was thinking before!

**Comment by dommitchell** [comment]
And it works like a dream! Closing!
