### ISSUE TITLE
Question: can we do anything about doaj dot com?

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#852]
From a friend. Is there anything we can do, short of buying doaj.com?

/start/
I’m not sure if this is on your radar but it might be something to address. I’ll explain why in a sec. So i was looking up a journal in doaj and i accidentally typed in doaj dot com (again don’t visit), I got lots of pop-ups that weren’t closing and eventually one that played audio that was quite ominous sounding, with a dystopian voice saying “this computer has malware” etc. I killed the processes and had a look:

In Google’s cache, the source code is:

http://pastebin.com/4dR3pV10

The source code now appears to be:

http://pastebin.com/t2GartkV

In my non technical opinion, the javascript there seems relatively benign and I’ve checked out the links in the source in Virustotal and they seem to be ok, I’ve also scanned my system (with old virus definitions) and it seems to be clean too. So hopefully there’s nothing malicious there.

So the issue is when I typed doaj.com into google, I got doaj.org and doaj.com and the header info for the latter says “directory of open access journals” (See screenshot). This could also be a problem in addition to people mistyping and arriving to this somewhat dodgy looking site. 

The IP address for doaj.com goes back to an Australian company but i’m not sure if they own the domain. 

/ends/
![screen shot 2015-08-25 at 18 49 02](https://cloud.githubusercontent.com/assets/5955396/9486892/ff53a90e-4bcc-11e5-917d-d3d8791238ef.png)

Also, is the js as benign as our friend thinks?

**Comment by richard-jones** [comment]
For reference, here's the whois entry on doaj.com

   Domain Name: DOAJ.COM
   Registrar: PDR LTD. D/B/A PUBLICDOMAINREGISTRY.COM
   Sponsoring Registrar IANA ID: 303
   Whois Server: whois.PublicDomainRegistry.com
   Referral URL: http://www.PublicDomainRegistry.com
   Name Server: NS1.ABOVE.COM
   Name Server: NS2.ABOVE.COM
   Status: clientTransferProhibited http://www.icann.org/epp#clientTransferProhibited
   Updated Date: 20-jun-2015
   Creation Date: 12-jun-2004
   Expiration Date: 12-jun-2016

>>> Last update of whois database: Thu, 27 Aug 2015 08:18:44 GMT <<<

Domain Name: DOAJ.COM
Registry Domain ID: 122345346_DOMAIN_COM-VRSN
Registrar WHOIS Server: whois.publicdomainregistry.com
Registrar URL: www.publicdomainregistry.com
Updated Date: 2015-07-18T12:58:23Z
Creation Date: 2004-06-12T05:41:37Z
Registrar Registration Expiration Date: 2016-06-12T05:41:37Z
Registrar: PDR Ltd. d/b/a PublicDomainRegistry.com
Registrar IANA ID: 303
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Registry Registrant ID: 
Registrant Name: domain admin
Registrant Organization: ahura fze
Registrant Street: p.o.box 62674 uae  
Registrant City: dubai
Registrant State/Province: dubai
Registrant Postal Code: 62674
Registrant Country: AE
Registrant Phone: +97.0720469033
Registrant Phone Ext: 
Registrant Fax: 
Registrant Fax Ext: 
Registrant Email: admin@indiandomain.com
Registry Admin ID: 
Admin Name: domain admin
Admin Organization: ahura fze
Admin Street: p.o.box 62674 uae 
Admin City: dubai
Admin State/Province: dubai
Admin Postal Code: 62674
Admin Country: AE
Admin Phone: +97.0720469033
Admin Phone Ext: 
Admin Fax: 
Admin Fax Ext: 
Admin Email: admin@indiandomain.com
Registry Tech ID: 
Tech Name: domain admin
Tech Organization: ahura fze
Tech Street: p.o.box 62674 uae 
Tech City: dubai
Tech State/Province: dubai
Tech Postal Code: 62674
Tech Country: AE
Tech Phone: +97.0720469033
Tech Phone Ext: 
Tech Fax: 
Tech Fax Ext: 
Tech Email: admin@indiandomain.com
Name Server: ns1.above.com
Name Server: ns2.above.com
DNSSEC:Unsigned
Registrar Abuse Contact Email: abuse-contact@publicdomainregistry.com
Registrar Abuse Contact Phone: +1-2013775952
URL of the ICANN WHOIS Data Problem Reporting System: http://wdprs.internic.net/

**Comment by richard-jones** [comment]
My (non-lawyer) opinion is that there's not a tremendous about to be done here.  There is precedent for domain names being forcibly removed from one owner and transferred to another who claims the "right" to it (my favourite being baa.com, which - in the 1990s - was a website about sheep), but I believe actual legal process is required, and possibly trademarks.  Not sure what the DOAJ status is around that.

One thing you could do is around 16th June 2016 trying to buy the domain name when it comes up for renewal.  There is a grace period, though, usually of a couple of weeks after the domain expires where only the last registrant can purchase it, so you'll only be able to get it if they forget about it for a long time.

You could offer to buy it from them, though domain squatters are looking to make money, so there will be a premium on it.

You could try emailing the Registrar Abuse Contact Email and seeing what they say about it, but I suspect that unless the site is doing something illegal they won't do anything.

Also, probably, you should find someone who knows a little about domain name law and ask them - all of my thoughts come from bits I've picked up in the news over the years!

**Comment by emanuil-tolev** [comment]
:+1: on everything Richard said :). This registration information looks quite sketchy (po box, name is "domain admin") so definitely a bad foreign domain broker. Might be worth talking if you know you're willing to pay up to X amount and if they speak enough English to allow you to perform a secure payment without scamming you (i.e. they will actually give you the domain after payment), like using an Escrow service (e.g. https://escrow.com/services/domain-and-website-escrow.aspx - not a recommendation from me as I've not used them, but so you get the idea). Alternatively you can wait until around this time in 2016 after the grace period expires - if they don't renew the domain or sell it.

**Comment by Steven-Eardley** [comment]
:+1: :+1: on those above - I'd just add that I wouldn't have much hope for getting it from them at renewal in 2016. In my experience, with domain names so cheap, it'll almost certainly be renewed by them for the chance of you giving them money. And lots of providers auto-renew.

That said, if there's no other action you'll be taking, it'll be worth keeping a look-out when the time comes around.

**Comment by dommitchell** [comment]
Nothing to do here for now.
