### ISSUE TITLE
Switch URL to https

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#866]
In the doaj footer, can you switch the <a href="http://creativecommons.org/licenses/by-sa/4.0/"><img src="/static/doaj/images/cc-by-sa.png" alt="Creative Commons Attribution ShareAlike license icon"></a>

to

<a href="https://creativecommons.org/licenses/by-sa/4.0/"><img src="/static/doaj/images/cc-by-sa.png" alt="Creative Commons Attribution ShareAlike license icon"></a>

Thanks!

**Comment by Steven-Eardley** [comment]
On live now.

**Comment by dommitchell** [comment]
Beautiful! Closing.
