### ISSUE TITLE
oa_end and other old journal information fields in 5 reapplications to DOAJ

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#871]
oa_end, author_pays, author_pays_url are all fields from the old journal structure we used to have. Those seem to have been copied over to the respective reapplications when these were generated. We don't show any information from these fields and had long ago decided that the "old journal information" box in the DOAJ back-end journal forms will be retired once the DOAJ finishes the reapplication cycle.

I suggest that these get cleaned up from the reapplications (deleted, presumably - no data will be lost as long as we hold all the old-style journal records).

FYI (for developers): run q=_exists_:bibjson.oa_end on live. Similar for the other fields.

The list of old fields I give above may not be exhaustive, it's best to check the current DOAJ back-end journal forms (specifically the Old Journal Information section) for an exhaustive list to clean up and put it in this issue before starting work.

**Comment by richard-jones** [comment]
We should check that all these old obsolete fields are now gone from the models and from the database before the refactor.
