### ISSUE TITLE
Display assed's email address in application form

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#878]
We would like to hyperlink the assed's name, or display their email address, in the Editor's short view:

![editor](https://cloud.githubusercontent.com/assets/5955396/10507392/664b77fc-7320-11e5-9dfb-5a9695f843ca.jpg)

where 'tested' is the assed.

Please can you let me know how much that would be?

**Comment by dommitchell** [comment]
They could add a note to the reapplication. DM to get more info. Will ask at team meeting today.

**Comment by dommitchell** [comment]
Updated the task. I had misunderstood the original request @richard-jones

**Comment by richard-jones** [comment]
This is relatively hard, as only the editor group name, and the editor name is attached to the record.

We could easily make the name a link to the editor/editor group search (just an hour or two's work), but if we want to display the editor email we would need to do one of the following:

1. attach the editor's email to the record directly in the index
2. run a second query for the editor's email address after the main search has run.

For either of these it's more than a day's work, I'd expect.

**Comment by dommitchell** [comment]
Closing for now
