### ISSUE TITLE
Make search API more flexible by allowing a few settings

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#879]
Just logging this idea that came through via email here.

> Hi Emanuil, 
> 
> [...]
> 
> I think it probably does make sense for you to change the default_operator to AND -- but best of all, for flexibly suporting clients, would be letting the client specify the default_operator as well as the minimum_should_match to be passed through to ElasticSearch. 
> 
> Thanks for the DOAJ API, it is quite handy and well-designed!

I agree with him that letting people specify those options would take advanced search applications using the DOAJ to a whole new level (of them being able to customise search at least). It should not put any noticeable load on the servers.

**Comment by emanuil-tolev** [comment]
It'd take probably about half a day.

**Comment by greboun** [comment]
It would be a great improvement I agree, let's discuss this in the next
meeting
