### ISSUE TITLE
Submitted application doesn't appear in the system

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#882]
https://doaj.org/admin/suggestion/6de7441d4c604769bc8931ee0c0f90a9

Publisher submitted reapplication on 2nd Sept and got a confirmation email: 

feedback@doaj.org 
To
XXXXX
Sep 2 at 12:47 PM
Dear Publisher,

Journal of Knowledge & Health 

Thank you for completing your reapplication to DOAJ which has been safely received!

Please save this email as a record of when you submitted your reapplication. We are unable to reply to emails requesting a status update for reapplications that are less than 3 months old.

Yours faithfully,

The DOAJ Editorial Team
+++++++++++++++++++++

I have had 2 other reports of this (but neither were able to produce a confirmation email). Wonder if it was when we were having the cluster problems?

**Comment by emanuil-tolev** [comment]
Ouch, that'd be really crap for them. I think it might well have been around that time, I'll try digging into the data (might take a little while).

**Comment by dommitchell** [comment]
We decided that we would leave this for now, low priority, unless we find more of these.

**Comment by richard-jones** [comment]
@emanuil-tolev - is this also related to split brain?

**Comment by emanuil-tolev** [comment]
Yeah 2nd sept is exactly that. Copying it into the other issue now.
