### ISSUE TITLE
The next version of Safari requires new icon for 'Pinned Tabs'

### ISSUE THREAD

**Issue by Steven-Eardley** [DOAJ/doaj#883]
Apple is too special to use a site's favicon when you use Safari 9's 'pinned tabs' feature, so if the DOAJ wants to use a custom image when a user pins the site for frequent use, it'll have to follow their [guidelines](https://developer.apple.com/library/prerelease/mac/releasenotes/General/WhatsNewInSafari/Articles/Safari_9.html#//apple_ref/doc/uid/TP40014305-CH9-SW20) - adding a new strictly black-only SVG image.

Note: this will benefit users who are Mac users AND use the most recent OS X (El Capitan) AND use Safari AND want to pin the site for frequent use - this is probably quite low priority!

**Comment by emanuil-tolev** [comment]
why didn't they just use the favicon like Chrome and Firefox.......

**Comment by Steven-Eardley** [comment]
They want more say in how it's designed, I think. It's supposed to be a subtle grey icon most of the time, with custom colouration when it's active. Very much like the ones we use using fontawesome.

Here is it is on my laptop:
<img width="148" alt="screen shot 2015-10-02 at 14 30 42" src="https://cloud.githubusercontent.com/assets/1446355/10247636/4ed89c20-6912-11e5-84fa-76116dba74b2.png">

The default behaviour is to create one with a letter from the site title. As you can see, it's actually done a fairly good job, including picking out the orange colour.

Still, the DOAJ could have something more custom if they like :)

**Comment by Steven-Eardley** [comment]
Looks like the default behaviour works well for us.
