### ISSUE TITLE
Journal and article icons

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#889]
The journal and article icons in Journals and Applications:

- have changed in live
- have changed in Admin under Journals.
- have disappeared under Applications

As per the call today this is something to do with a recent font update

**Comment by richard-jones** [comment]
@Steven-Eardley - could you take a peek at this when you get a moment?  The only thing outstanding is that the icons in the applications in admin have disappeared.  Looks like maybe in a newer version of bootstrap icon-signin isn't present, or something.

**Comment by dommitchell** [comment]
I'd like this one fixed please. It's low priority but too old to still be open! @richard-jones @Steven-Eardley

**Comment by emanuil-tolev** [comment]
All icons in facetviews should be fixed now

**Comment by dommitchell** [comment]
Great!
