### ISSUE TITLE
Add 'Ceased publication'field to journal records

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#890]
For continuations, DOAJ is changing its policy on discontinued journals. Under certain circumstances the journal will be able to remain in/visible in DOAJ. We need a 'Ceased publication' date field for journal records that can be added which then displays on the journal ToC page.

Can this be worked into Continutations project?

**Comment by richard-jones** [comment]
Yes, I think that this is part of the refactoring already pegged for this project.

**Comment by dommitchell** [comment]
Actually the old data had a field 'Year in which the journal stopped publishing OA content'. Can this be reused to become Year in which the journal stopped publishing'?

**Comment by emanuil-tolev** [comment]
I'd make a new field, as we're getting rid of the old journal records shortly anyway (with reapp shutdown). And we should also get rid of those parts of the admin / editor journal form that deals with the old metadata. This should be a proper part of the record handled in the same way as any other piece of metadata.

**Comment by richard-jones** [comment]
I have now added a field called "discontinued_date", which will hold this information.  I haven't tried to populate it from the old data, though.  I'll investigate the feasibility of that.

**Comment by richard-jones** [comment]
@dommitchell - I've had a look at the data, and there are 253 journals which have the fiend bibjson.oa_end.year.  I'm not sure whether ceasing to produce OA is the same as being discontinued - is that always the case?  If so, I could use this field where it exists to populate the new discontinued_date field.

**Comment by dommitchell** [comment]
Hmm, no. A journal may still continue but no longer be open access.

These 253 journals with an oa_end year: this is old data right? Aren't we getting rid of those?

**Comment by richard-jones** [comment]
Ok, in which case I think that we can't re-use that data to set the discontinued_date.

I can't remember what the status of the oa_end field is, but we are still holding the old data, and no plans to actually clear it out at our end, but I don't think it's being surfaced anywhere.

**Comment by dommitchell** [comment]
@emanuil-tolev said in Dec:
I'd make a new field, as we're getting rid of the old journal records shortly anyway (with reapp shutdown). And we should also get rid of those parts of the admin / editor journal form that deals with the old metadata. This should be a proper part of the record handled in the same way as any other piece of metadata.

I think we should follow that approach.

**Comment by dommitchell** [comment]
I added a Ceased publication date to https://testdoaj.cottagelabs.com/admin/journal/0023aaeb7bda4c5ea314e8c1b830d024. I expected to see a new line in the search entry in the Admin view (Ceased publication) or the Discontinued flag appear but it didn't. It does in the public view.

**Comment by richard-jones** [comment]
Ah, ok, we didn't make any changes to the admin search results (only the facets).  Easy to add.

**Comment by richard-jones** [comment]
This is in the next PR for continuations fixes

**Comment by dommitchell** [comment]
In the journal record, http://testdoaj.cottagelabs.com/admin/journal/0fb09e308a9343e997bbb7374569e02e, please change 'Date this Journal was discontinued, in the form YYYY-MM-DD' to 'Date this Journal was discontinued, or ceased publication YYYY-MM-DD.'

**Comment by richard-jones** [comment]
Removing the day value is hard, because this will break the date handling.  Can you just set the day to 1st of the month?

We can change the display of dates to only use the year and month values easily enough.

In the mean time, though, I will make the small text alteration

**Comment by dommitchell** [comment]
> Can you just set the day to 1st of the month?

Sounds like a plan!

**Comment by dommitchell** [comment]
All good!
