### ISSUE TITLE
Removed journal from DOAJ: articles still findable

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#900]
We removed http://bit.ly/1GhwBJX from the DOAJ on 11th Sept.

Somehow an article published in that journal is still findable online: https://doaj.org/article/287f83f673a94a67954d0aa146ab826b

How?

**Comment by emanuil-tolev** [comment]
Somebody had linked to it. We wouldn't display links to it (as the journal's ToC would be taken down) but we still displayed the article. I checked, and luckily the system state is changed correctly (the article was marked as taken out of DOAJ correctly), but the /article page was just not paying attention :). I've rolled out a hotfix, this article and all others like it should now 404 if you click on a direct link to it.

**Comment by dommitchell** [comment]
Great! Thank you!
