### ISSUE TITLE
An application or reapplication should not be save-able with text in an URL field

### ISSUE THREAD

**Issue by greboun** [DOAJ/doaj#902]
I noted in a application that the field of Q31  Enter the URL... could be filled with text only and the record was saveable. Acc to Dominic this could be a bug??

![image](https://cloud.githubusercontent.com/assets/12031556/10541602/b196da38-7412-11e5-89b8-7b28a9f11599.png)

**Comment by emanuil-tolev** [comment]
Yes, if that can really happen and validation is on (i.e. you haven't checked the "Allow incomplete form" checkbox), that is a small bug.

**Comment by greboun** [comment]
It happens n all the Dove press reapplications  eg

https://doaj.org/admin/suggestion/3fc74615c61e4cb09b9bc63275b5c7ff



Dr. Tom Olijhoek
Editor-in-Chief  DOAJ
Support us: www.doaj.org/support

**Comment by Steven-Eardley** [comment]
The validator was missing. Fix is now live.

**Comment by greboun** [comment]
Thanks  issue closed
