### ISSUE TITLE
Remove blanks for fields in the data

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#903]
For example publisher names, platforms, Societies etc #887

**Comment by dommitchell** [comment]
From a colleague, providing much more detail:
/start/
There are two basic situations:
    Extra spaces at the end (or beginning) of the text
    Double or multiple spaces within the text

The extra spaces are not normally apparent on DOAJ web pages, because they are usally fixed automatically by the browser for display. However, they do make it difficult to deduplicate journal titles and publishers' names. 

I have not checked all the DOAJ fields, but here are figures for the number of journals with extra spaces for the main fields that moreo uses:

    Journal titles - 665 journals
    Journal URLs - 145 journals
    Alternative titles - 158 journals
    Publishers - 559 journals
    Societies - 47 journals

I could provide you with lists should you want them, although you may prefer to get your developers to run a data-cleansing exercise on all your fields to trim off leading and trailing spaces, and to reduce multiple spaces to single spaces.
/end/

**Comment by emanuil-tolev** [comment]
Interesting. Unrelated to resolving this (which is not hard, though probably not totally trivial with testing it properly) - How'd they get that data, API?

**Comment by dommitchell** [comment]
Nope CSV file!

/start/
Should you want to investigate your CSV File yourself in Excel, you may find the followng helpful: Insert a column next the field you wish to check, and add a formula such as =IF(LEN(a2)=LEN(TRIM(a2)),"","spaces!") - where A2 is the cell being checked. Fill or copy the formula down the new column. You can then sort or filter on the new column to group together the errant rows for inspection.
/end/

**Comment by emanuil-tolev** [comment]
Oh yeah :)
