### ISSUE TITLE
Produce a list of journals removed from DOAJ that have articles attached to them

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#904]
As part of the continuation project, we will be reviewing our removal policy for journals that no longer publish. The criteria for NOT removing a journal is:

- they have article metadata in DOAJ
- they have an online, albeit, mothballed version of the site
- the content is preserved in an official repository

To find out about the first point above, we need to know how many journals that are NOT in DOAJ and which have articles associated with them.

Please produce and run a script to produce a CSV list of journals and ISSN so that we can review. If possible, a count of the number of articles would be helpful.

**Comment by dommitchell** [comment]
Assigning this to the continuations project as I hope it can be done then.

**Comment by richard-jones** [comment]
This is not covered by the continuations estimate, so putting it also under tnm.

**Comment by richard-jones** [comment]
I've now written the script for this, and submitted a PR

@emanuil-tolev - I've assigned to you, as it needs merging and running on live.  I'll leave it to you and @Steven-Eardley to decide who actually does it.

Probably worth merging and deploying that PR before merging the continuations work down

**Comment by Steven-Eardley** [comment]
PR for this #1010 and a doc change PR #1007 can be merged and run before continuations. I'm currently running article migrations, so will let you know when this can be done.

**Comment by Steven-Eardley** [comment]
This has been deployed to live. When ready, it will be run with:
```python portality/scripts/not_in_doaj_with_articles.py -o <output file path>```

**Comment by Steven-Eardley** [comment]
@richard-jones this looks like it's related to the number of articles that are about to be deleted by ```article_cleanup_sync.py``` - wasn't that already counting these? (I'll see if the numbers are the same!)

**Comment by dommitchell** [comment]
Deleted? Or simply removed?

**Comment by Steven-Eardley** [comment]
Deleted - a bulk delete operation, see #941

**Comment by dommitchell** [comment]
Ah yes, this is article delete. All good.

**Comment by Steven-Eardley** [comment]
Ah! yes! this is a journal script. All good - my question is answered.

**Comment by dommitchell** [comment]
So I am unsure now what has been done here. I wanted a list of journals that have article metadata associated with them but are not in DOAJ. NOT those journals removed because they never submitted a reapplication but those journals that have been removed at some point between March 2014 and now where article metadata is associated with that journal.

Is that what has been done?

**Comment by richard-jones** [comment]
This issue covered the development of a script which outputted the following: " journals that are NOT in DOAJ and which have articles associated with them".

There is a separate issue #1006 which covered the removal of journals which did not reapply, and which also output a CSV, detailing the journals which were removed by that process.

Both of these have been done now, so you should have all the associated data, which together I think make up the complete picture.  We can also always re-run the script from this issue to get the latest information.

**Comment by dommitchell** [comment]
OK, thanks for the clarification. I *didn't* get the output from this one.

**Comment by Steven-Eardley** [comment]
*Github doesn't support CSV?*

@dommitchell the script was run on live; 2080 journals are not in DOAJ but have articles. Attached is a zip with the csv.

[20160524_not_in_doaj_with_articles.csv.zip](https://github.com/DOAJ/doaj/files/279883/20160524_not_in_doaj_with_articles.csv.zip)

**Comment by dommitchell** [comment]
> Github doesn't support CSV?

Crazy huh??

Thank you. All good here!
