### ISSUE TITLE
Turn URLs in an application into real URLs

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#905]
Please let me know how difficult it would be to turn the URLs in an application form, under editing, into real URLs or followable links so that editors can click on them to follow them instead of having to cut and paste them as they do now.

**Comment by richard-jones** [comment]
I think that would depend on how exactly we wanted to do this.  Right now I'm not sure what I'd do, but a couple of options are:

* for all url fields, duplicate the content of the field into a clickable link below the input box
* for all url fields, have a "copy this link" button, or something similar

Either way, we're looking at some fairly low-level changes to how the form renderers work, so it would be moderately time consuming.  A couple of days, at a guess.

I've removed the tnm label, and assigning back to you @dommitchell for decision.

**Comment by dommitchell** [comment]
@greboun any feeling for the priority of this one?
