### ISSUE TITLE
Generate reapplication record

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#906]
Libyan Journal of Medicine is missing its reapplication record. Please generate one:

3d2c55c62a4c4aa79e65113e802530d8
1819-6357

**Comment by dommitchell** [comment]
As per #590 journal is now in DOAJ.

**Comment by emanuil-tolev** [comment]
How do you guys search for all applications by a specific publishers on the UI?

**Comment by emanuil-tolev** [comment]
OK, this publisher seems to have 31 reapplications. We do have some complicating circumstances:

1/ This publisher has a Reapp CSV.
2/ This publisher has submitted 29 of their 31 reapplications
3/ We want to *add* a reapplication (original post in this issue)

If I do 3/ then they shall have 32 reapplications available to them, 29 of which would have been submitted. I believe this means we will need to regenerate their CSV - but clearly they might have downloaded it. They have never uploaded a CSV.

Are you happy for me to regenerate their CSV? If they have a local copy stored somewhere they will not be able to use this any more. If they wish to continue their work, they will need to

- redownload their reapplication CSV
- copy over all the information in a spreadsheet program, taking care to avoid assigning the wrong information to the new reapplication (for 1819-6357). I can't guarantee it will go at the end of the CSV (it most probably will not). Any copying they do will need to just be done carefully, probably in 2 parts around the new reapplication column.

Now, obviously they've never uploaded a CSV so clearly they've used the UI so far to submit all their reapplications, so I would be happy to add this reapplication and regenerate the CSV if you think that's OK.

**Comment by dommitchell** [comment]
> Now, obviously they've never uploaded a CSV so clearly they've used the UI so far to submit all their reapplications, so I would be happy to add this reapplication and regenerate the CSV if you think that's OK.

That would be grand! I can confirm that they submitted everything by hand in the end.

**Comment by dommitchell** [comment]
@emanuil-tolev will regenerate this and delete the CSV

**Comment by emanuil-tolev** [comment]
Here's the CSV for posterity as I've deleted it now: https://www.dropbox.com/s/hqmkuq3leusdm2y/reapplications_16544951.csv?dl=0

**Comment by emanuil-tolev** [comment]
original filename: 16544951.csv (which will need to be used if it's restored to appdata/doaj/reapp_csvs ).

**Comment by emanuil-tolev** [comment]
OK, reapplication should be generated. Find it at https://doaj.org/admin/suggestion/1f4a1b02a98c42d3b85b40bd1fcd1810 . Script output:

```
(doaj)cloo@doaj-app-1:~/repl/production/doaj/src/doaj$ DOAJENV=production python portality/migrate/reapplication/reapp_init.py -j 3d2c55c62a4c4aa79e65113e802530d8
Running in production
Loaded final config from /home/cloo/repl/production/doaj/src/doaj/production.cfg
Generating Reapplication for journal 3d2c55c62a4c4aa79e65113e802530d8
```

**Comment by dommitchell** [comment]
Confirmed and thanks!
