### ISSUE TITLE
Application form: text change

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#909]
Question 50: change wording to

Does the journal allow readers to 'read, download, copy, distribute, print, search, or link
to the full texts of its articles' and allow readers to 'use them for any other lawful purpose'?

**Comment by Steven-Eardley** [comment]
> the full texts' of its articles'

You have an extra apostrophe there

**Comment by dommitchell** [comment]
Good catch! Updated.

**Comment by Steven-Eardley** [comment]
How do you feel about using italics instead?

quotes:
<img width="569" alt="screen shot 2015-10-22 at 13 00 05" src="https://cloud.githubusercontent.com/assets/1446355/10664680/2f888726-78bd-11e5-9ad1-ddbcef967fba.png">

italics: 
<img width="560" alt="screen shot 2015-10-22 at 13 01 31" src="https://cloud.githubusercontent.com/assets/1446355/10664684/36232c3a-78bd-11e5-9aeb-afef395940e3.png">

**Comment by dommitchell** [comment]
I like italics! :+1:

**Comment by Steven-Eardley** [comment]
Live now!

**Comment by dommitchell** [comment]
Great! Thank you for the fast turnaround!
