### ISSUE TITLE
Workflow emails re/app wording

### ISSUE THREAD

**Issue by Steven-Eardley** [DOAJ/doaj#910]
from @dommitchell:
>I've had to add 'or reapplication' to the emails being sent out to
publishers because many are getting in touch asking why they have an
email about a new application.

**Comment by Steven-Eardley** [comment]
@dommitchell can you clarify which emails are causing confusion? We do differentiate between applications and reapplications for some of the cases. Here are the emails sent to publishers:

```
publisher_application_accepted.txt
publisher_application_editor_assigned.txt
publisher_application_inprogress.txt
publisher_application_received.txt
publisher_bulk_reapp_complete.txt
publisher_bulk_reapp_error.txt
publisher_bulk_reapp_file_error.txt
publisher_reapplication_accepted.txt
publisher_reapplication_received.txt
publisher_reapplication_rejected.txt
```

**Comment by Steven-Eardley** [comment]
My guess would be these two, which don't have a reapplication case:
```
publisher_application_editor_assigned.txt
publisher_application_inprogress.txt
```
But if it's the other ones, perhaps something is broken and it's not detecting when something needs a reapplication-worded email.

**Comment by emanuil-tolev** [comment]
And this is the directory of production email templates (where to check those files): https://github.com/DOAJ/doaj/tree/production/portality/templates/email

**Comment by dommitchell** [comment]
I already edited https://github.com/DOAJ/doaj/tree/static_pages/portality/templates/email which as my own branch

I changed:
assoc_editor_application_assigned.txt
publisher_application_editor_assigned.txt 
publisher_application_inprogress.txt

They just need to go live. Hope I haven't done something wrong... :/

**Comment by emanuil-tolev** [comment]
Ah ok we thought you wanted us to change them. I have recently updated static_pages so your changes should be fine. @Steven-Eardley you ok to release static pages? I create a hotfix out of an updated production and git merge static_pages. You should get a conflict if they differ in an incompatible way (though as I say, they should not).

**Comment by Steven-Eardley** [comment]
Okie, working on it now

**Comment by Steven-Eardley** [comment]
```static_pages``` (with the changes for this issue) deployed to live. Closing.
