### ISSUE TITLE
Reapplications: uploading CSV doesn't validate URLs | Seems to be bumping an answer

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#911]
Should the publisher CSV for reapplications be validating for real URLs? Because it isn't at the moment. See the attached which processed successfully.

Also: processing the spreadsheet bumps the third answer to question 25 'National Library' to 25b eg https://doaj.org/admin/suggestion/e423d135150b430c93e06665597e079e

See 
[11786957 final.xlsx](https://github.com/DOAJ/doaj/files/19444/11786957.final.xlsx)

**Comment by emanuil-tolev** [comment]
> Should the publisher CSV for reapplications be validating for real URLs? Because it isn't at the moment. See the attached which processed successfully.

What isn't a real URL? Sorry if I'm being a bit dumb but I read 3-4 journals and they seem to mostly be copy/pasted dovepress URLs, which in itself you may or may not like from an editorial perspective, but wouldn't make them invalid URLs. What cell's got an invalid one?

I can confirm the national library/other thing, it does seem weird. The CSV question is "25a) If a national library, which one?", their answer is

**Comment by greboun** [comment]
I have seen that a form was filled with ticking  national library:   name
 and in other : national library
other> national library should be an invalid option

Dr. Tom Olijhoek
Editor-in-Chief  DOAJ
Support us: www.doaj.org/support

**Comment by emanuil-tolev** [comment]
I think this is being caused by the system itself, I don't think people are actually putting that text in Other. Like in the reapp CSV above - question 25b is actually empty, but after ingestion that text appears. This is the system being unable to interpret the "national library" option well enough I think. The implementation of this was quite tricky back in early 2014 (having 2 text fields with 2 checkboxes). So no need to add more validation, but do need to change the system to understand this value better.

**Comment by dommitchell** [comment]
> What isn't a real URL?

Apologies. In some answers, instead of a URL, the publisher is putting text. Check out Question 31: https://doaj.org/admin/suggestion/06940b0f92db46229a971a2b82b27b5a

> this is being caused by the system itself, I don't think people are actually putting that text in Other.

Right. That's the problem. Sample answer in the form:
x A national library: PubMed
x Other: A national library

Same answer in the CSV:
25) What digital archiving policy or program(s) does the journal belong to? LOCKSS, CLOCKSS, National library
25a) If a national library, which one? PubMed NCBI
25b) If Other, enter it here [BLANK]

It seems that entering 'National library' as answer to (25) throws things off kilter.

**Comment by dommitchell** [comment]
This is working correctly. Because a value to Q25 isn't recognised, it gets automatically deposited to Q25b: Other.
