### ISSUE TITLE
ToC builder needs to ignore / in volume name

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#913]
http://bit.ly/1NpGaWY

Now look at the ToC: https://doaj.org/toc/2194-9050

The publisher has a volume numbering system that includes '/'. The / is preventing articles being attached to the ToC correctly.

Would it be a simple change to make / be treated as a normal character?

**Comment by Steven-Eardley** [comment]
It could be as simple as escaping or url-encoding the character so it isn't interpreted as part of the path, yes.

I think.

**Comment by dommitchell** [comment]
Another example of this: https://doaj.org/toc/2300-5866/2/2/2011

**Comment by richard-jones** [comment]
@Steven-Eardley - could you track this alongside your work on changing the ToC; probably moving to fv2 will get rid of this issue (see #983 )

**Comment by Steven-Eardley** [comment]
Yes, I believe the fv2 ToC has fixed this - see https://testdoaj.cottagelabs.com/toc/2300-5866?source=%7B%22query%22%3A%7B%22filtered%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22term%22%3A%7B%22bibjson.journal.volume.exact%22%3A%22VIII%22%7D%7D%2C%7B%22term%22%3A%7B%22index.issn.exact%22%3A%222300-5866%22%7D%7D%5D%7D%7D%2C%22query%22%3A%7B%22match_all%22%3A%7B%7D%7D%7D%7D%2C%22from%22%3A0%2C%22size%22%3A100%7D

**Comment by dommitchell** [comment]
Great!
