### ISSUE TITLE
Add new sponsor: PLoS

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#918]
![new-plos-logo](https://cloud.githubusercontent.com/assets/5955396/10876557/136d1fa0-813e-11e5-8bbf-b0682d4f8ec2.jpg)

and link to https://www.plos.org/

Thanks!

**Comment by emanuil-tolev** [comment]
I'll get this as I'm doing an early release for something anyway. FYI they style it PLOS nowadays (e.g. open homepage and see title of browser window), I had it corrected on another project with them.

**Comment by emanuil-tolev** [comment]
done on live

**Comment by dommitchell** [comment]
Superfast! Thank you!
