### ISSUE TITLE
Contact us link on API page returns error

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#920]
When not logged in, the Contact Us link under Authenticated Routes on https://doaj.org/api/v1/docs returns an error: https://doaj.org/api/v1/%7Bcontact_us_url%7D

**Comment by Steven-Eardley** [comment]
This is live now. I also fixed the CSS which was causing some discrepancies in font sizes. (bonus!)

**Comment by dommitchell** [comment]
Great!
