### ISSUE TITLE
Clear form entry field on hidden questions

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#921]
original issue: **Unable to save form**

Invokes 'Problem with submitted form error' but no indication on the form where or what the error is:

https://doaj.org/admin/suggestion/003cd6bc210344a09333c641dba95a47

Reported by @greboun

**Comment by Steven-Eardley** [comment]
Well, the error is on question 31, which is hidden! Say 'yes' for the preceding question and you see "N/A" is in the text box. This is related to a fix I recently put in at @greboun's request, issue #902

**Comment by Steven-Eardley** [comment]
That's quite tricky to find - we should perhaps clear that text box when the question is hidden, so there isn't a chance for nasty data to get in there.

**Comment by dommitchell** [comment]
@greboun I'll leave this to you to look at first. We can discuss later.

**Comment by greboun** [comment]
I think it would be best to clear the text box atomatically when the
Question is hidden like you suggest
Thanks for sorting this out

Dr. Tom Olijhoek
Editor-in-Chief  DOAJ
Support us: www.doaj.org/support

**Comment by Steven-Eardley** [comment]
The fix is live now - you can check that hiding questions will clear the hidden text box.

**Comment by dommitchell** [comment]
Great! Thank you!
