### ISSUE TITLE
Add new sponsor: De Gruyter

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#923]
Link to http://www.degruyteropen.com/

![dg_open_h](https://cloud.githubusercontent.com/assets/5955396/11039278/23fd0c08-8707-11e5-9936-3b92d0957d7a.jpg)

**Comment by Steven-Eardley** [comment]
Live now

**Comment by dommitchell** [comment]
Smashing! Closing

**Comment by dommitchell** [comment]
I am very sorry but publisher wants logo changed:

![dg_open_h](https://cloud.githubusercontent.com/assets/5955396/11066264/c27803a4-87c7-11e5-8729-5cec5da3bf63.jpg)

**Comment by Steven-Eardley** [comment]
Such is life. I'm halfway through a release just now, it'll go in afterwards!

**Comment by Steven-Eardley** [comment]
Sorted

**Comment by dommitchell** [comment]
Thank you and apologies again!
