### ISSUE TITLE
Search differentiates between capital and small letters

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#925]
Try searching on "International journal of Women’s Health" (small j) - no results

Try searching on "International Journal of Women’s Health" (capital j) - 2 results

That shouldn't happen.

**Comment by richard-jones** [comment]
Is that with the quote marks around it?  Because quote marks mean "exactly as specified", which is why it would differentiate between lower and upper case.

**Comment by richard-jones** [comment]
Though in attempting to reproduce, I'm having some trouble.  I'm relatively easily able to find the journal with either search criteria.

**Comment by richard-jones** [comment]
Note that if you copy and paste from here, something has messed with the apostrophe which makes neither search work (probably a microsoft character set).  If you replace it with a normal apostrophe, both searches seem to work fine.

**Comment by dommitchell** [comment]
Huh! So it is the apostrophe that is the problem and not the capitals...? I just did a search on "International journal of Women's Health" and it worked fine!

**Comment by greboun** [comment]
More on this note
When I do a search in admin on users  and I search for @elsevier  there are
no results   searching for @elsevier.com returns one result

Dr. Tom Olijhoek
Editor-in-Chief  DOAJ
Support us: www.doaj.org/support

**Comment by dommitchell** [comment]
> When I do a search in admin on users and I search for @elsevier there are no results searching for @elsevier.com returns one result

Yeh, this is slightly different. To search on email addresses in users, you must use either the full email address, or the entire prefix before the @ or the entire suffix after the @. You can't just search on a part of either.
