### ISSUE TITLE
History system refactor

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#935]
Make the following modifications to the article and journal history systems:

* re-write snapshot() to output a json file to disk
* store snapshots on disk in per-day directories (for easy delete)
* store snapshots one per file with name <id>_<timestamp>.json

Old directories should then be archived off (e.g. to S3/glacier or just deleted) based on some retention policy.

**Comment by emanuil-tolev** [comment]
@richard-jones we wrote this spec thinking that currently history records were only ever written by the system, not queried. Obviously it's quite hard to query a bunch of folders which disappear after a few months on the fly.

It'd be useful to chat about ```portality.view.doaj.toc``` a.k.a. portality/view/doaj.py:178 and ```portality.models.openurl.OpenURLRequest.query_for_vol``` a.k.a. portality/models/openurl.py:168 . These two methods are in constant use by the live system and do query the Elasticsearch history of **journals only**.

I see no obstacles to *article* changes being archived as we initially thought.

**Comment by emanuil-tolev** [comment]
> I see no obstacles to article changes being archived as we initially thought.

This involves

models.history.ArticleHistory.get_history_for(article_id)

```python
    @classmethod
    def get_history_for(cls, about):
        q = ArticleHistoryQuery(about)
        res = cls.query(q=q.query())
        hists = [cls(**hit.get("_source")) for hit in res.get("hits", {}).get("hits", [])]
        return hists
```

My proposition is to simply delete this method. The way to find old records would be to retrieve them from S3/Glacier (if old enough) and to ```fgrep -r -i <article_id>``` them - not something we'd want to keep around in Python.
