### ISSUE TITLE
History system migration / backup

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#936]
The current article and journal histories should be taken out of ES and serialised to files on disk, then retained/deleted as per the retention policy.

The indexes for these should then be deleted.  In parallel with #935 this will get rid of the existing history system

**Comment by emanuil-tolev** [comment]
> The current article and journal histories should be taken out of ES and serialised to files on disk, then retained/deleted as per the retention policy.

From meeting today: actually just take a full backup of the history types and just delete the types.

**Comment by emanuil-tolev** [comment]
note first try on harvester instance

**Comment by richard-jones** [comment]
@emanuil-tolev - this is done now, isn't it?  Can we close?
