### ISSUE TITLE
Run load test ("load" requests, harvester, scripts and backups) + analyse

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#940]
Harvester load test, with the following criteria:
- normal load coming from web front end (via #937 )
- harvester running
- backups running
- normal asynchronous scripts running

**Comment by emanuil-tolev** [comment]
We're running this as a copy of live. Actual backups are running, async scripts are all running (except workflow emails). Leaving open to leave analysis results in here when done.
