### ISSUE TITLE
Article cleanup script

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#941]
Building on the existing journalinfo.py script, we need a script which does the following for each article:
1. Checks that there is a corresponding journal
   - If there is not, the article should be deleted
2. Ensure that the article in_doaj status is the same as the journal's
3. Applies the journal's information to the article metadata as needed

In order for this to be run regularly it needs to be performant.  The following changes should be made to how the script works:
1. All journal records requested should be cached, so they are only looked up once
2. scroll search over articles (might already do this, but check)
3. Don't write articles that don't need writing (i.e. where they haven't changed)
4. Bulk write articles
5. Bulk delete articles

**Comment by richard-jones** [comment]
In addition, we're going to need to add an extra field to the "journal" portion of the article model: "issn".

This is so that the journal can provide the article with the issn to use in generating the toc, in the case that the article also contains another issn which isn't known by the journal record.  In that latter case, this can cause the article to provide the incorrect toc url in the search interface.

When we've done that, we then need to modify the search interface to read the issn for the toc from the journal portion of the record.

**Comment by Steven-Eardley** [comment]
@richard-jones how much does it matter that keys are unicode strings? Sometimes when ```Article.get_journal_metadata()``` is run, it replaces unicode keys ```[{u'type': u'CC BY', u'title': u'CC BY'}]``` with non-unicode keys from the Journal object ```[{'type': u'CC BY', 'title': u'CC BY'}]```

This is triggering my 'a change has been written' bit, although I think they are unicode when I next retrieve them, after saving the Article object. So the cycle continues.

I'm only seeing this within licenses from Journals, so far.

**Comment by Steven-Eardley** [comment]
Related issue to this script: bug fix #982

**Comment by richard-jones** [comment]
There's no strong need for the keys to be unicode - we don't use any special characters in the keys so they should be pretty much interchangeable between unicode and str.  So, if you want to force it to be one way or the other, that's good with me!

**Comment by Steven-Eardley** [comment]
>When we've done that, we then need to modify the search interface to read the issn for the toc from the journal portion of the record.

Would it be sufficient to change the Article's ```index.issn``` to the new one from ```journal.issn``` when the index is built?

**Comment by richard-jones** [comment]
I'm not sure.  Thoughts below...

We need the journal.issn field to link to a single known issn for the journal, that we guarantee will link successfully, but the index.issn contains all known issns for the article, for searching purposes.  That means, I think, that journal.issn is a string and index.issn is a list.

We need to check that we're not re-using the field in two different kinds of context, otherwise we might break one or the other in the process.  But, if the contexts are actually the same, then this would be a reasonable way to reduce effort and data stored.

Perhaps go over this in call?

**Comment by Steven-Eardley** [comment]
Completed, and released with Continuations.

**Comment by richard-jones** [comment]
We have this code essentially in place, and other issues surrounding it, so closing this one
