### ISSUE TITLE
Areas that need refinement over the coming 6 months - discussion item

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#942]
XML upload process:
- documentation
- troubleshooting. What invokes each error message? Why? Inventorise each error message like we did in #475 
- update and make clearer some of the error messages #367 
- XLS. The information on this page is out of date and incomplete https://doaj.org/features#xml_upload. We need to publish the list of what's required, what isn't, what attributes must be present, rules #631 
- past issues: #686 #679 #824 
- add missing language code #857 
- make volume field compulsory #473 

Closing the reapplication process
- what needs to be done in what order? A step by step description would be great.
- would all reapplications have to be processed through to an accepted / rejected decision?

Refactoring
- see below

**Comment by dommitchell** [comment]
To be added to. Meeting to be scheduled for December.

**Comment by richard-jones** [comment]
Some refactoring tasks:

* Looking at moving to a "business logic" layer for the core, which will allow us to keep separate the main content workflows (e.g. article ingest) from the various ways into the system (e.g. article web form, XML upload, API)

* Re-working the core object models to use the new data-object code we are now using in the API.  There's a lot of improvements we could make here, and it would be nice to finally rename a Suggestion to Application!

**Comment by dommitchell** [comment]
Added a lot of detail around what is required for the XML piece.

**Comment by dommitchell** [comment]
Headings for discussion
1. Documentation for the site (users/troubleshooting/etc.)
2. Article Ingest - metadata form, XML upload, XSD, related to refactoring
3. Reapplication (and its shutdown)
4. Business logic refactoring
5. Core system object refactoring (and how to handle legacy data model)
6. Application form refactoring/layout (may imply model changes)

**Comment by richard-jones** [comment]
We completed our discussion sessions, and out of it a couple of bits of work emerged:

* documenting the article xml upload errors and resolutions
* a modification to the toc to use a facetview style approach
* A good understanding in the team about the end-of-reapplication process

I'm therefore closing this off, as it doesn't have any follow-up actions required.
