### ISSUE TITLE
Add new sponsor: AAAS

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#943]
Please add a new sponsor and link to http://www.aaas.org/

![aaas-logo-157x52px](https://cloud.githubusercontent.com/assets/5955396/11235632/4b0f4720-8dd3-11e5-9518-030805c478a5.png)

**Comment by Steven-Eardley** [comment]
live the noo

**Comment by dommitchell** [comment]
Beautiful! Thanks!
