### ISSUE TITLE
Sorry your account does not have an associated email address error

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#945]
Seeing a few emails with this message in it:

Sorry your account does not have an associated email address

when people trying to reset their own passwords. And all have email addresses associated with them.

EG 1488559x

Do we know why?

**Comment by dommitchell** [comment]
Another example: 1307234X

**Comment by emanuil-tolev** [comment]
Wow, that's .. uncanny. Obviously the error is there for really rare circumstances of legacy data and administrative accounts. If it couldn't find the account you'd get (the much more often seen)

```
Hm, sorry, your account username / email address is not recognised.
```

Now the error you've reported is when there *was* an account, but it didn't contain an "email" field. But these accounts do contain an email field. It's my favourite kind of bug, starting with a logical impossibility.

FYI I tried a pw reset and it did send it me to me (received immediately) so it doesn't look like the functionality is entirely broken.

**Comment by emanuil-tolev** [comment]
Hmmm. This actually works on test!

* * *

A password reset request for account '1488559x' has been received and processed.
Please visit http://testdoaj.cottagelabs.com/account/reset/blahblah and enter your new password.

If you are the user '1488559x' and you requested this change, please visit that link now and set the password to something of your preference.

If you are the user '1488559x' and you did not request this change, you can ignore this email.

Regards,
The DOAJ Team

* * *

I hate to suggest it, but could it have been an intermittent problem? Perhaps ask just one of the users to try again? And if it works, the other one. Obviously I could try it on live but it'll send them an actual email...

**Comment by dommitchell** [comment]
Still getting lots of emails from people where this link isn't working. One or two then get back to me and say they got it working. I don't have the time to pin this down. Closing for now.
