### ISSUE TITLE
Journal facet "Date added to DOAJ" doesn't display correct results

### ISSUE THREAD

**Issue by remocrevo** [DOAJ/doaj#952]
On the DOAJ website, when you choose the "Journals" facet and then choose a year from the "Date added to DOAJ" facet, the search results are from the year after the chosen year.  For example, if you choose 2014 (the newest option currently), you see only journals with a "Date added to DOAJ" value in 2015.

**Comment by Steven-Eardley** [comment]
Hi @remocrevo, I'm having trouble replicating the off-by-one issue, and I see over 1200 journals on the public search page added in 2015. Please can you provide a few more details:

* is the issue you've reported on the main search page, https://doaj.org/search ?
* Do you have any particular query in the search box?
* which browser are you using?
* have you tried [clearing your browser cache for the DOAJ](https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache) and trying again?

**Comment by remocrevo** [comment]
Hi @Steven-Eardley, thanks for the quick response! Yes, this is starting at the main search page.  Same results in Firefox, IE and Chrome, all on Windows 7, all after clearing the cache. I'm not doing any search query, only loading the search page and clicking on the two facets.  I'm attaching a screenshot of how the "Date added" facet looks after I click on the "Journals" facet; there is no 2015 option shown.  

![doaj_date_facet](https://cloud.githubusercontent.com/assets/8701105/11400033/f790abee-9358-11e5-8569-b2401b836947.png)

The second screenshot shows the search results (showing dates added from 2015) when I click the 2014 date facet.  Also, here's the decoded URL for that results page:

https://doaj.org/search?source={"query":{"filtered":{"filter":{"bool":{"must":[{"term":{"_type":"journal"}},{"range":{"created_date":{"gte":"1420070400000"}}}]}},"query":{"match_all":{}}}},"from":0,"size":10}

![doaj_2014_results](https://cloud.githubusercontent.com/assets/8701105/11400321/b597d558-935a-11e5-8340-ba882aff0475.png)

**Comment by Steven-Eardley** [comment]
Thanks for the extra information. We've done some head-scratching about this, and we reckon we've found a probable cause: our UI was using the JavaScript method```getFullYear()``` which was rendering the threshold date (2015-01-01 0000) relative to the time in your location, which would have been in 2014.

We've changed this to ```getUTCFullYear()```, so you should see the correct dates. Thanks for bringing this bug to our attention!

**Comment by remocrevo** [comment]
It works great!  Thanks for your work on this.
