### ISSUE TITLE
Generate 3 missing reapplication records

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#960]
2 records missing for the same account:
Amsterdam Law Forum - 1876-8156
European Journal of Life Writing - 2211-243X
(Account 22115242)

and

1 record missing for:
Technology Interface Journal - 1523-9926
(Account 21578052)

**Comment by dommitchell** [comment]
Can we have these done asap?

**Comment by emanuil-tolev** [comment]
> Technology Interface Journal - 1523-9926

https://doaj.org/admin/suggestion/7376d52d4f794c5cbc74dbdef6da7af2

> Amsterdam Law Forum - 1876-8156

https://doaj.org/admin/suggestion/0413b550c157457880cda8735caa6295

> European Journal of Life Writing - 2211-243X

https://doaj.org/admin/suggestion/e5cc63c933e34987b660067e2b2ff08f

:)

**Comment by emanuil-tolev** [comment]
Hey @greboun - going to start assigning issues to you when they are marked ready for review, so you can close them if they look ok. You can also filter by "ready for review" label in the issue list.

**Comment by dommitchell** [comment]
Thanks! Looking good!
