### ISSUE TITLE
Sending email to wrong contact name

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#961]
There is a bug in the confirmation emails going out for reapplications.

/start/
Dear Fernando César Lima Leite,
Congratulations! Your reapplication for Revista Ibero-Americana de Ciência da Informação has been successful and the journal has been accepted back into DOAJ. Please go to the new journal record and review to check for accuracy. In particular, please check that the ISSN information is correct.
/end/

We don't know where Fernando is coming from because the name of the contact in the reapplication record is Murilo Bastos da Cunha
https://doaj.org/admin/journal/607fd93912b04b60bd23320ebf047ac2

Can you please verify where you are pulling the name field from and correct it so that it pulls in the name of the journal contact in Question 9 of the reapplication form?

**Comment by Steven-Eardley** [comment]
@dommitchell the system is doing the right thing - see my email entitled 'doaj issue 961 - publisher name incorrect'. The account the journal is owned by is named Fernando; you could assign the journal to a different account for Murilo if you like.

**Comment by dommitchell** [comment]
Thanks! Closing and opening new, separate issue

**Comment by dommitchell** [comment]
Now I think about this: where are we pulling the name information from? We don't store that anywhere in the user database....

**Comment by Steven-Eardley** [comment]
Of the 8074 accounts in DOAJ, 7308 have a name field. You can see the email I mentioned above for a sample of what we store for accounts. Under the normal workflow we create a new account when a journal is accepted, using the contact information from the application form. So we do store the names, but don't have an interface for changing it on existing accounts.

The situation reported in this issue has arisen because we intentionally send reapplication notifications to the *existing* account, rather than allowing a new account to take over an existing journal when they reapply.

**Comment by dommitchell** [comment]
Yah, I am just wondering where those names came from originally. They must have been imported when we migrated in 2012/3. As you say, there is nowhere to change them in the current interface and there is also nowhere that they are displayed:  eg https://doaj.org/account/00015113

**Comment by Steven-Eardley** [comment]
They continue to come from the application form; the journal contact fields. We just don't display them anywhere else, or allow anyone to change them!

**Comment by emanuil-tolev** [comment]
This continues to be a problem as "journal accepted" emails are targeted at account.name, but there's no interface to update those names. We've been asked to amend some names already. It would be good to either:

- add an interface to change the names
- stop using account-level names in the journal acceptance process and just email whoever was on the application contact when the journal is accepted

**Comment by emanuil-tolev** [comment]
Should discuss in meeting tomorrow.

**Comment by emanuil-tolev** [comment]
> stop using account-level names in the journal acceptance process and just email whoever was on the application contact when the journal is accepted

That won't work, we want to protect the account from having the email/name changed on (re)application so we need to keep using account-level data.

**Comment by emanuil-tolev** [comment]
Solution under TnM is to:

- allow editing of "account.name" in the "my account" page
    - make sure admins can do it too
    - handles nulls well - there are lots of nulls
- on publisher_application_accepted, publisher_application_editor_assigned, publisher_application_inprogress: email both the account-level email if there is one (with the account-level name, allowing it to be null) **AND** the journal contact name (Q10 on the appl form)

* * *

We've also discovered a potential issue. New accounts created on application approval are potentially using the wrong email. @greboun thinks the suggester's email and name (questions 56 and 57) should be used here instead. This is done portality/formcontext/formcontext.py:344 (in _create_account_on_suggestion_approval). The code is ```suggestion_contact = util.listpop(suggestion.contacts())```. We should create a new issue to fix this in the future.

**Comment by emanuil-tolev** [comment]
Rolled out - should be possible to edit name, and we responded to DOAJ team over email for this.
