### ISSUE TITLE
Mandrillapp delivery failure

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#963]
Is this a capacity issue?

Delivery to the following recipient failed permanently:

```
 feedback@mail136-14.atl41.mandrillapp.com
```

Technical details of permanent failure:
The recipient server did not accept our requests to connect. Learn more at https://support.google.com/mail/answer/7720
[(10) mail.mail136-14.atl41.mandrillapp.com. [198.2.136.14]:25: socket error]

**Comment by emanuil-tolev** [comment]
The error means that the remote mail server (where the target email account was supposed to be hosted) has failed to respond to the attempt to deliver the mail. I'm not sure why the target is feedback@mail136-14.atl41.mandrillapp.com , that seems like a nonsensical address for DOAJ to be sending mails to.

There shouldn't be any capacity issues as we're covering the Mandrill cost and it's set to auto-renew, plus the minimum # of emails to purchase is 25k (so I doubt we're anywhere near that figure yet).

**Comment by richard-jones** [comment]
Have we resolved the issues with mandrill, now, so this can be closed off?

**Comment by dommitchell** [comment]
@emanuil-tolev can this be closed?

**Comment by richard-jones** [comment]
We no longer use mandrill, so this issue is obsolete
