### ISSUE TITLE
Add new sponsor: ISSN

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#966]
![issn_logo](https://cloud.githubusercontent.com/assets/5955396/11712981/d27bf38e-9f30-11e5-8156-c6b05d6783b8.jpg)

Link to http://www.issn.org/

**Comment by emanuil-tolev** [comment]
How meta. Congratulations on landing this sponsorship.

**Comment by Steven-Eardley** [comment]
Live now

**Comment by dommitchell** [comment]
Great!
