### ISSUE TITLE
Question: journals that supply metadata

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#968]
Is there a way, via any of our current connections to DOAJ metadata for someone to be able to tell which journals provide metadata and which don't? ie via OAI, API, etc

**Comment by richard-jones** [comment]
For an individual journal, they can query (via the UI or the API) for articles associated with it.  But there's currently no capability to do a "show me all journals that have articles".  

We'd need to create an additional bit of journal data to store that, and keep it synchronised, in a similar way as we do with the articles for journal information.

**Comment by ClaraDOAJ** [comment]
Ok, thanks!  Let's close it. If someone asks again, maybe we can think of adding new info,.
