### ISSUE TITLE
Update site to show 2016 copyright

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#970]
Please update the site so the footer now reads:

© 2003-2016

**Comment by emanuil-tolev** [comment]
Um, shall we just put the current year in there with Python?

**Comment by dommitchell** [comment]
Yeh just whatever is simpler. 2016 is fine.

**Comment by emanuil-tolev** [comment]
This is live now, it shows the current year as it is in UK time at any given moment.

**Comment by dommitchell** [comment]
Perfect!
