### ISSUE TITLE
Add a traceable query string to all URLs in the widget

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#974]
We talked about making traffic from the widget traceable. I suggested that all we needed, to be able to track traffic in Google Analytics, was to add ?wid to the end of all URLs generated by the widgets.

I would like some analysis done on this in the next 3 months so that we can have something ready to action in the 2nd quarter of 2016. This is going to be important for us to trace usage and possible funding.

**Comment by dommitchell** [comment]
Adding @Steven-Eardley to the thread

**Comment by emanuil-tolev** [comment]
@Steven-Eardley since you fiddled with this bit recently, does that sound like something quick you have time to do? I'll put it on my list otherwise

**Comment by dommitchell** [comment]
@Steven-Eardley please revisit this one.

**Comment by emanuil-tolev** [comment]
`?origin=widget&source=thequerythatwastherebefore`

**Comment by richard-jones** [comment]
There has not been any movement on this for some time, so I've been taking a look, and trying to decide what the appropriate way forward is.

First, we have two widgets:

1. The simple search widget - this is just a glorified redirect from the client website to our website
2. The fixed query widget - this embeds DOAJ search results into client pages

Tracking referrals from (1) is relatively straightforward, and I've written some basic code which takes a "ref" parameter, which propagates to the search interface, which is therefore logged with google analytics.

(2) is a bit more complicated - queries by this widget are via our low-level query api, and are not logged in GA.  Logging them there would be very very hard, and would potentially flood the analytics with data most of which isn't useful.

So, perhaps we should have a discussion about what we actually need from this before I do any more, to make sure that we're recording the right kind of behaviour.

**Comment by dommitchell** [comment]
(1) is fine. That's all I need for that.

For (2) it would be nice just to know who is using this. Instead of traffic via all links in the widget, can we track who has taken this option? Are there any reporting possibilities available at that higher level instead?

**Comment by richard-jones** [comment]
A few options for (2):

* We write a script which can analyse the current web logs for downloads of the fixed query widget javascript, and provide a csv of results.  This could then be run on demand.  This would be an imperfect measure of usage, as intermediate caches would prevent download of the javascript each time a user loads the widget.

* We use the script from above, and automate its execution to run and email you results on some defined period.  

* We add an extra parameter to search queries from the widget, which we can do log analysis on.  Again, options are to do this manually on demand, or automated periodically.  This would allow reporting at a query-level

* Use the extra parameter (see previous point) to search queries to take some active logging/reporting action (tbd)

* On initialisation, send a request to DOAJ to alert that the widget is being used.  Then produce some kind of report over that information.  This would allow reporting at a widget-download level.  


All of these options count /users/ of the widget, not sites that embed the widget.  It will also not be trivial to put this information into google analytics, we would be looking to do a custom/home-made report for this data.

We should go through this with the whole team at some point to determine the main requirement for reporting, and discuss the time/effort implications.

**Comment by richard-jones** [comment]
Note, we don't know if it will be possible to identify who is embedding the widget.  Some experimentation required.

**Comment by richard-jones** [comment]
To do next:

1. Release the code for recording referrals by the simple search widget

2. Do a log analysis of downloads of the fixed query widget, to get an idea of the scale of usage

After (2) we may then need to go on and do an experiment around whether we can detect the domain that the widget is operating in, and send that information back to DOAJ when the widget is initialised.

**Comment by dommitchell** [comment]
@richard-jones this is part of the Google Analytics work

**Comment by emanuil-tolev** [comment]
Data on external hits to *the fixed query widget only*, by web server logs and referral data:

```
    104 Nov 2016
    646 Dec 2016
    635 Jan 2017
    825 Feb 2017
    657 Mar 2017
    627 Apr 2017
    592 May 2017
    828 Jun 2017
    754 Jul 2017
    880 Aug 2017
   1354 Sep 2017
   2674 Oct 2017
   2881 Nov 2017
   2240 Dec 2017
    985 Jan 2018 (incomplete, data as of 16 Jan 2018)
```
