### ISSUE TITLE
Change to footer.html

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#975]
We had some feedback where someone searching for article content was looking at an abstract and then saw in the footer: 'This work is licensed under CC BY-SA'. He thought that meant that the article was licensed as CC BY-SA. How can we avoid that ambiguity? I suggest:

'This site and the metadata in it is licensed under CC BY-SA'

Thoughts?

**Comment by Steven-Eardley** [comment]
I agree with you, and I suppose it can be a leap in some cases to realise 'this work' is the DOAJ site itself.

> 'This site and the metadata in it is licensed under CC BY-SA'
perhaps 'DOAJ site and metadata are licensed under CC BY-SA'? Don't ask me if metadata is plural!

**Comment by emanuil-tolev** [comment]
:+1: I thought we already had language to that effect, but ok, if it's unclear it's unclear.

**Comment by dommitchell** [comment]
OK, thanks

Let's change it to: 'The DOAJ site and its metadata are licensed under CC BY-SA'

**Comment by Steven-Eardley** [comment]
This change is live now

**Comment by dommitchell** [comment]
Perfect!
