### ISSUE TITLE
Display bug in journal metadata CSV

### ISSUE THREAD

**Issue by dommitchell** [DOAJ/doaj#977]
The display in the CSV for subject classifications isn't rendering correctly which is causing problems downstream for librarians and folks using the CSV file for their dbs. AND sometimes classifications are missing.

For example: https://doaj.org/toc/2346-9129 -  Agriculture: Agriculture (General) where a colon (:) means that the second subject is a sub-category of the first.

or https://doaj.org/toc/2307-2113 -  Bibliography. Library science. Information resources: Information resources (General) | Medicine: Medicine (General) which in the CSV renders as Medicine, Medicine (General), Information resources (General)

We agreed a specific display of subject categories with @richard-jones. You can read the display rules here: https://doaj.org/faq#lcc

In the CSV, all words are separated by a comma and some are missing. Can you fix this so that the CSV uses colons, full stops and pipes and every category?

**Comment by Steven-Eardley** [comment]
This is live

**Comment by dommitchell** [comment]
Great!
