### ISSUE TITLE
Unable to save applications (Springer ?)

### ISSUE THREAD

**Issue by greboun** [DOAJ/doaj#980]
it seems that new applications from Springer cannot be edited and saved
the problem is not in the subject classification absence   filling this out still  lead to error message  problem with the application form

https://doaj.org/admin/suggestion/116b280d55ca4067a449715b1036d0fe
https://doaj.org/admin/applications?source=%7B%22query%22%3A%7B%22filtered%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22term%22%3A%7B%22admin.editor_group.exact%22%3A%22Tom%22%7D%7D%2C%7B%22term%22%3A%7B%22admin.application_status.exact%22%3A%22pending%22%7D%7D%2C%7B%22term%22%3A%7B%22index.country.exact%22%3A%22Iran%2C%20Islamic%20Republic%20of%22%7D%7D%5D%7D%7D%2C%22query%22%3A%7B%22match_all%22%3A%7B%7D%7D%7D%7D%2C%22from%22%3A0%2C%22size%22%3A10%7D

**Comment by emanuil-tolev** [comment]
Attempted change of editor group from Tom to German1 and it came up with an error without scrolling to error message.

**Comment by emanuil-tolev** [comment]
Could be potentially required to assign Associate editor. @greboun testing.

**Comment by emanuil-tolev** [comment]
This is an invalid data problem from before there was a validator on the field. It's question 31 (put Yes to question 30). I'd say this is TnM probably a couple of hours.

**Comment by emanuil-tolev** [comment]
@greboun you don't need to check, ew think we've found the problem

**Comment by greboun** [comment]
Thanks

I can probably handle these applications for the moment  by deleting the
content of Q 31 manually/

TOM

Dr. Tom Olijhoek
Editor-in-Chief  DOAJ
Support us: www.doaj.org/support

**Comment by greboun** [comment]
deleted N/A in Q31 manually and save worked!

TOM

Dr. Tom Olijhoek
Editor-in-Chief  DOAJ
Support us: www.doaj.org/support

**Comment by emanuil-tolev** [comment]
> I can probably handle these applications for the moment  by deleting the
> content of Q 31 manually/

Probably, but this will likely happen again - we don't know exactly how many there are that put in invalid data before we put in a fix to make it impossible to put in invalid data... we can hold off on doing anything if you want, but it seems like you'll just run into this again if we don't.

**Comment by greboun** [comment]
Please Fix ASAP  but if I am blocked in the meantime I will do the manual
trick

TOM

Dr. Tom Olijhoek
Editor-in-Chief  DOAJ
Support us: www.doaj.org/support

**Comment by richard-jones** [comment]
So, we have a manual workaround for this one, but what's the overall state of the issue?  I don't think it affected many records, can we identify them and manually clean them, then close this off?

**Comment by greboun** [comment]
I have manually corrected  applications, seems to be always Springer.
This is no big deal for us So for me CL need not put time in this
Close this off
TOM

Dr. Tom Olijhoek
Editor-in-Chief  DOAJ
Support us: www.doaj.org/support
