### ISSUE TITLE
Workflow: ability to select multiple records and perform batch operations

### ISSUE THREAD

**Issue by greboun** [DOAJ/doaj#981]
#800

requirements now that give the most advantage
!) batch allocate to group / associate editor
2) batch update status
with just these **two batch operations**  the editorial process would could save a lot of time
could be implemented best according to @richardjones possibility 2:
__ A specific "bulk edit" area, possibly as an expandable page segment on the admin area search interfaces (in a similar location, say, as the bulk delete). In this case we would have specific actions that could be taken (status change, withdraw/reinstate, etc), or specific metadata fields that could be edited__    https://github.com/DOAJ/doaj/issues/800.

**Comment by richard-jones** [comment]
We've previously estimated on this, so currently filing in a new "batch editing" milestone to be considered at some point in the future.

**Comment by richard-jones** [comment]
This is a general issue, related to the project we have nearly finished, so I'm going to close it off in preference for more specific issues.
