### ISSUE TITLE
Article metadata duplication: bibjson.subject

### ISSUE THREAD

**Issue by Steven-Eardley** [DOAJ/doaj#982]
Each time `Article.add_journal_metadata()` is run, duplicate subjects are added. They are appended from the journal, rather than checking if they exist first. This has been confirmed in data from the live index.

To fix:
- code change to check for existence in `GenericBibJSON.add_subject()` before append
- write a migration to remove existing duplicates from `Article.bibjson.subject`

**Comment by richard-jones** [comment]
This indicates that we need to introduce de-duplication into the bibjson model - putting under tnm, as although a bug is also 18 months old!

**Comment by richard-jones** [comment]
@Steven-Eardley - this is resolved, right?  Can we close?
