### ISSUE TITLE
Replace ToC Article view with FV2

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#983]
Replace existing ToC display, which relies heavily on Volume/Issue metadata to be present in the articles, with a search-based article view.

This will re-use the search-based approach that we have used across the board in DOAJ, by providing an embedded facetview on the Journal ToC page. It will have the following features:

* support the existing URL scheme, including the volume and issue numbers, in order to seed any search
* Re-write the URL to include the full search parameters (as the search page does), so that URLs are shareable
* Provide a stripped-down results display using the current citation style
* Provide "Volume", "Year" facets for narrowing search. On selection of "Volume" an "Issue" facet will appear. On selection of "Year" a "Month" facet will appear.
* Provide the usual free-text and sorting search controls.
* Provide paging, but defaults to long page sizes, so that in many cases a full issue will fit on one page of results

Technical notes:
See the dynamic facets on the public search page for how to use a callback to render the right facets: https://github.com/DOAJ/doaj/blob/develop/portality/static/doaj/js/available_facetviews/public.journalarticle.facetview.js#L110

**Comment by Steven-Eardley** [comment]
@richard-jones @emanuil-tolev, what is the difference between the two approaches to creating a facet for year / month:

The existing method for year is a histogram made from the timestamp in the index.
```python
year_published_histogram : {
    type: "date_histogram",
    field: "index.date",
    interval: "year",
    display: "Year of publication",
    value_function : function(val) {
        return (new Date(parseInt(val))).getUTCFullYear();
    },
    size: false,
    short_display: 15,
    sort: "desc",
    disabled: false
}
```

I've replaced this with a simple terms facet that comes from the bibjson string year. This has helped because I have to enable and disable facets using their field, and if I use another histogram for the month, it also comes from the ```index.date``` field.
```python
year : {
    field: "bibjson.year.exact",
    display: "Year of Publication",
    disabled: false
},
```

Do I lose anything by not using a histogram?

**Comment by emanuil-tolev** [comment]
The main difference I can see is your data is coming from 2 different sources. Index.date may have been quite heavily sanitised as opposed to bibjson.year .

**Comment by Steven-Eardley** [comment]
From meeting: using histogram has some validation and normalisation advantages - duplicate the ```index.date``` field as a workaround for facetview2 considering fields as IDs, preventing two facets on same field.

**Comment by dommitchell** [comment]
- please change 'Table of Contents' to 'TableS of Contents'

And a cheeky one: is it a lot of work to add the share/embed button?

**Comment by dommitchell** [comment]
Hi Steve, what's the latest on this one?

**Comment by Steven-Eardley** [comment]
The main body has been released! the extra dev work for the share / embed hasn't been done yet

**Comment by Steven-Eardley** [comment]
@dommitchell the share/embed button has been added - visible now on live.

**Comment by dommitchell** [comment]
Nice!

**Comment by dommitchell** [comment]
The shortener isn't present: https://doaj.org/toc/2383-4544. When you click on Share, there is no option to shorten the URL. Is that a separate piece of functionality?

**Comment by Steven-Eardley** [comment]
It is - it was originally written hard-coded to doaj.org/search. That'll need reworking if it is to be re-used for this page.

**Comment by emanuil-tolev** [comment]
Is there a need to shorten these URLs? They appear to be more readable and not much longer than bit.ly's own.

**Comment by emanuil-tolev** [comment]
Oh, unless you select options to modify what you're viewing on the ToC page of course - ignore me.
