### ISSUE TITLE
Document article xml upload exceptions and possible causes

### ISSUE THREAD

**Issue by richard-jones** [DOAJ/doaj#984]
1. List all possible errors the user might see
2. Determine all possible causes for each error (errors may have more than one cause)
3. Define what investigation should be done in the case that an error has more than one cause
4. Define what corrective action can be taken by DOAJ staff or the user to resolve the problem.

Then make the following documentation:

1. DOAJ staff guide - detailed information about the error, and what they should advise the user to do, or what corrective action they should take. This will be available as a text file in the DOAJ code repository.

2. User guide - slightly less detailed troubleshooting documentation, to help users solve the regular problems themselves. This guide will be in HTML and linked from the article XML upload status table, with an anchor pointing to the relevant error.

**Comment by emanuil-tolev** [comment]
@greboun @richard-jones see new version of the docs on the test server: https://testdoaj.cottagelabs.com/publishers#failed (and section below that one).

**Comment by emanuil-tolev** [comment]
@greboun is this ready to release to live? Have a look, feel free to share the link in the comment above with the DOAJ team...

**Comment by richard-jones** [comment]
@greboun - here are the links you need to follow to review:

Public documentation for end-users: https://testdoaj.cottagelabs.com/publishers#failed

Troubleshooting for DOAJ admins - https://github.com/DOAJ/doaj/blob/develop/docs/articlexml/TROUBLESHOOTING.md

**Comment by dommitchell** [comment]
All good. Can be made live.
