### ISSUE TITLE
Admin view date applied should change to date (record was) created

### ISSUE THREAD

**Issue by greboun** [DOAJ/doaj#988]
Reaoplications submitted show date appied  and last updated
Date applied should become date record was created   , lst updated can remain last updated
Last updated for reapplication in practice  is in fact  the date that the form was SUBMITTED = DATE APPLIED.  
ERGO  Current Date applied ISNOT date applied

![image](https://cloud.githubusercontent.com/assets/12031556/13179758/9d692888-d725-11e5-80b2-96f25e6fea77.png)

**Comment by emanuil-tolev** [comment]
So Date Applied should be one of:
- time the form was actually submitted (rather the last time the form was submitted by the publisher, since they can edit much as they like until it's picked up by an editor).
- "not applied yet"

**Comment by greboun** [comment]
Yes, that is right
Did not think of the angle of publishers editing after subitting which does
not always happen
So often last updated is date applied

Dr. Tom Olijhoek
Editor-in-Chief  DOAJ
Support us: www.doaj.org/support

**Comment by dommitchell** [comment]
I need to discuss this with Tom. Please do nothing here for now. ON HOLD.
