### ISSUE TITLE
Bulk change status of re- applications submitted to 'on hold'

### ISSUE THREAD

**Issue by greboun** [DOAJ/doaj#989]
When we have publishers that look suspicious (possible preadatory)  we need to give their application a special status.
I chose on' hold' for this ,then the journals will be evaluated later on in the year by new editors specialized in dev country applications
I now have already 75 journals where status of all need to be changed from reapplication submitted to on hold,  we like to have a script to do this kind of task
- journals reapplications submitted   , country = XXXXXXX

**Comment by Steven-Eardley** [comment]
Task to do under TNM, write a script "set status by query" which will set an application's status by any ES query, saving a file report consisting of:

```application_id   old_status -> new_status```

**Comment by richard-jones** [comment]
With the new bulk edit interface, is this now obsolete
