### ISSUE TITLE
Make public UI APC facet more accurate (if possible)

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#994]
Investigate if it's possible to include a "no information" value in the "Article processing charges (APCs)" on the public search UI. This is in addition to the Yes/No there right now.

index.has_apc is the field in question. We want "No information" when there is no tick and no bibjson.apc information. We want "No" when there is a tick and there is no bibjson.apc information. We want "Yes" when there is a tick and there is bibjson.apc information.

Verify that the tick is actually a good criterion here (e.g. there are no journals without a tick, but with bibjson.apc information, and that the presence of a tick truly is a good criterion for the "No").

Also note that the tick is not available via the API. I recommend just staying on the "let's finish the reapps and reject lots of old journals" topic when it comes to the API.

**Comment by emanuil-tolev** [comment]
Any journal created after 19 Mar 2014 (double check this is what we used for applying tick) OR there is a last_reapplication field.

**Comment by Steven-Eardley** [comment]
from ```settings.py```

```python
# tick (on toc) and doaj seal settings
TICK_THRESHOLD = '2014-03-19T00:00:00Z'
```

**Comment by greboun** [comment]
When can this be implemented?
This determines when I cangive the info to Peter Suber and post an update
on the DOAJ Blog

THNX

TOM

Dr. Tom Olijhoek
Editor-in-Chief  DOAJ
Support us: www.doaj.org/support

**Comment by emanuil-tolev** [comment]
Hey @greboun 

TnM issues can be prioritised within all TnM tasks, but TnM tasks themselves rarely have a deadline on their own, it's generally (if the task is top priority, then whenever a developer starts working from the TnM queue again). We're looking at when that might be happening in the next few weeks though and I'll tell you shortly.

**Comment by emanuil-tolev** [comment]
This is a bit more complex than I thought. The issue is that right now the APC facet is over the index.has_apc field, which is a true/false field. What we want is to essentially change the facet so that it derives information from two fields: the tick, and index.has_apc .

When I wrote the original post / proposal, I was thinking of this in terms of "do we even have the necessary information to answer this question". We do have the information, spread across two fields. So it is still possible, but more complex to do in terms of development.

We have three options to solve this in terms of development approach:

1. Change the value of the has_apc field from being true/false to being a string which says "Yes/No/No Information". This would require a migration and we'd have to inform API users.
2. A similar option would be to introduce a new field, apc_info_type or something like that. This would contain "Yes/No/No Information" calculated by the method I proposed originally. This would require a migration and a new facet in the UI, not much else.
3. Rewrite the APC facet so it's a more complex nested aggregation, specifically one that first splits the records by whether they have the tick, and then splits them again by whether they have apc information. Three of the resulting groups directly match "Yes/No/No Information". I'm not sure how well the current UI library is suited to a nested aggregation - I would guess it would need at least a small amount of work to support that. This would require no migrations, but is just a bit more complex (or complex in a different way) than the others.

I would gladly do one of these, perhaps preferring 3 or if that's not straightforward, 2. But, there's also the issue that this won't be of any use after next Monday when we will be removing all the old journals, therefore "no" in the current APC facet will really mean "no", rather than "no + no information".

But, obviously that's not much use to Peter who wants this information precisely before we remove all those journals. So what I'll do is I'll try to do option 3 manually and give you the numbers of "Journals with APCs", "Journals without APCs", "Journals for which we have no APC information and which will get removed on 9 May" @greboun .

**Comment by emanuil-tolev** [comment]
@greboun I realise I did advise you it would be better to do a proper change rather than one-off numbers. At the time I wasn't sure whether we were really going to remove those journals or not so soon (or whether we were in for another 6 months before removing them), in which case a facet change would have made sense. In this case, since the change would be rendered moot by modifying the catalogue in just 1 week time, it doesn't make much sense.

**Comment by emanuil-tolev** [comment]
cc @richard-jones @Steven-Eardley to review query and rationale:

Query:
```javascript
{
    "query" : {
        "match_all" : { }
    },
    "aggs" : {
        "apc" : {
            "terms" : { "field" : "index.has_apc.exact" },
            "aggs" : {
                "ticked": {
                    "terms" : { "field" : "admin.ticked" }
                }
            }
        }
    }
}
```

Results:
```javascript
{
    "aggregations": {
        "apc": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
                {
                    "key": "No",
                    "doc_count": 13847,
                    "ticked": {
                        "doc_count_error_upper_bound": 0,
                        "sum_other_doc_count": 0,
                        "buckets": [
                            {
                                "key": "F",
                                "doc_count": 11368
                            }
                            ,
                            {
                                "key": "T",
                                "doc_count": 2479
                            }
                        ]
                    }
                }
                ,
                {
                    "key": "Yes",
                    "doc_count": 1376,
                    "ticked": {
                        "doc_count_error_upper_bound": 0,
                        "sum_other_doc_count": 0,
                        "buckets": [
                            {
                                "key": "T",
                                "doc_count": 1346
                            }
                            ,
                            {
                                "key": "F",
                                "doc_count": 30
                            }
                        ]
                    }
                }
            ]
        }
    }
}
```

Journals with APCs: 1,376
Journals without APCs: 2,479
Journals missing APC information: 11,368

I know from elsewhere the journals we're about to remove (i.e. ones that have completed reapplication) are not that many, they're more in the 4-6k range. So what's going on with so many missing their APC info then? Well, there are ~4,500 reapplications which have been submitted, but are pending review. Those journals will not be removed from DOAJ straightaway next week, but they are also not accepted yet, so their (old) journal records currently in the catalogue don't have any APC information.

Due to this last bit, note a correction to my previous post - we **cannot** say "Journals for which we have no APC information and which will get removed on 9 May". Because the group that's missing APC info =/= group which will be removed at all.

Let me know if that's useful for Peter @greboun .

**Comment by emanuil-tolev** [comment]
> we cannot say "Journals for which we have no APC information and which will get removed on 9 May". Because the group that's missing APC info =/= group which will be removed at all.

I suppose that means my paragraph on whether to make the APC facet more accurate also needs reconsidering:

> But, there's also the issue that this won't be of any use after next Monday when we will be removing all the old journals, therefore "no" in the current APC facet will really mean "no", rather than "no + no information".

More accurately, the facet won't become correct on 9 May, but it'll become more and more correct as all reapplications are processed. On an unrelated note, we should consider what we do with journals who reapplication is rejected after 9 May - in theory their old records should also be withdrawn immediately (since that's what would have happened to those journals who did not reapply at all).

**Comment by greboun** [comment]
Let me recuperate
As I see it the new journals accepted and the reapplications accepted have the right info on APC, either yes or No +the amounts
The journals that will be removed (reapplications pending) have No meaning no info
The journals rapplications submitted have No meaning No information (until evaluation completed)
So the **current** facet No will become more accurate over time.
I still would like to see Yes, No, No information after the removal of the journals with reapplications pending.
I don't understand why currently before the removal there are 11368 journals with No information of which 4500 are reapplications submitted (which will not be removed) This looks like we will be removing about 7000 journals!  Acording to the admin view there are 3273 journals with reapplications pending which are the ones to be removed
How to explain the different number?

**Comment by dommitchell** [comment]
Note to self.
http://bit.ly/1TtyFyX - APC counts
versus
http://bit.ly/1W8wN5g - APC counts.

**Comment by greboun** [comment]
Concerning the issue of having a new facet in the UI       WE STILL NEED THIS
What Peter Suber (and me too)  wants is to be sure that all the information  DOAJ displays is correct
Meaning that
 APC **No**  there is no APC
APC **Yes**  there is an APC
APC   **no information**     we do not have the info yet

This means that we still need the facet showing no information for journals where the reapplication has been submitted and not yet accepted or rejected

**Comment by dommitchell** [comment]
@greboun Thanks! That helps.

@emanuil-tolev we do still need to make the distinction

> More accurately, the facet won't become correct on 9 May, but it'll become more and more correct as all reapplications are processed.

Yes! However, it is misleading now and that is causing problems. How many journals charge APCs is *highly* political and much debated. People are looking to DOAJ to provide an indication which we can do with some accuracy, only not right now. At the moment, we lump together 'no information' (today that is all those journal records with a reapplication submitted but not yet processed) and 'No' (journals for which we have the specific information).

I think that we have discussed this before and creating a *Not* label is difficult. Can you tell me then how many of the journals currently in DOAJ today fall into the No information category? If we can get that figure, I can update the blog post to give recent figures.

**Comment by emanuil-tolev** [comment]
Continue with implementing facet with logic from https://github.com/DOAJ/doaj/issues/994#issuecomment-216124035

**Comment by richard-jones** [comment]
I've created a hotfix PR which implements this functionality.

I'm also in the process of porting the new behaviour over to the continuations branch (so for the time being, the behaviour on the live site will be newer than the behaviour on the test site).

**Comment by dommitchell** [comment]
This is live on the site now. Was that intended? http://bit.ly/1OWggxW

**Comment by dommitchell** [comment]
Looking good! Closing.
