### ISSUE TITLE
Add collapsible groups of DOAJ members to /members static page

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#996]
Consortia are already listed on https://doaj.org/members . If help is needed to identify the exact list of consortia if you can't tell by the name (there should be 15 in total), ask @jbarnsby .

Consortia are listed under their respective (main) country where they (chiefly) operate. These are and will continue to be listed by DOAJ admins who edit the /members page. The idea here is to add the ability to collapse/expand a list each consortium's members.

For example, currently we have:

#### Russia
* NEICON - National Electronic Information Consortium

We want to end up with

#### Russia
* <a href="#expand">[+]</a> <a href="http://neicon.ru/" target="_blank">NEICON - National Electronic Information Consortium</a>

The [+] is a link which expands / collapses the list of members. It might be decorated with a dotted underline to distinguish it from link following immediately after - the name of the consortium, which will link to its website (as it does right now).

Ideally this will be done as unobtrusively as possible with JS. I would consider simply adding a class like "expandable" to the ```<li>``` element containing the consortium name, and adding the [+] entirely via Javascript. That way, if JS doesn't work for some reason, you don't get lots of inoperative [+] links. This also makes it relatively easy for DOAJ admins to operate.

I'd recommend the following HTML structure for listing the consortium members (just bc I had to check guidelines on nested lists):

```
<ul class="the usual country-level list listing various organisations, including our consortium(s) in the country">
<li class="expandable the-element-for-1-consortium">
        <span class="expand-collapse inserted-via-JS">+</span> <a href="consortium website">Consortium 1</a>
        <ul class="one_consortiums_members">
            <li>Poppleton Library (these could also be links to individual websites, DOAJ admins know how to add/edit them)</li>
            <li>Poppleton University Press</li>
        </ul>
</li>
```

It'd be good to get one example actually, so get 1 consortium and a list of its members. When development is finished this will become the first example consortium which DOAJ admins like @jbarnsby can copy to other consortia.

**Comment by emanuil-tolev** [comment]
This has been agreed to proceed under T&M for a few/several hours of work. We need an example (I've asked for one) and probably a stricter estimate just to help guide the work internally to CL, but besides that this should be ready to be picked up.

**Comment by jbarnsby** [comment]
Consortium example (listed under USA):
Virtual Library of Virginia (VIVA)

Members:
Bridgewater College
Christopher Newport University
College of William & Mary
Eastern Shore Community College
Eastern Virginia Medical School
George Mason University
Hampden-Sydney College
James Madison University
Liberty University
Longwood University
Lynchburg College
Mary Baldwin College
Marymount University
Norfolk State University
Northern Virginia Community College
Old Dominion University
Paul D. Camp Community College
Piedmont Virginia Community College
Radford University
Regent University
Shenandoah University
Southside Virginia Community College
Sweet Briar College
Tidewater Community College
University of Mary Washington
University of Richmond
University of Virginia
University of Virginia's College at Wise
VCCS Systems Office
Virginia Commonwealth University
Virginia Military Institute
Virginia State University
Virginia Tech
Washington & Lee University

**Comment by jbarnsby** [comment]
Example consortium and members added to ticket today.

Best,
Judith

Judith Barnsby
DOAJ Publication Specialist

**Comment by emanuil-tolev** [comment]
Consortium website: http://www.vivalib.org/

@jbarnsby are we going to want individual members' websites? Though if we do, you don't have to paste them here - you can add them easily after the work is done.

**Comment by jbarnsby** [comment]
Yes, we'll want to be able to link from each member name to their web site.

Judith Barnsby
DOAJ Publication Specialist

**Comment by emanuil-tolev** [comment]
tech note: Instead of using a special class, just apply this code to all lists which have other lists nested inside.

**Comment by richard-jones** [comment]
Ok, what I've done here is to add some javascript to the page which will make any first level nested list collapsible.  So, if you have a consortium like this:

```html
<li><a href="http://www.vivalib.org/index.html"><b>Virtual Library of Virginia (VIVA)</b></a>
    <ul>
        <li>Bridgewater College</li>
        <li>Christopher Newport University</li>
    </ul>
</li>
```

I've inserted the VIVA members as a list, which were provided in a comment above.  

@dommitchell - Do you want to provide me with the other lists to go in here too, or will you add them via modifications to the static files over time?

If the latter, I can prep a PR for this shortly.  Otherwise, just let me have the lists when you are ready, and I can make the update.

**Comment by dommitchell** [comment]
@jbarnsby were there other consortia to be provided here, that you can remember?

**Comment by emanuil-tolev** [comment]
It might be best to provide the feature on the test server, then ask @jbarnsby and @dommitchell to have a look at the static files and add some consortia themselves (since this feature is supposed to be supported through fairly clean & easy HTML editing).

**Comment by richard-jones** [comment]
For the purposes of expediency I've raised a PR for this now, and when it's merged, then it will be a simple matter of updating the static pages whenever is needed to add the new collapsible consortium lists.

**Comment by emanuil-tolev** [comment]
This was released live a week or so ago.

see Virtual Library of Virginia (VIVA) at https://doaj.org/members

**Comment by jbarnsby** [comment]
Great, thank you!

Judith

Judith Barnsby
DOAJ Publication Specialist
