### ISSUE TITLE
Space at the end of publisher name

### ISSUE THREAD

**Issue by emanuil-tolev** [DOAJ/doaj#999]
![doaj-mdpi-listed-twice](https://cloud.githubusercontent.com/assets/1190172/13751085/620f60d4-ea00-11e5-80a2-91ccecc8611c.png)

Submitter says:

---

search query: https://doaj.org/search?source={%22query%22%3A{%22filtered%22%3A{%22filter%22%3A{%22bool%22%3A{%22must%22%3A[{%22term%22%3A{%22_type%22%3A%22journal%22}}]}}%2C%22query%22%3A{%22query_string%22%3A{%22query%22%3A%22%22mdpi%20ag%22%22%2C%22default_operator%22%3A%22AND%22}}}}%2C%22from%22%3A0%2C%22size%22%3A10}

returns "132 records". For this records, two entries are provided in the publisher filter:

Publisher
MDPI AG (126)
MDPI AG (6)

see screenshot. It looks like the publisher entry of the later 6 journals needs to be trimmed ("MDPI%20AG%20" != "MDPI%20AG"). Maybe a right trim would improve the filter values in general?

---

Problem source: data supplied by publishers (MDPI in this case I suppose).

Potential solution: change all article metadata ingestion mechanisms to trim whitespace off either end of the publisher name and run a migration script removing leftmost and rightmost spaces from all publisher names, only saving the journal or article or application if anything was changed.

**Comment by emanuil-tolev** [comment]
@greboun Do you think is this important enough to include in T&M right now, or should we wait until a more general data cleanup project? There are 19 open issues labelled data cleanup in the tracker atm.

**Comment by dommitchell** [comment]
No longer an issue. Closing
